export default {
  layout: {
    intro: '汇课堂 是长沙云易公司旗下专注货币对交易教育的学习平台',
    address: '湘ICP备2020016999号-1',
    searchCourse: '搜索讲师和课程',
    watchToBook: '观看至 第 {x} 章',
    watchToVideo: '观看至 第 {x} 集',
    noData: '暂无数据',
    loginout: '退出登录',
    loginRegister: '登录/注册',
    huidouRemaing: 'F Coin余额',
    huidouPay: 'F Coin充值',
    myStudy: '我的学习',
    mySubscribe: '我的订阅',
    myReserve: '我的预约',
    authentication: '品牌中心',
    userMenuList: [
      { title: '个人主页', name: 'lectureVideo', icon: 'a-huiche1' },
      { title: '作品管理', name: 'creation', icon: 'creation-list' },
      { title: '消息中心', name: 'myInformation', icon: 'information', line: true },
      { title: 'F Coin中心', name: 'buyBeans', icon: 'myCoin' },
      { title: '我的订单', name: 'myOrder', icon: 'purchased' },
      { title: '已购课程', name: 'buyCourse', icon: 'orders', line: true },
      { title: '我的订阅', name: 'mySubscribe', icon: 'subscription' },
      { title: '我的预约', name: 'myReserve', icon: 'icon-20-reserve' },
      { title: '我的收藏', name: 'myCollection', icon: 'favorite2' },
      { title: '历史记录', name: 'historyRecord', icon: 'recording', line: true },
      { title: '品牌中心', name: 'authentication', icon: 'icon-authentication' },
      { title: '设置', name: 'personalData', icon: 'setting', line: true }
    ],
    loginRegisterRouter: '注册登录',
    register: '注册',
    articleList: '货币对交易入门，货币对交易新手入门，货币对交易投资培训',
    videoList: '货币对交易入门视频_货币对交易教程视频下载_货币对交易入门视频_货币对交易视频讲座',
    searchList: '搜索结果',
    feedback: '反馈',
    testDownload: '试卷',
    loginAgreement: '登录协议',
    offLevel: '内容已下架',
    achievement: '个人成就',
    shareLogin: '登录',
    historyRecord: '历史记录',
    personalData: '个人资料',
    accountSecurity: '账号安全',
    language: '地区与语言',
    myOrder: '我的订单',
    payOrder: '支付页面',
    payStatus: '支付状态',
    buyBeans: '购买F Coin',
    buyCourse: '已购课程',
    myCollection: '我的收藏',
    shareInfo: '分享',
    navList: [
      { label: '首页', value: 'home', icon: 'menu-home' },
      { label: '直播', value: 'liveList', icon: 'menu-live' },
      { label: '视频', value: 'videoList', icon: 'menu-video' },
      { label: '电子书', value: 'articleList', icon: 'menu-article' },
      { label: '讲师', value: 'lecturerList', icon: 'menu-lecturer' },
      { label: '红人评选', value: 'activity', icon: 'activity-icon' },
      { label: '活动', value: 'outSideEvent', icon: 'menu-event' }
    ],
    chapterDetails: '文章章节详情',
    articleInfo: '文章章节列表',
    videoDetail: '视频详情',
    myInformation: '我的消息',
    aboutUs: '关于我们',
    login: '登录',
    bindEmail: '邮箱绑定',
    bindPhone: '手机号绑定',
    forgetPwd: '忘记密码',
    mailCode: '邮箱验证',
    guide: {
      '1': '全新金融直播社区，投资分享，交流学习，知识变现，一站搞定！',
      '2': '重磅直播功能，随时随地看直播，在线互动，每次行情不错过！',
      '3': 'TradingLive 首届交易红人评选正式开启！',
      '4': '开直播，传视频，发布电子书，分享你的投资观点！',
      '5': '一键查看订阅讲师最新动态！',
      '6': '将TradingLive添加到桌面，下次直接从桌面访问！'
    },
    download: '下载App',
    scanLoad: '扫一扫，去下载',
    downloadInfo: '金融学习直播社区',
    tokenOverdue: '登录过期',
    loginAgain: '登录信息已过期，请重新登录'
  },
  seoTitle: {
    searchList: '{x} | {x}最新消息 - TradingLive',
    creation: '创作中心 - TradingLive',
    login: '登录 - TradingLive',
    aboutUs: '关于我们 - TradingLive',
    loginAgreement: '用户协议 - TradingLive',
    feedback: '意见反馈 - TradingLive',
    testDownload: 'TradingLive APP下载-提供最新苹果iOS版和安卓版APP下载',
    errorPage: 'TradingLive',
    index: 'TradingLive - 金融学习直播社区',
    liveList: '外汇交易实战直播_外汇投资直播_外汇实盘交易直播 - TradingLive',
    liveAudience: '{x} | TradingLive',
    anchorList: '主播人气排行榜 | TradingLive',
    videoList: '外汇交易教程视频 | 外汇培训视频 | 外汇初学者视频 - TradingLive',
    videoDetail: '{x} | TradingLive',
    articleList: '外汇电子书_外汇图书馆_外汇交易电子书在线阅读 - TradingLive',
    articleInfo: '{x} | TradingLive',
    chapterDetails: '{x} | TradingLive',
    lecturerList: '外汇培训讲师_外汇交易教学导师 - TradingLive',
    lecturerDetail: '{x} | TradingLive',
    mySubscribe: '我的订阅 | TradingLive',
    myReserve: '我的预约 | TradingLive',
    buyCourse: '已购课程 | TradingLive',
    myCollection: '我的收藏 | TradingLive',
    historyRecord: '历史记录 | TradingLive',
    authentication: '品牌中心 | TradingLive',
    buyBeans: 'F Coin中心 | TradingLive',
    myOrder: '我的订单 | TradingLive',
    myInformation: '消息中心 | TradingLive',
    personalData: '设置 | TradingLive',
    payOrder: '订单支付丨TradingLive',
    payStatus: '订单支付丨TradingLive',
    livingSelf: '我正在直播：{x}，快来观看吧！',
    livingOther: '{x}正在直播：{y}，快来观看吧！',
    upComing: '{x}，马上要开播了，快来预约吧！',
    voteNomination: 'TradingLive 交易红人评选',
    voteCandidate: 'TradingLive 交易红人评选-候选人',
    voting: 'TradingLive 交易红人评选-候选人投票',
    award: 'TradingLive 交易红人评选-颁奖典礼'
  },
  seoDesc: {
    searchList: 'TradingLive为您专业提供有关{x}的直播、视频和电子书，想了解{x}最新消息，来TradingLive。',
    testDownload:
      'TradingLive app是一款是以直播、视频、电子书和金融讲师为内容载体，覆盖外汇、股票和数字货币等多元知识领域的app，本页面为您提供TradingLive最新苹果版下载、iOS版下载以及TradingLive安卓版app下载等多种下载方式。',
    index:
      'TradingLive是全球首个多语言金融学习直播社区，以让投资学习更高效，知识分享更便捷为品牌使命。TradingLive以金融直播、视频、文章为内容载体，覆盖外汇、股票和数字货币等多元知识领域。',
    liveList:
      'TradingLive外汇直播栏目是一个外汇交易相关的金融直播室，提供外汇交易实盘解析、投资分享，交流学习等内容的视频直播。',
    liveAudience: '',
    anchorList:
      'TradingLive主播人气排行榜栏目为您提供又新又全的人气主播排行榜，主播相关视频内容，支持在线观看。更有海量高清外汇交易视频、相关直播、用户，满足您的在线观看需求。',
    videoList:
      'TradingLive视频栏目为您提供外汇交易教程视频、投资交易教学视频、经纪商资讯，交易分析视频，金融资讯视频等。',
    videoDetail: '',
    articleList:
      'TradingLive外汇电子书栏目为您免费提供外汇电子书，股票电子书，加密货币电子书，适合所有交易者了解关键交易概念、外汇技术和基本面分析。学习更多的外汇交易策略和外汇交易技巧。',
    articleInfo: '',
    chapterDetails: '',
    lecturerList:
      'TradingLive 对最佳外汇教育者，股票导师，数字货币导师进行了评级。 交易导师的知识和经验将帮助您在外汇市场和其他金融投资取得成功并避免常见的初学者错误。',
    lecturerDetail: '',
    voteNomination:
      'TradingLive 首届交易红人评选正式开启，聚焦「金融领域」，探索「投资机会」，发现「交易红人」，表彰「行业先锋」，覆盖「线上与线下」，现在提名你最喜爱的交易员，一起来参加这场专属于金融投资人的盛宴吧！',
    voteCandidate: 'TradingLive 首届交易红人评选正式开启，为您心仪的交易红人提名。',
    voting: '为您心仪的交易红人候选人进行投票，每天可投10票。',
    award: '颁奖典礼现场将颁发出交易红人评选奖项。经过提名候选人、投票等环节决出最佳交易红人。'
  },
  commons: {
    noData: '当前内容找不到了',
    lambeau: '100集系统化交易课程',
    lambeauTip: '100集外汇动画视频',
    lambeauTip1: '猴博士教你轻松学外汇',
    drLambeau: '猴博士',
    lambeauTrade: '猴博士外汇课程',
    lambeauTradeIntro: '系统动画课程，从新手到高阶！共100集！',
    search: '搜索',
    searchTag: '搜索标签',
    studyRecord: '学习记录',
    information: '消息',
    determineBtn: '确定',
    confirmBtn: '确认',
    cancelBtn: '取消',
    edit: '编辑',
    KnowledgePoint: '个知识点',
    noRelateContent: '暂无相关内容',
    tips: '本商品为虚拟商品，购买后不支持退换、转让，请谅解',
    video: '视频',
    read: '电子书',
    recommond: '推荐',
    lookMore: '查看更多',
    videoOff: '该视频已下架',
    articleOff: '该文章已下架',
    big: '小学',
    middle: '中学',
    small: '大学',
    huidou: 'F Coin',
    balance: '余额',
    startReadding: '开始阅读',
    sendValidCodeSuccess: '发送验证码成功',
    sendValidCodeFail: '获取失败，稍后再试',
    free: '免费',
    recommendTag: '推荐标签',
    menuList: [
      { label: '电子书', value: 1 },
      { label: '视频', value: 0 }
    ],
    backToTop: '返回顶部',
    simpleChinese: '简体中文',
    traditionalChinese: '繁體中文',
    homePage: '专注货币对交易的学习平台',
    commentLimit: '输入评论大于{x}个字符',
    showMe: '介绍一下你自己',
    changeLanguageMsg: '当前访问的语言与您不一致',
    changeLanguageBtn: '切换语言',
    bindMsg: '该账号已绑定其他用戶',
    currencyText: { BEAN: 'F Coin', CNY: 'CNY', TWD: 'TWD', USD: 'USD' },
    unloadMsg: { size: '上传头像图片大小不能超过!', limit: '上传头像图片只能是 JPG或者PNG 格式!' },
    discount: '优惠',
    slideMsg: '请滑动滑块验证',
    yesterday: '昨天',
    today: '今天',
    totalChapters: '共{x}章',
    totalSessions: '共{x}课',
    chapters: '章',
    next: '下一章',
    prev: '上一章',
    chapter: '章',
    and: '和',
    share: '分享',
    more: '更多',
    upload: '上传',
    uploadCoverTip: '为取得最佳显示效果。请使用一张不低于{x}x{y}像素的图片',
    images: '头像',
    see: '查看',
    all: '全部',
    seeAll: '查看全部',
    android: '安卓',
    go: '去',
    count: '次',
    totalFind: '共找到{x}门{y}相关课程',
    uploadImgFail: '上传失败,请重新上传',
    success: '成功',
    sessions: '课',
    diversity: '分集',
    slideToRight: '向右滑动验证',
    LOADING: '加载中...',
    ERROR_TITLE: '非常抱歉，这出错了...',
    CHECK_OUT: '验证通过',
    select: '请选择',
    AllEdit: '批量操作',
    comeBack: '返回',
    tip: '提示',
    ruleTip: '您是中国大陆地区用户，请访问符合大陆地区政策规定的银行实盘外汇网站',
    toLogin: '请登录符合大陆政策规定的网站',
    FBDescciption: '学外汇，上汇课堂！',
    purchase: '购买',
    detail: '详细信息',
    title: '标题',
    titlePlace: '请输入标题',
    introPlace: '请输入简介',
    announce: '公告',
    tag: '标签',
    selectTag: '选择标签',
    coverImg: '封面图',
    uploadCoverImg: '上传封面图',
    editCoverImg: '修改封面',
    scheduleTime: '安排时间',
    close: '关闭',
    end: '结束',
    or: '或者',
    report: '举报',
    fail: '失败',
    notFree: '付费',
    isPublic: '公开范围',
    public: '公开',
    self: '私密',
    timePublish: '定时发布',
    retry: '重试',
    publish: '发布',
    publishSuccess: '发布成功',
    publishFail: '发布失败',
    continueEdit: '继续编辑',
    unPublish: '取消发布',
    closeIntro: '返回后，您编辑的信息将不会被保存',
    community: '社区',
    preview: '预告',
    top: '榜单',
    failed: '失败',
    subscription: '订阅',
    deleteFail: '删除失败',
    deleteConfirm: '确认删除？',
    rankList: '排行榜',
    creationCenter: '创作中心',
    worksManage: '作品管理',
    cancelEdit: '取消编辑',
    offlineTip: '当前网络不可用，请检查网络连接',
    timeoutTip: '请求超时，请重试',
    ensureCancelSubscription: '确认取消订阅吗?',
    selectTagRequiredTip: '至少选择一个标签',
    didSetTagNumbers: '还可以选择{x}个标签',
    maxSelectTagTip: '选择标签数已达上限',
    tomorrow: '明天',
    skip: '跳过',
    interestTagTitle: '选择您感兴趣的标签',
    interestLangTitle: '选择您感兴趣的内容语言',
    interestTagTip: '根据兴趣，更好的为您生成内容',
    interestLangTip: '根据语言，更好的为您推荐内容',
    interestLangSubTip: '温馨提示：默认会为您推荐当前应用语言的内容',
    previewArticle: '预览',
    custom: '自定义',
    isFree: '是否收费',
    fwCoinVerPrice: 'F Coin原价',
    fwCoinPrice: 'F Coin折扣价',
    addChapterLength: '至多添加{x}个章节',
    required: '必填',
    selected: '精选',
    inputMsg: { tags: '请选择标签', image: '请上传封面图', fCoins: '请输入F Coins' },
    unAuthTip: { title: '暂未认证', msg: '认证通过后，才可以设置付费内容哦', confirmText: '去认证' },
    forbidText: '很抱歉，我们不对中国大陆开放',
    forbidTitle: '品牌使命',
    forbidIntro:
      'TradingLive作为全球首个多语言金融学习直播社区，旨在让投资学习更高效，知识分享更便捷。\n\n    TradingLive 提供英文、简体中文，繁体中文、越南语、泰语和阿拉伯语版本。',
    uploadTypeLimit: '只允许上传jpg、jpeg、png格式的图片',
    uploadSizeLimit: '请上传小于5M的图片'
  },
  index: {
    live: '精彩直播',
    video: '精选视频',
    ebook: '精选电子书',
    studentsEvaluation: '学员评价',
    lecturer: '全球名师',
    historicalRecord: '历史记录',
    avatangeOne: '交易学习平台',
    avatangeTwo: '行业资源优势',
    avatangeThree: '实现财富增值',
    avatangeOneTipsOne: '汇课堂是一个多元化的货币对交易学习平台',
    avatangeOneTipsTwo: '拥有超过150名专业货币市场领域的教师和编辑',
    avatangeTwoTipsOne: '依托丰富的互联网经验及货币市场行业资源优势',
    avatangeTwoTipsTwo: '汇课堂已吸引了全球16个国家与地区的货币对交易投资者注册使用',
    avatangeThreeTipsOne: '目前有超过20万的货币对交易投资者在汇课堂学习',
    avatangeThreeTipsTwo: '帮助越来越多的用户掌握货币对交易投资理财技能，实现财富增值',
    learn: '学习',
    alreadyOff: '该内容已下架',
    meta: {
      title: '汇课堂-专注货币对交易的学习平台',
      keywords: '货币对交易知识入门,货币对交易知识书籍推荐,货币对交易知识分享,货币对交易入门学习,货币对交易视频'
    }
  },
  setting: {
    avatar: '头像',
    nickName: '昵称',
    intro: '自我介绍',
    changeAvatar: '更换头像',
    changeBgImg: '更换背景',
    changeLanguage: '更改语言',
    changeLanguageSuccess: '更改语言成功',
    language: '语言',
    phoneNumberBind: '手机号绑定',
    phoneBind: '绑定',
    thirdAccountBind: '第三方帐号绑定',
    weixin: '微信',
    QQ: 'QQ',
    weibo: '微博',
    replaceBtn: '更换',
    bindBtn: '绑定',
    unBindBtn: '未绑定',
    untie: '解绑',
    verifyByThirdAccount: '通过第三方帐号验证',
    huiliao: '汇聊',
    sureToUntie: '确认解除绑定吗？',
    noSelfIntro: '添加一句自我介绍吧！',
    alertMsg: '为了你的帐号安全，请先绑定一种第三方帐号',
    untieSuccess: '解绑成功',
    emailNumberBind: '邮箱绑定',
    noSetPwd: '未设置密码',
    addPwd: '设置密码',
    edit: '修改',
    phoneLink: '手机',
    emailLink: '邮箱',
    password: '密码',
    currentPwd: '请输入原密码',
    enterPwd: '请输入新密码',
    confirmPwd: '请再次输入新密码',
    ensurePwdErr: '确认密码错误',
    changePassword: '修改密码',
    changePwdSuccess: '修改成功',
    modify: '修改',
    unBind: '未绑定',
    unSet: '未设置',
    checkEmail: '验证现有邮箱',
    checkEmailTip: '为了您的账户安全，需要进行验证',
    inputNewEmail: '输入新邮箱',
    inputNewEmailTip: '为了您的账户安全，需要进行验证',
    setPwdTip: '8-20位，至少包含数字/字母/符号2种组合',
    coverImg: '封面照片',
    editCover: '编辑封面',
    sex: '性别',
    sexList: [
      { label: '保密', value: 0 },
      { label: '男', value: 1 },
      { label: '女', value: 2 }
    ],
    area: '所在地区',
    email: '联系邮箱',
    link: '链接',
    add: '添加',
    birthday: '生日',
    modifyInfo: '修改信息'
  },
  myInformation: {
    lookLink: '查看链接',
    cancelReply: '取消回复',
    reply: '回复',
    replySuccess: '回复成功',
    menuList: [
      { label: '系统消息', value: 0 },
      { label: '活动通知', value: 2 },
      { label: '回复我的', value: 1 }
    ]
  },
  myOrder: {
    orderPayTime: '下单时间',
    orderNumber: '订单号:',
    cancelOrder: '取消订单',
    deleteOrder: '删除订单',
    deleteOrderMsg: '是否删除此订单',
    cancelOrderSuccess: '取消订单成功',
    deleteOrderSuccess: '删除订单成功',
    order: '订单',
    orderDetail: '订单详情',
    goHome: '回到首页',
    repay: '继续支付',
    course: '课',
    totalPrice: '总价',
    needPay: '需付',
    toPay: '去支付',
    goodsName: '商品名称',
    orderState: '订单状态',
    buyer: '购买者',
    buyerPhone: '购买者手机',
    buyerEmail: '购买者邮箱',
    goodsPrice: '商品价格',
    huidouPayment: 'F Coin支付',
    applePay: '苹果支付',
    googlePay: '谷歌支付',
    zhifubaoPayment: '支付宝',
    cashPayment: '支付金额',
    createTime: '订单创建时间',
    bugCourseStudy: '购买课程开始学习',
    shareForFree: '分享免费看',
    shareForFreeArticle: '分享免费看',
    bugOriginPrice: '原价购买',
    orderInfo: '订单信息',
    myHuidou: '我的F Coin',
    rechargeBeans: 'F Coin充值',
    purchaseInfo: '购买信息',
    courseInfo: '商品名',
    price: '价格',
    actuallyPay: '实付',
    limitedTimeOffer: '限时特惠',
    payWay: '支付方式',
    payCash: '需支付金额',
    payHuidou: '需支付F Coin',
    confirmPayment: '确认支付',
    tipsHuidou: 'F Coin已转入个人账户中',
    tipsPrev: '订单已放入已购课程中',
    tips: '若对此订单有疑问点击右下角问题反馈',
    loadingTips: '订单已生成，等待支付结果中 如对此订单有疑问点击右下角问题反馈',
    lookCourse: '查看课程',
    feedback: '问题反馈',
    actualPay: '实付金额',
    payTip: '请在24小时内完成支付',
    payByWeixin: '微信扫码支付',
    menuList: [
      { label: '全部订单', value: 1 },
      { label: '待支付', value: 2 },
      { label: '已完成', value: 3 },
      { label: '交易关闭', value: 4 }
    ],
    durationOpt: [
      { value: 1, label: '全部订单' },
      { value: 2, label: '最近半年' },
      { value: 3, label: '最近一个月' },
      { value: 4, label: '最近一周' }
    ],
    payStatus: { '1': '已支付', '2': '待支付', '3': '已过期', '4': '已取消', '5': '退款中', '6': '已退款' },
    orderStatus: { '2': '取消订单', '3': '删除订单', '4': '删除订单' },
    cancelOrderMsg: '是否取消此订单',
    knowledgePoint: '个知识点',
    zhifubaoMsg: '您已经跳转至支付宝收银台,是否已完成充值?',
    repayOrder: '重复支付订单',
    orderProcessing: '订单处理中',
    payOnline: '在线支付',
    payError: '订单支付失败，请重试'
  },
  myHuidou: {
    goodsName: '商品名称',
    transactionHour: '交易时间',
    revenueandExpenditure: '收支',
    transactionWay: '交易方式',
    congratulations: '恭喜你获得',
    payTip: '您的F Coin余额不足，请充值！',
    menuList: [
      { label: '全部记录', value: 0 },
      { label: '消费记录', value: 1 },
      { label: '充值记录', value: 2 }
    ]
  },
  myCollection: {
    edit: '编辑',
    favorite: '收藏',
    favoriteSuccess: '收藏成功',
    cancelFavor: '取消收藏',
    cancelFavorSuccess: '取消收藏成功',
    confirmCancelFavor: '确认取消收藏',
    sureToCancelFavor: '是否确认取消收藏此',
    conentcoubnt: '条内容？',
    sureToCancelFavorNum: '是否确认取消收藏此 {x} 条内容？',
    cancelChoose: '取消选择'
  },
  buyCourse: { selectAll: '全选', unSelectAll: '全不选' },
  buyBeans: {
    payRightNow: '立即支付',
    rechargeBeans: 'F Coin充值',
    huidouBill: 'F Coin账单',
    beansIncome: 'F Coin收入',
    description: '充值如遇到问题，请在反馈中选择【付费相关】提交相应说明，工作人员看到后会尽快联系您解决问题',
    huidou: 'F Coin',
    buyNow: '立即购买',
    transactionType: '交易类型',
    transactionHour: '交易时间',
    revenueandExpenditure: '收支',
    orderNumber: '订单号',
    conversion: '兑换',
    redeemCode: '我有兑换码',
    redeemPlaceholder: '请输入兑换码',
    converSuccess: '兑换成功',
    durationOpt: [
      { value: 1, label: '全部时间' },
      { value: 2, label: '最近半年' },
      { value: 3, label: '最近一个月' },
      { value: 4, label: '最近一周' }
    ],
    courseName: '课程名称',
    withdraw: '提现',
    beansIncomeOrder: '收入订单',
    income: '收入',
    warmPrompt: '温馨提示',
    withdrawIntro: '若要提现，请联系官方客服邮箱',
    known: '我知道了',
    balanceIntro: '通过充值购买、邀请码兑换以及参与活动领取的F Coin，不可以提现。但是可以用来购买课程。'
  },
  video: {
    tableContent: '目录',
    purchase: '免费解锁',
    relatedSuggestion: '相关推荐',
    courseComment: '课程评论',
    lookMoreComment: '查看更多评论',
    saySomeWord: '我也来说两句...',
    allComments: '全部评论',
    comments: '评论',
    hotComments: '热门评论',
    newestComments: '最新评论',
    hot: '热门',
    newest: '最新',
    reply: '回复',
    delete: '删除',
    cancelReply: '取消回复',
    noComments: '暂无评论',
    expand: '展开',
    retract: '收起',
    course: '课',
    videoTitle: '视频标题',
    videoUnavailable: '此视频暂无法播放，请稍后再试',
    playVideo: '播放',
    next: '下一集',
    pause: '暂停',
    mute: '音量',
    unmute: '静音',
    unmuted: '取消静音',
    fullScreen: '全屏',
    nonFullScreen: '退出全屏',
    reload: '重新加载',
    replay: '重播',
    networkAnomaly: '网络异常，请重新加载',
    noContent: '评论不能为空',
    deleteComment: '删除评论',
    deleteMsg: '是否要删除此评论',
    deleteSuccess: '删除成功',
    commonSuccess: '评论发布成功',
    delMsg: '该视频已删除',
    meta: {
      title: '货币对交易入门视频_货币对交易教程视频下载_货币对交易入门视频_货币对交易视频讲座-汇课堂',
      keywords:
        '货币对交易入门视频_货币对交易教程视频下载_货币对交易入门视频_货币对交易视频讲座_货币对交易技巧视频,货币对交易培训视频',
      description:
        '汇课堂货币对交易视频频道提供货币对交易入门视频，货币对交易教程视频下载，货币对交易入门视频，货币对交易知识视频讲座等最新教程，让货币对交易新手投资者快速入门学习货币对交易知识。'
    },
    videoText: '加载视频组件中...',
    loadingFail: '加载视频组件失败',
    noNext: '沒有下一集了',
    tryLook: '试看1分钟，',
    buyVideo: '购买观看全部',
    shareVideoFree: '分享观看全部',
    uploadVideo: '上传视频',
    dragFile: '拖放要上传的视频文件',
    selectFile: '选择文件',
    addDetail: '添加详细信息',
    introPlace: '向观看者详细介绍您的视频',
    coverImgIntro: '上传一张可展示您视频内容的图片，建议上传高清封面尺寸',
    publishVideo: '发布视频',
    uploadSuccess: '上传成功',
    uploadFail: '上传失败',
    intro: '简介',
    inputTitle: '请输入标题',
    price: '价格',
    free: '免费',
    pay: '付费',
    pulicScope: '公开范围',
    public: '公开',
    private: '私密',
    scheduleRelease: '定时发布',
    videoSize: '视频大小不能超过2G',
    videoFormat: '仅支持 MOV/MP4/MKV/FLV/AVI/3GP格式的视频',
    videoDuration: '视频时长不能短于10秒',
    mostSelect: '最多选择{x}个标签',
    miniplayer: '迷你播放器',
    exitMiniplayer: '展开',
    videoFormatTip: '视频大小上限为2G，时长不得短于10s，支持MP4, MOV, MKV, FLV, AVI, 3GP',
    uploadAgreement: '上传视频，即表示您已同意 TradingLive 的 {x} 和 {y}',
    retryUpload: '重新上传',
    uploadingVideo: '正在上传视频...',
    transcodingVideo: '正在处理视频...',
    uploading: '正在上传中',
    limit: '最多只能同时上传6个视频',
    skipTitle: '已为您跳过片头',
    uploadingcount: '正在上传{x}个',
    ranking: '视频热播榜',
    noSharing: '私密视频暂不支持分享',
    noSharingEbook: '私密电子书暂不支持分享',
    buyForWatch: '试看已结束，购买可观看完整视频',
    shareForWatch: '试看已结束，分享可观看完整视频'
  },
  search: {
    result: '结果',
    sorryMsg: '抱歉！沒有找到与 {x} 相关的內容。',
    relateContent: '相关的內容。',
    displayMore: '显示更多',
    totalFoundResult: '共{x}条搜索结果'
  },
  help: {
    feedback: '意见反馈',
    questionType: '问题类型',
    chooseType: '(选择你遇到的问题类型)',
    addPics: '添加相关图片',
    mostPics: '(最多4张)',
    addMoreMsg: '请输入具体信息',
    submit: '提交',
    submitSuccess: '提交成功',
    chooseClass: '请选择问题类型',
    limitContent: '请输入小于200个字符的反馈意见',
    contentEmpty: '请输入反馈内容'
  },
  errorPage: { ErrorTips: '抱歉，你访问的页面不存在。', returnHomePage: '返回首页' },
  article: {
    ebook: '电子书',
    purchase: '免费解锁',
    articleDirectory: '文章目录',
    chapter: '章节',
    moreChapter: '更多章节',
    nextPage: '下一章节',
    tableContent: '目录',
    primaryChapter: '小学篇',
    middleChapter: '中学篇',
    universityChapter: '大学篇',
    articleTitle: '文章标题',
    introduction: '简介',
    purchaseAll: '购买阅读全文',
    lastChapter: '已是最后一章',
    meta: {
      title: '货币对交易入门课程_货币对交易新手入门_货币对交易投资培训_货币对交易入门知识-汇课堂',
      keywords: '货币对交易入门，货币对交易新手入门，货币对交易投资培训',
      description:
        '汇课堂货币对交易学院频道提供货币对交易入门、货币对交易新手入门、货币对交易投资培训、货币对交易培训的最新教程，让货币对交易新手投资者快速入门学习货币对交易的基础知识。'
    },
    cardText: 'HUIKETANG',
    delMsg: '该文章已删除',
    uploadArticle: '上传电子书',
    coverImgIntro: '上传一张可展示您电子书内容的图片，建议上传高清封面尺寸',
    inputContent: '请输入正文',
    introPlace: '请输入简介说明',
    editChapter: '编辑章节',
    mostUploadImg: '最多支持上传100张图片',
    addArticleChapter: '新增章节',
    sellPrice: '请输入F Coin实付价格',
    uploadWord: {
      text: '点击上传或将文档拖拽至此处',
      limit: '文档不超过15M,支特doc及docx格式',
      checkLabel: '默认保留原文档格式，若要修改，请重新编辑后再次导入',
      formatError: '请上传.doc,.docx格式的文件',
      limitError: '文档不能超过15M',
      tips: [
        '1. 文件中的公式不支持导入，请手动输入公式',
        '2. 文档越大，解析时间越长，请耐心等待',
        '3. 若文档中存在编辑器不支持的文本样式（例如表格），将以纯文本展示',
        '4. 不能保证所有格式（例如公式、代码）都能正确导入，建议检查、确认无误后发布'
      ]
    },
    disabledTip: '暂不支持修改内容，若要修改，请重新编辑原文档后再次导入。',
    editorLimitedTip: '不能超过1万字符',
    bold: '加粗',
    picture: '图片',
    word: '文档'
  },
  account: {
    huiketang: 'TradingLive',
    goHuiketang: '学交易，上汇课堂！',
    accountSecret: '汇聊老用户？点这里账密登录',
    loginAndRegister: '点这里手机验证码登录/注册',
    thirdLogin: '其他第三方登录',
    loginHuiketang: '登录汇课堂',
    code: '手机验证码',
    mobileLogin: '手机登录',
    loginByaccountSecret: '账密登录',
    createAccount: '未注册用户将自动创建帐号',
    loginRegister: '登录/注册',
    agree: '注册登录即代表您已同意',
    userProtocol: '《汇课堂用户协议》',
    privacyProtocol: '《汇课堂隐私协议》',
    phone: '请输入手机号',
    password: '请输入密码',
    codeInput: '请输入验证码',
    login: '登录',
    loginOrEstablish: '创建/登录',
    forgetPassqord: '忘记密码？',
    goHuiliao: '前往汇聊找回',
    getCode: '获取验证码',
    remaining: '剩余{x}秒',
    seconds: '秒',
    level: '等级说明',
    upgradeLevel: '提升等级',
    downLoad: '扫码下载 TradingLive APP',
    consolidate: '在 TradingLive APP中进行试题练习，巩固已学交易知识，提升自己的等级！',
    accountSafety: '帐号安全',
    bindMibile: '绑定手机号',
    bindMibileTip: '绑定手机号完成注册',
    finishRegister: '完成注册',
    loginObtain: '登录领取',
    verifyObtain: '请验证手机领取F Coin',
    obtainBean: '领取F Coin',
    ruleOne: '请使用参与活动的手机号登录汇课堂app，登录后权益自动到账',
    ruleTwo: '活动时间：长期有效',
    ruleThree: '每个汇课堂用户仅能从一次分享中得到一次F Coin',
    userAgreement: '用户协议',
    privacyAgreement: '隐私政策',
    riskAgreement: '风险披露',
    intelligentAgreement: '认证协议',
    communityGuidelines: '社区准则',
    helpCenter: '帮助中心',
    regionLanguage: '区域语言',
    correctPhone: '请输入正确的手机号码',
    correctCode: '请输入正确的验证码',
    correctPass: '请输入正确的密码',
    validateTip1: '没收到短信？',
    validateTip2: '试试邮箱验证',
    agreementList: [
      { title: '用户协议', type: 1 },
      { title: '隐私政策', type: 2 },
      { title: '风险披露', type: 3 },
      { title: '认证协议', type: 5 },
      { title: '社区准则', type: 6 }
    ],
    brandsText: '继续即表示您同意TradingLive的认证协议'
  },
  pagination: { lastPage: '上一页', nextPage: '下一页' },
  share: {
    invite: '分享邀好友，免费学课程',
    rule: '分享得F Coin规则',
    QRCode: '微信扫二维码分享',
    copy: '复制',
    ruleDescription: '规则说明:',
    firstRule:
      '1、分享付费课程给好友助力，每有一个用户注册或者登录时，分享者可获得100F Coin，助力者若是新用户可获得100F Coin，若是老用户则得30F Coin；',
    secondRule: '2、同一个课程链接分享者最多获得10人助力，获得F Coin上限为1000个，助力者对同一个课程链接只能助力1次；',
    thirdRule: '3、分享者与助力者使用参与活动的手机号登录汇课堂app后，所获得的F Coin会自动到账；',
    fourthRule: '4、活动时间：长期有效。',
    getHuidou: '登录后才能获取F Coin',
    huiketangTitle: '领F Coin, 学交易',
    freeGet: '免费得',
    originalPriceBuy: '原价购买',
    getMethod: '选择一种获取途径',
    shareFriend: '分享给好友',
    toShareLink: '已复制链接,分享给您的好友吧~',
    errorShare: '分享失败',
    im: '我是',
    allGet: '已全部拿到',
    sharePersonMsg: '为您助力，离获得全部还差一小步',
    late: '遗憾，来晚了一步'
  },
  personCenter: {
    baseInfo: '基本信息',
    userMenuList: {
      buyCourse: '已购课程',
      myCollection: '我的收藏',
      mySubscribe: '我的订阅',
      myReserve: '我的预约',
      buyBeans: 'F Coin中心',
      myOrder: '我的订单',
      myInformation: '消息',
      historyRecord: '历史记录',
      authentication: '品牌中心',
      setting: '设置'
    },
    settingMenuList: [
      { title: '个人资料', name: 'personalData' },
      { title: '帐号安全', name: 'accountSecurity' }
    ],
    confirmBtn: '保存',
    changeInfoFail: '修改信息失败',
    editSuccess: '修改成功',
    bindSuccess: '绑定成功',
    message: {
      about: { pattern: '请输入0-200字符之间的自我介绍' },
      nickname: { required: '昵称不能为空', pattern: '请输入1-50个字符的昵称' }
    },
    goHome: '{x}秒 后自动跳转到首页',
    PersonalHomepage: '个人主页',
    myReserve: '我的预约',
    msgCenter: '消息中心',
    reserveMenuList: [
      { label: '正在直播', value: 2, type: 2 },
      { label: '即将开始', value: 1, type: 1 },
      { label: '回放', value: 3, type: 3 }
    ],
    lecturerLambeauVideoTagList: [
      { label: '全部', value: 0, type: 0 },
      { label: '入门', value: 1, type: 1 },
      { label: '技术分析', value: 2, type: 2 },
      { label: '基本面分析', value: 3, type: 3 },
      { label: '交易策略', value: 4, type: 4 },
      { label: '交易心理', value: 5, type: 5 },
      { label: '知识点', value: 6, type: 6 }
    ],
    doctorHou: '猴博士外汇课程',
    selectSex: '请选择性别',
    selectArea: '请选择地区',
    inputEmail: '请输入邮箱',
    inputURL: '请输入网址',
    accountName: '用户名'
  },
  bookmark: { cancel: '取消书签', add: '添加书签', successCancel: '取消书签成功~', successAdd: '添加书签成功~' },
  pictures: { error: '上传图片只能是JPG或PNG格式', limitSizeError: '上传图片大小不能超过 5MB!' },
  examination: { remind: '非常抱歉，网站不支持考试相关内容', downloadRemind: '请下载APP体验' },
  shareHelp: {
    shareTitle: '助力赢F Coin，免费学交易!',
    shartContent: '正在使用汇课堂学习货币对交易，这是我最近学习的课程，需要获得你的协助',
    amount: '已被助力{x}次',
    assistWill: 'F Coin助攻墙',
    shareTips: '暂时还没有好友助攻',
    shareBtn: '助力好友领取F Coin',
    haicha: '还差{x}次拿到全部F Coin'
  },
  download: {
    index: '下载',
    trade: '交易学习',
    tip1: '文章+动画视频结合',
    tip2: '形式丰富，内容通俗易懂',
    test: '考试巩固',
    tip3: '1000+课后习题与考卷',
    tip4: '巩固知识，检验学习效果',
    pk: 'PK对战',
    tip5: '挑战榜单对手答题PK',
    tip6: '趣味不断，学习娱乐两不误',
    tip7: '学交易，上汇课堂',
    tip8: '你想要的交易知识统统都有！'
  },
  about: {
    aboutUs: '关于我们',
    contactUs: '联系我们',
    aboutFxy: '关于TradingLive',
    aboutFxyContent1:
      'TradingLive是一个专注于外汇教育的学习平台，致力于为外汇投资者提供从入门、进阶到精通的体系化外汇学习内容。',
    aboutFxyContent2:
      '我们团队围绕多元化学习与游戏化做题为核心，通过原创动画视频与文章为知识载体，为用户提供系统全面、有趣易懂的外汇学习课程。另外在移动端APP我们还提供1000+外汇知识题目与解析，引进游戏化的PK机制，让外汇投资学习更具趣味性。',
    vision: '愿景',
    visionContent:
      'TradingLive 希望充分利用互联网的便利，为全球外汇交易者打造一个外汇垂直领域的教学平台，通过提供高效高价值的外汇内容与课程，帮助越来越多的投资者减少行业信息不对称，并掌握外汇交易的知识与技能。',
    mediaRepost: '媒体报道',
    partner: '合作伙伴',
    contactUsContent:
      '我们一直在努力改进我们的服务，并重视您的反馈。 如果您有什么要告诉我们的，请使用以下邮箱与我们联系以获得有关外汇或与本网站相关的任何内容的帮助或支持。',
    email: '邮箱',
    contactUsBy: '通过以下社交网络关注我们'
  },
  footer: {
    aboutUs: '关于我们',
    contactUs: '联系我们',
    userAgreement: '用户协议',
    privacyPolicy: '隐私政策',
    riskContent:
      '金融工具交易属于高风险投资活动，有导致部分或全部投资本金损失的风险，可能不适合所有投资者。本网站所包含的任何观点、聊天信息、通知、新闻资讯、研究调查、分析、价格或其他信息都是作为一般市场信息提供的，仅供教育和娱乐之用，并不构成投资建议。 所有的观点、市场行情、推荐或任何其他内容可能随时会改变，恕不另行通知。TradingLive对因使用或根据这些信息而直接或间接造成的任何损失或损害概不负责。'
  },
  login: {
    signInTitle: '登录',
    createTitle: '注册',
    email: '邮箱',
    mobile: '手机号',
    emailPlaceHolder: '请输入邮箱',
    passwordPlaceHolder: '请输入密码',
    forgetPassword: '忘记密码?',
    signIn: '登录',
    signUp: '注册',
    createAccount: '创建账号',
    singEmail: '去登录',
    signInSuccess: '登录成功!',
    agreementTip: '注册/登录表示您已阅读并同意《用户协议》和《隐私政策》',
    otherLogin: '第三方登录',
    needEmail: '请输入邮箱',
    errEmail: '邮箱格式错误，请重新输入',
    needPassword: '请输入密码',
    toLongPassword: '密码长度需为 8-20 个字符',
    errPassword: '密码必须包含数字/字母/符号中两种组合',
    send: '发送',
    nextStep: '下一步',
    preStep: '上一步',
    finish: '完成',
    setNewPwd: '请输入新密码',
    setNewPwdAgain: '请再次输入新密码',
    submit: '提交',
    resetComplete: '密码重置成功!',
    successReset: '您的密码已被重置，快去体验吧！',
    bindEmail: '绑定邮箱',
    bindPhone: '绑定手机号',
    bindOtherLoginTip: '为了您的账户安全，需要进行验证',
    welcomeBack: '设置密码',
    backTip: '8-20位，至少包含数字/字母/符号2种组合',
    enter: '验证邮箱',
    setPwd: '设置密码',
    done: '完成',
    inputMailCode: '输入邮箱验证码',
    signLoading: '正在登录中...',
    haveAccount: '已经有账号？',
    haveNoAccount: '还没有账号？'
  },
  lecturer: {
    lecturer: '讲师',
    location: '地区',
    classification: '分类',
    lecturerScore: '讲师评分',
    lecturerAvarge: '讲师头像',
    resetFilter: '重置条件',
    subscribe: '订阅',
    alreadySubscribe: '已订阅',
    works: '{x} 作品',
    worksNum: '{x} 作品数',
    fans: '{x} 粉丝',
    subscriber: '{x} 订阅者',
    messageBoard: '社区',
    message: '留言',
    confirmSetScore: '评分提交确认',
    setScore: '确定给该讲师评分为{x}分',
    age: '年龄',
    businessEmail: '商务邮箱',
    briefIntroduction: '简介',
    videoWorks: '视频作品',
    articleWorks: '文章作品',
    lecturerEvaluate: '讲师满意度评价',
    personalProfile: '个人简介',
    presonalInformation: '个人信息',
    homePageLink: '链接',
    scored: '{x}人已评',
    addScore: '评分成功',
    subscribeSuccess: '订阅成功',
    cancleSubScribeSuccess: '取消订阅成功',
    addAppToDesk: '添加到桌面',
    addAppTitle: '添加TradingLive到桌面',
    addAppIntrol: '下次可从桌面直接访问TradingLive',
    addAppRightNow: '立即添加',
    noIntroduction: '该讲师暂时没有简介',
    joinRightNow: '立即加入',
    lecturerDisable: '该讲师已被封禁'
  },
  creationCenter: {
    date: '日期',
    viewerCount: '观看量',
    commentCount: '评论量',
    collection: '收藏量',
    shareCount: '转发量',
    downloadCount: '下载量',
    approvalStatus: '当前状态',
    approvalling: '审核中',
    approvalFail: '审核未通过',
    approvalSuccess: '审核通过',
    localLive: '本地直播',
    otherLive: '第三方直播',
    playback: '回放生成中：{x}分钟'
  },
  authentication: {
    intelligent: '达人认证',
    intelligentTips: '适合内容创作者进行认证，认证通过后将获得一系列创作激励权益。',
    identifyLabel: '独特身份标识',
    trafficSupport: '流量扶持',
    contentRevenue: '付费内容收入',
    divideInto: '广告分成',
    brands: '品牌入驻',
    brandsTips: '适合品牌方入驻，扩大品牌曝光，触达行业名人，精准投放广告，助力商业增长。',
    certificationMark: '独特认证标识',
    brandExposure: '品牌曝光',
    advertising: '投放广告',
    startCertification: '开始认证',
    startEnter: '开始入驻',
    warmPrompt: '温馨提示：一个账号只能选择一种认证方式',
    intelligentUnderReview:
      '达人认证审核中，我们将在3-5个工作日内处理您的认证请求。认证通过后将认证成功邮件到您的邮箱，同时您也可以留意该账号的认证状态。',
    brandsUnderReview:
      '品牌入驻审核中，我们将在1-2个工作日内处理您的入驻请求。认证通过后将会以邮件的形式给您发送认证信息，同时您也可以留意该账号的认证状态。',
    intelligentSuccess: '您的账号已进行达人认证，该账号将享有以下权益：',
    intelligentSuccessInfo:
      '\n      <p>1.独特的身份标识。</p>\n      <p>2.该账号发布的内容将会获得优先推荐的机会。</p>      \n      <p>3.该账号可上传付费内容并获得收入。</p>    \n      <p>4.该账号可参与广告分成。</p>\n    ',
    brandsSuccess: '该账号已完成品牌入驻，入驻信息如下：',
    brandsSuccessInfo: '\n      <p>企业名称：{x}</p>\n      <p>企业网站：{y}</p>\n    ',
    intelligentFailed: '非常抱歉，您的达人认证审核不通过，原因如下：',
    brandsFailed: '非常抱歉，您的品牌入驻审核不通过，原因如下：',
    reauthentication: '重新认证',
    againReauth: '重新入驻',
    startIntelligent: '开始达人认证',
    submitInfo: '提交认证信息',
    worksCount: '发布作品数 >= 5',
    subscribeCount: '订阅数 >= 200',
    bindEmail: '绑定邮箱',
    toMeet: '已满足',
    failToMeet: '未满足',
    authNow: '立即认证',
    realName: '真实姓名',
    inputRealName: '请输入真实姓名',
    countryName: '国家',
    selectCountry: '请选择国家',
    creationType: '创作类型',
    selectCreationType: '请选择创作类型',
    creationTypeList: [
      { value: 2, label: '视频' },
      { value: 3, label: '直播' },
      { value: 1, label: '电子书' }
    ],
    socialMediaLink: '社交媒体链接',
    inputSocialMediaLink: '请输入社交媒体链接',
    restsContact: '其他联系方式',
    inputRestsContact: '请输入其他联系方式',
    contactsName: '联系人姓名',
    inputContactsName: '请输入联系人姓名',
    contactsJob: '联系人职位',
    inputContactsJob: '请输入联系人职位',
    enterpriseName: '企业名称',
    inputEnterpriseName: '请输入企业名称',
    enterpriseType: '企业类型',
    selectEnterpriseType: '请选择企业类型',
    enterpriseScale: '企业规模',
    selectEnterpriseScale: '请选择企业规模',
    enterpriseWebsite: '企业网站',
    inputEnterpriseWebsite: '请输入企业网站',
    enterpriseEmail: '联系邮箱',
    inputEnterpriseEmail: '请输入联系邮箱',
    submitIntelligent: '已提交达人认证请求',
    submitBrands: '已提交品牌入驻请求'
  },
  live: {
    live: '直播',
    livePreview: '直播预览',
    startLive: '开始直播',
    createLive: '创建直播',
    titlePlace: '添加一个可描述您直播的标题',
    introPlace: '向观看者详细介绍您的直播',
    announce: '添加一条置顶直播间的公告',
    coverImgIntro: '上传一张可代表您的直播的图片',
    liveLink: 'YouTube直播链接',
    liveLinkIntro: '复制您在YouTube已创建直播的链接，以便可以同步开始直播',
    isPlayback: '开启回放',
    playback: '回放',
    liveTimeIntro: '选择您要开始直播的时间',
    deviceManage: '设备管理',
    noDevice: '暂无设备',
    camera: '摄像头',
    microphone: '麦克风',
    screenManage: '屏幕管理',
    shareScreen: '共享屏幕',
    shareScreenIntro: '将您的屏幕内容实时展示给观众',
    resolutionSelect: '清晰度选择',
    endLive: '结束直播',
    endLiveTips: '观众正在赶来的路上，确认结束直播？',
    chatRoom: '聊天室',
    wannaSay: '我想说两句...',
    addDevice: '添加设备',
    clearAll: '清空全部',
    clearAllIntro: '确定要清除所有设备？',
    startTime: '开始时间',
    startTimeTip: '距离 {x} 开播还有',
    day: '天',
    hour: '时',
    min: '分',
    second: '秒',
    peopleReserved: '{x} 人已预约',
    invite: '邀请好友',
    watched: '观看',
    reserve: '预约',
    reserveNow: '立即预约',
    reserved: '已预约',
    isAllowPlay: '是否允许浏览器播放声音',
    newMsg: '{x} 新消息',
    anchorComing: '主播还在赶来的路上，稍等片刻~',
    anchorLeave: '主播暂时离开，休息一下~',
    livePlayback: '回放视频正在制作中，请稍后观看',
    recommendLive: '推荐直播',
    clickWatchLive: '点击观看直播',
    clickWatchPlayback: '点击观看回放',
    loadFailTry: '加载失败，请点击重试~',
    liveEnd: '直播已结束',
    mute: '禁言',
    unmute: '取消禁言',
    recall: '撤回',
    someoneMuted: '{x}被禁言',
    someoneUnmuted: '{x}被取消禁言',
    topRule: '排行榜根据近期的热度展示，动态更新',
    turnOffCamera: '关闭摄像头',
    turnOffMicro: '关闭麦克风',
    liveIntro: '直播简介',
    audience: '{x} 名观众',
    recommendFilm: '推荐影片',
    banned: '你被主播禁言',
    goodRecommendation: '精彩推荐',
    reserveSuccess: '预约成功',
    cancelReserveSuccess: '取消预约成功',
    selectDevice: '请选择设备开播',
    getCameraFail: '摄像头启用失败，请检查设备是否正常',
    getMicrophoneFail: '麦克风启用失败，请检查设备是否正常',
    shareScreenFail: '共享屏幕失败，请重试',
    recoverLiveConfirm: '是否恢复直播？',
    recoverLive: '恢复直播',
    freshFail: '刷新失败',
    addLiveDevice: '添加直播设备',
    startSoon: '即将开始',
    emptyTip: '不能发送空的内容哦！',
    isMuted: '您已被禁言',
    isUnmuted: '您已被取消禁言',
    sendErrorTryAgain: '评论发送失败，再试一次吧~',
    liveCenter: '直播中心',
    liverOffShelf: '因为涉嫌违规，您的直播被下架。',
    liveOffPower: '抱歉，您的直播权限已被关闭。',
    liveDurationTime: '开播时长',
    watchLiveCount: '观看人数',
    newSubscribeCount: '新增粉丝',
    thumbsUpsCount: '点赞数量',
    commentCount: '评论数量',
    safetyTip:
      'TradingLive努力营造积极健康的直播氛围，对直播内容进行24小时巡查。任何传播违法、违规、低俗等不良信息的行为一经发现，违规者账号将予以封禁处理。',
    guessYouLike: '猜你喜欢',
    haveNoIntro: '暂无简介',
    enterLiveRoom: '进入直播间',
    closeVideo: '关闭视频',
    openVideo: '开启视频',
    enterSelfLive: '您当前正在直播，暂时无法观看，否则会影响直播效果~',
    reserveLiveStarted: '您预约的直播开始',
    reserveLiveStartedTip: '{x}正在直播：{y}，快来观看吧！',
    noWatch: '暂不观看',
    watchNow: '立即观看',
    liveStartRemind: '开播提醒',
    liveStartRemindTip: '您发布的直播马上就要开始啦，请前往直播间准时开播。',
    startLiveNow: '去开播',
    noStartLive: '暂不开播',
    viewOriginal: '查看原文',
    viewTranslation: '查看翻译',
    auto: '自动',
    youTubeHelp: {
      title: '如何生成YouTube视频链接？',
      or: '或者',
      conList: [
        '首先，在YouTube上创建直播预约，开始直播→摄像头→创建直播→直播预览→分享→复制视频链接；',
        '其次，将视频链接粘贴至输入框，并填写预告信息；',
        '最后，当您在YouTube开启直播后，TradingLive将同步开启直播。'
      ]
    },
    views: '{x} 次观看',
    startDate: '直播时间',
    ranking: '主播排行榜',
    appHadStart: '您已在App端开启直播',
    confirmLeave: '当前正在直播，确定离开此页面？',
    scanQrcode: '扫描二维码，在手机上观看'
  },
  obsLive: {
    desc: '关联直播软件以开始直播，当开始直播后，观众将会收到您的直播推送',
    help: '视频流设置帮助',
    setting: '直播设置',
    serviceAddr: '服务器地址',
    streamSecret: '串流秘钥',
    helpDetail1: '1. 下载并设置您的直播软件',
    helpDetail2: '2. 将服务器地址和串流秘钥粘贴至您的软件中',
    helpDetail3: '3. 使用您的直播软件开始向我们发送您的视频流',
    liveNow: '{x}正在直播',
    copyFailed: '复制失败',
    copySuccess: '复制成功'
  },
  report: {
    reportTitle: '举报原因',
    reportSuccessTitle: '感谢您的反馈！',
    reportSuccessContent: '非常感谢您的支持，我们将尽快处理。'
  },
  aboutUs: {
    contactUs: '联系我们',
    about: {
      title: '关于我们',
      intro: 'TradingLive作为全球首个多语言金融学习直播社区，旨在让投资学习更高效，知识分享更便捷。'
    },
    brandStory: {
      title: '品牌故事',
      intro:
        'TradingLive诞生的初衷是为了打破边界，通过直播社区拉近普通投资者与专业投资者之间的距离。\n\n全球超35个国家的投资者在我们的社区中精进，我们致力于打造专业而多元的金融学习社区，我们的认证讲师大多数曾任职于全球顶尖金融机构或私募基金机构。\n\nTradingLive在未来将继续聚焦于投资者教育，通过一系列的扶持政策，进一步推动金融外汇行业的发展。'
    },
    live: { title: '直播', intro: '让投资学习更高效' },
    shortVideoShooting: { title: '短视频', intro: '随时随地开启拍摄，分享投资观点' },
    globalMentors: { title: '全球讲师', intro: '汇聚全球金融讲师' },
    wonderfulFinancialVideos: { title: '精彩视频', intro: '让知识分享更便捷' },
    selectedEBooks: { title: '精选电子书', intro: '聚合全球金融资讯' },
    events: { title: '展会活动', intro: '参加TradingLive展会活动，提升公司品牌知名度' },
    ourPartners: { title: '合作伙伴', intro: '品牌曝光' },
    downloadApp: { title: '下载App', intro: '立即加入金融直播社区' },
    scanAppText: '扫码下载TradingLive App',
    business: '商务合作',
    followUs: '关注我们',
    feedback: '意见反馈',
    more: '更多讲师',
    viewPage: '查看个人主页',
    drLambeau: { title: '猴博士外汇课程', intro: '100集系统化的外汇课程，有趣生动的动画教学，让你从新手到高手！' }
  },
  activity: {
    nominationNow: '立即提名',
    viewCandidate: '查看交易员',
    tip: '提名将于3月13日正式开启',
    rule: '活动规则',
    vote: '投票',
    voteEnd: '投票已结束',
    voteEndTip: '获奖者将在颁奖典礼上公布',
    comingsoon: '敬请期待',
    nomination: '提名交易员',
    inputTraderName: '请输入交易员名字',
    nominationEnd: '提名阶段已结束',
    surname: '姓氏',
    name: '名字',
    inputSurname: '请输入姓氏',
    inputName: '请输入名字',
    company: '公司名称',
    inputCompany: '请输入公司名称',
    companyEmail: '提名人邮箱',
    inputEmail: '请输入提名人邮箱',
    correctEmail: '请输入正确的邮箱地址',
    nominationField: '提名领域',
    selectField: '请选择提名领域',
    nominationLimit: '每人最多提名3个领域，您已达提名上限',
    post: '职位',
    inputPost: '请输入职位',
    nominationReason: '提名理由',
    inputReason: '请输入提名理由',
    avatar: '交易员照片',
    imgTip: '建议头像尺寸1:1，大小需小于5M',
    imgLimit: '请上传小于5M的图片',
    uploadAvatar: '请上传交易员照片',
    submit: '提交',
    submitSuccess: '官方审核通过后即可参与投票',
    continueNomination: '继续提名',
    backToActivity: '返回活动页面',
    success: '提名成功',
    title_1: '交易红人评选',
    searchHistory: '搜索历史',
    nominationShareTitle: '{x}已被提名{y}，快来看看吧！',
    votingShareTitle: '{x}正在竞选{y}，快来为我投票吧！',
    awardShareTitle: '{x}荣获{y}，快来看看吧！',
    shareDesc:
      'TradingLive首届交易红人评选正式开启，聚焦「金融领域」，探索「投资机会」，发现「交易红人」，表彰「行业先锋」，覆盖「线上与线下」，现在提名你最喜爱的交易员，一起来参加这场专属于金融投资人的盛宴吧！',
    voteCount: '最终得票',
    voteSuccess: '投票成功，您今天还剩{x}票！',
    voteLimit: '已达投票上限',
    voteLimitTip: '当前账号已达每日投票上限，您可通过以下方式提升每日投票次数。',
    shareAddVote: '每日分享活动或交易员——每日投票次数+5',
    shareNow: '立即分享',
    loginAddVote: '每日登录TradingLive——每日投票次数+10',
    loginNow: '立即登录',
    voteCountLimit: '当前账号已达每日投票上限，您可邀请其他用户来为您喜爱的交易员投票。',
    voteDeviceLimit: '当前设备已达投票上限',
    voteIpLimit: '当前IP已达投票上限',
    emailAddress: '邮箱地址',
    inputEmailAddress: '请输入邮箱地址',
    voteNow: '立即投票',
    inputEmailCode: '请输入验证码',
    sendCode: '发送验证码',
    second: '秒',
    voteTip: '投票说明：请使用真实账户进行投票，TradingLive会对虚假投票进行过滤。',
    sliderTip: '请向右滑动验证',
    verifySuccess: '验证成功',
    voteException: '投票异常',
    voteExceptionTip1: '请完成安全验证以继续投票',
    review: '往期回顾',
    voteExceptionTip2: '投票失败，请联系活动工作人员',
    emailCode: '验证码',
    loginSuccess: '登录成功，您可立即投票',
    nextVerify: '再进行一步验证以继续登录',
    sliderToverify: '请滑动滑块完成验证',
    addVoteFailed: '登录加票失败，该TradingLive账号今天已经加过票',
    addVoteFailed1: '登录加票失败，该投票邮箱今天已经加过票',
    addVoteSuccess: '登录加票成功，您今天还剩{x}票',
    voteFailed: '投票失败，请刷新后重试',
    done: '已完成',
    securityVerification: '安全验证',
    securityVerificationTxt: '请选择正确答案以完成验证',
    securityVerificationError: '验证失败',
    securityVerificationErrorTxt: '您已验证失败多次，请稍后再试',
    contactUs: '如有任何疑问，请联系event@trading.live',
    confirm: '确认',
    again: '请再试一次',
    answerVerifySuccessTitle: '验证成功',
    answerVerifySuccessSubtitle: '安全验证通过，请继续投票'
  }
}
