export default {
  common: {
    confirm: '确定',
    affirm: '确认',
    remove: '删除',
    cancel: '取消',
    tips: '提示',
    finish: '完成',
    know: '知道了',
    time: '时间',
    count: '{x} 个',
    hand: '{x} 手',
    order: '{x} 单',
    score: '{x} 分',
    person: '{x} 人',
    times: '{x} 次',
    second: '{x} 秒',
    minutes: '{x} 分钟',
    hour: '{x} 小时',
    day: '{x} 天',
    month: '{x} 个月',
    year: '{x} 年',
    shortsecond: '{x} 秒',
    shortminutes: '{x} 分钟',
    shorthour: '{x} 小时',
    shortday: '{x} 天',
    justNow: '刚刚',
    minuteAgo: '{x} 分钟前',
    hourAgo: '{x} 小时前',
    yesterday: '昨天 {x}',
    beforeYesterday: '前天 {x}',
    yearUnit: '年',
    monthUnit: '月',
    dayUnit: '天',
    hourUnit: '时',
    minutesUnit: '分',
    secondUnit: '秒',
    hundredMillion: '{x} 亿',
    trillion: '{x} 万亿',
    loading: '加载中...',
    noMore: '没有更多数据了',
    all: '全部',
    reset: '重置',
    unfoldAll: '展开全部',
    packUp: '收起',
    unfold: '展开',
    back: '返回',
    warning: '警告',
    noData: '暂无数据',
    imageFormat: '仅支持 JPG、JPEG 或 PNG 的图片格式！',
    imageSize: '图片大小不得超过 {x} MB',
    shareFb: '分享FastBull，获取一个月的跟单权限',
    noNetLaterTry: '网络异常，请稍后再试...',
    copy: '复制',
    copySuccess: '链接已复制',
    appDownload: 'APP下载-FastBull',
    fbDownload: 'FastBull APP下载',
    getSuccess: '已获取一个月跟单权限',
    reLogin: '登录状态已失效，请重新登录。',
    notFound: '抱歉，您访问的页面地址有误或者该页面不存在',
    returnToLast: '返回上一页',
    returnToHome: '返回首页',
    forbidden: '访问被拒绝',
    noAccess: '您无权使用所提供的凭据查看此目录或页面。',
    serverError: '出错了',
    tryRefresh: '请刷新页面再试一次',
    operationConfirm: '操作确认',
    select: '请选择',
    download: '下载',
    close: '关闭',
    isDelete: '已删除',
    noResult: '抱歉，未能找到相关结果',
    tryAgain: '您可以尝试更换关键词再次进行搜索',
    loginInOther: '您的账号在另外一浏览器上登录。如非本人操作，则密码可能泄露，请立即修改密码',
    chartLoading: '图表加载中...',
    custom_service: '客服',
    common_look: '查看'
  },
  message: {
    messageCenter: '消息中心',
    system: '社区通知',
    trading: '交易信号',
    comment: '评论回复',
    account: '账户通知',
    answer: '专家问答',
    noMoreData: '没有更多数据了',
    viewAll: '查看全部',
    noNewMsg: '暂无新消息',
    noMessage: '消息空空如也',
    systemMsgTypeList: [
      {type: 0, label: '所有内容'},
      {type: 1, label: '社区通知'},
      {type: 3, label: '我跟随的'},
      {type: 4, label: '跟随我的'}
    ],
    commentMsgTypeList: [
      {type: 0, label: '账户评论'},
      {type: 1, label: '新闻评论'},
      {type: 2, label: '视频评论'}
    ],
    accountMsgTypeList: [
      {type: 0, label: '所有内容'},
      {type: 1, label: '账户变动'},
      {type: 2, label: '排名更新'},
      {type: 4, label: '交易战报'}
    ],
    open: '开仓',
    openTime: '开仓时间',
    close: '平仓',
    closeTime: '平仓时间',
    riskWarning: '风险警告',
    subscribeNotice: '跟单公告',
    clickView: '点击查看',
    allSource: '所有来源',
    replyYou: '回复了您',
    answerYou: '回答了您的提问',
    commentAccount: '评论了您的交易账户',
    commentYou: '评论了您',
    viewDetail: '查看详情',
    commentTypeList: ['账户评论', '消息回复'],
    reportAccount: '举报了您的交易账户',
    waitFollow: '等待跟随',
    followSuccess: '跟随成功',
    followFailed: '跟随失败',
    ignore: '已忽略',
    tryFollow: '正在尝试跟随此信号，请稍后...',
    followOrder: '跟随订单',
    followStatus: '跟随状态',
    unit: '单位',
    noSignal: '暂无交易信号',
    orderId: '跟随订单ID',
    statusList: ['等待跟随', '跟随成功', '跟随失败', '已忽略'],
    statusTitle: ['等待原因', '跟随订单ID', '失败原因', '忽略原因'],
    goSetting: '前往设置',
    viewOrder: '查看订单',
    stopProfit: '止盈',
    stopLoss: '止损',
    openPrice: '开仓价',
    closePrice: '平仓价',
    delist: '当前内容已下架',
    remove: '当前内容已删除'
  },
  home: {
    actualIntro: '实盘账户总数',
    actual: '实盘账户总数',
    profitIntro: '实盘盈利账户数',
    profitAccount: '盈利账户',
    lossIntro: '实盘亏损账户数',
    lossAccount: '亏损账户',
    blastingIntro: '出现过爆仓的实盘账户数',
    blastingAccount: '爆仓账户',
    allMen: '所有牛人',
    openAccountToDate: '开户至今',
    lastJune: '近六月',
    already: '已跟单',
    yieldValueChart: '收益率（TWR）走势图',
    favor: '猜你喜欢',
    refresh: '换一批',
    unlimited: '不限',
    rank: '综合评级',
    earnings: '账户收益',
    riskLevel: '风险等级',
    broker: '交易商',
    goodAt: '擅长品种',
    moreOptions: '更多选项',
    dealWinRate: '交易胜率',
    ratio: '盈亏比',
    openTime: '开户时间',
    capital: '资金量级',
    accountType: '账户类型',
    platform: '交易平台',
    clear: '清空',
    noContent: '没找到相关内容',
    noBroker: '未搜索到相关交易商',
    accountRatingRangeList: [
      {value: 1, label: 'A级'},
      {value: 2, label: 'B级'},
      {value: 3, label: 'C级'}
    ],
    twrRangeList: [
      {value: '', label: '不限'},
      {value: 2, label: '0%~30%'},
      {value: 3, label: '30%~60%'},
      {value: 4, label: '60%~100%'},
      {value: 5, label: '100%~200%'},
      {value: 6, label: '200% 以上'}
    ],
    riskLevelList: [
      {value: 1, label: '低'},
      {value: 2, label: '中'},
      {value: 3, label: '高'}
    ],
    winRateRangeList: [
      {value: 0, label: '不限'},
      {value: 2, label: '50% 以上'},
      {value: 3, label: '60% 以上'},
      {value: 4, label: '70% 以上'},
      {value: 5, label: '80% 以上'},
      {value: 6, label: '90% 以上'}
    ],
    profitLossRatioRangeList: [
      {value: 0, label: '不限'},
      {value: 2, label: '0.5 以上'},
      {value: 3, label: '1.0 以上'},
      {value: 4, label: '1.5 以上'},
      {value: 5, label: '2.0 以上'},
      {value: 6, label: '2.5 以上'},
      {value: 7, label: '3.0 以上'}
    ],
    openingTimeRangeList: [
      {value: 0, label: '不限'},
      {value: 1, label: '≤ 1 个月'},
      {value: 2, label: '> 1 个月'},
      {value: 3, label: '> 3 个月'},
      {value: 4, label: '> 6 个月'},
      {value: 5, label: '> 12 个月'}
    ],
    amountOfFundsRangeList: [
      {value: 0, label: '不限'},
      {value: 1, label: '100 以下'},
      {value: 2, label: '100 到 1000'},
      {value: 3, label: '1000 到 3000'},
      {value: 4, label: '3000 到 1万'},
      {value: 5, label: '1 万到 10 万'},
      {value: 6, label: '10 万到 30 万'},
      {value: 7, label: '30 万以上'}
    ],
    accountTypeList: [
      {value: 1, label: '实盘'},
      {value: 2, label: '模拟盘'}
    ],
    orderList: [
      {value: 2, name: '收益率'},
      {value: 3, name: '最大回撤'},
      {value: 4, name: '胜率'},
      {value: 5, name: '盈亏比'},
      {value: 6, name: '跟单人数'}
    ],
    niuTopTypeList: ['收益最高', '量化最佳', '单量最多', '胜率最高'],
    threeMonthData: '近三月数据',
    dataFieldList: ['日均收益', '量化交易占比', '日均单量', '交易胜率'],
    threeMonthEarnings: '近三月收益',
    positionDuration: '平均持仓时间',
    lastThreeMonth: '近三个月',
    detail: '详情',
    appraise: '每周精选',
    nextUpdate: '下次更新',
    currentStage: '当前榜单周期',
    stage: '第 {x} 期',
    nobodyOnTheList: '本期无上榜名单',
    ruleContent:
      '从收益、量化、单量、胜率四个方面（基于近三月数据），评选出最优秀的交易账户。单项指标上能力突出加上有良好的盈利表现，才能上榜每周精选。',
    udpateTime: '每周六{x}更新',
    weeklySelection: '每周精选',
    totalAccountNum: '总账户',
    echartMeaning: '图表意义',
    transactionSoftwareList: [
      {value: 2, label: 'MT4'},
      {value: 1, label: 'MT5', disabled: true}
    ],
    infiniteTxt: '无限',
    selectBrokerNum: '已选{x}个交易商',
    moreSelect: '多选',
    indexSubTabItem1: '收益60%~100%',
    indexSubTabItem2: '低风险',
    indexSubTabItem3: '12月以上',
    indexSubTabItem4: '资金量1万到10美金',
    indexSubTabItem5: '胜率90%以上',
    indexSubTabItem6: '盈亏比3倍以上',
    filterNiuTitle: '牛人筛选',
    selectBrokerTitle: '选择交易商',
    allTimePeriod: '全部时段',
    searchBroker: '搜索交易商',
    KOLInterview: 'KOL专访',
    userEvaluation: '用户评价',
    interestBroker: '感兴趣的交易商'
  },
  aiRating: {
    gradeTimes: 'AI评级次数',
    dataCutOff: '数据截至 {x}',
    gradeModel: '多维评判模型',
    modelIntro:
      'AI评级系统从盈亏、订单、仓位、品种、风格这五个维度对交易账户进行全方位的审查，准确地评估一个账户在盈利能力、稳定性以及风险性等方面的表现。',
    sample: '海量样本表现',
    sampleIntro: '成千上万的交易账户，数以千万计的交易订单，客观、公正的评判结果，是对AI评级系统最好的赞同。',
    highAccount: '高级账户',
    highIntro: '拥有较好的盈利能力，在稳定性和风险性方面表现良好。',
    profitAccount: '盈利账户',
    middleAccount: '中级账户',
    middleIntro: '具备一定的盈利能力，但在稳定性和风险控制方面，还需提高。',
    lowAccount: '低级账户',
    lowIntro: '盈利能力较差，且伴随着巨大的交易风险。',
    moreClient: '更高的评级，更多的客户',
    moreIntro:
      '评级越高，账户的实力越强，被客户跟单和关注的可能性就越大。牛人榜现有跟单中，超过 {x} 的被跟单账户均为 A级 以上账户。',
    allUse: '他们都在使用',
    yourScore: 'AI评级系统，为您的交易考卷打出最真实的评分。快来看看您的得分吧~',
    profitLoss: '盈亏',
    orderForm: '订单',
    position: '仓位',
    variety: '品种',
    style: '风格'
  },
  account: {
    settingOptions: [
      {value: 1, name: '资料设置'},
      {value: 2, name: '权限设置'}
    ],
    deleteAccount: '删除账户',
    sureToDelete: '您确定要删除此交易账户？',
    deleteMatters: '注意：已被您删除的交易账户在七天内无法再次进行绑定。',
    confirmDelete: '确定删除',
    cancelSubscribeBeforeDel: '该账户当前跟单了 {x} 个信号账户，若要删除此账户，请先取消这些跟单。',
    deleteSuccess: '{x} 已成功删除',
    deleteFailed: '{x} 删除失败',
    settingSaved: '设置已保存',
    accountPermission: '账户权限',
    subscribePermission: '跟单权限',
    accountPrivate:
      '账户权限当前处于关闭状态，其他人暂无法跟单此账户的交易信号。<br/>\n若要出售交易信号，请将账户权限设为 “公开”，并打开跟单权限。',
    commentPermission: '评论权限',
    accountcommentForbid: '该账户的评论权限已被系统禁用。如有疑问，请联系客服。',
    positionOrder: '持仓订单',
    historyOrder: '历史订单',
    weeklyReport: '每周向我发送此账户的交易情况。',
    monthlyReport: '每月向我发送此账户的交易情况。',
    tradingDayReport: '交易日报',
    tradingWeekReport: '交易周报',
    tradingMonthReport: '交易月报',
    linkAbnormal: '连接异常',
    linkAbnormalExplain: '该交易账户连接异常，请不要跟单。',
    riskAccount: '风险账户',
    riskAccountExplain: '该交易账户存在较大亏损风险，请谨慎跟单。',
    abnormalAccount: '异常账户',
    abnormalAccountExplain: '该交易账户的真实性存疑，请谨慎跟单。',
    sixMonthEarnings: '近六月收益',
    actualAccount: '实盘交易账户',
    virtualAccount: '模拟盘交易账户',
    balance: '余额',
    netValue: '净值',
    maxDrawdown: '历史最大回撤',
    drawdownTips:
      '开户至今，净值曾出现过的最大的亏损幅度（百分比）。<br/>\n      对于新绑定的交易账户，其在绑定之前的历史最大回撤将使用余额数据来计算。<br/>\n      注意，MT4 的最大回撤算法有一定的缺陷，而牛人榜矫正了此算法，以使结果更加准确，故两者的最大回撤结果可能不一致。',
    deposit: '入金',
    withdrawal: '出金',
    fetch: '取款',
    save: '存款',
    creditFetch: '信用额出金',
    creditSave: '信用额入金',
    dealAccount: '交易账户',
    dataSynchronizationErr: '数据同步失败，请检查账号或密码！',
    notOpen: '暂未开通，敬请期待',
    signalProvider: '成为信号提供者',
    tradingAccountSetting: '交易账户设置',
    profitLossRatio: '盈亏比',
    dateOptions: [
      {value: 0, name: '全部时段'},
      {value: 1, name: '近1月'},
      {value: 2, name: '近3月'},
      {value: 3, name: '近6月'},
      {value: 4, name: '近12月'}
    ],
    yieldRate: '收益率',
    totalProfitLoss: '总盈亏',
    synthesizeRank: '综合排名',
    rankTips: '综合排名依据综合评级得分而来，仅实盘账户方可参与排名。',
    synthesizeScore: '综合得分',
    scoreTips: '从盈亏、订单、仓位、品种以及风格等多个维度对交易账户进行评级打分。',
    periodList: [
      {value: 1, name: '天'},
      {value: 2, name: '周'},
      {value: 4, name: '月'}
    ],
    profitLossTitle: ['每日盈亏', '每周盈亏', '每月盈亏'],
    forbidBroker:
      '牛人榜已不再支持交易商 {x}，该交易商的交易账户将无法绑定到本社区。同时，现有的该交易商的交易账户也将不再允许跟单。',
    accountSetting: '账户设置',
    earningsReport: '收益统计',
    clickToView: '点击柱子查看交易报告',
    openAccountTime: '开户时间',
    currency: '存款货币',
    timeZone: '交易时区',
    cutOff: '统计截至',
    profitLoss: '盈亏',
    handCount: '手数',
    orderCount: '单量',
    balanceOptions: [
      {value: 1, name: '原始', content: '原始的余额/净值曲线图，但受出入金影响，可能有断层。'},
      {
        value: 2,
        name: '修正',
        content:
          '将出入金数据进行了折算，使余额/净值曲线变得更加连续而平滑，以便更加真实的了解账户余额/净值的变化趋势，该方法不会产生失真。'
      }
    ],
    varietyDistribute: '交易品种分布',
    timesOptions: [
      {value: 1, name: '仓位'},
      {value: 2, name: '笔数'}
    ],
    profitDistribute: '交易盈亏分布',
    profitDirection: '交易方向分布',
    incomeOptions: [
      {value: 1, name: '方向'},
      {value: 2, name: '盈亏'}
    ],
    positionTime: '持仓时间',
    holdOptions: [
      {value: 1, name: '仓位'},
      {value: 2, name: '盈亏'}
    ],
    totalAvg: '总平均持仓',
    profitAvg: '盈利单平均持仓',
    lossAvg: '亏损单平均持仓',
    loading: '正在加载',
    promptContent:
      '<p>温馨提示：</p>\n      1. 计算各项统计数据时，已排除挂单和出入金数据；<br/>\n      2. 综合评级和各项统计数据于北京时间每天 08:00 发布更新；<br/>\n      3. 不论账户存款货币为何种货币，在与盈亏相关的统计数据末尾，我们均使用符号 $ 来表明该数据为盈亏类数据；<br/>\n      4. MT4 的最大回撤算法有一定的缺陷，而牛人榜矫正了此算法，以使结果更加准确，故两者的最大回撤结果可能不一致；<br/>\n      5. 盈亏比和收益风险比的最大值被限定为 100.00，收益率的最大值被限定为 100.00w%。<br/>',
    totalOrder: '共 {x} 个订单，已加载 {y}',
    longOrder: '多单',
    shortOrder: '空单',
    longShort: '多/空',
    shippingSize: '仓位大小',
    profitOrder: '盈利订单',
    lossOrder: '亏损订单',
    orderPosition: '订单仓位',
    orderProfitLoss: '订单盈亏',
    profitLossTip: '包括隔夜利息和手续费',
    handCountTip: '不包含挂单',
    inventory: '库存费',
    procedure: '手续费',
    notInclude: '不包括挂单和出入金',
    filter: '筛选',
    browseTotal: '访问量统计',
    subscribeTotal: '跟单量统计',
    subscribeList: [
      {value: 1, name: '跟单量'},
      {value: 2, name: '访问量'}
    ],
    totalBrowse: '总访问量',
    totalSubscribe: '总跟单量',
    tradingOrderCnt: '交易单量',
    winRate: '胜率',
    tradingHand: '交易手数',
    orderDistribute: '单量分布',
    profitLossDistribute: '盈亏分布',
    totalProfitExplain: '注：总盈亏数据包含了库存费和手续费',
    cutDown: '最近更新',
    todayRise: '今日上升',
    today: '今日',
    totalEarnings: '累计收益',
    earningsTips:
      '累计收益：截至昨日结束时的余额收益率，使用 TWR 算法计算。<br/>\n      绝对收益：截至昨日结束时的总盈亏除以总入金量（含信用额）*100%。',
    absoluteEarnings: '绝对收益',
    noStrategy: 'TA还没有填写此账户的交易策略',
    accountName: '账户名称',
    totalDeposit: '累计入金',
    accountNetValue: '净值',
    positionProfit: '持仓盈亏',
    closeProfit: '已平仓盈亏',
    accountLever: '杠杆',
    totalWithdrawal: '累计出金',
    accountBalance: '余额',
    credit: '信用额',
    dataOverviewExplain: [
      '指定周期内所有订单的盈亏之和。',
      '盈利订单数占总订单数的百分比。',
      '平均每笔订单的持仓时间。',
      '使用 EA 交易的订单数量占比。',
      '指定周期内所有订单的手数之和。',
      '盈利单的平均盈利与亏损单的平均亏损之比。',
      '平均每笔订单的交易手数。',
      '重仓交易（订单对资金的占用在 15% 以上）的订单数量占比。',
      '指定周期内的订单数量。',
      '订单的库存费之和。',
      '盈利订单的总盈利金额除以盈利订单的数量。',
      '盈利最高的一笔订单的盈利金额。',
      '平均每天交易的订单数量。',
      '订单的手续费之和。',
      '亏损订单的总亏损金额除以亏损订单的数量。',
      '亏损最高的一笔订单的亏损金额。'
    ],
    positionDuration: '平均持仓时间',
    quantizedRatio: '量化交易占比',
    totalHand: '总手数',
    avgTradingHand: '平均交易手数',
    heavyTradingRatio: '重仓交易占比',
    totalOrderCount: '总单量',
    totalInterest: '总利息',
    avgProfit: '平均盈利金额',
    maxProfit: '单笔最大盈利',
    avgDayOrder: '日均单量',
    totalProcedure: '总手续费',
    avgLoss: '平均亏损金额',
    maxLoss: '单笔最大亏损',
    variety: '品种',
    type: '类型',
    closeTimeRange: '平仓时段',
    startTime: '起始时间',
    endTime: '结束时间',
    typeList: [
      {value: -1, name: '全部'},
      {value: 1, name: '市价单'},
      {value: 2, name: '挂单'}
    ],
    replenish: [
      {value: 4, name: '存取款'},
      {value: 8, name: '信用额'}
    ],
    period: '周期',
    openTime: '开仓时间',
    closeTime: '平仓时间',
    openClosePrice: '开/平仓价格',
    open: '开',
    close: '平',
    openPrice: '开仓价格',
    closePrice: '平仓价格',
    stopProfitLoss: '止损/止盈',
    direction: '方向',
    notice: '公告',
    cannotConnect: '无法连接到该账户',
    connecting: '正在连接（{x}s）',
    reconnectionNow: '立即重连',
    noBindOrPrivate: '该交易账户已被设为私有或解绑',
    accountInit: '账户初始化中，请稍后...',
    dataStatistics: '数据统计',
    tradingOrder: '交易订单',
    subscriber: '跟单者 {0}',
    tradingNotice: '交易公告',
    comment: '评论 {0}',
    tradingReport: '虚假交易举报 {0}',
    connectFail: '连接失败',
    connectSuccess: '连接成功',
    browseChange: '账户的访问量变化曲线，可反映该账户近期的热度情况。',
    subscribeChange: '账户的跟单量变化曲线，可反映该账户受欢迎的程度和趋势。',
    dataOverview: '数据概览',
    dataDeneral: '数据总览',
    importantIndex: '重要指标',
    plAnalysis: '盈亏分析',
    incomeStatistics: '收益统计',
    changeAccount: '切换账户',
    stopProfit: '止盈',
    stopLoss: '止损',
    texes: '税金',
    helpYouUndestand: '帮助您了解自己的交易账户',
    addAccount: '添加账号',
    selectTraderBrokers: '请选择交易服务器',
    inputAccountNum: '请输入4~16位数字',
    inputAccountPwd: '请输入4~32位密码',
    inputAccountExplain: '请简单介绍您的交易策略，16~128字符',
    accountExplain: '允许或禁止其他人查看此账户的交易数据。禁止后，此账户将不会对外展示。',
    positionExplain: '允许或禁止其他人查看此账户的持仓交易订单，但此账户的跟随者始终可以查看。',
    historyExplain: '允许或禁止其他人查看此账户的历史交易订单，但此账户的跟随者始终可以查看。',
    commentExplain: '允许或禁止其他人对此账户进行评论。',
    weekReportExplain: '允许或禁止每周向我发送此账户的交易情况。',
    monthReportExplain: '允许或禁止每月向我发送此账户的交易情况。'
  },
  dataCenter: {
    market: '交易市场',
    report: '持仓报告',
    technical: '技术形态',
    profitAccount: '盈利账户',
    fromYesterday: '较昨日',
    actualCount: '实盘账户总数',
    yesterday: '昨日',
    lossAccount: '亏损账户',
    popularBroker: '流行交易商排行',
    popularExplain:
      '根据交易商在社区内的实盘账户数量形成排名，差评率则以用户在交易账户详情页内对交易商的评价结果统计而来。',
    userSelect: '用户选择',
    negativeRate: '差评率',
    masterPosition: '{x} 高手持仓',
    short: '看空',
    long: '看多',
    neutral: '中性',
    blastingIntro: '出现过爆仓的实盘账户数',
    blastingAccount: '爆仓账户',
    unit: '单位：',
    accountDistribute: '账户分布',
    accountChange: '账户数量变化',
    varietyDistribute: '交易品种分布',
    winRateDistribute: '交易胜率分布',
    cutOff: '截止',
    profit: '盈利',
    loss: '亏损',
    blasting: '爆仓',
    orderForm: '订单',
    shippingSpace: '仓位',
    accountRatio: '账户占比',
    accountNumber: '账户数（个）',
    profitLossRatio: '盈利 / 亏损',
    dealStyle: '交易风格偏好',
    lossRate: '亏损率',
    dealStyleList: ['短线交易', '长线交易', '量化 EA 交易', '黄金原油交易'],
    styleExplainList: [
      '持仓时间短，交易胜率高，单量可观，深受交易者喜爱。但其盈亏比通常较低，属小赚大亏型策略。',
      '长达数周甚至上月的持仓周期，极高的盈亏比，极低的交易频率，需要交易者有十足的耐心。',
      '将手工操盘经验总结固化为一个逻辑严谨的数学模型，使用 EA 插件按照既定的规则自动进行交易。',
      '非常受欢迎的两个商品期货，具有较广的受众群体，在诸多交易软件上均可操作，高手如云。'
    ],
    styleAccountRatio: ['短线账户占比', '长线账户占比', '量化 EA 账户占比', '黄金原油账户占比'],
    speculate: '投机情绪现状',
    updateFrequency: '每 15 分钟更新一次',
    tradeVariety: '交易品种',
    accountCount: '账户数（个） 多/空',
    accountCountTips: '当前持仓的净头寸为做多或做空的账户数量',
    shippingSpaceLabel: '仓位（手） 多/空',
    shippingSpaceTips: '当前持仓的多单手数之和空单手数之和，不含挂单',
    marketEmotion: '市场情绪（多/空）',
    dealStyleTip: ['包含 {x} 风格的账户数除以社区总账户数。', '专注 黄金或原油 交易的账户数除以社区总账户数。'],
    lossRateTip: ['包含 {x} 风格的账户中，有 {y} 是亏损的。', '专注 黄金或原油 交易的账户中，有 {y} 是亏损的。'],
    accountExplain:
      '截至 {0}({1})，共有 {2} 个交易账户在交易 {3}，其中持仓亏损的账户有 {4} 个，持仓盈利的账户有 {5} 个。',
    orderList: '订单簿',
    orderListTips: '发现市场潜在的支撑/阻力位置，了解市场的价格密集成交区',
    positionChange: '持仓人数和头寸变化',
    longAccountNum: '多头账户数',
    shortAccountNum: '空头账户数',
    netPosition: '净头寸',
    rise: '看涨',
    fall: '看跌',
    putOrder: '挂单',
    position: '持仓',
    marketChange: '行情和头寸变化',
    longCash: '多头头寸',
    shortCash: '空头头寸',
    closePrice: '收盘价',
    upsAndDowns: '日内涨跌',
    newestPrice: '最新价',
    marketEmotion1: '市场情绪',
    currentPosition: '当前持仓订单 {x} 个',
    longOrderCount: '多单 {x} 个',
    shortOrderCount: '{x} 个 空单',
    price: '价格',
    subscribeCnt: '跟单量',
    windVane: '交易风向标',
    allMaster: '他们都是 {x} 高手',
    longMaster: '长线高手',
    shortMaster: '短线高手',
    quantizationMaster: '量化高手',
    form: '形态',
    name: '名称',
    variety: '品种',
    period: '周期',
    createTime: '产生时间',
    trend: '趋势',
    dataSupport: '由 FastBull 提供数据支持',
    chartTimeZone: '图表时区',
    allForm: '所有形态',
    allVariety: '所有品种',
    allPeriod: '所有周期',
    kingList: '榜单之王',
    formDesc1:
      '锤子线属于底部反转形态，是一种柱体较小，但上影线或下影线较长的 K 线（影线通常比柱体长两倍以上）。 在锤子线之前，必定先有一段下降趋势（哪怕是较小规模的下降趋势），这样锤子线才可能够逆转这个趋势。如果这是出现在上升趋势中，则我们称它为上吊线，而非锤子线。',
    formDesc2:
      '上吊线的实体与上吊线次日的开盘价之间向下的缺口越大，那么上吊线就越有可能构成市场的顶部。在上吊线之后，如果市场走出了一根阴线，并且它的收盘价低于上吊线的收盘价，那么，这也可以看做上吊线成立的一种佐证。上吊线属于顶部反转形态，必须出现在一段上升趋势之后。',
    formDesc3:
      '射击之星又称为“倒转锤头”，仿如枪的准头。射击之星可以是阴线或阳线，但实体比较短小，上影线较长，其位置主要出现在顶部，是一种十分明显的见顶信号。这一形态的形成是开盘价比较低，多头组织力量向上攻，一度急升，但尾市卖压加强，收盘价又回落至开盘价附近（射击之星因为光芒短暂又被称为“流星”）。',
    formDesc4:
      '倒锤线与射击之星不同的地方在于，它出现在行情的底部，表示价格有可能回升。从实际使用来看，倒锤线与射击之星的反转强度不如上吊线和锤子线，因此在使用时最好结合下一根 K 线及其他分析方法来进一步分析。',
    formDesc5:
      '吞没形态通常指阴包阳或者阳包阴形态，阳包阴即倒数第二根 K 线为阳线，倒数第一根为阴线，且倒数第二根 K 线完全包含了倒数第一根 K 线，阴包阳则与此相反。此外，阳包阳和阴包阴也很常见，前者通常是卖点，后者通常是买点，但不能仅以此贸然断定买卖方向，还是需要结合其他技术手段综合分析。',
    formDesc6:
      '吞没形态通常指阴包阳或者阳包阴形态，阳包阴即倒数第二根 K 线为阳线，倒数第一根为阴线，且倒数第二根 K 线完全包含了倒数第一根 K 线，阴包阳则与此相反。此外，阳包阳和阴包阴也很常见，前者通常是卖点，后者通常是买点，但不能仅以此贸然断定买卖方向，还是需要结合其他技术手段综合分析。',
    formDesc7:
      '三只乌鸦也称“黑三兵”，意思是连续出现三根向下的阴线，通常为行情崩盘的前兆，出现此类K线形态一般表明价格后势将进一步下跌。而“红三兵”与此相反，红三兵如果发生在下降趋势中，一般是市场的强烈反转信号；如果市价在较长时间的横盘后出现红三兵的走势形态，并且伴随着成交量的逐渐放大，则是行情启动的前奏，可引起密切关注。',
    formDesc8:
      '三只乌鸦也称“黑三兵”，意思是连续出现三根向下的阴线，通常为行情崩盘的前兆，出现此类K线形态一般表明价格后势将进一步下跌。而“红三兵”与此相反，红三兵如果发生在下降趋势中，一般是市场的强烈反转信号；如果市价在较长时间的横盘后出现红三兵的走势形态，并且伴随着成交量的逐渐放大，则是行情启动的前奏，可引起密切关注。',
    formDesc9:
      '启明星是由三根 K 线组成的 K 线组合形态，它是一种行情见底转势的形态。这种形态如果出现在下降趋势中应引起注意，因为此时趋势已发出比较明确的反转信号，是一个非常好的买入时机。',
    formDesc10:
      '黄昏星与启明星正好相反，它是较强烈的上升趋势中出现反转的信号。黄昏之星的 K 线组合形态如果出现在上升趋势中应引起注意，因为此时趋势已发出比较明确的反转信号或中短期的回调信号，对于我们来说可能是非常好的卖出时机或中短线回避的时机。',
    formDesc13:
      '乌云盖顶又称乌云线，是 K 线图较为常见顶部反转形态之一。 这种形态由一阴一阳两根K线组成，它们一般出现在上升趋势之后，在有些情况下也可能出现在水平调整区间的顶部，是一个看跌信号。',
    formDesc14:
      '曙光初现由两根走势完全相反的较长的 K 线构成。 前一天为阴线，后一天为阳线。第二天阳线向下跳空低开，开盘价远低于前一天的收盘价；但第二天的收盘价却高于前一天的收盘价，并且阳线的收盘价深入第一根阴线的实体部分中，至少达到前一天阴线实体的一半。',
    formDesc15:
      '十字星，是一种只有上下影线，没有柱体的 K 线，即开盘价等于收盘价。其中：上影线越长，表示卖盘力量较大；而下影线越长，表示买盘力量较大，如果在价格的高位或低位出现较为明显的十字线，则意味着行情很有可能出现反转。',
    formDesc16:
      '十字星，是一种只有上下影线，没有柱体的 K 线，即开盘价等于收盘价。其中：上影线越长，表示卖盘力量较大；而下影线越长，表示买盘力量较大，如果在价格的高位或低位出现较为明显的十字线，则意味着行情很有可能出现反转。',
    formDesc17:
      '孕线形态与吞没形态相比，两根 K 线的顺序正好颠倒过来。在吞没形态中，后面是一根长长的实体，将它前面的小实体覆盖进去；孕线形态是后一根 K 线实体较小，并且被前一根较长的实体包容进去。该形态的名字的由来，也是缘于“怀孕”的意思。长的 K 线为“母”线，小的 K 线为“子”线，或是“胎”线，以示其包容含义。',
    formDesc18:
      '孕线形态与吞没形态相比，两根 K 线的顺序正好颠倒过来。在吞没形态中，后面是一根长长的实体，将它前面的小实体覆盖进去；孕线形态是后一根 K 线实体较小，并且被前一根较长的实体包容进去。该形态的名字的由来，也是缘于“怀孕”的意思。长的 K 线为“母”线，小的 K 线为“子”线，或是“胎”线，以示其包容含义。',
    formDesc19:
      '孕线形态与吞没形态相比，两根 K 线的顺序正好颠倒过来。在吞没形态中，后面是一根长长的实体，将它前面的小实体覆盖进去；孕线形态是后一根 K 线实体较小，并且被前一根较长的实体包容进去（如果后一根 K 线是十字星，则称十字孕线）。该形态的名字的由来，也是缘于“怀孕”的意思。长的 K 线为“母”线，小的 K 线为“子”线，或是“胎”线，以示其包容含义。',
    formDesc20:
      '孕线形态与吞没形态相比，两根 K 线的顺序正好颠倒过来。在吞没形态中，后面是一根长长的实体，将它前面的小实体覆盖进去；孕线形态是后一根 K 线实体较小，并且被前一根较长的实体包容进去（如果后一根 K 线是十字星，则称十字孕线）。该形态的名字的由来，也是缘于“怀孕”的意思。长的 K 线为“母”线，小的 K 线为“子”线，或是“胎”线，以示其包容含义。',
    traderStyle: '交易偏好',
    winningAccounts: '盈利账户占比',
    losingAccounts: '亏损账户占比',
    dealLong: '做多',
    dealShort: '做空',
    sellingPrice: '卖价',
    buyingPrice: '买价',
    hangingOrderData: '挂单数据',
    positionOrderData: '持仓数据',
    periodicalNumber: '第{x}期',
    greatestRule: '评选规则',
    selectTraderStyle: '选择交易品种'
  },
  user: {
    sendMsg: '发消息',
    userId: '用户ID',
    attention: '关注',
    collect: '收藏',
    home: '主页',
    contest: '比赛',
    social: '社交',
    vip: '会员',
    setting: '设置',
    about: '关于',
    accountListLen: '允许绑定的交易账户数量上限为 {x} 个。',
    addAccount: '添加账户',
    loginRegister: '注册/登录',
    logoutSuccess: '退出成功',
    accountLis: '账户列表',
    totalAccount: '共 {x} 个账户',
    noBindAccount: 'TA还没有绑定交易账户',
    unfoldAll: '展开全部',
    foldAll: '收起全部',
    similarAccount: '相似账户',
    changeAccount: '换一批',
    signaturePlaceholder: '这个人很懒，什么都没留下',
    loginViewOrder: '登录后可查看持仓订单',
    brokerGrade: '您认为该账户的交易商 {x} 可靠吗？',
    soldOut: '建议FastBull牛人榜下架该交易商，不再支持该交易商的账户绑定',
    accountReport: '虚假交易举报',
    suspects: '请指出该交易账户的虚假点、可疑点，以便广大汇友参考或甄别',
    reliable: '挺可靠',
    unreliable: '不可靠',
    suggestSoldOut: '建议下架',
    reportSuccess: '举报成功！',
    emoji: '表情',
    picture: '图片',
    uploadFailed: '图片上传失败',
    submitAfterUpload: '请在图片上传完成后提交！',
    addPicture: '添加图片',
    btnTextList: ['评论', '回复', '确定举报'],
    praise: '赞',
    reply: '回复',
    writeYourComment: '请输入回复内容...',
    moreReply: '更多回复',
    residueReplay: '剩余 {x} 条回复',
    account: '账户',
    grade: '评级',
    subscribe: '跟单',
    accountPraise: '账户口碑',
    accountComment: '账户评论',
    allComment: '所有评论',
    needComment: '大家都需要您一针见血的评论（评论无法修改与删除，请理性评论）。',
    excellent: '优秀',
    ordinary: '一般',
    noGood: '差劲',
    commentSuccess: '评论成功！',
    replySuccess: '回复成功！',
    inputNotice: '请输入公告内容',
    allowNoticeCount: '交易公告每天最多允许发送 {x} 条',
    totalCount: '共{x}条',
    publish: '发布',
    publishSuccess: '公告发布成功！',
    isDeleteNotice: '是否删除公告？',
    deleteNotice: '删除公告',
    closeComment: '该帐户已关闭评论权限',
    privateComment: '私有账户，不能发布评论',
    privateReport: '私有账户，不能发布举报信息',
    length1: '请至少输入 1 个字符。',
    length512: '最多只能输入 512 个字符',
    noAccount: '还没有交易账户',
    tradingPlatform: '交易软件',
    broker: '交易商',
    brokerServer: '交易服务器',
    dealAccountNum: '交易账号',
    tradingPassword: '交易密码',
    passwordExplain: '如果您不需要进行跟随交易，输入观摩密码即可。',
    inputPassword: '请输入交易密码',
    tradingStrategy: '交易策略',
    strategyExplain: '请简单介绍您的交易策略。',
    passwordLength: '交易密码为 4-32 个字符',
    strategyLength: '交易策略最少需要输入 16 个字符',
    searchName: '搜索交易商或服务器名称',
    record: '搜索记录',
    hotSearch: '热门搜索',
    result: '搜索结果',
    inputAccount: '请输入交易账号',
    inVerification: '账户验证中...',
    accountLength: '交易账号为 4-16 位数字',
    bindOvertime: '绑定账户超时',
    addTradingAccount: '添加交易账户',
    linkAccount: '连接账户',
    accountSetting: '账户设置',
    otherBind: '交易账户已被他人绑定',
    howToFind: '如何找回？',
    findAccount: '找回账户',
    stepTitle: '请按以下步骤找回您被他人占用的交易账户：',
    findStep1: '1. 使用交易密码登录 MT4/MT5。',
    findStep2: '2. 更改交易账户当前的交易密码或观摩密码。',
    findStep3: '3. 回到牛人榜，重新添加交易账户。',
    addSuccess: '添加成功',
    initExplain: '系统正在为该账户进行数据初始化操作，大概需要 3 分钟，初始化完成后该账户即可正常使用。',
    bindNow: '立即绑定',
    brokerBan: '该交易商已被禁用',
    accountRate: '优秀：交易能力较强<br/>\n      一般：交易能力一般<br/>\n      差劲：交易能力较弱',
    accountReportTips: '如果交易账户被多人举报为虚假交易，FastBull牛人榜将向相关交易商反馈并验证数据的真实性。',
    accountList: '账户列表',
    conversionRate: '转化率',
    nowDay: '当天',
    lastSevenDay: '近7日',
    yesterday: '昨日',
    notice: '公告',
    edit: '编辑',
    totalYieldRate: '累计收益率',
    bindAccountTips: '暂未添加交易账户，快去前往添加吧~',
    subscribeTips: '跟随交易信号，与大咖为伍',
    toSubscribe: '去跟单',
    contesting: '正在参赛',
    season: '{x} 赛季',
    rank: '排名',
    chatroom: '聊天室',
    friend: '好友',
    groupChat: '群聊',
    topic: '话题',
    writer: '作家',
    news: '新闻',
    video: '视频',
    pictureVideo: '图片视频',
    file: '文件',
    audio: '语音',
    chatRecord: '聊天记录',
    followed: '已关注',
    fans: '粉丝',
    article: '文章',
    cancelCollect: '取消收藏',
    simulationGroup: '模拟账户组',
    actualGroup: '实盘账户组',
    contestData: '大赛数据',
    awardsCount: '获奖次数',
    totalAward: '奖励总金额',
    topScore: '最高得分',
    megagameRecord: '大赛记录',
    entryAccount: '参赛账户',
    score: '分值',
    ranking: '排名',
    awards: '奖励',
    extraAward: '额外奖励',
    auditStatus: '审核状态',
    status: ['审核通过', '审核失败', '审核中'],
    noRecord: '暂无交易大赛记录',
    socialGroup2: '我管理的群({x})',
    socialGroup3: '我加入的群({x})',
    comeFrom: '来自于: {x}',
    socialGroup1: '我创建的群({x})',
    nextStep: '下一步',
    selectBrokers: '选择交易服务器',
    bindSuccess: '绑定成功',
    goFollowOrder: '去跟单',
    accountDetail: '账户详情',
    bindAgain: '重新绑定',
    traderAccount: '交易账户',
    traderLever: '杠杆',
    subscribeNum: '跟单人数 {0}',
    depositCurrency: '存款货币',
    accountName: '账户名称',
    withoutSignature: '未设置交易格言',
    fastbullVIP: 'Fastbull会员',
    openVipForFree: '免费开通会员',
    logout: '退出登录',
    shareFB: '分享Fastbull',
    copyLink: '复制链接',
    addFriend: '加好友',
    addFriendVerify: '加好友验证',
    waitVerify: '等待验证',
    added: '已添加',
    defaultVerify: '我是{x}',
    inputVerifyInfo: '请输入验证信息：',
    addSuccessTip: '您的好友添加请求已经发送成功，正在等待对方确认。',
    send: '发送',
    sendApplySuccess: '发送申请成功',
    cancelAttentionConfirm: '确定不再关注该用户吗？',
    userCenter: '个人中心',
    openFBAPP: '打开APP',
    supportNewsPrice: '提供更快更全的财经新闻和报价',
    noCollect: '暂未添加收藏',
    accountPwd: '账户密码',
    fxchat_niu_trading_select: '请选择交易商',
    fxchat_niu_trading_select_first: '请先选择交易商',
    fxchat_niu_trading_server_select: '请选择',
    fxchat_niu_account_input_hint: '4～16位数字',
    fxchat_niu_observe_account_input_hint: '4～32位密码',
    fxchat_niu_observe_password_tip: '如果您不需要进行跟随交易，输入观摩密码即可',
    fxchat_niu_trading_strategy_hint: '请简单介绍你的交易策略，16~128字',
    fxchat_niu_account_bind: '交易账户被他人绑定,',
    commentAfterLogin: '请先{x}后发表评论^_^',
    noBodyAdd: '添加失败，对方设置了不允许任何人添加好友。'
  },
  grade: {
    synthesizeGrade: '综合评级',
    gradeTips: '综合评级依据近六月的交易数据统计而来，每天更新一次。',
    tradeAbility: '交易能力',
    goodAtVariety: '专注品种',
    riskLevel: '风险等级',
    maxDrawdown: '最大回撤',
    viewGradeReport: '查看综合评级报告',
    rank: '综合排名 {x} 名',
    score: '综合得分 {x} 分',
    tradeAbilityList: ['超强', '很强', '良好', '一般', '较弱', '很弱'],
    riskLevelList: ['低风险', '中风险', '高风险'],
    profitAndLoss: '账户盈亏',
    orderControl: '订单控制',
    varietyData: '品种数据',
    dealStyle: '交易风格',
    dealPosition: '仓位数据',
    gradeStr: ['优秀', '良好', '一般', '较差'],
    gradeScore: '评级得分',
    scoreTooltip:
      'A+（90 分以上），交易能力超强！<br/>\nA（85 分以上），交易能力很强！<br/>\nB+（80 分以上），交易能力良好！<br/>\nB（75 分以上），交易能力一般！<br/>\nC+（60 分以上），交易能力较弱！<br/>\nC（60 分以下），交易能力很弱！\n    ',
    tradeGrade: '交易评级',
    gradeExplain: '综合评级以近六月的评级结果为准，评级信息每天更新一次',
    yieldRateTooltip: '指定时段内的余额收益率，使用 TWR 算法计算。',
    maxDrawdownTooltip:
      '指定时段内，净值（若无净值数据则使用余额数据替代）曾出现过的最大跌幅。因出入金影响，该值可能超过 100%。',
    yieldRiskRatioTooltip:
      '收益率 / 最大回撤率。当收益率小于等于 0 时，收益风险比直接取 0；当最大回撤为 0 时，收益风险比则取 100。',
    yieldRiskRatio: '收益风险比',
    orderTotalTooltip: '指定时段内的订单数量。',
    orderTotal: '订单总数',
    dealFrequencyTooltip: '指定时段内平均每天交易的订单数量。',
    dealFrequency: '交易频率',
    frequencyUnit: '{x} 单/天',
    stopProfitRateTooltip: '指定时段内的订单中，设有止盈或止损的订单占比。',
    stopProfitRate: '止盈止损率',
    varietyFreight: '品种仓位',
    heavyRatioTooltip: '指定时段内的订单中，重仓交易（订单对资金的占用在 15% 以上）的订单数量占比。',
    heavyRatio: '重仓比例',
    focusVarietyTooltip: '指定时段内，经常交易的品种数量。',
    focusVariety: '专注品种',
    profitLossRatioTooltip:
      '指定时段内的订单中，盈利单的平均盈利与亏损单的平均亏损之比。当平均亏损为 0 时，盈亏比则取 100。',
    profitLossRatio: '盈亏比',
    dealStyleTooltip: '指定时段内的交易风格。',
    profitPositionTooltip: '指定时段内的订单中，盈利单的平均持仓时长。',
    profitPosition: '盈利单平均持仓',
    lossPositionTooltip: '指定时段内的订单中，亏损单的平均持仓时长。\n',
    lossPosition: '亏损单平均持仓',
    gradeResult: '评级结果仅供参考，不构成任何投资建议',
    general: '整体概况',
    evaluateList: [
      '订单数量太少，无法准确评级',
      '给自己打个气，逆水行舟，不进则退',
      '专业能力还有待提高',
      '还可以再进一步，不要当韭菜',
      '表现很棒，继续努力',
      '当之无愧的交易牛人',
      '天才级的交易水准'
    ],
    profitAbility: {
      worst: '盈利能力非常差',
      veryBad: '盈利能力很差',
      bad: '盈利能力较差',
      needToImprove: '盈利能力有待提高',
      common: '盈利能力一般',
      strong: '盈利能力较强',
      stronger: '盈利能力很强',
      strongest: '盈利能力非常强'
    },
    earnings: {
      veryInstability: '收益很不稳定。',
      instability: '收益不太稳定。',
      stabilize: '收益较为稳定。',
      veryStabilize: '收益很稳定。',
      mostStabilize: '收益非常稳定。'
    },
    dealRisk: {
      lowest: '交易风险很低',
      smaller: '交易风险较小',
      controlled: '交易风险可控',
      high: '交易风险偏高',
      higher: '交易风险很高',
      gigantic: '交易风险巨大'
    },
    earningsRiskRatio: {
      worst: '收益风险比非常差。',
      veryBad: '收益风险比很差。',
      needToImprove: '收益风险比有待提高。',
      rational: '收益风险比合理。',
      good: '收益风险比很好。',
      veryGood: '收益风险比非常好。'
    },
    avgDailyYield: '账户平均日化 {x}',
    avgWeekYield: '账户平均周化 {x}',
    avgMonthYield: '账户平均月化 {x}',
    dayProfit: '日盈利概率为 {x}',
    monthProfit: '月盈利概率为 {x}',
    maxDrawdownIs: '而最大回撤为 {x}',
    earningsRiskValue: '收益风险比为 {x}',
    dealFrequencyExplain: [
      '交易频率控制较好，请继续保持，毕竟做得越多，做错的几率越大。',
      '交易频率偏高，适当降低交易频率，有助于更好的控制风险。'
    ],
    stopExplain: [
      '由于止盈或止损设置率较低，可能会有一定的交易风险。',
      '交易目标不太明确，善用止盈或止损，可在一定程度上降低交易风险。',
      '交易目标通常比较明确，进出场需谨慎，不打无把握的仗。',
      '交易目标明确，具有良好的交易习惯。'
    ],
    accumulativeDeal: '累计交易 {x} 天',
    avgOrder: '平均每天 {x} 单',
    stopPercent: '对 {x} 的订单设置了止盈止损',
    heavyExplain: [
      '具有良好的仓位风控意识，整体仓位控制比较合理。',
      '偶尔进行重仓交易。',
      '时常进行重仓交易，务必要做好风险控制。',
      '重仓交易太过频繁，可能产生极高的交易风险，请谨慎。'
    ],
    heavyPercent: '在 {x} 个订单中，重仓占比为 {y}',
    suggestion: '建议为所有重仓单带好止盈止损，摒弃赌博思维，做好风险控制。',
    noFocus: '无任何专注品种或擅长品种，建议专注一两个品种，或许能更好的提升交易能力。',
    focusVarietyAt: '专注的品种为 {x}，',
    focusCount: '专注于 {x} {y}个品种，',
    profitLossStr: '在该品种上累计盈亏为 {x}，还需要继续努力，把它做得更好。',
    profitLossTotal: '它们的盈亏之和为 {x}，继续加油。',
    goodAtStr: '最擅长 {x}，其利润占据了总利润的 {y}，继续加油。',
    tradingStyle: ['日内交易', '短线交易', '长线交易', '量化交易', '无交易风格'],
    tradingType: ['日内', '短线', '长线', '量化'],
    winAndRatio: '{x}单的胜率在 {y} 左右，盈亏比在 {z} 左右。',
    beGoodAt: '擅长{x}',
    noTradingStyle: '没有明确的交易风格，短线单的胜率在 {x}，长线单的胜率在 {y}。',
    avgPosition: '总平均持仓时长为 {x}，盈利单平均盈利 {y}，亏损单平均亏损 {z}。',
    joinAndRate: '加入牛人榜</br>评测您的交易能力',
    rated: '已评测 {x} 个交易账户，平均得分 {y}',
    rateNow: '立即评测',
    isTheRating: 'AI评级正在为您评级，请稍后…',
    scoreTips:
      '综合得分还包含了另外三项附加分，用于衡量交易账户在用户评价、逆势扛单以及生存周期等方面的表现情况。<br/>口碑附加分：{x} 分<br/>持仓附加分：{y} 分<br/>周期附加分：{z} 分',
    warmPrompt: '温馨提示',
    traderForShort: '短线交易',
    traderForLong: '长线交易',
    traderForQuantification: '量化交易',
    traderForGold: '黄金原油交易',
    traderForShortTip: '短线交易简介',
    traderForLongTip: '长线交易简介',
    traderForQuantificationTip: '量化交易简介',
    traderForGoldTip: '黄金原油交易简介',
    goldMaster: '黄金原油高手'
  },
  subscribe: {
    openSubscribe: '开通跟单权限',
    connectionNormal: '账户连接状态正常',
    accountIsReal: '账户类型为实盘账户',
    notAbnormal: '未被系统标记为异常账户',
    brokerCompliance: '所属交易商为合规交易商',
    equityMoreThan: '账户净值不低于 1000.00$',
    openNow: '立即开通',
    openSuccess: '跟单权限开通成功',
    disqualification: '该账户不符合开通条件',
    openCondition: '成为信号提供者，需满足以下条件：',
    closeSubscribe: '关闭跟单权限',
    closeSubscribeConfirm: '您确定要关闭此交易账户的跟单权限吗？',
    closePunishmentExplain: '该账户名下已有 {x} 个跟单者，如果此时关闭跟单权限，系统将根据社区规则对您进行以下惩罚：',
    punishment: '禁止该交易账户的跟单权限，为期 90 天。',
    consider: '再想一想',
    closeNow: '立即关闭',
    closeSuccess: '跟单权限关闭成功',
    lengthen: '延长跟单',
    follow: '跟单',
    selectAccount: '请选择跟随账户',
    alreadyFollow: '已跟随账户',
    followDays: '已跟随 {x} 天，{y} 到期',
    notFollow: '未跟随账户',
    accountIsDelete: '跟随账户已被删除。',
    accountDelete: '信号账户已被删除。',
    subscribeForbid: '该账户的跟单权限已被禁止。',
    subscribeClose: '该账户没有开通跟单权限。',
    closeAfterExpire: '该账户不再允许跟单。',
    followAccountOffline:
      '您的交易账户<span>#{x}</span>已掉线，暂时无法使用。如果该账户的连接密码已被更改，请<a target="_blank" href="{y}">前往账户设置</a>页更新连接密码。',
    brokerForbid: '牛人榜将不再支持交易商 {x}，因此，该交易商下的交易账户也将不再允许跟单。',
    fictitiousTradesTips: '该账户可能存在虚假交易，已被禁止跟单。',
    violateRuleTips: '由于您违反付费跟单规则，系统已禁止您跟单牛人榜内的任何信号。如有疑问，请联系客服。',
    limitationUser: '受限用户',
    subscribeWarning: '跟单警告',
    riskAccountTips: '该账户可能存在较高风险，请谨慎跟单。切勿轻信他人，避免上当受骗。',
    userAbnormalTips: '该账户所属用户出现异常，请谨慎跟单。',
    noCanFollow: '暂无可跟随账户，',
    noAccount: '您还没有绑定交易账户，',
    accountOffline: '该账户已掉线，暂时无法使用。',
    brokerLimit: '交易商受限',
    accountFollowTips:
      "您的交易账户<span>#{x}</span>当前使用的连接密码为观摩密码，不具有交易权限，因此无法在牛人榜内进行跟随交易。<br/>\n您需<a target='_blank' href='{y}'>前往账户设置</a>将该账户的连接密码更新为<span>交易密码</span>，然后再进行跟单。",
    dealLimit: '交易受限',
    forbidSubscribe: '禁止跟单',
    followSuccess: '跟单成功',
    followSetting: '设置跟单参数',
    subscriber: '跟单者',
    subscribeTypeList: [
      {value: 1, name: '正在跟单'},
      {value: 2, name: '历史跟单'}
    ],
    params: '跟单参数',
    subscribeTime: '跟单时间',
    subscribePeriod: '跟单周期',
    subscribeEndTime: '跟单结束时间',
    totalSubscribePeriod: '累计跟单时长',
    otherUser: '他还在跟单',
    patternList: [
      {name: '固定手数', value: 1},
      {name: '固定比例', value: 2}
    ],
    directionList: [
      {name: '正向跟随', value: 1},
      {name: '反向跟随', value: 2},
      {name: '只跟随平仓', value: 3}
    ],
    notice: '跟单公告',
    moreTradingNotice: '查看更多交易公告<br/>请前往交易账户详情页',
    hot: '热门跟单',
    count: '跟单量',
    allSource: '全部来源',
    detail: '跟单详情',
    cancelTips: '如果只是想暂停跟随交易，请前往跟单设置窗口，将跟随状态设为“关”即可',
    cancel: '取消跟单',
    setting: '跟单设置',
    detailStatusList: ['', '跟单中', '已到期', '已取消', '已退款', '未开始'],
    orderId: '订单 ID',
    startTime: '开始时间',
    endTime: '结束时间',
    cancelTime: '取消时间',
    cancelReason: '取消原因',
    notStartTips: '“未开始”的订单将在“跟单中”的订单到期后开始生效',
    confirmTocancel: '确定要取消跟单？',
    subscribeStartTime: '跟单开始时间',
    followAccount: '跟随账户',
    followStatus: '跟随状态',
    followStateTips: '关闭跟随后，既无法跟随开仓，也无法跟随平仓。但您仍会在消息中心收到信号账户的开平仓信号。',
    baseSetting: '基本设置',
    varietySetting: '品种设置',
    followNotice: '跟随须知',
    followPattern: '跟随模式',
    followPatternTips:
      '固定比例：根据信号账户与跟随账户之间的净值关系来计算跟随手数，并按此处指定的比例倍数来放大或缩小手数大小。<br/>\n      固定手数：无论信号账户开多少手，均只按此处指定的手数来跟随开仓。如无特殊要求，推荐使用“固定比例”跟随。',
    maxHand: '最大手数',
    maxHandTips: '单笔跟随开仓手数若超过此限定值，则按此限定值开仓。',
    noLimit: '不限制',
    followDirection: '跟随方向',
    followDirectionTips: '只跟随平仓：即不再跟随信号账户的开仓操作，只跟随平仓操作。',
    contractSize: '合约大小',
    contractSizeTips:
      '相同品种的合约大小在不同平台上可能不一样，这会导致跟随手数不正确。本功能仅在跟随模式为“固定比例”时生效。',
    sizeList: [
      {name: '自适应', value: 1},
      {name: '忽略', value: 2}
    ],
    signalAccount: '信号账户',
    followLimit: '交易限制',
    followLimitTips:
      '此功能用于限制跟随账户只进行指定类别的交易。<br/>\n      假设跟随方向为【反向跟随】，EURUSD 的交易限制为【只开空单】，若：<br/>\n      信号源开 EURUSD 多单，跟随账户反向之后应开空单，与交易限制不冲突，开空。<br/>\n      信号源开 EURUSD 空单，跟随账户反向之后应开多单，但与交易限制发生冲突，不开多。<br/>',
    setManually: '无法识别，请手动设置',
    limitList: [
      {name: '不限制', value: 0},
      {name: '只开空单', value: 1},
      {name: '只开多单', value: 2},
      {name: '禁止开仓', value: 3}
    ],
    followRuleContent:
      '跟随规则：<br/>\n      1. 挂单不会立即跟随，当其成交为市价单时，方才进行跟随。<br/>\n      2. 止盈/止损不会跟随，以避免跨平台跟随时因交易环境（价格、点差等）的差异而导致的提前出场等问题。<br/>\n      3. 合约自适应功能并不支持所有品种，如股指、期货、股票等品种便不被支持。<br/>\n      4. 开仓手数若超过交易商规定的最大手数或低于交易商规定的最小手数，则按最大手数或最小手数开仓。<br/>\n      5. 受各端网络环境影响，交易信号可能会产生延迟。若信号被延迟太久，应放弃跟随。因此，系统默认会丢弃延迟时间超过 180s 的开仓信号或超过 30 分钟的平仓信号。',
    notMatchTips:
      '跟随账户下有 {x} 个品种无法与信号账户下的交易品种相匹配，导致它们无法进行跟随交易，请在“品种设置”栏目下予以确认。',
    maxLotsMoreThan: '最大开仓手数不得小于固定开仓手数',
    allMatchTips: '在“品种设置”栏目下，请务必确保信号账户与跟随账户的品种名称已被映射正确，否则将导致跟随异常。',
    hasConfirm: '我已确认',
    gotoCheck: '前往核实',
    settingSuccess: '设置成功',
    mySubscribe: '我跟单的',
    account: '信号账户',
    currPosition: '当前持仓',
    yesterdayEarnings: '昨日收益',
    monthEarnings: '近1月收益',
    status: '跟单状态',
    statusList: ['跟单中', '{x} 天后到期', '即将到期'],
    totalTime: '累计跟单时长',
    operation: '操作',
    viewToAccount: '查看跟单我的人，请前往<a target="_blank" href="{x}">交易账户详情</a>页面',
    times: '倍',
    connectionAnomaly:
      '您的交易账户 #{x} 已掉线，暂时无法使用。<br/>如果该账户的连接密码已被更改，请前往 个人中心-交易账户-账户设置 页更新连接密码。',
    passwordTypeTips:
      '您的交易账户 #{x} 当前使用的连接密码为观摩密码，不具有交易权限，因此无法在牛人榜内进行跟随交易。<br/>您需前往 个人中心-交易账户-账户设置 页将该账户的连接密码更新为 交易密码，然后再进行跟单。',
    goNow: '立即前往',
    warmPrompt: '温馨提示：<br/>\n      1. 您可随时进入“个人主页”->“跟单”栏目下修改您的跟随设置。<br/>',
    fixedHands: '固定手数',
    fixedRatio: '固定比例',
    fixedRatioTips: '根据信号账户与跟随账户之间的净值关系来计算跟随手数，并按此处指定的比例倍数来放大或缩小手数大小。',
    fixedHandsTips: '无论信号账户开多少手，均只按此处指定的手数来跟随开仓。如无特殊要求，推荐使用 “固定比例” 跟随。',
    ratio: '{x} 倍',
    signalVariety: '品种(信号账户)',
    followVariety: '品种(跟随账户)',
    selectVariety: '选择品种',
    searchVariety: '搜索品种',
    hasQuestion: '遇到问题？请联系<span>官方客服</span>',
    subscribeInfo: '跟单信息',
    followAgain: '再次跟单',
    residueLong:
      '您的跟单权限剩余时长为 {0} 个月，暂不支持继续延长跟单。\n      <br/>注意，剩余的跟单时长最长只支持 {1} 个月。因此，您可在剩余的跟单时长不足 {2} 个月时再来延长跟单。',
    subscribeExpire: '跟单期满',
    closeTips: '只想接收信号，不跟单，可关闭跟随状态',
    shareGetFollow: '分享获取跟单权限功能已停用，请前往会员中心开通会员后进行跟单',
    signalNotFollow: '信号账户不支持跟单',
    initNotFollow: '初始化中，请稍后重试'
  },
  header: {
    searchLabel: '搜索',
    product: '产品',
    market: '市场',
    information: '资讯',
    signal: '信号',
    match: '比赛',
    activity: '活动',
    broker: 'Brokers',
    more: '更多',
    chart: '图表',
    stockFilter: '筛选器',
    financialCalendar: '财经日历',
    toolKit: '工具',
    cost: '价格',
    feature: '功能特色',
    dataMarket: '市场数据',
    overview: '概览',
    myOptional: '我的自选',
    news: '新闻',
    transactionAnalysis: '分析',
    quickInformation: '快讯',
    column: '专栏',
    answer: '专家问答',
    data: '数据',
    video: '视频',
    institutionalViewPoint: '机构观点',
    analystViewPoint: '分析师观点',
    columnTopic: '专栏话题',
    columnist: '专栏作家',
    dataCenter: '数据中心',
    marketTrend: '市场动向',
    institutionalData: '机构数据',
    centralBankInterestRate: '央行利率',
    macroEconomy: '宏观经济',
    niuList: '牛人榜',
    bestNiuer: '每周精选',
    AISignal: '最新信号',
    fansActivity: '粉丝见面会',
    web_ib_seminar: 'IB研讨会',
    voteActivity: '红人评选',
    web_fans_hongkong: '中国·香港',
    web_fans_hochiminh: '越南·胡志明',
    web_fans_dubai: '阿联酋·迪拜',
    web_fans_cairo: '埃及·开罗',
    web_fans_nigeria: '尼日利亚·拉各斯',
    business: '商业',
    recruit: '招聘',
    aboutUs: '关于我们',
    whiteLabel: '白标',
    dataAPI: '数据API',
    webPlugins: '网页插件',
    feedback: '意见反馈',
    helpCenter: '帮助中心',
    agreement: '用户协议',
    policy: '隐私政策',
    comingSoon: '即将上线',
    marketPrice: '行情',
    calendar: '日历',
    quotation: '报价',
    PRO: 'Pro',
    AIRating: 'AI评级',
    latestViewPoints: '最新观点',
    calendarWallpaper: '日历壁纸',
    speculativeMood: '投机情绪',
    hangingOrderPosition: '挂单持仓',
    varietyCorrelation: '品种相关性',
    popularIndex: '热门指标',
    hotTopic: '热门话题',
    recentUpdate: '最近更新',
    language: '语言',
    popularSearch: '热门搜索',
    historySearch: '最近搜索',
    myCollection: '我的收藏',
    myConcern: '我的关注',
    mySubscription: '我的跟单',
    personalInformation: '个人信息',
    memberCenter: '会员中心',
    accountSetting: '账号设置',
    logOut: '登出',
    scanDownload: '扫一扫，下载',
    moreInformation: '更快的财经资讯和报价',
    downloadApp: '下载APP',
    addFBToDesk: '添加Fastbull到桌面',
    loadFromDesk: '下次可以从电脑桌面直接访问Fastbull',
    addToDesk: '添加到桌面',
    recommendSelfSelection: '推荐自选',
    waitingForDeal: '待成交',
    inTransaction: '交易中',
    overDeal: '交易结束',
    overdue: '已过期',
    profitMaking: '盈利',
    lossMaking: '亏损',
    profitLoss: '盈亏',
    financialTools: '金融工具',
    homePage: '首页',
    clickLogin: '点击登录',
    AppDescription: '更快更全的财经新闻和报价',
    supportResistance: '支撑阻力',
    copyright: 'Copyright © {x} FastBull Ltd',
    risk: '风险披露',
    riskText1:
      '交易股票、货币、商品、期货、债券、基金等金融工具或加密货币属高风险行为，这些风险包括损失您的部分或全部投资金额，所以交易并非适合所有投资者。',
    riskText2:
      '做出任何财务决定时，应该进行自己的尽职调查，运用自己的判断力，并咨询合格的顾问。本网站的内容并非直接针对您，我们也未考虑您的财务状况或需求。本网站所含信息不一定是实时提供的，也不一定是准确的。本站提供的价格可能由做市商而非交易所提供。您做出的任何交易或其他财务决定均应完全由您负责，并且您不得依赖通过网站提供的任何信息。我们不对网站中的任何信息提供任何保证，并且对因使用网站中的任何信息而可能造成的任何交易损失不承担任何责任。',
    riskText3:
      '未经本站书面许可，禁止使用、存储、复制、展现、修改、传播或分发本网站所含数据。提供本网站所含数据的供应商及交易所保留其所有知识产权。',
    cookieTips:
      '我们使用cookie来了解您如何使用我们的网站并改善您的体验，包括个性化内容。如继续使用我们的网站，即表示您接受我们使用cookies。如您想了解更多，请点击这里 ',
    viewDetail: '查看详情',
    authorization: '授权使用',
    function: '功能',
    company: '公司',
    user: '用户',
    theLatestValue: '最新值',
    allSearchResult: '查看所有搜索结果',
    loginBtn: '登录',
    signUPBtn: '注册',
    freeToOpenVIP: '免费开通VIP',
    web_opinion_hot_author: '热门作家',
    market_finance_coverview: '概览',
    freeForevet: '永久免费',
    moduleDark: '暗黑模式',
    loginForMoreFunc: '登录查看更多功能',
    noLogin: '未登录'
  },
  sideLayout: {
    news_calendar_filter_only_import: '只看重要',
    news_snowfall: '相关链接',
    news_unscramble: '快讯解读',
    news_unscramble_long: '长期',
    news_unscramble_short: '短期',
    news_unscramble_bearish: '利空',
    news_unscramble_bullish: '利多',
    calendar_time_up: '时间',
    calendar_prev_up: '前值',
    calendar_est_up: '预测值',
    calendar_act_up: '公布值',
    calendar_unrelease: '未公布',
    calendar_revised: '修正前',
    calendar_act: '公布值',
    calendar_est: '预测值',
    calendar_prev: '前值',
    new_share: '分享',
    vip_invite_friends_immediately: '分享给好友，免费得会员',
    vip_invite_friends_title: '立即分享',
    qa_header_title: '专家问答',
    qa_header_online: '在线答疑',
    qa_ask_question: '我要提问...',
    qa_post_first_question: '快来发布第一条提问吧',
    qa_expert: '专家',
    qa_view_translation: '查看翻译',
    qa_view_original: '查看原文',
    qa_answer: '回答',
    qa_cancel_answer: '取消回答',
    qa_answer_placeholder: '回答{0}',
    qa_confirm_delete_question: '确认删除该条提问？',
    qa_confirm_delete_answer: '确认删除该条回答？',
    qa_select_pic_format: '请选择png、jpg、jpeg、gif、bmp，webp格式',
    qa_common_bottom: '我是有底线的',
    qa_remind_max_char: '最多输入{0}个字符',
    qa_cancel_reply: '取消回复',
    qa_reply_someone: '回复{0}',
    quote_nav_more: '更多',
    quote_link_more: '查看更多',
    quote_table_asset: '资产',
    quote_table_last: '最新价',
    quote_table_netchg: '涨跌额',
    quote_table_chg: '涨跌幅',
    quote_table_update: '更新时间',
    news_news_trending: '热门',
    quote_table_high: '最高',
    quote_table_low: '最低',
    quote_watchlist: '自选',
    quote_my_watchlist: '我的自选',
    reminderg: '提醒设置',
    maincontainer_market: '行情',
    news_flash: '快讯',
    news_calendar: '日历',
    q_a: '问答',
    home_tab_chat: '聊天',
    common_side_layout: '布局',
    common_layout_single: '单列布局',
    common_layout_vertical: '上下布局',
    common_layout_tile: '并列布局',
    cale_unpublish_time: '{0}后公布',
    cale_unpublish_time_h: '{0}时',
    cale_unpublish_time_min: '{0}分',
    add_asset_name: '添加资产名称或代码',
    add_to_favorites: '添加自选',
    recentlyViewed: '最近浏览',
    common_market_closed: '市场关闭',
    chart_indicator: '指标',
    chart_strategy: '策略',
    chart_edit: '编辑器',
    chart_backtest: '回测',
    chart_order: '新订单',
    chart_template: '模板',
    chart_sync: '同步',
    chart_history: '历史',
    chart_remind: '提醒',
    chart_log: '日志',
    chart_connect: '正在连接服务器，请稍后...',
    searchStocksTips: '在主窗口按 A-Z 或 0-9 任意键，即可启动品种搜索'
  },
  dataCollect: {
    fxchat_login_edit_user_info_title: '编辑个人信息(1/3)',
    fxchat_login_complete_material_title: '完善您的资料(2/3)',
    fxchat_login_recommendation_title: '优质推荐(3/3)',
    fxchat_information_nick_name: '昵称',
    fxchat_login_field_title: '输入您的昵称',
    fxchat_information_sex: '性别',
    fxchat_information_sex_man: '男',
    fxchat_information_sex_women: '女',
    fxchat_information_sex_other: '其他',
    fxchat_information_sex_secret: '保密',
    fxchat_material_morning: 'Hi，“{0}”早上好! 欢迎来到FastBull',
    fxchat_material_noon: 'Hi，“{0}”中午好! 欢迎来到FastBull',
    fxchat_material_afternoon: 'Hi，“{0}”下午好! 欢迎来到FastBull',
    fxchat_material_night: 'Hi，“{0}”晚上好! 欢迎来到FastBull',
    fxchat_material_introduction: '为了更好给您推荐更优质的内容，请简单介绍一下自己吧。',
    fxchat_recommendation_subtitle: '根据您所选资料，为您精准推荐。',
    fxchat_material_summarize: '太棒了！根据您提供的信息，我们将定制专属优质的内容给您。',
    fxchat_material_assistant_name: 'AI机器人',
    fxchat_material_look: '立即查看',
    fxchat_material_reselect: '重新选择',
    fxchat_recommendation_see_more: '查看更多',
    fxchat_recommendation_open_fxchat: '开启FastBull',
    fxchat_recommendation_open_group: '群聊',
    fxchat_recommendation_open_niu: '热门牛人',
    fxchat_not_group_introduction: '群主很懒，还没有群介绍~',
    fxchat_recommendation_join: '加入',
    fxchat_recommendation_has_join: '已加入',
    fxchat_login_skip: '跳过',
    fxchat_recommendation_follow: '关注',
    fxchat_recommendation_has_follow: '已关注',
    fxchat_login_trading_type: '您比较感兴趣的交易市场？（可多选）'
  },
  setting: {
    personalData: '个人资料',
    accountSafety: '账户安全',
    informSetting: '通知设置',
    privacy: '隐私',
    blacklist: '黑名单',
    remove: '移除',
    removeSuccess: '移除成功',
    shieldingTime: '拉黑时间: {x}',
    addStyle: '加我为好友的方式',
    allowAll: '允许任何人加好友',
    needVerify: '需要发送验证消息',
    notAllowAny: '不允许任何人加好友',
    findByPhone: '通过手机找到我',
    findByPhoneTips: '关闭后，其他用户将不能通过上述信息找到你',
    follow: '跟单',
    followTips: '开启后，跟单信息将对外显示',
    contest: '比赛',
    contestTips: '开启后，比赛信息将对外显示',
    emailNotice: '电子邮件通知偏好',
    weeklySelection: 'FastBull每周市场精选资讯',
    willPushNews: '我们将为你推送您近期关注的相关重大资讯新闻',
    sendWeek: '每周发送',
    dailyHighlights: 'FastBull今日市场重大资讯',
    sendDay: '每天发送一次（周一-周五）',
    baseInfo: '基本信息',
    nickname: '昵称',
    joinStyle: '入群方式',
    aphorism: '交易格言',
    editInfo: '编辑个人信息',
    interestInfo: '感兴趣的信息',
    noAddInterest: '暂未添加感兴趣的内容~',
    dealPlatform: '交易平台',
    dealMarket: '交易市场',
    dealVariety: '交易品种',
    dealStyle: '交易风格',
    avatar: '头像',
    modifyAvatar: '修改头像',
    username: '用户名',
    sex: '性别',
    dealAge: '交易年龄',
    address: '所在地',
    industry: '从事行业',
    modify: '修改',
    addIndustry: '添加从事行业',
    userIntro: '个人简介',
    interestDealInfo: '感兴趣的交易信息',
    add: '添加',
    sexList: [
      {value: 0, name: '男'},
      {value: 1, name: '女'},
      {value: 2, name: '保密'}
    ],
    industryType: '行业类型',
    inIndustry: '业内行业',
    outIndustry: '非业内行业',
    interestPlayform: '感兴趣的交易平台',
    interestMarket: '感兴趣的交易市场',
    interestStyle: '感兴趣的交易风格',
    interestVariety: '感兴趣的交易品种',
    maxOption: '最多可以选择{x}项',
    blackTypeList: [
      {value: 1, name: '通讯录'},
      {value: 2, name: '群聊'}
    ],
    accountInfo: '账户信息',
    userPassword: '用户密码',
    haveSet: '已设置',
    isNotSet: '未设置',
    phoneNumber: '手机号码',
    notBind: '未绑定',
    bind: '绑定',
    email: '邮箱地址',
    bindThird: '绑定第三方',
    unBind: '解除',
    bindPhone: '绑定手机号',
    changePhone: '修改手机号',
    inputPhone: '请输入手机号',
    and: '和',
    inputPhoneTips: '请输入正确的手机号',
    inputVerifyCode: '请输入4位验证码',
    oldPhoneNumber: '原手机号码',
    newPhoneNumber: '新手机号码',
    bindEmailOpen: '请绑定邮箱开启帐密登录功能',
    bindEmail: '绑定邮箱',
    setPassword: '设置密码',
    password: '密码',
    inputPwd: '请输入密码',
    pwdRules: '密码要求6-20位，包含数字、字母、符号中至少2种',
    updatePwd: '修改密码',
    currentPwd: '当前密码',
    forgetPwd: '忘记密码？',
    newPwd: '新密码',
    pwdNotSame: '两次密码不一致',
    emailResetPwd: '输入您的电子邮件地址，我们将向您发送一个链接以重置您的密码',
    sendResetLink: '发送重置链接',
    inputEmail: '请输入邮箱号',
    inputRightEmail: '请输入正确的邮箱',
    alreadSendLink: '我们已经向您发送了一个链接来重置您的密码',
    alreadSendTo: '我们已发送一封邮件到',
    noGetFindHelp: '如果您在5分钟内没有收到一封信，请检查“垃圾邮件”或寻求帮助',
    findHelp: '寻求帮助',
    getVerifyCode: '获取验证码',
    notGet: '仍未收到？',
    resend: '重发邮件',
    inputCode: '请输入验证码',
    beGetting: '正在获取...',
    resendAfter: '{x} s 后可重发',
    selectAvatar: '选择头像',
    customAvatar: '自定义头像',
    reUpload: '重新上传',
    defaultAvatar: '默认头像',
    imgType: '仅支持 {x} 的图片格式!',
    inputNickname: '请输入昵称',
    inputUsername: '请输入用户名',
    usernameTips: '用户名只能包含小写字母、数字、下划线、句点。更改你的用户名也将更改你的个人主页链接'
  },
  vip: {
    equities: '权益',
    detail: '明细',
    hasCode: '我有兑换码',
    inputCode: '请输入兑换码',
    conversion: '兑换',
    shareGet: '分享免费得会员',
    shareGetYear: '分享免费领取1个月会员',
    inviteUser: '邀请的新用户点击你分享的链接，完成登录注册后即可获得1个月会员时长',
    scanQRCode: '手机扫描二维码',
    shareLink: '分享链接领取会员',
    recharge: '充值得会员',
    agree: '我已阅读并同意',
    agreement: '会员服务协议',
    privilege: '会员特权',
    time: '时间',
    duration: '获取会员时长',
    getMode: '获取方式',
    status: '状态',
    redeemRules: '兑换码使用规则：<br/>\n1.已激活的兑换码无法再次使用<br/>\n2.超过兑换码有效期无法使用',
    privilegeList: [
      {id: 1, title: 'AI快讯快速达', desc: '实时快速送达更多精选快讯内容'},
      {id: 2, title: '追踪更多行情品种', desc: '可添加更多自选品种，实时追踪更多行情数据'},
      {id: 3, title: '宏观数据、经济指标更全面', desc: '更全面的指标历史数据，助力分析宏观市场'}
    ],
    shareTitle: '我在FastBull给你开通了超值VIP，最高价值1648元，快来领取吧~'
  },
  promotion: {
    volumnMuteDefault: '默认静音播放',
    enableVolumn: '开启声音',
    kolInterview: 'KOL专访',
    userComment: '用户评价',
    moreFunction: '更多功能',
    moreFunctionTxt: '探索新功能，你想要的这里都有！'
  },
  tdk: {
    title: 'FastBull - 更快的财经资讯和报价',
    homeTitle: '外汇神级人物_外汇牛人榜_外汇牛人盘点 - （品牌词）',
    homeDesc: 'FastBull牛人榜，让您跟随最赚钱的投资者，学习他们的策略，提升交易水准。',
    greatestTitle: 'FastBull每周精选',
    greatestDesc: 'FastBull每周精选，收益、量化、单量、胜率，评选出最优秀的投资者。',
    helpTitle: '帮助中心-FastBull',
    helpDesc: '在我们的帮助中心查找常见问题的答案和有用的资源。',
    userTitle: '【{x}】- 个人主页',
    userDesc: '通过个人主页，找到志同道合的交易者吧。'
  },
  about: {
    downloadApp: '下载APP',
    aboutFb: '关于FastBull',
    fbExplain:
      'FastBull是金融互联网的技术创新者，我们在众多地区建立了编辑和翻译团队，并将继续致力于各个国家的本地化内容建设。同时我们拥有最具有技术实力和规模的研发团队和产品团队，将在未来不断提供顶级的软件体验。',
    service: '提供的服务',
    product: '产品',
    productExplain: '我们已上架财经日历和工具功能，更多重磅功能即将上线：超级图表，股票筛选器，市场数据等尽请期待。',
    signal: '信号',
    signalExplain: '资讯、牛人榜、每周精选、最新信号、比赛。交易大牛做单信号实时提供，可实时跟单交易，让交易更简单。',
    message: '资讯',
    messageExplain:
      '新闻、快讯、分析、专栏、数据、视频。覆盖全球实时热点，分析师的交易观点，和机构观点数据。同时7X24小时实时更新热点事件，财经数据。',
    market: '市场',
    marketExplain:
      '我们提供了，外汇市场、商品、指数，美股，数字货币，CME等市场行情。未来我们将持续提供全球股票市场和ETF、债券等市场行情。',
    business: '商业',
    businessExplain: '我们提供一些免费/付费的第三方服务，白标、数据API、网页插件，提供数据源支持和技术支持。',
    course: '发展历程',
    contact: '联系我们',
    partner: '合作伙伴',
    email: '官方邮箱',
    feedback: '意见反馈',
    scan: '扫码体验',
    android: 'Android版',
    ios: 'iOS版',
    downloadTips: '与全球投资者实时讨论、分享你的交易想法和观点',
    chat: '即时聊天',
    chatExplain: '汇聚全球交易牛人，畅聊交易',
    chart: '社交图表',
    chartExplain: '分析行情、讨论交易、订阅信号',
    realTimeSignal: '实时信号',
    realTimeSignalExplain: '真实交易信号，免费跟单',
    contest: '交易竞赛',
    contestExplain: '展示交易能力的最佳舞台',
    answer: '专家答疑',
    answerExplain: '向专家提问，免费获取专业意见',
    analyse: '交易分析',
    analyseExplain: '观摩学习投资专家的交易逻辑',
    calendar: '财经日历',
    calendarExplain: '专业分析工具深入解读经济数据',
    news: '精选新闻',
    newsExplain: '汇聚全球金融专家的深度观点',
    tools: '海报工具',
    toolsExplain: '支持个性化定制各类金融海报',
    more: '更多',
    moreExplain: '下载FastBull，体验更多精彩功能',
    downloadFrom: '下载自'
  },
  chat: {
    headTabs: ['全部', '聊天室', '群聊', '好友'],
    placeInput: '请输入...',
    connecting: '正在连接聊天室'
  },
  chart: {
    period: ['{x}分钟', '{x}小时', '日', '周', '月']
  }
}
