export default {
  common: {
    confirm: 'Confirm',
    affirm: 'Confirm',
    remove: 'Delete',
    cancel: 'Cancel',
    tips: 'Hint',
    finish: 'Done',
    know: 'Got it',
    time: 'Time',
    count: '{x} items',
    hand: '{x} lots',
    order: '{x} orders',
    score: '{x} points',
    person: '{x} followers',
    times: '{x} times',
    second: '{x} seconds',
    minutes: '{x} minutes',
    hour: '{x} hours',
    day: '{x} days',
    month: '{x} months',
    year: '{x} years',
    shortsecond: '{x} s',
    shortminutes: '{x} min',
    shorthour: '{x} h',
    shortday: '{x} d',
    justNow: 'Just now',
    minuteAgo: '{x} minute ago | {x} minutes ago',
    hourAgo: '{x} hour ago | {x} hours ago',
    yesterday: 'YTD {x}',
    beforeYesterday: '2D Ago {x}',
    yearUnit: 'Year',
    monthUnit: 'Month',
    dayUnit: 'Day',
    hourUnit: 'Hour',
    minutesUnit: 'Minute',
    secondUnit: 'Second',
    hundredMillion: '{x} billion',
    trillion: '{x} trillion',
    loading: 'Loading...',
    noMore: 'No more data',
    all: 'All',
    reset: 'Reset',
    unfoldAll: 'Expand All',
    packUp: 'Close',
    unfold: 'Expand',
    back: 'Back',
    warning: 'Warning',
    noData: 'No data',
    imageFormat: 'Only JPG, JPEG or PNG files allowed',
    imageSize: 'Image size no more than {x} MB',
    shareFb: 'Share FastBull for One-Month Free Signals',
    noNetLaterTry: 'Network anomalies. Please try again later...',
    copy: 'Copy',
    copySuccess: 'Link copied',
    appDownload: 'APP Download-FastBull',
    fbDownload: 'FastBull APP Download',
    getSuccess: 'You now have access to one-month free signals',
    reLogin: 'Your login has expired. Please log in again.',
    notFound: 'Sorry, the address of the page you visited is wrong or the page does not exist',
    returnToLast: 'Back ',
    returnToHome: 'Home',
    forbidden: 'Access denied',
    noAccess: 'You do not have permission to view this directory or page using the credentials you supplied.',
    serverError: 'Error',
    tryRefresh: 'Please refresh the page and try again',
    operationConfirm: 'Confirm',
    select: 'Select',
    download: 'Download',
    close: 'Close',
    isDelete: 'Deleted',
    noResult: 'Sorry, no results found',
    tryAgain: 'You may try another keyword and search again',
    loginInOther:
      'Your account is logged in on another browser. If it is not done by yourself, the password may be leaked. Please change the password immediately.',
    chartLoading: 'Chart loading...',
    custom_service: 'Customer Service',
    common_look: 'View'
  },
  message: {
    messageCenter: 'Notifications',
    system: 'Community Notifications',
    trading: 'Trading Signals',
    comment: 'Replies',
    account: 'Account Notifications',
    answer: 'Expert Q&A',
    noMoreData: 'No more data',
    viewAll: 'View All',
    noNewMsg: 'No new message yet',
    noMessage: 'No message available',
    systemMsgTypeList: [
      {type: 0, label: 'All Content'},
      {type: 1, label: 'Community Notifications'},
      {type: 3, label: 'My Signal Providers'},
      {type: 4, label: 'My Followers'}
    ],
    commentMsgTypeList: [
      {type: 0, label: 'Account Comments'},
      {type: 1, label: 'News Comments'},
      {type: 2, label: 'Video Comments'}
    ],
    accountMsgTypeList: [
      {type: 0, label: 'All Content'},
      {type: 1, label: 'Account Changes'},
      {type: 2, label: 'Ranking Updates'},
      {type: 4, label: 'Trading Reports'}
    ],
    open: 'Open',
    openTime: 'Opening Time',
    close: 'Close',
    closeTime: 'Closing Time',
    riskWarning: 'Risk Warnings',
    subscribeNotice: 'Announcements',
    clickView: 'View',
    allSource: 'All Sources',
    replyYou: 'replied to you',
    answerYou: 'answered your question',
    commentAccount: 'commented on your trading account',
    commentYou: 'commented on you',
    viewDetail: 'View Details',
    commentTypeList: ['Comments', 'Replies'],
    reportAccount: 'reported your trading account',
    waitFollow: 'Waiting',
    followSuccess: 'Followed Successfully',
    followFailed: 'Failed to Follow',
    ignore: 'Ignored',
    tryFollow: 'Trying to follow this signal. Please wait...',
    followOrder: 'Order',
    followStatus: 'Status',
    unit: 'Unit',
    noSignal: 'No trading signals yet',
    orderId: 'Order ID',
    statusList: ['Waiting', 'Followed', 'Failed to Follow', 'Ignored'],
    statusTitle: ['Why Waiting', 'Order ID', 'Failure Reason', 'Why ignored'],
    goSetting: 'Go to Settings',
    viewOrder: 'View Trade',
    stopProfit: 'TP',
    stopLoss: 'SL',
    openPrice: 'Opening Price',
    closePrice: 'Closing Price',
    delist: 'The content has been removed',
    remove: 'The content has been deleted'
  },
  home: {
    actualIntro: 'Live Accounts',
    actual: 'Live Accounts',
    profitIntro: 'Profitable Live Accounts',
    profitAccount: 'Profit Accounts',
    lossIntro: 'Losing Live Accounts',
    lossAccount: 'Loss Accounts',
    blastingIntro: 'Live accounts liquidated in the past',
    blastingAccount: 'Liquidated Accounts',
    allMen: 'All Top Traders',
    openAccountToDate: 'Since account opening',
    lastJune: 'Past 6 months',
    already: 'Followers',
    yieldValueChart: 'TWR Chart',
    favor: 'You may also like',
    refresh: 'Change',
    unlimited: 'All',
    rank: 'Overall Rating',
    earnings: 'TWR',
    riskLevel: 'Risk Level',
    broker: 'Brokers',
    goodAt: 'Good at',
    moreOptions: 'More',
    dealWinRate: 'Win Rate',
    ratio: 'P/L Ratio',
    openTime: 'Account Duration',
    capital: 'Deposit',
    accountType: 'Account Type',
    platform: 'Broker',
    clear: 'Clear',
    noContent: 'Content unavailable',
    noBroker: 'Content unavailable',
    accountRatingRangeList: [
      {value: 1, label: 'Level A'},
      {value: 2, label: 'Level B'},
      {value: 3, label: 'Level C'}
    ],
    twrRangeList: [
      {value: '', label: 'All'},
      {value: 2, label: '0%~30%'},
      {value: 3, label: '30%~60%'},
      {value: 4, label: '60%~100%'},
      {value: 5, label: '100%~200%'},
      {value: 6, label: '> 200%'}
    ],
    riskLevelList: [
      {value: 1, label: 'Low'},
      {value: 2, label: 'Medium'},
      {value: 3, label: 'High'}
    ],
    winRateRangeList: [
      {value: 0, label: 'All'},
      {value: 2, label: '≥ 50%'},
      {value: 3, label: '≥ 60% '},
      {value: 4, label: '≥ 70%'},
      {value: 5, label: '≥ 80%'},
      {value: 6, label: '≥ 90%'}
    ],
    profitLossRatioRangeList: [
      {value: 0, label: 'All'},
      {value: 2, label: '≥ 0.5'},
      {value: 3, label: '≥ 1.0'},
      {value: 4, label: '≥ 1.5'},
      {value: 5, label: '≥ 2.0'},
      {value: 6, label: '≥ 2.5'},
      {value: 7, label: '≥ 3.0'}
    ],
    openingTimeRangeList: [
      {value: 0, label: 'All'},
      {value: 1, label: '≤ 1 month'},
      {value: 2, label: '> 1 month'},
      {value: 3, label: '> 3 months'},
      {value: 4, label: '> 6 months'},
      {value: 5, label: '> 12 months'}
    ],
    amountOfFundsRangeList: [
      {value: 0, label: 'All'},
      {value: 1, label: '< 100'},
      {value: 2, label: '100 to 1,000'},
      {value: 3, label: '1,000 to 3,000'},
      {value: 4, label: '3,000 to 10,000'},
      {value: 5, label: '10,000 to 100,000'},
      {value: 6, label: '100,000 to 300,000'},
      {value: 7, label: '> 300,000'}
    ],
    accountTypeList: [
      {value: 1, label: 'Live'},
      {value: 2, label: 'Demo'}
    ],
    orderList: [
      {value: 2, name: 'TWR'},
      {value: 3, name: 'Max Drawdown'},
      {value: 4, name: 'Win Rate'},
      {value: 5, name: 'P/L Ratio'},
      {value: 6, name: 'Followers'}
    ],
    niuTopTypeList: ['Highest TWR', 'Best EA Trading', 'Most Trades', 'Highest Win Rate'],
    threeMonthData: 'Data for Past 3M',
    dataFieldList: ['Daily TWR', 'EA%', 'Daily Trades', 'Win Rate'],
    threeMonthEarnings: 'TWR for Past 3M',
    positionDuration: 'Holding',
    lastThreeMonth: 'Past 3 Months',
    detail: 'Details',
    appraise: 'Weekly Rankings',
    nextUpdate: 'Next Update',
    currentStage: 'Current Ranking',
    stage: 'Issue {x}',
    nobodyOnTheList: 'No ranking in this issue',
    ruleContent:
      'Rank top traders in terms of P/L, EA, number of trades, and win rate in the past 3 months respectively. Profitable accounts with excellent trading records are qualified for the weekly rankings.',
    udpateTime: 'Updated Every Saturday at {x}',
    weeklySelection: 'Weekly Rankings',
    totalAccountNum: 'General account',
    echartMeaning: 'Chart Meaning',
    transactionSoftwareList: [
      {value: 2, label: 'MT4'},
      {value: 1, label: 'MT5', disabled: true}
    ],
    infiniteTxt: 'Unlimited',
    selectBrokerNum: '{x} brokers selected',
    moreSelect: 'Multiple Choice',
    indexSubTabItem1: 'TWR 60%~100%',
    indexSubTabItem2: 'Low Risk',
    indexSubTabItem3: '> 12 months',
    indexSubTabItem4: 'Funding amount: USD 10 to 10k ',
    indexSubTabItem5: 'Win rate > 90%',
    indexSubTabItem6: 'P/L Ratio > 3',
    filterNiuTitle: 'Select Top Traders',
    selectBrokerTitle: 'Select Brokers',
    allTimePeriod: 'Any Time',
    searchBroker: 'Search for Brokers',
    KOLInterview: 'KOL Interviews',
    userEvaluation: 'User Reviews',
    interestBroker: 'Interested Broker'
  },
  aiRating: {
    gradeTimes: 'Number of AI ratings',
    dataCutOff: 'Data by {x}',
    gradeModel: 'Rating based on multiple metrics',
    modelIntro:
      "The AI ​​rating system conducts a comprehensive review of trading accounts from five dimensions: P/L, orders, positions, financial instruments, and styles, and accurately evaluates an account's performance in terms of profitability, stability, and risk.",
    sample: 'Proven Track Records',
    sampleIntro:
      'Thousands of trading accounts and tens of millions of trade orders, with objective & unbiased judging results, are the best endorsement of the AI Rating System.',
    highAccount: 'Elite Account',
    highIntro: 'Great performance in profitability, volatility, and risk level.',
    profitAccount: 'Profit Account',
    middleAccount: 'Standard Account',
    middleIntro: 'Good profitability but average volatility and risk level.',
    lowAccount: 'Basic Account',
    lowIntro: 'Low profitability with high-level risk.',
    moreClient: 'Higher ratings, more customers',
    moreIntro:
      'The higher the rating, the stronger the account and the greater the possibility of being copied and followed by customers. Among the existing copied trades on Top Traders, more than {x} copied accounts are A-level or above.',
    allUse: 'They are all in use',
    yourScore:
      'The AI ​​rating system gives you the most realistic score for your trading exam paper. Come and see your score~',
    profitLoss: 'P/L',
    orderForm: 'Order',
    position: 'Position',
    variety: 'Instrument',
    style: 'Style'
  },
  account: {
    settingOptions: [
      {value: 1, name: 'Data Settings'},
      {value: 2, name: 'Permission Settings'}
    ],
    deleteAccount: 'Delete Account',
    sureToDelete: 'Are you sure you want to delete this trading account?',
    deleteMatters: 'Note: The trading account cannot be linked once deleted until 7 days later.',
    confirmDelete: 'Confirm ',
    cancelSubscribeBeforeDel:
      'This account is currently copying {x} signal accounts. Please cancel these copied trades first if you want to delete the account.',
    deleteSuccess: '{x} deleted',
    deleteFailed: 'Failed to delete {x}',
    settingSaved: 'Settings saved',
    accountPermission: 'Account Permission',
    subscribePermission: 'Signal Providing Permission',
    accountPrivate:
      'You are not allowed to provide signals to other users.\nTo sell signals, set your account access to "Public" and enable the signal providing permission',
    commentPermission: 'Comment Permission',
    accountcommentForbid:
      'This account has been blocked from posting comments. Please contact customer service if you have any questions.',
    positionOrder: 'Open Orders',
    historyOrder: 'Historical Orders',
    weeklyReport: 'Send me trading report for this account weekly',
    monthlyReport: 'Send me trading report for this account monthly',
    tradingDayReport: 'Daily Report',
    tradingWeekReport: 'Weekly Report',
    tradingMonthReport: 'Monthly Report',
    linkAbnormal: 'Disconnected',
    linkAbnormalExplain: 'The trading account is disconnected. Please do not copy it.',
    riskAccount: 'Account in Loss',
    riskAccountExplain: 'This trading account has a greater risk of loss. Please be careful when copying trades.',
    abnormalAccount: 'Abnormal Account',
    abnormalAccountExplain: 'This trading account is being verified. Please be careful when copying trades.',
    sixMonthEarnings: 'TWR for Past 6M',
    actualAccount: 'Live Account',
    virtualAccount: 'Demo Account',
    balance: 'Balance',
    netValue: 'Equity',
    maxDrawdown: 'MDD',
    drawdownTips:
      'Max Drawdown (MDD) refers to the maximum loss experienced since account opening. For newly linked accounts, MDD is based on account balance. Please note Top Traders calculates MDD differently from MT4 for improved accuracy, leading to inconsistencies.',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    fetch: 'Withdrawal',
    save: 'Deposit',
    creditFetch: 'Credit in',
    creditSave: 'Credit out',
    dealAccount: 'Trading Account',
    dataSynchronizationErr: 'Data sync failed. Please check your account or password!',
    notOpen: 'Unavailable yet. Please stay tuned',
    signalProvider: 'Become a signal provider',
    tradingAccountSetting: 'Trading Account Settings',
    profitLossRatio: 'P/L Ratio',
    dateOptions: [
      {value: 0, name: 'Any Time'},
      {value: 1, name: '1 Month'},
      {value: 2, name: '3 Months'},
      {value: 3, name: '6 Months'},
      {value: 4, name: '12 Months'}
    ],
    yieldRate: 'TWR',
    totalProfitLoss: 'Total P&L',
    synthesizeRank: 'Overall Ranking',
    rankTips: 'The overall ranking is based on the aggregate score of live accounts',
    synthesizeScore: 'Aggregate Score',
    scoreTips:
      'Rate and score accounts on metrics such as P/L, number of trades, position size, instruments and styles.',
    periodList: [
      {value: 1, name: 'Day'},
      {value: 2, name: 'Week'},
      {value: 4, name: 'Month'}
    ],
    profitLossTitle: ['Daily P&L', 'Weekly P&L', 'Monthly P&L'],
    forbidBroker:
      '\nTrading accounts opened with {x} are disqualified from providing signals at Top Traders and are not allowed to be added to Top Traders any more.',
    accountSetting: 'Account Settings',
    earningsReport: 'TWR Statistics',
    clickToView: 'Click bar to view trading report',
    openAccountTime: 'Opening Time',
    currency: 'Deposit Currency',
    timeZone: 'Time Zone',
    cutOff: 'Data by',
    profitLoss: 'P/L',
    handCount: 'Lots',
    orderCount: 'Number of Trades',
    balanceOptions: [
      {
        value: 1,
        name: 'Original',
        content: 'Original balance/equity curve, but affected by deposits and withdrawals, there may be gaps. '
      },
      {
        value: 2,
        name: 'Revised',
        content:
          'The deposit and withdrawal data have been revised to make the balance/equity curve more continuous and smooth, so as to more truly understand the change of account balance/equity. This method produces no distortion.'
      }
    ],
    varietyDistribute: 'Financial Instruments',
    timesOptions: [
      {value: 1, name: 'Position Size'},
      {value: 2, name: 'Number of Trades'}
    ],
    profitDistribute: 'Profit & Loss',
    profitDirection: 'Trade Types',
    incomeOptions: [
      {value: 1, name: 'Type'},
      {value: 2, name: 'P&L'}
    ],
    positionTime: 'Holding Periods',
    holdOptions: [
      {value: 1, name: 'Position'},
      {value: 2, name: 'P/L'}
    ],
    totalAvg: 'Avg. period for all',
    profitAvg: 'Avg. period for profit trades',
    lossAvg: 'Avg. period for loss trades',
    loading: 'Loading',
    promptContent:
      '<p>Kind tips:</p>\n1. Pending orders and deposit/withdrawal data are excluded;<br/>\n2. All data is updated at 08:00 GMT+8 on a daily basis;<br/>\n3. P/L number is displayed with a $ currency symbol, which is an ; <br/>\n4. The max drawdown calculated in MT4 is imperfect, so Top Traders has improved it and make it more accurate, hence the difference between MT4 and FastBull;<br/>\n5. P/L and return-to-risk ratio will not exceed 100.00; TWR will not exceed 100.00w%.<br/>',
    totalOrder: '{x} trades in total, {y} loaded',
    longOrder: 'Long Trades',
    shortOrder: 'Short Trades',
    longShort: 'L/S',
    shippingSize: 'Position Size',
    profitOrder: 'Profit Trades',
    lossOrder: 'Loss Trades',
    orderPosition: 'Position Size',
    orderProfitLoss: 'P/L',
    profitLossTip: 'Swap fee and commission considered',
    handCountTip: 'Excluding pending orders',
    inventory: 'Swap Fee',
    procedure: 'Commission',
    notInclude: 'Excluding pending orders, deposits and withdrawals',
    filter: 'Filter',
    browseTotal: 'Visit Statistics',
    subscribeTotal: 'Follower Stats',
    subscribeList: [
      {value: 1, name: 'Followers'},
      {value: 2, name: 'Visits'}
    ],
    totalBrowse: 'Total Visits',
    totalSubscribe: 'Followers',
    tradingOrderCnt: 'Total Trades',
    winRate: 'Win Rate',
    tradingHand: 'Trading Lots',
    orderDistribute: 'Trades Distribution',
    profitLossDistribute: 'P/L Distribution',
    totalProfitExplain: 'Note: Swap and commission have been taken into consideration when calculating P/L',
    cutDown: 'Latest Updates',
    todayRise: 'Rising Today',
    today: 'Today',
    totalEarnings: 'Cumulative TWR',
    earningsTips:
      'Cumulative TWR: Balance return by the end of yesterday, calculated using the TWR method.\nAbsolute TWR: Total P/L by the end of yesterday divided by the total deposit amount (including credit limit) * 100%.',
    absoluteEarnings: 'Absolute TWR',
    noStrategy: 'No trading strategy for this account',
    accountName: 'Account Name',
    totalDeposit: 'Cumulative Deposits',
    accountNetValue: 'Equity',
    positionProfit: 'Floating P/L',
    closeProfit: 'Realized P/L',
    accountLever: 'Leverage',
    totalWithdrawal: 'Cumulative Withdrawals',
    accountBalance: 'Balance',
    credit: 'Credit Amount',
    dataOverviewExplain: [
      'The sum of profits and losses of all orders ',
      'Number of profitable trades/ number of total trades',
      'The average holding time of each trade. ',
      'The proportion of orders using EA. ',
      'The sum of all the lot sizes ',
      'Avg. profit of all profitable trades / avg. loss of all losing trades. ',
      ' Lots per trade',
      ' Number of trades with large position sizes (>15% of the funds) / number of all trades.',
      'Number of all trades',
      'Total swap fees',
      'Total profit / number of profitable trades',
      'Profit of the most profitable trade',
      'Avg. number of trades per day',
      'Total commission',
      'Total loss / the number of all losing trades',
      'Loss of the largest losing trade. '
    ],
    positionDuration: 'Avg. Holding Period',
    quantizedRatio: 'EA Trades',
    totalHand: 'Total Lots',
    avgTradingHand: 'Avg. Lots',
    heavyTradingRatio: 'Large Position Size',
    totalOrderCount: 'Total Trades',
    totalInterest: 'Total Swap Fee',
    avgProfit: 'Avg. Profit ',
    maxProfit: 'Max Profit per Trade',
    avgDayOrder: 'Daily Trades',
    totalProcedure: 'Total Commission',
    avgLoss: 'Avg. Loss ',
    maxLoss: 'Max Loss per Trade',
    variety: 'Instrument',
    type: 'Type',
    closeTimeRange: 'Closing Period',
    startTime: 'Start Time',
    endTime: 'End Time',
    typeList: [
      {value: -1, name: 'All'},
      {value: 1, name: 'Market Order'},
      {value: 2, name: 'Pending Order'}
    ],
    replenish: [
      {value: 4, name: 'Deposit and Withdrawal'},
      {value: 8, name: 'Credit'}
    ],
    period: 'Cycle',
    openTime: 'Opening Time',
    closeTime: 'Closing Time',
    openClosePrice: 'Open/Close Price',
    open: 'Open',
    close: 'Close',
    openPrice: 'Open Price',
    closePrice: 'Close Price',
    stopProfitLoss: 'SL/TP',
    direction: 'Trade Type',
    notice: 'Announcement',
    cannotConnect: 'Unable to connect to this account',
    connecting: 'Connecting ({x}s)',
    reconnectionNow: 'Reconnect',
    noBindOrPrivate: 'The trading account has been set as private or unlinked',
    accountInit: 'Account initializing. Please wait...',
    dataStatistics: 'Statistics',
    tradingOrder: 'Orders',
    subscriber: 'Followers {0}',
    tradingNotice: 'Announcements',
    comment: 'Comments {0}',
    tradingReport: 'Reporting {0}',
    connectFail: 'Failed to connect',
    connectSuccess: 'Connected',
    browseChange: 'The traffic chart reflects the popularity of the account.',
    subscribeChange: 'The chart is an indication of the popularity and trend of the signal account.',
    dataOverview: 'Data Overview',
    dataDeneral: 'Data General View',
    importantIndex: 'Key Indicators',
    plAnalysis: 'P&L Analysis',
    incomeStatistics: 'Return Stats',
    changeAccount: 'Switch Account',
    stopProfit: 'TP',
    stopLoss: 'SL',
    texes: 'Tax',
    helpYouUndestand: 'Improve your trading performance',
    addAccount: 'Add Account',
    selectTraderBrokers: 'Select a Server',
    inputAccountNum: 'Enter 4~16 digits',
    inputAccountPwd: 'Enter a 4~32 digit password',
    inputAccountExplain: 'Please briefly introduce your trading strategy, within 16~128 characters',
    accountExplain:
      'Allow or prohibit others from viewing the trading data of this account. When prohibited, this account will not be displayed publicly.',
    positionExplain:
      'Allow or prohibit public access to all open trades of this account, which are still viewable to all followers ',
    historyExplain:
      'Allow or prohibit public access to all historical trades of this account, which are still viewable to all followers ',
    commentExplain: 'Allow or prohibit others from commenting on this account.',
    weekReportExplain: 'Allow or prohibit sending me weekly trading reports for this account.',
    monthReportExplain: 'Allow or prohibit sending me monthly trading reports for this account.'
  },
  dataCenter: {
    market: 'Markets',
    report: 'Positions Report',
    technical: 'Price Patterns',
    profitAccount: 'Profit Accounts',
    fromYesterday: 'vs. YTD',
    actualCount: 'Total Live Accounts',
    yesterday: 'YTD',
    lossAccount: 'Loss Accounts',
    popularBroker: 'Popular Broker Ranking',
    popularExplain:
      'The ranking is based on the number of live accounts opened with each broker; The negative review rate is based on the comments on each broker posted at the Details section at the Trading Account Page.',
    userSelect: 'User Selection',
    negativeRate: 'Negative Review Rate',
    masterPosition: '{x} Expert Position',
    short: 'Sell',
    long: 'Buy',
    neutral: 'Neutral',
    blastingIntro: 'Live accounts that have liquidated',
    blastingAccount: 'Liquidated Accounts',
    unit: 'Unit:',
    accountDistribute: 'Account Distribution',
    accountChange: 'Account Changes',
    varietyDistribute: 'Instrument Distribution',
    winRateDistribute: 'Win Rate Distribution',
    cutOff: 'Deadline',
    profit: 'Profit',
    loss: 'Loss',
    blasting: 'Liquidation',
    orderForm: 'Order',
    shippingSpace: 'Position',
    accountRatio: 'Account Proportion',
    accountNumber: 'Number of Accounts ',
    profitLossRatio: 'Profit / Loss',
    dealStyle: 'Trading Style',
    lossRate: 'Loss Rate',
    dealStyleList: ['Short-term Trading', 'Long-term Trading', 'EA Trading', 'Gold & Crude Trading'],
    styleExplainList: [
      'Short position holding period, high trading win rate, considerable order volume, and deeply loved by traders. However, its P/L ratio is usually low, and it is a strategy of small profits and large losses. ',
      'The holding period that lasts for several weeks or even a month, with an extremely high P/L ratio, and extremely low trading frequency requires traders to have patience. ',
      'Summarize the manual trading experience as a logically rigorous mathematical model, and use EA plug-ins to automatically conduct trades according to established rules. ',
      'Two very popular commodity futures, with a wide audience, can be traded on many trading software, and there are many experts. '
    ],
    styleAccountRatio: [
      'Short-term Account Proportion',
      'Long-term Account Proportion',
      'EA Account Proportion',
      'Gold & Crude Account Proportion'
    ],
    speculate: 'Current Speculative Sentiment',
    updateFrequency: 'Updated every 15 minutes',
    tradeVariety: 'Instruments',
    accountCount: 'Accounts Long/Short',
    accountCountTips: 'The current net position is the number of long or short accounts.',
    shippingSpaceLabel: 'Position (lots) Long/Short',
    shippingSpaceTips:
      'The sum of the number of long lots and the number of short lots currently held, excluding pending orders.',
    marketEmotion: 'Sentiment (Long/Short)',
    dealStyleTip: [
      'The number of accounts containing {x} style divided by the total number of accounts in the community. ',
      'The number of accounts focusing on gold or crude oil trading is divided by the total number of accounts in the community. '
    ],
    lossRateTip: [
      'Among the accounts containing {x} style, {y} are in loss. ',
      'Among the accounts focusing on gold or crude oil trading, there are {y} losses. '
    ],
    accountExplain:
      'As of {0}({1}), there are {2} trading accounts trading {3}, of which {4} accounts are holding losses and {5} accounts are making profits.',
    orderList: 'Order Book',
    orderListTips:
      'Discover potential support/resistance positions in the market and understand the market’s price-intensive trading areas',
    positionChange: 'Position holders and changes in positions',
    longAccountNum: 'Number of long accounts',
    shortAccountNum: 'Number of short accounts',
    netPosition: 'Net position',
    rise: 'Bullish',
    fall: 'Bearish',
    putOrder: 'Pending order',
    position: 'Open order',
    marketChange: 'Market and position changes',
    longCash: 'Long position',
    shortCash: 'Short position',
    closePrice: 'Closing price',
    upsAndDowns: 'Intraday rise or fall',
    newestPrice: 'Latest price',
    marketEmotion1: 'Sentiments',
    currentPosition: '{x} open orders',
    longOrderCount: '{x} long orders',
    shortOrderCount: '{x} short orders',
    price: 'Price',
    subscribeCnt: 'Followers',
    windVane: 'Trends',
    allMaster: 'They are all {x} experts',
    longMaster: 'Long-term trading experts',
    shortMaster: 'Short-term trading experts',
    quantizationMaster: 'EA trading experts',
    form: 'Pattern',
    name: 'Name',
    variety: 'Instrument',
    period: 'Cycle',
    createTime: 'Generation time',
    trend: 'Trend',
    dataSupport: 'Powered by data from FastBull',
    chartTimeZone: 'Chart time zone',
    allForm: 'All patterns',
    allVariety: 'All instruments',
    allPeriod: 'All cycles',
    kingList: 'Top Ranked',
    formDesc1:
      'The hammer pattern is a bullish reversal pattern, especially when it occurs at the bottom of a downtrend. Its body is small, but its lower shadow is long (usually two times longer than the real body). It has little or no upper shadow. There must be a price decline (even a slight decline) for the pattern to be called the hammer. When a similarly shaped pattern occurs in an uptrend, we call it the hanging man pattern.',
    formDesc2:
      "The hanging man is a bearish reversal candlestick pattern that appears at the end of the uptrend. If the next candlestick after the hanging man is bearish and closes below the hanging man's, the pattern is considered valid and has a bearish significance. The greater the downward gap between the hanging man's real body and the next candlestick's open, the more likely the hanging man marks the market top.",
    formDesc3:
      'The shooting star is a bearish candlestick pattern with a long upper shadow, a small real body located at the lower end, and little or no lower shadow. It mainly appears at the end of an upward price swing, so it may signal the end of the upswing. This pattern forms when the bulls drive the price up in the early part of the trading session. But by the end of the trading session, bears have aggressively pushed the price down near the open (this pattern is also referred to as "meteor" because it lasts for a short time). When a similar pattern occurs at the end of a downward price swing, it is called an inverted hammer).\n',
    formDesc4:
      'The difference between the inverted hammer and the shooting star is that the inverted hammer occurs at the bottom of a downtrend and signals a potential bullish reversal. In terms of usage, the reversal strength of the inverted hammer and shooting star is not as great as the hanging man and hammer. Therefore, when using, it is best to combine it with the next candlestick and also use other methods to do further analysis.',
    formDesc5:
      'An engulfing pattern is a two-candlestick pattern that can be bearish or bullish. The bullish engulfing pattern is formed in a downswing, and it consists of one bearish candlestick followed by a bullish candlestick that engulfs it. The bearish engulfing is the opposite. Additionally, bull-engulfing-bull and bear-engulfing-bear are both common patterns you can see on the chart. Usually, the former indicates buying pressure, while the latter shows selling pressure. However, traders should not conduct rash tradings merely relying on a pattern but need to analyze with other technical methods.\n',
    formDesc6:
      'An engulfing pattern is a two-candlestick pattern that can be bearish or bullish. The bullish engulfing pattern is formed in a downswing, and it consists of one bearish candlestick followed by a bullish candlestick that engulfs it. The bearish engulfing is the opposite. Additionally, bull-engulfing-bull and bear-engulfing-bear are both common patterns you can see on the chart. Usually, the former indicates buying pressure, while the latter shows selling pressure. However, traders should not conduct rash tradings merely relying on a pattern but need to analyze with other technical methods.',
    formDesc7:
      '"Three Black Crows", also known as " Three Black Soldiers", refers to three consecutive downward candlesticks, usually as a precursor to the market collapse. It\'s a pattern that generally indicates a further decline in prices. While the " Three Red Soldiers " is the opposite. If the Three Red Soldiers occur in a downtrend, it is generally a strong market reversal signal; if the market price appears in the Three Red Soldiers pattern after a long period of sideways trading, and is accompanied by a gradual increase in volume, it is a prelude to the start of the market, which can cause close attention.\n',
    formDesc8:
      '"Three Black Crows", also known as " Three Black Soldiers", refers to three consecutive downward candlesticks, usually as a precursor to the market collapse. It\'s a pattern that generally indicates a further decline in prices. While the " Three Red Soldiers " is the opposite. If the Three Red Soldiers occur in a downtrend, it is generally a strong market reversal signal; if the market price appears in the Three Red Soldiers pattern after a long period of sideways trading, and is accompanied by a gradual increase in volume, it is a prelude to the start of the market, which can cause close attention.\n',
    formDesc9:
      'Morning Star is a K-line combination form composed of three K-lines. It is a form in which the market bottoms out and turns. If this form appears in a downward trend, you should pay attention, because at this time the trend has sent a relatively clear reversal signal, which is a very good buying opportunity.',
    formDesc10:
      'The evening star is the opposite of the morning star and signals a reversal in a stronger uptrend. If the K-line combination form of the Evening Star appears in an upward trend, we should pay attention to it, because at this time the trend has sent out a relatively clear reversal signal or a short- to medium-term callback signal, which may be a very good time for us to sell or The time to avoid short and medium term.',
    formDesc13:
      'Dark cloud cover, also known as dark cloud line, is one of the more common top reversal patterns on K-line charts. This form consists of two K lines, one yin and one yang. They generally appear after an upward trend. In some cases, they may also appear at the top of the horizontal adjustment range, which is a bearish signal.',
    formDesc14:
      "The first light consists of two longer candlesticks that move in completely opposite directions. The previous day was a Yin line and the next day was a Yang line. The next day the Yang line gapped downward and opened lower, and the opening price was much lower than the closing price of the previous day; but the closing price of the next day was higher than the closing price of the previous day, and the closing price of the Yang line went deep into the real body of the first Yin line In part, it reaches at least half of the previous day's negative line entity.",
    formDesc15:
      'Doji is a K-line with only upper and lower shadow lines and no column, that is, the opening price is equal to the closing price. Among them: the longer the upper shadow line, the stronger the selling force; the longer the lower shadow line, the stronger the buying force. If a more obvious cross appears at the high or low price, it means that the market is very likely. A reversal occurs.',
    formDesc16:
      'Doji is a K-line with only upper and lower shadow lines and no column, that is, the opening price is equal to the closing price. Among them: the longer the upper shadow line, the stronger the selling force; the longer the lower shadow line, the stronger the buying force. If a more obvious cross appears at the high or low price, it means that the market is very likely. A reversal occurs.',
    formDesc17:
      'Compared with the engulfing pattern, the order of the two K lines is exactly reversed in the harami pattern. In the engulfing pattern, there is a long real body behind it, covering the small real body in front of it; in the harami pattern, the latter K-line real body is smaller and is contained by the previous longer real body. The origin of the name of this form is also due to the meaning of "pregnancy". The long K line is the "mother" line, and the small K line is the "child" line, or "fetal" line, to show its inclusive meaning.',
    formDesc18:
      'Compared with the engulfing pattern, the order of the two K lines is exactly reversed in the harami pattern. In the engulfing pattern, there is a long real body behind it, covering the small real body in front of it; in the harami pattern, the latter K-line real body is smaller and is contained by the previous longer real body. The origin of the name of this form is also due to the meaning of "pregnancy". The long K line is the "mother" line, and the small K line is the "child" line, or "fetal" line, to show its inclusive meaning.',
    formDesc19:
      'Compared with the engulfing pattern, the order of the two K lines is exactly reversed in the harami pattern. In the engulfing pattern, there is a long real body behind it, covering the small real body in front of it; in the harami pattern, the latter K-line real body is smaller and is included by the previous longer real body (if the latter If a K line is a cross star, it is called a cross harami). The origin of the name of this form is also due to the meaning of "pregnancy". The long K line is the "mother" line, and the small K line is the "child" line, or "fetal" line, to show its inclusive meaning.',
    formDesc20:
      'Compared with the engulfing pattern, the order of the two K lines is exactly reversed in the harami pattern. In the engulfing pattern, there is a long real body behind it, covering the small real body in front of it; in the harami pattern, the latter K-line real body is smaller and is included by the previous longer real body (if the latter If a K line is a cross star, it is called a cross harami). The origin of the name of this form is also due to the meaning of "pregnancy". The long K line is the "mother" line, and the small K line is the "child" line, or "fetal" line, to show its inclusive meaning.',
    traderStyle: 'Style',
    winningAccounts: 'Accounts Winning',
    losingAccounts: 'Accounts Losing',
    dealLong: 'Buy',
    dealShort: 'Sell',
    sellingPrice: 'Ask Price',
    buyingPrice: 'Bid Price',
    hangingOrderData: 'Pending Order Data',
    positionOrderData: 'Open Order Data',
    periodicalNumber: 'Issue {x}',
    greatestRule: 'Ranking Rules',
    selectTraderStyle: 'Select Instrument'
  },
  user: {
    sendMsg: 'Send Message',
    userId: 'User ID',
    attention: 'Following',
    collect: 'Favorites',
    home: 'Home',
    contest: 'Contest',
    social: 'Chat',
    vip: 'Member',
    setting: 'Settings',
    about: 'About',
    accountListLen: 'You can link up to {x} trading accounts.',
    addAccount: 'Add Account',
    loginRegister: 'Sign Up/Log In',
    logoutSuccess: "You've been logged out",
    accountLis: 'Account List',
    totalAccount: '{x} accounts',
    noBindAccount: 'No trading account linked',
    unfoldAll: 'Expand All',
    foldAll: 'Collapse All',
    similarAccount: 'Similar Accounts',
    changeAccount: 'Change',
    signaturePlaceholder: 'No content available',
    loginViewOrder: 'Log in to view open orders',
    brokerGrade: "How's the reliability of the broker used by the account?",
    soldOut:
      "It is recommended that FastBull Top Traders remove this broker and no longer support this broker's account linking.",
    accountReport: 'Fraudulent Trading Reporting',
    suspects: 'Please advise any suspicious activity of the trading account.',
    reliable: 'Very Reliable',
    unreliable: 'Unreliable',
    suggestSoldOut: 'Recommend to Remove',
    reportSuccess: 'Reported!',
    emoji: 'Emojis',
    picture: 'Images',
    uploadFailed: 'Failed to upload',
    submitAfterUpload: 'Please upload image first',
    addPicture: 'Add Images',
    btnTextList: ['Comment', 'Reply', 'Confirm Reporting'],
    praise: 'Thumbs Up',
    reply: 'Reply',
    writeYourComment: 'Please enter your reply...',
    moreReply: 'More Replies',
    residueReplay: '{x} replies remaining',
    account: 'Account',
    grade: 'Rating',
    subscribe: 'Copy',
    accountPraise: 'Ratings',
    accountComment: 'Comments',
    allComment: 'All Comments',
    needComment: 'Enter your comment (comments cannot be modified or deleted. Please comment properly).',
    excellent: 'Good',
    ordinary: 'Average',
    noGood: 'Poor',
    commentSuccess: 'Commented!',
    replySuccess: 'Replied!',
    inputNotice: 'Please enter announcement content',
    allowNoticeCount: 'Up to {x} announcements allowed per day',
    totalCount: 'Total {x} announcements',
    publish: 'Publish',
    publishSuccess: 'Announcement published!',
    isDeleteNotice: 'Delete the announcement?',
    deleteNotice: 'Delete',
    closeComment: 'You are not allowed to post comment on this account',
    privateComment: 'This account is visible to the owner only. You are not allowed to post comment.',
    privateReport: 'This account is visible to the owner only. You are not allowed to report this account',
    length1: 'Please enter at least 1 character.',
    length512: 'You can only enter up to 512 characters',
    noAccount: 'No trading account yet',
    tradingPlatform: 'Trading Software',
    broker: 'Brokers',
    brokerServer: 'Server',
    dealAccountNum: 'Account',
    tradingPassword: 'Master Password',
    passwordExplain: "If you don't copy trades, you can enter the investor password.",
    inputPassword: 'Please enter master password',
    tradingStrategy: 'Trading Strategy',
    strategyExplain: 'Please introduce your trading strategy.',
    passwordLength: 'Master password requires 4-32 characters',
    strategyLength: 'At least 16 characters required',
    searchName: 'Search for broker or server name',
    record: 'Search History',
    hotSearch: 'Popular Searches',
    result: 'Search Results',
    inputAccount: 'Please enter account number',
    inVerification: 'Account verification in progress...',
    accountLength: 'The trading account number requires 4-16 digits',
    bindOvertime: 'Linking Account Timeout',
    addTradingAccount: 'Add Account',
    linkAccount: 'Link Account',
    accountSetting: 'Account Settings',
    otherBind: 'Account compromised.',
    howToFind: 'How to recover?',
    findAccount: 'Recover your account.',
    stepTitle: 'How to recover account:',
    findStep1: '1. Log in to MT4/MT5 using your master password.',
    findStep2: '2. Change the master or investor password.',
    findStep3: '3. Add your trading account again at Top Traders',
    addSuccess: 'Added successfully',
    initExplain: 'The account can be used after data initialization, which may take about 3 minutes.',
    bindNow: 'Link Now',
    brokerBan: 'The broker has been banned',
    accountRate: 'Good: Strong trading ability\nAverage: Average trading ability\nPoor: Weak trading ability',
    accountReportTips:
      '\nFastBull Top Traders will reach out to the broker used and verify the data if a trading account is repeatedly reported.',
    accountList: 'Account List',
    conversionRate: 'Conversion rate',
    nowDay: 'Today',
    lastSevenDay: 'Past 7D',
    yesterday: 'YTD',
    notice: 'Announcements',
    edit: 'Edit',
    totalYieldRate: 'Cumulative TWR',
    bindAccountTips: 'No trading account yet. Add now~',
    subscribeTips: 'Follow trading signals, invest with top traders',
    toSubscribe: 'Go to Copy',
    contesting: 'My Contesting Accounts',
    season: '{x} Season',
    rank: 'Ranking',
    chatroom: 'Chatrooms',
    friend: 'Friends',
    groupChat: 'Groups',
    topic: 'Topic',
    writer: 'Writers',
    news: 'News',
    video: 'Videos',
    pictureVideo: 'Images & Videos',
    file: 'Documents',
    audio: 'Voice',
    chatRecord: 'Chat History',
    followed: 'Following',
    fans: 'Fans',
    article: 'Articles',
    cancelCollect: 'Remove',
    simulationGroup: 'Demo Accounts',
    actualGroup: 'Live Accounts',
    contestData: 'Contest Data',
    awardsCount: 'Awards',
    totalAward: 'Award Amounts',
    topScore: 'Highest Score',
    megagameRecord: 'Contest Records',
    entryAccount: 'Accounts',
    score: 'Scores',
    ranking: 'Rankings',
    awards: 'Prizes',
    extraAward: 'Extra Bonuses',
    auditStatus: 'Status',
    status: ['Approved', 'Rejected', 'Reviewing'],
    noRecord: 'Record unavailable',
    socialGroup2: 'Groups I Manage ({x})',
    socialGroup3: 'Groups I Joined ({x})',
    comeFrom: 'From: {x}',
    socialGroup1: 'Groups I Created ({x})',
    nextStep: 'Next ',
    selectBrokers: 'Select Server',
    bindSuccess: 'Linked',
    goFollowOrder: 'Copy Now',
    accountDetail: 'Account Details',
    bindAgain: 'Try Again',
    traderAccount: 'Trading Account',
    traderLever: 'Leverage',
    subscribeNum: 'Followers {0}',
    depositCurrency: 'Deposit Currency',
    accountName: 'Account Name',
    withoutSignature: 'No trading motto set',
    fastbullVIP: 'FastBull Member',
    openVipForFree: 'Free Membership',
    logout: 'Log Out',
    shareFB: 'Share FastBull',
    copyLink: 'Copy Link',
    addFriend: 'Add Friend',
    addFriendVerify: 'Verification',
    waitVerify: 'Waiting for verification',
    added: 'Added',
    defaultVerify: 'I am {x}',
    inputVerifyInfo: 'Please enter verification info:',
    addSuccessTip: 'Your friend request has been sent, waiting for confirmation from the other party.',
    send: 'Send',
    sendApplySuccess: 'Application sent successfully',
    cancelAttentionConfirm: 'Are you sure you want to unfollow this user?',
    userCenter: 'Personal Center',
    openFBAPP: 'Open APP',
    supportNewsPrice: 'Provide faster and more comprehensive financial news and quotes',
    noCollect: 'No favorites added yet',
    accountPwd: 'Password',
    fxchat_niu_trading_select: 'Select',
    fxchat_niu_trading_select_first: 'Please select a broker first',
    fxchat_niu_trading_server_select: 'Select',
    fxchat_niu_account_input_hint: '4-16 digits',
    fxchat_niu_observe_account_input_hint: '4-32 characters',
    fxchat_niu_observe_password_tip: "\nPlease enter the investor password if you don't copy trades",
    fxchat_niu_trading_strategy_hint: 'Introduce your trading strategy in 16 ~128 characters.',
    fxchat_niu_account_bind: 'Account compromised,',
    commentAfterLogin: 'Please {x} first before posting a comment',
    noBodyAdd: 'Friend request failed. The user enabled No One can send him/her requests.'
  },
  grade: {
    synthesizeGrade: 'Overall rating',
    gradeTips:
      'The comprehensive rating is based on the transaction data of the past six months and is updated once a day.',
    tradeAbility: 'Trading ability',
    goodAtVariety: 'Focus on',
    riskLevel: 'Risk level',
    maxDrawdown: 'Max. Drawdown',
    viewGradeReport: 'View comprehensive rating report',
    rank: '{x} in overall ranking',
    score: 'Aggregate score {x} points',
    tradeAbilityList: ['Excellent', 'Very good', 'Good', 'Average', 'Poor', 'Bad'],
    riskLevelList: ['Low risk', 'Medium risk', 'High risk'],
    profitAndLoss: 'Account P/L',
    orderControl: 'Order control',
    varietyData: 'Instrument data',
    dealStyle: 'Trading style',
    dealPosition: 'Position data',
    gradeStr: ['Excellent', 'Good', 'Average', 'Poor'],
    gradeScore: 'Rating score',
    scoreTooltip:
      'A+ (above 90 points), excellent trading ability! <br/>A (85 points or above), very good trading ability! <br/> B+ (above 80 points), good trading ability! <br/> B (75 points or above), average trading ability! <br/> C+ (above 60 points), poor trading ability! <br/> C (less than 60 points), bad trading ability!',
    tradeGrade: 'Trading Rating',
    gradeExplain:
      'The comprehensive rating is based on the rating results of the past six months, and the rating info is updated once a day.',
    yieldRateTooltip: 'The return refers to the time weighted rate of return (TWR)',
    maxDrawdownTooltip:
      'The largest decline in net worth (if there is no net worth data, balance data will be used instead) within a specified period. Due to the impact of deposits and withdrawals, this value may exceed 100%.',
    yieldRiskRatioTooltip:
      'TWR/Max Drawdown. When the TWR is less than or equal to 0, the return-to-risk ratio is set to 0. When the max drawdown is 0, the return-to-risk ratio is set to 100.',
    yieldRiskRatio: 'Return-to-Risk Ratio',
    orderTotalTooltip: 'The number of orders within the specified period.',
    orderTotal: 'Total number of orders',
    dealFrequencyTooltip: 'The average number of orders traded per day during the specified period.',
    dealFrequency: 'Trading frequency',
    frequencyUnit: '{x} orders/day',
    stopProfitRateTooltip:
      'The proportion of orders with a take profit or stop loss among the orders within the specified period.',
    stopProfitRate: 'TP & SL rate',
    varietyFreight: 'Instruments & position',
    heavyRatioTooltip:
      'Among the orders within a specified period, the proportion of orders with heavy positions (orders occupying more than 15% of funds).',
    heavyRatio: 'Big position ratio',
    focusVarietyTooltip: 'The number of frequently traded financial instruments within a specified period.',
    focusVariety: 'Instruments',
    profitLossRatioTooltip:
      'The ratio of the average profit of profitable orders to the average loss of loss orders among orders within a specified period. When the average loss is 0, the P/L ratio is 100.',
    profitLossRatio: 'P/L ratio',
    dealStyleTooltip: 'Trading style within a specified time period.',
    profitPositionTooltip:
      'The average holding period of profitable orders among the orders within the specified period.',
    profitPosition: 'Average position of profitable orders',
    lossPositionTooltip: 'The average holding period of loss orders among orders within the specified period.',
    lossPosition: 'Average position of losing orders',
    gradeResult: 'Rating results are for reference only and do not constitute any investment advice.',
    general: 'Overall overview',
    evaluateList: [
      `The number of orders is too small to accurately rate`,
      `Cheer yourself up and sail against the current. If you don't advance, you will retreat`,
      `Professional abilities need to be improved`,
      `You can go further, don't be played for a sucker`,
      `Your performance is great, keep up the good work`,
      'You must be a top trader',
      'Marvelous trading'
    ],
    profitAbility: {
      worst: 'Profitability is extremely poor',
      veryBad: 'Profitability is very poor',
      bad: 'Profitability is poor',
      needToImprove: 'Profitability needs to be improved',
      common: 'Profitability is average',
      strong: 'Profitability is strong',
      stronger: 'Profitability is very strong',
      strongest: 'Profitability is extremely strong'
    },
    earnings: {
      veryInstability: 'Extremely Unstable Profitability. ',
      instability: 'Unstable Profitability. ',
      stabilize: 'Stable Profitability ',
      veryStabilize: 'fffffff. ',
      mostStabilize: 'The income is very stable. '
    },
    dealRisk: {
      lowest: 'The trading risk is very low',
      smaller: 'The trading risk is low',
      controlled: 'The trading risk is controllable',
      high: 'The trading risk is high',
      higher: 'The trading risk is very high',
      gigantic: 'The trading risk is huge'
    },
    earningsRiskRatio: {
      worst: 'The return-to-risk ratio is extremely low. ',
      veryBad: 'The return-to-risk ratio is very low. ',
      needToImprove: 'The return-to-risk ratio needs to be improved. ',
      rational: 'The return-to-risk ratio is reasonable. ',
      good: 'The return-to-risk ratio is high. ',
      veryGood: 'The return-to-risk ratio is very high. '
    },
    avgDailyYield: 'Account average daily change {x}',
    avgWeekYield: 'Account average weekly balance {x}',
    avgMonthYield: 'Average monthly balance of account {x}',
    dayProfit: 'The daily profit probability is {x}',
    monthProfit: 'The monthly profit probability is {x}',
    maxDrawdownIs: 'And the maximum drawdown is {x}',
    earningsRiskValue: 'The return-to-risk ratio is {x}',
    dealFrequencyExplain: [
      'The trading frequency is well controlled. Please continue to maintain it. After all, the more you do, the greater the chance of making mistakes. ',
      'The trading frequency is relatively high. Reducing the trading frequency appropriately will help to better control risks. '
    ],
    stopExplain: [
      'Due to the low take-profit or stop-loss setting rate, there may be certain trading risks. ',
      'The trading goal is not very clear. Making good use of stop-profit or stop-loss can reduce trading risks to a certain extent. ',
      'Trading objectives are usually relatively clear. You need to be cautious when entering and exiting the market, and do not fight uncertain battles. ',
      'Clear trading goals and good trading habits. '
    ],
    accumulativeDeal: 'Cumulative trading for {x} days',
    avgOrder: 'Average {x} orders per day',
    stopPercent: "Take-profit and stop-loss are set for {x}'s order",
    heavyExplain: [
      'Have good awareness of position risk control, and the overall position control is relatively reasonable. ',
      'Occasionally carry out heavy trading. ',
      'Be sure to do a good job in risk control when conducting heavy trades from time to time. ',
      'Trading with heavy positions too frequently may result in extremely high transaction risks. Please be cautious. '
    ],
    heavyPercent: 'Among {x} orders, big positions account for {y}',
    suggestion:
      'It is recommended to bring a stop profit and stop loss for all heavy warehouse orders, abandon the gambling mentality, and do a good job in risk control.',
    noFocus:
      'There are no special financial instruments that you are good at. It is recommended to focus on one or two instruments, which may better improve your trading ability.',
    focusVarietyAt: 'The focused instrument is {x},',
    focusCount: 'Focus on {x} {y} instruments,',
    profitLossStr:
      'The cumulative P/L on this instrument is {x}, and we still need to continue working hard to make it better.',
    profitLossTotal: 'The sum of their profits and losses is {x}, keep going.',
    goodAtStr: 'Best at {x}, its profit accounts for {y} of the total profit, keep working hard.',
    tradingStyle: ['Intraday trading', 'Short-term trading', 'Long-term trading', 'EA trading', 'No trading style'],
    tradingType: ['Intraday', 'Short-term', 'Long-term', 'EA'],
    winAndRatio: 'The win rate of {x} is around {y}, and the P/L ratio is around {z}.',
    beGoodAt: 'Good at {x}',
    noTradingStyle:
      'There is no clear trading style. The win rate of short-term orders is {x}, and the win rate of long-term orders is {y}.',
    avgPosition:
      'The total average position length is {x}, the average profit of profit orders is {y}, and the average loss of loss orders is {z}.',
    joinAndRate: 'Join the Top Traders\nto assess your trading ability',
    rated: '{x} trading accounts have been assessed, with an average score of {y}',
    rateNow: 'Assess now',
    isTheRating: 'AI Rating is rating you. Please wait...',
    scoreTips:
      'The comprehensive score also includes three additional points, which are used to measure the performance of the trading account in terms of user evaluation, counter-trend orders, and survival cycle. <br/>Extra points for word-of-mouth: {x} points<br/>Additional points for position: {y} points<br/>Additional points for period: {z} points',
    warmPrompt: 'Kind tips',
    traderForShort: 'Short-term trading',
    traderForLong: 'Long-term trading',
    traderForQuantification: 'EA trading',
    traderForGold: 'Gold & crude oil trading',
    traderForShortTip: 'Introduction to short-term trading',
    traderForLongTip: 'Introduction to long-term trading',
    traderForQuantificationTip: 'Introduction to EA trading',
    traderForGoldTip: 'Introduction to gold & crude oil trading',
    goldMaster: 'Gold & crude oil expert'
  },
  subscribe: {
    openSubscribe: 'Enable Signal Providing Permission',
    connectionNormal: 'Account in normal connection ',
    accountIsReal: 'It is a live account',
    notAbnormal: 'Not labled as abnormal',
    brokerCompliance: 'Trading with a regulated broker',
    equityMoreThan: 'Equity should be more than $1,000.00',
    openNow: 'Enable Now',
    openSuccess: 'Signal providing permission enabled',
    disqualification: 'This account is not eligible for providing signals',
    openCondition: 'A signal provider should meet the following requirements:',
    closeSubscribe: 'Disable signal providing permission',
    closeSubscribeConfirm: 'Are you sure you want to disable the signal providing permission?',
    closePunishmentExplain:
      'You have {x} followers under this account. You will be punished if the signal providing permission is disabled for the account: ',
    punishment: 'The trading account will be banned from providing signals for 90 days.',
    consider: 'Cancel',
    closeNow: 'Confirm',
    closeSuccess: 'Signal providing permission disabled',
    lengthen: 'Extend Subscription',
    follow: 'Copy',
    selectAccount: 'Select Account to Follow',
    alreadyFollow: 'Accounts Following',
    followDays: 'Copying for {x} days, due on {y}',
    notFollow: 'Accounts Not Following',
    accountIsDelete: 'The following account has been deleted.',
    accountDelete: 'The signal account has been deleted',
    subscribeForbid: 'This account has been blocked from providing signals',
    subscribeClose: 'This account has not enabled signal providing service',
    closeAfterExpire: 'This account does not allow traders to copy',
    followAccountOffline:
      'Your trading account <span>#{x}</span> has been disconnected and is temporarily unavailable. If the connection password of this account has been changed, please <a target="_blank" href="{y}"> go to the account settings </a> page to update the connection password.',
    brokerForbid:
      'Top Traders does not support {x}, and thus all trading accounts opened with it will not be allowed to copy trades.',
    fictitiousTradesTips: 'Due to potential trading data fabrication, this account is not allowed to provide signals',
    violateRuleTips:
      'You are not allowed to copy any trades at Top Traders due to violation against our community rules. Please contact customer service if you have any questions.',
    limitationUser: 'Restricted User',
    subscribeWarning: 'Warning',
    riskAccountTips: 'This account may involve greater risk of loss',
    userAbnormalTips: 'This account belongs to a user with abnormal status. Please copy trades with caution.',
    noCanFollow: 'There are currently no accounts to copy.',
    noAccount: "\nYou haven't linked your trading account yet,",
    accountOffline: 'This account has been disconnected  and is temporarily unavailable.',
    brokerLimit: 'Broker Restricted',
    accountFollowTips:
      "You can't copy trades as you are using investor password for your account <span>#{x}</span>. <br/>\nYou need to <a target='_blank' href='{y}'> go to the account settings </a> and update <span> the master password </span>.",
    dealLimit: 'Trading Restricted',
    forbidSubscribe: 'Subscription Not Allowed',
    followSuccess: 'Successfully Followed',
    followSetting: 'Set Parameters',
    subscriber: 'Followers',
    subscribeTypeList: [
      {value: 1, name: 'Copying Now'},
      {value: 2, name: 'History'}
    ],
    params: 'Parameters',
    subscribeTime: 'Start Time',
    subscribePeriod: 'Duration',
    subscribeEndTime: 'End Time',
    totalSubscribePeriod: 'Accumulated Time for Copying',
    otherUser: 'He is still copying trades',
    patternList: [
      {name: 'Fixed Lot Size', value: 1},
      {name: 'Fixed Copy Ratio', value: 2}
    ],
    directionList: [
      {name: 'Copy', value: 1},
      {name: 'Reverse', value: 2},
      {name: 'Copy Close Signals Only', value: 3}
    ],
    notice: 'Announcements',
    moreTradingNotice: 'To view more trading announcements,<br/>please go to the trading account details page',
    hot: 'Popular Signal Providers',
    count: 'Followers',
    allSource: 'All Sources',
    detail: 'Details',
    cancelTips: 'To stop copying, please go to the copy trade settings and turn off the feature.',
    cancel: 'Cancel Copy Trading',
    setting: 'Settings',
    detailStatusList: ['', 'Copying Now', 'Expired', 'Cancelled', 'Refunded', 'Unstarted'],
    orderId: 'Order ID',
    startTime: 'Start Time',
    endTime: 'End Time',
    cancelTime: 'Cancellation Time',
    cancelReason: 'Reason',
    notStartTips: '"Unstarted" orders will take effect after the "Copying Now" orders expire.',
    confirmTocancel: 'Are you sure you want to cancel copy trading?',
    subscribeStartTime: 'Copy Trading Start Time',
    followAccount: 'Following Account',
    followStatus: 'Status',
    followStateTips: 'You will still receive signals after you stop copying trades',
    baseSetting: 'Basic Settings',
    varietySetting: 'Instrument Settings',
    followNotice: 'Instructions',
    followPattern: 'Mode',
    followPatternTips:
      'Fixed Copy Ratio: Your lot size is calculated proportionally to your equity, which is recommended.\n\n<br/> Fixed Lot Size: Open and close a fixed lot size regardless of the lot size of the signal account.',
    maxHand: 'Max Lots',
    maxHandTips: 'Lots will not exceed this upper limit even if the signal account opens a larger lot size.\n',
    noLimit: 'No Limit',
    followDirection: 'Direction',
    followDirectionTips: 'Copy Close Signals Only: New positions will not be copied.',
    contractSize: 'Contract Size',
    contractSizeTips:
      'The contract size may vary from broker to broker, causing inconsistency in the lot size for you copying trades. \nYou can adjust contrace size only when you choose a Fixed Copy Ratio.',
    sizeList: [
      {name: 'Self-adaptive', value: 1},
      {name: 'Ignore', value: 2}
    ],
    signalAccount: 'Signal Account',
    followLimit: 'Restrictions',
    followLimitTips:
      'When activated, the following account will be restricted in copy trading <br/> For instance, you set your copy mode to "Reverse" and only allow short orders on EURUSD, then: <br/> If the signal account opens a long position on EURUSE, the following account will place a short trade; <br/> Nevertheless, if the signal account places a short trade on EURUSD, the following account will not open a long position even it\'s set to copy the reverse trade because you\'ve set the restrictions. <br/>',
    setManually: 'Unrecognized. Please set it manually',
    limitList: [
      {name: 'No Limit', value: 0},
      {name: 'Short Only', value: 1},
      {name: 'Long Only', value: 2},
      {name: "Don't Open Position", value: 3}
    ],
    followRuleContent:
      'Rules:<br/>\n\n1. Pending orders will not be copied until they are executed at a fixed price; <br/>\n2. SL/TP will not be followed as exit points may vary from broker to broker (which may have different quotes and spreads...);<br/>\n3. Self-adaption does not apply to some assets, such as indices, futures, stocks;  <br/>\n4. In copy trading, the lot size of an open position is subject to the max/min lot size required by the broker; <br/>\n5. You may experience delays when copying trades. An open signal will be ignored automatically if delayed for 180s and longer, and a close signal 30 min.',
    notMatchTips:
      '{x} instruments in your following account does not match those in the signal account and cannot be followed. Please check in the "Instrument Settings".',
    maxLotsMoreThan: 'Max. lot size should be larger than the fixed lot size.',
    allMatchTips:
      'Please ensure the instruments in your following account match those in the signal account, or abnormality may occur.',
    hasConfirm: "I've confirmed",
    gotoCheck: 'Go to Verify',
    settingSuccess: 'Set Successfully',
    mySubscribe: 'My Copy Trades',
    account: 'Signal Account',
    currPosition: 'Current Positions',
    yesterdayEarnings: "YTD's TWR",
    monthEarnings: 'TWR in Past 1M',
    status: 'Copy Trading Status',
    statusList: ['Copying Now', 'To Expire in {x} Days', 'Expiring Soon'],
    totalTime: 'Total Copy Trading Duration',
    operation: 'Action',
    viewToAccount: 'You can view your followers at <a target="_blank" href="{x}"> trading account details </a> page',
    times: 'Times',
    connectionAnomaly:
      'Your trading account #{x} has been offline and is temporarily unavailable. <br/>If the connection password of this account has been changed, please update it at Profile-Trading Account-Account Settings.',
    passwordTypeTips:
      'You are not allowed to copy trades as you are using an investor password for your trading account #{x}. <br/> Please change it to master password at Profile-Trading Account-Account Settings before copying trades.',
    goNow: 'Go Now',
    warmPrompt: 'Reminder:<br/> 1. You can change your copy trade settings at "Profile" -> "Copy Trading". <br/>',
    fixedHands: 'Fixed Lot Size',
    fixedRatio: 'Fixed Copy Ratio',
    fixedRatioTips:
      'Lot size for your following account is calculated proportionally to your equity, which is recommended.',
    fixedHandsTips: 'Lot size for your following account is fixed regardless of the lot size of the signal account.',
    ratio: '{x} times',
    signalVariety: 'Instrument (Signal Account)',
    followVariety: 'Instrument (Following Account)',
    selectVariety: 'Select Instrument',
    searchVariety: 'Search Instrument',
    hasQuestion: 'Any questions? Please contact <span>customer service</span>',
    subscribeInfo: 'Copy Trading Info',
    followAgain: 'Copy Again',
    residueLong:
      'You can follow this account for the remaining {0} months. Renewal is not allowed.\n<br/>Please note you can follow this account for {1} months at most. Please renew your subscription when the remaining time is shorter than {2} months.',
    subscribeExpire: 'Expired',
    closeTips:
      'If you want to only receive signals  without copying trades, you can modify the subscription settings. ',
    shareGetFollow: '"Share to get free signals" is unavailable now. Please open membership before copying trades.',
    signalNotFollow: "The signal account doesn't allow copy trading",
    initNotFollow: 'Initializing. Please try again later'
  },
  header: {
    searchLabel: 'Search',
    product: 'Products',
    market: 'Markets',
    information: 'News',
    signal: 'Signal',
    match: 'Contests',
    activity: 'Event',
    broker: 'Brokers',
    more: 'More',
    chart: 'Charts',
    stockFilter: 'Screeners',
    financialCalendar: 'Economic Calendar',
    toolKit: 'Tools',
    cost: 'Pricing',
    feature: 'Features',
    dataMarket: 'Market Data',
    overview: 'Overview',
    myOptional: 'Watchlist',
    news: 'News',
    transactionAnalysis: 'Analysis',
    quickInformation: '24/7',
    column: 'Columns',
    answer: 'Q&A with Experts',
    data: 'Data',
    video: 'Videos',
    institutionalViewPoint: 'Views from Institutions',
    analystViewPoint: 'Views from Analysts ',
    columnTopic: 'Topics',
    columnist: 'Columnists',
    dataCenter: 'Data Warehouse',
    marketTrend: 'Market Trend',
    institutionalData: 'Institutional Data',
    centralBankInterestRate: 'Policy Rates',
    macroEconomy: 'Macroeconomics',
    niuList: 'Top Traders',
    bestNiuer: 'Weekly Rankings',
    AISignal: 'AI Signals',
    fansActivity: 'Fans Party',
    web_ib_seminar: 'IB Seminar',
    voteActivity: 'Awards',
    web_fans_hongkong: 'Hongkong, China',
    web_fans_hochiminh: 'Ho Chi Minh City, Vietnam',
    web_fans_dubai: 'Dubai, UAE',
    web_fans_cairo: 'Cairo, Egypt',
    web_fans_nigeria: 'Lagos, Nigeria',
    business: 'Business',
    recruit: 'Hiring',
    aboutUs: 'About Us',
    whiteLabel: 'White Label',
    dataAPI: 'Data API',
    webPlugins: 'Web Plug-ins',
    feedback: 'Feedback',
    helpCenter: 'Help Center',
    agreement: 'User Agreement',
    policy: 'Privacy Policy',
    comingSoon: 'Coming Soon',
    marketPrice: 'Quotes',
    calendar: 'Calendar',
    quotation: 'Quotes',
    PRO: 'Pro',
    AIRating: 'AI Rating',
    latestViewPoints: 'Latest Views',
    calendarWallpaper: 'Calendar Wallpaper',
    speculativeMood: 'Sentiment',
    hangingOrderPosition: 'Orders',
    varietyCorrelation: 'Correlation',
    popularIndex: 'Top Indicators',
    hotTopic: 'Trending Topics',
    recentUpdate: 'Latest Updates',
    language: 'Language',
    popularSearch: 'Top Searches',
    historySearch: 'Recent Searches',
    myCollection: 'My Favorites',
    myConcern: 'My Following',
    mySubscription: 'My Copied Trades',
    personalInformation: 'Personal Info',
    memberCenter: 'Member Center',
    accountSetting: 'Account Settings',
    logOut: 'Log Out',
    scanDownload: 'Scan to Download',
    moreInformation: 'Faster financial news and quotes',
    downloadApp: 'Download APP',
    addFBToDesk: 'Add FastBull to Desktop',
    loadFromDesk: 'Next time you can access FastBull directly from your computer desktop',
    addToDesk: 'Add to Desktop',
    recommendSelfSelection: 'Recommended',
    waitingForDeal: 'Pending',
    inTransaction: 'Trading',
    overDeal: 'Closed',
    overdue: 'Expired',
    profitMaking: 'Profit',
    lossMaking: 'Loss',
    profitLoss: 'P&L',
    financialTools: 'Financial Tools',
    homePage: 'Home',
    clickLogin: 'Log In',
    AppDescription: 'Faster and more comprehensive financial news and quotes',
    supportResistance: 'Support & Resistance',
    copyright: 'Copyright © {x} FastBull Ltd',
    risk: 'Risk Disclosure',
    riskText1:
      'The risk of loss in trading financial instruments such as stocks, FX, commodities, futures, bonds, ETFs and crypto can be substantial. You may sustain a total loss of the funds that you deposit with your broker. Therefore, you should carefully consider whether such trading is suitable for you in light of your circumstances and financial resources.',
    riskText2:
      "No decision to invest should be made without thoroughly conducting due diligence by yourself or consulting with your financial advisors. Our web content might not suit you since we don't know your financial conditions and investment needs. Our financial information might have latency or contain inaccuracy, so you should be fully responsible for any of your trading and investment decisions. The company will not be responsible for your capital loss.",
    riskText3:
      "Without getting permission from the website, you are not allowed to copy the website's graphics, texts, or trademarks. Intellectual property rights in the content or data incorporated into this website belong to its providers and exchange merchants.",
    cookieTips:
      'We use cookies to understand how you use our website and improve your experience, including personalized content. If you continue to use our website, it means that you accept our use of cookies. Please click here if you want to know more.',
    viewDetail: 'View Details',
    authorization: 'Agree',
    function: 'Function',
    company: 'Company',
    user: 'User',
    theLatestValue: 'Latest Value',
    allSearchResult: 'View All Search Results',
    loginBtn: 'Log In',
    signUPBtn: 'Sign Up',
    freeToOpenVIP: 'Upgrade to Pro for Free',
    web_opinion_hot_author: 'Top Columnists',
    market_finance_coverview: 'Overview',
    freeForevet: '',
    moduleDark: '',
    loginForMoreFunc: '',
    noLogin: ''
  },
  sideLayout: {
    news_calendar_filter_only_import: 'Top News Only',
    news_snowfall: 'Related Links',
    news_unscramble: 'Analysis & Opinion',
    news_unscramble_long: 'LT',
    news_unscramble_short: 'ST',
    news_unscramble_bearish: 'Bearish',
    news_unscramble_bullish: 'Bullish',
    calendar_time_up: 'TIME',
    calendar_prev_up: 'PREV',
    calendar_est_up: 'FCST',
    calendar_act_up: 'ACT',
    calendar_unrelease: 'Unpublished',
    calendar_revised: 'Prior to revised',
    calendar_act: 'Act',
    calendar_est: 'Fcst',
    calendar_prev: 'Prev',
    new_share: 'Share',
    vip_invite_friends_immediately: 'Refer and earn free upgrade',
    vip_invite_friends_title: 'Share',
    qa_header_title: 'Q&A with Experts',
    qa_header_online: 'Online Q&A',
    qa_ask_question: 'I have a question...',
    qa_post_first_question: 'Post your first question',
    qa_expert: 'Expert',
    qa_view_translation: 'View translation',
    qa_view_original: 'View source text ',
    qa_answer: 'Answer',
    qa_cancel_answer: 'Cancel the answer',
    qa_answer_placeholder: 'Answer {0}',
    qa_confirm_delete_question: 'Are you sure you want to delete the question?',
    qa_confirm_delete_answer: 'Are you sure you want to delete the answer?',
    qa_select_pic_format: 'Please choose png, jpg, jpeg, gif, bmp, and webp formats',
    qa_common_bottom: 'No more content',
    qa_remind_max_char: 'Enter a maximum of {0} characters',
    qa_cancel_reply: 'Cancel the reply',
    qa_reply_someone: 'Reply {0}',
    quote_nav_more: 'More',
    quote_link_more: 'More',
    quote_table_asset: 'SYMBOL',
    quote_table_last: 'LAST',
    quote_table_netchg: 'NET CHG.',
    quote_table_chg: '%CHG.',
    quote_table_update: 'UPDATE',
    news_news_trending: 'Trending',
    quote_table_high: 'HIGH',
    quote_table_low: 'LOW',
    quote_watchlist: 'Watchlist',
    quote_my_watchlist: 'My Watchlist',
    reminderg: 'Reminder Settings',
    maincontainer_market: 'Quotes',
    news_flash: '24/7',
    news_calendar: 'Calendar',
    q_a: 'Answer',
    home_tab_chat: 'Chat',
    common_side_layout: 'Layout',
    common_layout_single: 'One-column',
    common_layout_vertical: 'Two-row',
    common_layout_tile: 'Two-column',
    cale_unpublish_time: 'Announced in {0}',
    cale_unpublish_time_h: '{0} h',
    cale_unpublish_time_min: '{0} min',
    add_asset_name: 'Add Symbol or Code',
    add_to_favorites: 'Add to Favorites',
    recentlyViewed: 'History',
    common_market_closed: 'Closed',
    chart_indicator: 'Indicators',
    chart_strategy: 'Strategy',
    chart_edit: 'Editor',
    chart_backtest: 'Backtest',
    chart_order: 'New Order',
    chart_template: 'Templates',
    chart_sync: 'Sync',
    chart_history: 'History',
    chart_remind: 'Alert',
    chart_log: 'Log',
    chart_connect: 'Connecting to server, please wait...',
    searchStocksTips: 'Press any key from A to Z or from 0 to 9 in the main window to search symbols'
  },
  dataCollect: {
    fxchat_login_edit_user_info_title: 'Add Personal Info (1/3)',
    fxchat_login_complete_material_title: 'Complete Your Profile (2/3)',
    fxchat_login_recommendation_title: 'Customize Your Content（3/3）',
    fxchat_information_nick_name: 'Alias',
    fxchat_login_field_title: 'Enter Your Alias',
    fxchat_information_sex: 'Gender',
    fxchat_information_sex_man: 'Male',
    fxchat_information_sex_women: 'Female',
    fxchat_information_sex_other: 'Others',
    fxchat_information_sex_secret: 'Prefer not to say',
    fxchat_material_morning: 'Good morning! {0}. Welcome to FastBull.',
    fxchat_material_noon: 'Good afternoon! {0}. Welcome to FastBull.',
    fxchat_material_afternoon: 'Good afternoon! {0}. Welcome to FastBull. ',
    fxchat_material_night: 'Good evening! {0}. Welcome to FastBull. ',
    fxchat_material_introduction: 'Tell us a little bit about yourself to help us better pick content for you.',
    fxchat_recommendation_subtitle: "We'll pick personalized content for you based on your preferences.",
    fxchat_material_summarize:
      "Great! We'll tailor the content for you according to your preference.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ",
    fxchat_material_assistant_name: 'AI Chatbot',
    fxchat_material_look: 'View Now',
    fxchat_material_reselect: 'Reselect',
    fxchat_recommendation_see_more: 'More',
    fxchat_recommendation_open_fxchat: 'Open FastBull',
    fxchat_recommendation_open_group: 'Group Chat',
    fxchat_recommendation_open_niu: 'Trending',
    fxchat_not_group_introduction: 'No description yet',
    fxchat_recommendation_join: 'Join',
    fxchat_recommendation_has_join: 'Joined',
    fxchat_login_skip: 'Skip',
    fxchat_recommendation_follow: 'Follow',
    fxchat_recommendation_has_follow: 'Following',
    fxchat_login_trading_type: 'Which trading markets interest you? (Select one or more)'
  },
  setting: {
    personalData: 'Personal Info',
    accountSafety: 'Account Security',
    informSetting: 'Notification Settings',
    privacy: 'Privacy',
    blacklist: 'Blacklist',
    remove: 'Remove',
    removeSuccess: 'Removed successfully',
    shieldingTime: 'Blocked: {x}',
    addStyle: 'Methods for Friending Me',
    allowAll: 'Allow anyone to friend me',
    needVerify: 'Require verification',
    notAllowAny: 'No one is allowed to friend me',
    findByPhone: 'Find me via phone number',
    findByPhoneTips: "Other users can't find you through the above info if you turn it off.",
    follow: 'Copy Trading',
    followTips: 'Your copy trading details will be displayed publicly after turning it on.',
    contest: 'Contests',
    contestTips: 'Your contest details will be displayed publicly after turning it on.',
    emailNotice: 'Email Notification Preferences',
    weeklySelection: "FastBull Weekly Editor's Selection",
    willPushNews: 'We will deliver major financial news and breaking events to you',
    sendWeek: 'Weekly Updates',
    dailyHighlights: 'FastBull major market news for today',
    sendDay: 'News will be sent on business days',
    baseInfo: 'Basic Info',
    nickname: 'Alias',
    joinStyle: 'How to Join the Group',
    aphorism: 'Trading Motto',
    editInfo: 'Edit Personal Info',
    interestInfo: 'Trading Preferences',
    noAddInterest: 'No content yet~',
    dealPlatform: 'Brokers',
    dealMarket: 'Markets',
    dealVariety: 'Instruments',
    dealStyle: 'Styles',
    avatar: 'Avatar',
    modifyAvatar: 'Edit Avatar',
    username: 'Username',
    sex: 'Gender',
    dealAge: 'Trading Years',
    address: 'Location',
    industry: 'Your Professions',
    modify: 'Edit',
    addIndustry: 'Add Professions',
    userIntro: 'Profile',
    interestDealInfo: 'Your Preference',
    add: 'Add',
    sexList: [
      {value: 0, name: 'Male'},
      {value: 1, name: 'Female'},
      {value: 2, name: 'Secret'}
    ],
    industryType: 'Profession Type',
    inIndustry: 'Related Professions',
    outIndustry: 'Other Professions',
    interestPlayform: 'Select Brokers',
    interestMarket: 'Select Markets',
    interestStyle: 'Select Styles',
    interestVariety: 'Select Instruments',
    maxOption: 'You can select up to {x} items',
    blackTypeList: [
      {value: 1, name: 'Contacts'},
      {value: 2, name: 'Group Chats'}
    ],
    accountInfo: 'Account Info',
    userPassword: 'User Password',
    haveSet: 'Already Set',
    isNotSet: 'Not Set',
    phoneNumber: 'Phone Number',
    notBind: 'Not Linked',
    bind: 'Link',
    email: 'Email Address',
    bindThird: 'Link to a Third Party',
    unBind: 'Unlink',
    bindPhone: 'Link Phone Number',
    changePhone: 'Change Phone Number',
    inputPhone: 'Enter Phone Number',
    and: 'and',
    inputPhoneTips: 'Enter a valid phone number',
    inputVerifyCode: 'Enter the 4-digit verification code',
    oldPhoneNumber: 'Original Phone Number',
    newPhoneNumber: 'New Phone Number',
    bindEmailOpen: 'Please link your email address to enable account login ',
    bindEmail: 'Link Email Address',
    setPassword: 'Set Password',
    password: 'Password',
    inputPwd: 'Please enter password',
    pwdRules:
      'The password requires 6-20 characters, including at least 2 kinds from numbers, letters, and special characters.',
    updatePwd: 'Change Password',
    currentPwd: 'Current Password',
    forgetPwd: 'Forget Password?',
    newPwd: 'New Password',
    pwdNotSame: 'Password Inconsistency',
    emailResetPwd: "Enter your email address and we'll send you a reset link",
    sendResetLink: 'Send Reset Link',
    inputEmail: 'Please enter your email address',
    inputRightEmail: 'Please enter a valid email address',
    alreadSendLink: "We've sent you a password reset link",
    alreadSendTo: 'We have sent an email to',
    noGetFindHelp: "If you don't receive an email within 5 minutes, please check Spam or ask for help",
    findHelp: 'Ask for Help',
    getVerifyCode: 'Get Verification Code',
    notGet: "Still haven't received it?",
    resend: 'Resend an Email',
    inputCode: 'Enter verification code',
    beGetting: 'Retrieving...',
    resendAfter: 'Can be resent in {x} s',
    selectAvatar: 'Select Avatar',
    customAvatar: 'Add Avatar',
    reUpload: 'Re-upload',
    defaultAvatar: 'Default Avatars',
    imgType: 'Only {x} files allowed!',
    inputNickname: 'Please enter your alias',
    inputUsername: 'Please enter your username',
    usernameTips:
      'Usernames can only contain lowercase letters, numbers, underscores, and periods. The link to your profile will change if you change your username.'
  },
  vip: {
    equities: 'Rights and Interests',
    detail: 'Details',
    hasCode: 'I have a redeem code',
    inputCode: 'Enter the redeem code',
    conversion: 'Redeem',
    shareGet: 'Share to Get Pro for Free',
    shareGetYear: 'Share to get 1-year Pro for free',
    inviteUser:
      'Invite new users to click on your sharing link. After they signed up and logged in, you can get one-year membership.',
    scanQRCode: 'Scan QR code with mobile phone',
    shareLink: 'Share link to get membership',
    recharge: 'Upgrade to FastBull Pro',
    agree: 'I have read and agree to the terms in the',
    agreement: 'Pro Policy',
    privilege: 'Membership Privileges',
    time: 'Time',
    duration: 'Get Membership',
    getMode: 'Ways to Get',
    status: 'Status',
    redeemRules:
      'Rules for using redeem codes:\n1. The activated redeem code cannot be used again\n2. The redeem code becomes invalid if it has expired',
    privilegeList: [
      {id: 1, title: 'Quick access to 24/7', desc: 'Quick access to more editor-selected real-time news'},
      {
        id: 2,
        title: 'Follow more assets',
        desc: 'You can add more assets to your watchlist to follow more real-time quotes. '
      },
      {
        id: 3,
        title: 'More comprehensive macro data and economic indicators ',
        desc: 'More comprehensive historical data on indicators to help analyze macro markets'
      }
    ],
    shareTitle: "I've bought you a FastBull membership, worth 1648 yuan. Please come and get it!"
  },
  promotion: {
    volumnMuteDefault: 'On mute by default',
    enableVolumn: 'Unmute',
    kolInterview: 'KOL Interview',
    userComment: 'User Reviews',
    moreFunction: 'Explore More',
    moreFunctionTxt: 'Get whatever you need for trading at FastBull'
  },
  tdk: {
    title: 'FastBull - Faster Financial News and Quotes',
    homeTitle: 'FastBull Top Traders: Track the Most Profitable Traders',
    homeDesc:
      'FastBull Top Traders ranks traders based on a variety of factors, including profitability, stability, and risk. Track the most profitable traders and learn from their strategies.',
    greatestTitle: 'FastBull Weekly Rankings',
    greatestDesc: 'FastBull ranks investors and accounts weekly based on P/L, EA, followers, trades, and win rate.\n',
    helpTitle: 'Help Center - FastBull',
    helpDesc: 'Get answers to common questions and find helpful resources in our Help Center.',
    userTitle: '【{x}】- Profile',
    userDesc: 'This profile is a window into the world of 【{x}】. From insightful thoughts to engaging connections.'
  },
  about: {
    downloadApp: 'Download APP',
    aboutFb: 'About FastBull',
    fbExplain:
      'FastBull is a technology innovator for the Internet of Finance. We have established editorial and translation teams in many regions and will continue to work on content localization in various countries. We also have great R&D and product teams. Our team members are equipped with excellent technical skills and will keep delivering top-notch software experiences for our customers in the future.',
    service: 'Our Services',
    product: 'Products',
    productExplain:
      'We have launched the economic calendar and tools features, with more great features coming soon, such as Supercharts, Stock Screeners, Market Data, etc.',
    signal: 'Signals',
    signalExplain:
      'News, Top Traders, Weekly Rankings, Latest Signals, and Contests. Real-time trading signals from top traders are available for you to copy, making trading easier.',
    message: 'News',
    messageExplain:
      'News, 24/7, Analysis, Columns, Data, and Videos, covering global breaking news, and trading views from analysts and institutions. At the same time, popular events and economic data are updated 24/7.',
    market: 'Markets',
    marketExplain:
      'We provide forex, commodities, indices, U.S. stocks, crypto, CME and other markets. In the future, we will continue to offer markets of global stocks, ETFs, bonds, etc.',
    business: 'Business',
    businessExplain:
      'We offer some free or paid third-party services like White Label, Data API, and Web Plug-ins that provide data source and technical support.',
    course: 'Development',
    contact: 'Contact Us',
    partner: 'Partnership',
    email: 'Email Address',
    feedback: 'Feedback',
    scan: 'Scan QR Code',
    android: 'Android',
    ios: 'iOS',
    downloadTips: 'Discuss and share your trading ideas and views with global investors in real-time',
    chat: 'Instant Chat',
    chatExplain: 'Chat with global top traders about trading!',
    chart: 'Social Charts',
    chartExplain: 'Analyze markets, discuss trading, subscribe to signals',
    realTimeSignal: 'Real-time Signals',
    realTimeSignalExplain: 'Free Trading Signals to Copy',
    contest: 'Trading Contests',
    contestExplain: 'The best platform to show your trading ability',
    answer: 'Q&A with Experts',
    answerExplain: 'Get free professional advice from experts',
    analyse: 'Trading Analysis',
    analyseExplain: 'Learn the trading logic of investment experts',
    calendar: 'Economic Calendar',
    calendarExplain: 'A professional analysis tool providing in-depth interpretation of economic data',
    news: 'Featured News',
    newsExplain: 'Covering in-depth insights from global economic experts',
    tools: 'Poster Maker',
    toolsExplain: 'Support customization of various financial posters',
    more: 'More',
    moreExplain: 'Download FastBull to experience more exciting features',
    downloadFrom: 'Download from'
  },
  chat: {
    headTabs: ['All', 'Chatrooms', 'Groups', 'Friends'],
    placeInput: 'Type here...',
    connecting: 'Connecting'
  }
}
