export default {
  common: {
    confirm: 'Tentu',
    affirm: 'Konfirmasi',
    remove: 'Hapus',
    cancel: 'Batal',
    tips: 'Tips',
    finish: 'Selesai',
    know: 'Baik',
    time: 'waktu',
    count: '{x} item',
    hand: '{x} lot',
    order: '{x} pesanan',
    score: '{x} poin',
    person: '{x} orang',
    times: '{x} kali',
    second: '{x} detik',
    minutes: '{x} menit',
    hour: '{x} jam',
    day: '{x} hari',
    month: '{x} bulan',
    year: '{x} tahun',
    shortsecond: '{x} detik',
    shortminutes: '{x} menit',
    shorthour: '{x} jam',
    shortday: '{x} hari',
    justNow: 'Baru ini',
    minuteAgo: '{x} menit yang lalu',
    hourAgo: '{x} jam yang lalu',
    yesterday: 'Kemarin{x}',
    beforeYesterday: 'Sehari sebelum kemarin {x}',
    yearUnit: 'tahun',
    monthUnit: 'bulan',
    dayUnit: 'hari',
    hourUnit: 'jam',
    minutesUnit: 'menit',
    secondUnit: 'detik ',
    hundredMillion: '',
    trillion: '',
    loading: 'Sedang Diunduh',
    noMore: 'Tidak ada data lagi',
    all: 'semua',
    reset: 'Atur Ulang',
    unfoldAll: 'Besarkan Semua',
    packUp: 'Tutup ',
    unfold: 'Besarkan',
    back: 'kembali',
    warning: 'Peringatan',
    noData: 'Tidak ada data',
    imageFormat: 'Hanya format gambar JPG, JPEG, atau PNG yang didukung!',
    imageSize: 'Ukuran gambar tidak boleh melebihi {x} MB',
    shareFb: 'Bagikan FastBull dan dapatkan satu bulan hak  copy trading',
    noNetLaterTry: 'jaringan bermasalah, silakan coba lagi nanti...',
    copy: 'Salin',
    copySuccess: 'Disalin',
    appDownload: 'Unduh app-FastBull',
    fbDownload: 'Unduh APP FastBull',
    getSuccess: 'Dapat hak copy trade 1 bulan ',
    reLogin: 'Status login exp, silakan login kembali.',
    notFound: 'Maaf, alamat halaman yang Anda kunjungi salah atau halaman tersebut tidak ada',
    returnToLast: 'kembali ',
    returnToHome: 'Kembali ke beranda',
    forbidden: 'Akses Ditolak',
    noAccess: 'Anda tidak punya izin lihat direktori atau halaman ini pakai kredensial Anda.',
    serverError: 'Error',
    tryRefresh: 'Refresh dan coba lagi ',
    operationConfirm: 'Konfirmasi',
    select: 'Pilih',
    download: 'unduh',
    close: 'Tutup ',
    isDelete: 'Dihapus',
    noResult: 'Maaf, tidak ditemukan hasil relevan',
    tryAgain: 'Coba ubah kata kunci dan cari lagi',
    loginInOther: 'Akun Anda aktif di browser lain. Jika bukan anda, password mungkin bocor, segera ganti.',
    chartLoading: 'Memuat...',
    custom_service: 'Layanan Pelanggan',
    common_look: 'Lihat'
  },
  message: {
    messageCenter: 'Pusat Pesan',
    system: 'Pemberitahuan Komunitas',
    trading: 'sinyal trading',
    comment: 'Balas ',
    account: 'Pemberitahuan Akun',
    answer: 'Tanya Jawab Pakar\r',
    noMoreData: 'Tidak ada data lagi',
    viewAll: 'Lihat semua',
    noNewMsg: 'Belum ada berita baru',
    noMessage: 'Tidak ada pesan',
    systemMsgTypeList: [
      {type: 0, label: 'Semua Konten'},
      {type: 1, label: 'Notifikasi Komunitas'},
      {type: 3, label: 'Follow'},
      {type: 4, label: 'Follow saya'}
    ],
    commentMsgTypeList: [
      {type: 0, label: 'Komentar akun'},
      {type: 1, label: 'komentar berita'},
      {type: 2, label: 'Ulasan video'}
    ],
    accountMsgTypeList: [
      {type: 0, label: 'Semua Konten'},
      {type: 1, label: 'Perubahan Akun'},
      {type: 2, label: 'Pembaruan Peringkat'},
      {type: 4, label: 'Laporan Trading'}
    ],
    open: 'Buka posisi',
    openTime: 'Waktu buka',
    close: 'Tutup posisi',
    closeTime: 'Waktu tutup',
    riskWarning: 'Peringatan risiko',
    subscribeNotice: 'Notifikasi Copy Trading',
    clickView: 'Klik untuk melihat',
    allSource: 'Semua sumber',
    replyYou: 'Balas',
    answerYou: 'Jawab pertanyaan Anda\n',
    commentAccount: 'mengomentari akun trading Anda',
    commentYou: 'Komentar',
    viewDetail: 'periksa detail',
    commentTypeList: ['Komentar akun', 'Balasan pesan'],
    reportAccount: 'Laporkan akun trading Anda',
    waitFollow: 'Menunggu',
    followSuccess: 'Disalin',
    followFailed: 'Gagal Disalin',
    ignore: 'Abaikan',
    tryFollow: 'Salin sinyal ini, harap tunggu...',
    followOrder: 'Menyalin',
    followStatus: 'Status',
    unit: 'satuan',
    noSignal: 'Belum ada sinyal trading',
    orderId: 'Ikuti ID ini ',
    statusList: ['Menunggu', 'Disalin', 'Gagal Ikuti', 'Abaikan'],
    statusTitle: ['Alasan', 'Salin ID ini', 'Alasan Gagal', 'Abaikan alasan'],
    goSetting: 'ke pengaturan',
    viewOrder: 'periksa pesanan',
    stopProfit: 'Take Profit',
    stopLoss: 'Stop Loss',
    openPrice: 'harga buka',
    closePrice: 'Harga tutup',
    delist: 'Konten saat ini telah dihapus',
    remove: 'Konten saat ini telah dihapus'
  },
  home: {
    actualIntro: 'Total Akun Riil',
    actual: 'total akun riil',
    profitIntro: 'Akun yang untung ',
    profitAccount: 'profit',
    lossIntro: 'akun riil yang rugi ',
    lossAccount: 'Kerugian',
    blastingIntro: 'akun riil dilikuidasi',
    blastingAccount: 'rekening dilikuidasi',
    allMen: 'Semua Top Traders',
    openAccountToDate: 'Pembukaan akun sampai saat ini',
    lastJune: 'enam bulan akhir ',
    already: 'Pengikut ',
    yieldValueChart: 'Grafik Pengembalian (TWR).',
    favor: 'Mungkin suka ',
    refresh: 'Ubah ',
    unlimited: 'Semua',
    rank: 'Peringkat keseluruhan',
    earnings: 'Pengembalian',
    riskLevel: 'tingkat risiko',
    broker: 'Broker',
    goodAt: 'Asset Unggulan',
    moreOptions: 'Lebih ',
    dealWinRate: 'Tingkat Menang',
    ratio: 'rasio untung-rugi',
    openTime: 'Waktu buka akun',
    capital: 'Setor',
    accountType: 'Jenis akun',
    platform: 'platform trading',
    clear: 'Hapus',
    noContent: 'Tidak ditemukan konten relevan',
    noBroker: 'Tidak ditemukan broker terkait',
    accountRatingRangeList: [
      {value: 1, label: 'Tingkat A'},
      {value: 2, label: 'Tingkat B'},
      {value: 3, label: 'Tingkat C'}
    ],
    twrRangeList: [
      {value: '', label: 'Tidak ada batas'},
      {value: 2, label: '0%~30%'},
      {value: 3, label: '30%~60%'},
      {value: 4, label: '60%~100%'},
      {value: 5, label: '100%~200%'},
      {value: 6, label: 'Lebih dari 200%'}
    ],
    riskLevelList: [
      {value: 1, label: 'rendah'},
      {value: 2, label: 'sedang'},
      {value: 3, label: 'tinggi'}
    ],
    winRateRangeList: [
      {value: 0, label: 'Tanpa batas'},
      {value: 2, label: 'lebih dari 50%'},
      {value: 3, label: 'lebih dari 60%'},
      {value: 4, label: ' 70% atau lebih'},
      {value: 5, label: '80% atau lebih'},
      {value: 6, label: '90% atau lebih'}
    ],
    profitLossRatioRangeList: [
      {value: 0, label: 'Tanpa batas'},
      {value: 2, label: '0,5 ke atas'},
      {value: 3, label: '1.0 ke atas'},
      {value: 4, label: ' 1,5 ke atas'},
      {value: 5, label: '2.0 atau lebih tinggi'},
      {value: 6, label: '2.5 atau lebih tinggi'},
      {value: 7, label: '3.0 atau lebih tinggi'}
    ],
    openingTimeRangeList: [
      {value: 0, label: 'Tanpa batas'},
      {value: 1, label: '≤1 bulan'},
      {value: 2, label: '> 1 bulan'},
      {value: 3, label: '> 3 bulan'},
      {value: 4, label: '> 6 bulan'},
      {value: 5, label: '> 12 bulan'}
    ],
    amountOfFundsRangeList: [
      {value: 0, label: 'Tanpa batas'},
      {value: 1, label: 'di bawah 100'},
      {value: 2, label: '100 hingga 1000'},
      {value: 3, label: '1000 hingga 3000'},
      {value: 4, label: '3000 hingga 10.000'},
      {value: 5, label: '10.000 hingga 100.000'},
      {value: 6, label: '100.000 hingga 300.000'},
      {value: 7, label: 'lebih dari 300.000'}
    ],
    accountTypeList: [
      {value: 1, label: 'Live'},
      {value: 2, label: 'Demo'}
    ],
    orderList: [
      {value: 2, name: 'Tingkat pengembalian'},
      {value: 3, name: 'Drawdown maks'},
      {value: 4, name: 'Tingkat menang'},
      {value: 5, name: 'Rasio untung rugi'},
      {value: 6, name: 'Jumlah copy trade'}
    ],
    niuTopTypeList: ['Profit tertinggi', 'Kuantitatif terbaik', 'Pesanan tertinggi', 'Tingkat Menang tertinggi'],
    threeMonthData: 'Data 3 bln terakhir ',
    dataFieldList: ['Avg. Profit harian ', 'Rasio kuantitatif', 'Pesanan', 'Tingkat Menang'],
    threeMonthEarnings: 'Profit 3 bln akhir',
    positionDuration: 'Waktu Avg. ',
    lastThreeMonth: 'tiga bulan akhir',
    detail: 'Detail',
    appraise: 'Ranking mingguan',
    nextUpdate: 'Update berikutnya',
    currentStage: 'Ranking saat ini',
    stage: 'Edisi {x}',
    nobodyOnTheList: 'Tidak ada ranking dalam edisi ini',
    ruleContent:
      'Top Trader dipilih dari empat aspek: pendapatan, kuantifikasi, jumlah pesanan, dan tingkat kemenangan (berdasarkan data tiga bulan terakhir). Hanya mereka yang unggul dalam satu indikator dan kinerja profit baik yang dapat diikutsertakan dalam ranking mingguan.',
    udpateTime: 'Diupdate setiap hari Sabtu {x}',
    weeklySelection: 'Pilihan Mingguan',
    totalAccountNum: 'akun umum',
    echartMeaning: 'Arti Grafik',
    transactionSoftwareList: [
      {value: 2, label: 'MT4'},
      {value: 1, label: 'MT5', disabled: true}
    ],
    infiniteTxt: 'tak terbatas',
    selectBrokerNum: '{x} broker dipilih',
    moreSelect: 'Pilihan ganda',
    indexSubTabItem1: 'Untung 60%~100%',
    indexSubTabItem2: 'Resiko rendah',
    indexSubTabItem3: '> 12 bulan ',
    indexSubTabItem4: 'Jumlah pendanaan: 10.000 hingga 10 dolar AS',
    indexSubTabItem5: 'Tingkat kemenangan di atas 90%',
    indexSubTabItem6: 'Rasio untung-rugi > 3 kali lipat',
    filterNiuTitle: 'Seleksi Top Trader',
    selectBrokerTitle: 'Pilih broker',
    allTimePeriod: 'Semua ',
    searchBroker: 'Cari broker ',
    KOLInterview: 'Interview KOL ',
    userEvaluation: 'Komentar Pengguna',
    interestBroker: 'Broker Tertarik'
  },
  aiRating: {
    gradeTimes: 'Bilangan penilaian AI',
    dataCutOff: 'Data oleh {x}',
    gradeModel: 'Penilaian berdasarkan berbilang metrik',
    modelIntro:
      'Sistem penarafan AI menjalankan semakan komprehensif akaun dagangan daripada lima dimensi: P/L, pesanan, kedudukan, instrumen kewangan dan gaya, serta menilai prestasi akaun dengan tepat dari segi keuntungan, kestabilan dan risiko.',
    sample: 'Rekod Jejak Terbukti',
    sampleIntro:
      'Beribu-ribu akaun dagangan dan berpuluh-puluh juta pesanan trading, dengan keputusan penghakiman objektif & tidak berat sebelah, adalah sokongan terbaik bagi Sistem Penarafan AI.',
    highAccount: 'Akaun Elit',
    highIntro: 'Prestasi hebat dalam keuntungan, turun naik dan tahap risiko.',
    profitAccount: 'Akaun Untung',
    middleAccount: 'Akaun Standard',
    middleIntro: 'Keuntungan yang baik tetapi turun naik purata dan tahap risiko.',
    lowAccount: 'Akaun Asas',
    lowIntro: 'Keuntungan rendah dengan risiko tahap tinggi.',
    moreClient: 'Rating lebih tinggi, lebih ramai pelanggan',
    moreIntro:
      'Lebih tinggi rating, lebih kukuh akaun dan lebih besar kemungkinan untuk disalin dan diikuti oleh pelanggan. Antara dagangan yang disalin pada Pedagang Teratas, lebih daripada {x} akaun yang disalin adalah peringkat A atau lebih tinggi.',
    allUse: 'mereka semua sdg digunakan',
    yourScore:
      'Sistem penarafan AI memberi anda skor paling realistik untuk kertas peperiksaan dagangan anda. Datang dan lihat markah anda~',
    profitLoss: 'P/L',
    orderForm: 'Pesanan',
    position: 'posisi',
    variety: 'Instrumen',
    style: 'gaya'
  },
  account: {
    settingOptions: [
      {value: 1, name: 'Pengaturan profil'},
      {value: 2, name: 'Pengaturan izin'}
    ],
    deleteAccount: 'Hapus akun',
    sureToDelete: 'Apakah Anda yakin hapus akun ini?',
    deleteMatters: 'Catatan: Akun yang dihapus tidak dapat diikat lagi dalam waktu tujuh hari.',
    confirmDelete: 'Konfirmasi',
    cancelSubscribeBeforeDel:
      'Akun ini sedang mengikuti akun sinyal {x}. Jika ingin hapus akun ini, harap batalkan copy trade terlebih dahulu.',
    deleteSuccess: '{x} telah dihapus',
    deleteFailed: '{x} gagal dihapus',
    settingSaved: 'Pengaturan disimpan',
    accountPermission: 'Izin akun',
    subscribePermission: 'Hak Copy Trade',
    accountPrivate:
      'Hak akun saat ini ditutup, orang lain tidak dapat mengikuti dan copy sinyal trading akun ini.\nUntuk menjual sinyal trading, atur izin akun Anda ke "Publik" dan aktifkan hak copy trade.',
    commentPermission: 'Izin berkomentar',
    accountcommentForbid:
      'Izin komentar akun ini dinonaktifkan oleh sistem. Jika memiliki pertanyaan, silahkan hubungi layanan pelanggan.',
    positionOrder: 'pesanan berlangsung ',
    historyOrder: 'riwayat pesanan',
    weeklyReport: 'Kirimi saya laporan transaksi mingguan untuk akun ini.',
    monthlyReport: 'Kirimi saya laporan transaksi akun ini setiap bulan.',
    tradingDayReport: 'Laporan Harian',
    tradingWeekReport: 'laporan mingguan',
    tradingMonthReport: 'Laporan bulanan',
    linkAbnormal: 'Koneksi Terputus ',
    linkAbnormalExplain: 'Koneksi akun terputus, mohon jangan copy trade.',
    riskAccount: 'akun beresiko',
    riskAccountExplain: 'Akun ini punya resiko rugi yang besar, mohon salin/copy trade dengan hati-hati.',
    abnormalAccount: 'Akun tidak normal',
    abnormalAccountExplain: 'Keaslian akun trading ini dipertanyakan, harap salin/copy trade dengan hati-hati.',
    sixMonthEarnings: 'Profit 6 bln akhir',
    actualAccount: 'Akun Live',
    virtualAccount: 'Akun Demo',
    balance: 'Saldo',
    netValue: 'Nilai Bersih ',
    maxDrawdown: 'Retracement Lalu',
    drawdownTips:
      'Sejak rekening dibuka, kerugian (persentase) asset terbesar yang pernah terjadi.\nUntuk akun trading yang baru terikat, riwayat penarikan maks sebelum pengikatan akan dihitung menggunakan data saldo.\nPerhatikan bahwa algoritma retracement maks MT4 memiliki kekurangan tertentu, dan Peringkat Top Trader telah mengoreksi algoritma ini agar hasil lebih akurat, sehingga hasil retracement maks keduanya mungkin tidak konsisten.',
    deposit: 'Deposit',
    withdrawal: 'Tarik',
    fetch: 'Tarik',
    save: 'Setor',
    creditFetch: 'Batas Kredit Penarikan ',
    creditSave: 'Batas Kredit Setoran ',
    dealAccount: 'akun trading',
    dataSynchronizationErr: 'Sinkronisasi data gagal, periksa akun atau kata sandi Anda!',
    notOpen: 'Belum tersedia, harap pantau terus',
    signalProvider: 'Menjadi penyedia sinyal',
    tradingAccountSetting: 'Pengaturan akun',
    profitLossRatio: 'rasio untung-rugi',
    dateOptions: [
      {value: 0, name: 'Semua periode waktu'},
      {value: 1, name: '1 Bulan lalu'},
      {value: 2, name: '3 bulan lalu'},
      {value: 3, name: '6 bulan lalu'},
      {value: 4, name: '12 bulan lalu'}
    ],
    yieldRate: 'tingkat profit ',
    totalProfitLoss: 'untung rugi',
    synthesizeRank: 'peringkat keseluruhan',
    rankTips:
      'Peringkat komprehensif didasarkan pada skor peringkat komprehensif, dan hanya akun live yang dapat berpartisipasi.',
    synthesizeScore: 'peringkat keseluruhan',
    scoreTips:
      'Menilai dan rating akun dari berbagai dimensi seperti untung dan rugi, pesanan, posisi, variasi, dan gaya.',
    periodList: [
      {value: 1, name: 'hari'},
      {value: 2, name: 'minggu'},
      {value: 4, name: 'bulan'}
    ],
    profitLossTitle: ['Laba rugi harian', 'Laba rugi mingguan', 'Laba rugi bulanan'],
    forbidBroker:
      'Akun Trader {x} didiskualifikasi menyediakan sinyal kepada Top Trader dan tidak diijinkan menjadi Top Trader lagi. ',
    accountSetting: 'pengaturan akun',
    earningsReport: 'Statistik Pendapatan',
    clickToView: 'Klik pada bar untuk melihat laporan trading',
    openAccountTime: 'Waktu buka akun',
    currency: 'Mata uang deposit',
    timeZone: 'Zona Waktu ',
    cutOff: 'Statistik oleh',
    profitLoss: 'Laba rugi',
    handCount: 'Lot',
    orderCount: 'Pesanan',
    balanceOptions: [
      {
        value: 1,
        name: 'asli',
        conten:
          'Grafik kurva saldo/asset asli, namun karena pengaruh penyetoran penarikan, mungkin terdapat kesenjangan.'
      },
      {
        value: 2,
        name: 'Koreksi',
        conten:
          'Data setor dan tarik diubah agar kurva saldo/ekuitas lebih berkesinambungan dan lancar, sehingga memiliki pemahaman yang lebih realistis tentang tren perubahan saldo/ekuitas akun. Cara ini mencegah distorsi.'
      }
    ],
    varietyDistribute: 'Asset Trading',
    timesOptions: [
      {value: 1, name: 'posisi'},
      {value: 2, name: 'Trade'}
    ],
    profitDistribute: 'P&L',
    profitDirection: 'Arah Trading',
    incomeOptions: [
      {value: 1, name: 'arah'},
      {value: 2, name: 'Laba rugi'}
    ],
    positionTime: 'Waktu posisi',
    holdOptions: [
      {value: 1, name: 'posisi'},
      {value: 2, name: 'Laba rugi'}
    ],
    totalAvg: 'Posisi rata-rata',
    profitAvg: 'Posisi rata-rata pesanan untung',
    lossAvg: 'Rata-rata posisi pesanan rugi',
    loading: 'memuat',
    promptContent:
      '<p>Tip yang baik:</p>\n1. Saat menghitung berbagai data statistik, pending order serta data deposit dan penarikan telah dikecualikan;<br/>\n2. Peringkat komprehensif dan berbagai data statistik diperbarui pada pukul 08:00 waktu Beijing setiap hari;<br/>\n3. Simbol $ untuk menunjukkan bahwa data tersebut adalah data untung dan rugi. Mata uang deposit ditunjukkan di tempat lain;<br/>\n4. Drawdown max MT4 tidak sempura,jadi Top Trader harus mengoptimasikannya agar hasilnya lebih akurat, demikian menghasilkan perbedaan MT4 dan platform kami;<br/>\n5. Nilai maks rasio untung-rugi dan resiko-pengembalian adalah 100,00, dan tingkat profit dibatasi maks 100,00w%.<br/>',
    totalOrder: 'Total {x} pesanan, {y} dimuat',
    longOrder: 'Pesanan panjang',
    shortOrder: 'pesanan pendek',
    longShort: 'Panjang/Pendek',
    shippingSize: 'Ukuran posisi',
    profitOrder: 'Pesanan Profit',
    lossOrder: 'Pesanan Rugi',
    orderPosition: 'Posisi pesanan',
    orderProfitLoss: 'Untung Rugi Pesanan',
    profitLossTip: 'Termasuk biaya inventaris dan penanganan',
    handCountTip: 'Tidak termasuk pesanan tertunda',
    inventory: 'Biaya inventaris',
    procedure: 'Biaya penanganan',
    notInclude: 'Tidak termasuk pending order serta setor tarik dana',
    filter: 'Saring',
    browseTotal: 'Statistik Kunjungan',
    subscribeTotal: 'Statistik Vol. Copy Trade ',
    subscribeList: [
      {value: 1, name: 'Jumlah Copy Trade'},
      {value: 2, name: 'Jumlah Kunjungan'}
    ],
    totalBrowse: 'jumlah kunjungan',
    totalSubscribe: 'Jumlah Copy Trade',
    tradingOrderCnt: 'Volume transaksi',
    winRate: 'Tingkat Menang',
    tradingHand: 'Lot Trading',
    orderDistribute: 'Distribusi Pesanan',
    profitLossDistribute: 'Distribusi Untung Rugi ',
    totalProfitExplain: 'Catatan: Total data untung rugi termasuk biaya inventaris dan penanganan',
    cutDown: 'Update terkini',
    todayRise: 'Kenaikan hari ini',
    today: 'Hari ini',
    totalEarnings: 'Profit kumulatif',
    earningsTips:
      'Profit kumulatif: Profit pada saldo akhir kemarin, dihitung menggunakan algoritma TWR.\nKeuntungan absolut: total untung rugi akhir kemarin dibagi dengan total deposit/setor dana (termasuk limit kredit) * 100%.',
    absoluteEarnings: 'pengembalian absolut',
    noStrategy: 'TA belum isi strategi trading akun ini',
    accountName: 'nama akun',
    totalDeposit: 'Setoran kumulatif',
    accountNetValue: 'Nilai Bersih',
    positionProfit: 'untung rugi floating',
    closeProfit: 'untung rugi terealisasi',
    accountLever: 'Leverage ',
    totalWithdrawal: 'Penarikan kumulatif',
    accountBalance: 'Saldo',
    credit: 'jumlah kredit',
    dataOverviewExplain: [
      'Jumlah untung rugi semua pesanan. ',
      'Jumlah pesanan untung sebagai persentase dari total pesanan. ',
      ' Rata-rata waktu tahan setiap pesanan. ',
      'Proporsi pesanan pakai EA. ',
      'Jumlah ukuran lot semua pesanan ',
      'Rasio rata-rata keuntungan dari pesanan untung/Rasio rata-rata kerugian dari pesanan rugi. ',
      'lot trading per pesanan. ',
      'Proporsi order dengan posisi jumlah besar (order menempati lebih dari 15% dana). ',
      'Jumlah pesanan dalam periode yang ditentukan. ',
      'Jumlah biaya swap. ',
      'Jumlah keuntungan/pesanan untung. ',
      'Untung dari pesanan paling menguntungkan. ',
      'Rata-rata pesanan per hari. ',
      'Jumlah biaya servis. ',
      'Total rugi/nilai pesanan rugi ',
      'Kerugian dari pesanan paling rugi. '
    ],
    positionDuration: 'waktu tahan posisi',
    quantizedRatio: 'Pesanan EA',
    totalHand: 'Lot Total',
    avgTradingHand: 'Rata-rata lot ',
    heavyTradingRatio: 'Proporsi transaksi posisi jumlah besar',
    totalOrderCount: 'Total pesanan',
    totalInterest: 'bunga total',
    avgProfit: 'Untung rata-rata',
    maxProfit: 'Untung maks per pesanan',
    avgDayOrder: 'Pesanan harian',
    totalProcedure: 'Biaya penanganan',
    avgLoss: 'rugi rata-rata',
    maxLoss: 'rugi maks per pesanan',
    variety: 'Asset',
    type: 'jenis',
    closeTimeRange: 'Periode tutup ',
    startTime: 'waktu mulai',
    endTime: 'waktu akhir ',
    typeList: [
      {value: -1, name: 'semua'},
      {value: 1, name: 'pesanan harga pasar'},
      {value: 2, name: 'pesanan tertunda'}
    ],
    replenish: [
      {value: 4, name: 'Setor Tarik'},
      {value: 8, name: 'jumlah kredit'}
    ],
    period: 'siklus',
    openTime: 'Waktu Buka ',
    closeTime: 'Waktu tutup',
    openClosePrice: 'Harga buka/tutup  ',
    open: 'Buka',
    close: 'Tutup ',
    openPrice: 'Harga buka',
    closePrice: 'Harga tutup ',
    stopProfitLoss: 'SL/TP',
    direction: 'Arah Trade',
    notice: 'pengumuman',
    cannotConnect: 'Tidak dapat terhubung ke akun ini',
    connecting: 'Menghubungkan ({x}s)',
    reconnectionNow: 'Sambung Lagi ',
    noBindOrPrivate: 'Akun trading telah ditetapkan sebagai privat atau tidak terikat',
    accountInit: 'Inisialisasi akun, harap tunggu...',
    dataStatistics: 'Statistik',
    tradingOrder: 'Pesanan',
    subscriber: 'Pengikut  {0}',
    tradingNotice: 'Pengumuman',
    comment: 'Komentar {0}',
    tradingReport: 'Laporan {0}',
    connectFail: 'Koneksi gagal',
    connectSuccess: 'koneksi berhasil',
    browseChange: 'Kurva perubahan lalu lintas akun dapat mencerminkan popularitas akun saat ini.',
    subscribeChange: 'Kurva perubahan jumlah copy trade akun ini dapat mencerminkan popularitas dan tren akun.',
    dataOverview: 'Ringkasan Data',
    dataDeneral: 'Intisari Data',
    importantIndex: 'Indikator Utama',
    plAnalysis: 'Analisis Untung Rugi',
    incomeStatistics: 'Statistik Profit ',
    changeAccount: 'Ganti Akun',
    stopProfit: 'Take Profit',
    stopLoss: 'Stop Loss',
    texes: 'Pajak ',
    helpYouUndestand: 'Tingkatkan performa trading Anda',
    addAccount: 'Tambah akun',
    selectTraderBrokers: 'Pilih server',
    inputAccountNum: 'Masukkan 4~16 digit',
    inputAccountPwd: 'Masukkan kata sandi 4~32 digit',
    inputAccountExplain: 'Harap perkenalkan secara singkat strategi trading Anda, 16~128 karakter',
    accountExplain:
      'Izinkan atau larang orang lain melihat data trading akun ini. Jika dilarang, akun ini tidak ditampilkan secara publik.',
    positionExplain:
      'Izinkan atau larang orang lain melihat pesanan trading berjalan pada akun ini, namun penyalin akun ini selalu dapat melihatnya.',
    historyExplain:
      'Izinkan atau larang orang lain melihat riwayat pesanan akun ini, namun penyalin akun ini selalu dapat melihatnya.',
    commentExplain: 'Izinkan atau larang orang lain mengomentari akun ini.',
    weekReportExplain: 'Izinkan atau larang mengirimkan saya laporan trading mingguan akun ini.',
    monthReportExplain: 'Izinkan atau larang mengirimkan saya laporan trading bulanan untuk akun ini.'
  },
  dataCenter: {
    market: 'Pasar Trading ',
    report: 'Laporan posisi',
    technical: 'Pola teknikal',
    profitAccount: 'Akun Untung ',
    fromYesterday: 'vs kemarin',
    actualCount: 'Total akun Live',
    yesterday: 'Kemarin',
    lossAccount: 'Akun Rugi ',
    popularBroker: 'Peringkat Top Trader',
    popularExplain:
      'Peringkat didasarkan pada jumlah akun live pengguna broker di komunitas, dan tingkat ulasan negatif dihitung berdasarkan hasil evaluasi pengguna terhadap broker di halaman detail akun trading.',
    userSelect: 'Pilihan pengguna',
    negativeRate: 'Tingkat ulasan negatif',
    masterPosition: '{x} Posisi ahli',
    short: 'Pendek ',
    long: 'Panjang ',
    neutral: 'netral',
    blastingIntro: 'Jumlah akun live dilikuidasi',
    blastingAccount: 'rekening dilikuidasi',
    unit: 'satuan:',
    accountDistribute: 'Distribusi akun',
    accountChange: 'Perubahan jumlah akun',
    varietyDistribute: 'Distribusi Aset Trading ',
    winRateDistribute: 'Distribusi tingkat menang',
    cutOff: 'Tenggat waktu',
    profit: 'laba',
    loss: 'Rugi',
    blasting: 'Likuidasi',
    orderForm: 'Pesanan',
    shippingSpace: 'posisi',
    accountRatio: 'Proporsi akun',
    accountNumber: 'Jumlah akun (nomor)',
    profitLossRatio: 'Rugi/laba',
    dealStyle: 'gaya trading ',
    lossRate: 'Tingkat rugi',
    dealStyleList: [
      'Trading jangka pendek',
      'Trading jangka panjang',
      'EA kuantitatif',
      'Trading Emas dan minyak mentah'
    ],
    styleExplainList: [
      'Waktu penahanan posisi yang singkat, tingkat kemenangan transaksi yang tinggi, volume pesanan yang besar, dan sangat disukai oleh para pedagang. Namun, rasio untung-ruginya biasanya rendah, dan ini merupakan strategi untung kecil dan kerugian besar. ',
      'Holding period yang berlangsung selama beberapa minggu atau bahkan sebulan terakhir, rasio untung-rugi yang sangat tinggi, dan frekuensi trading yang sangat rendah mengharuskan para pedagang untuk memiliki kesabaran penuh. ',
      'Gabungkan ringkasan pengalaman trading manual ke dalam model matematika yang ketat secara logis, dan gunakan plug-in EA untuk melakukan transaksi secara otomatis sesuai dengan aturan yang ditetapkan. ',
      'Dua komoditas berjangka yang sangat populer, dengan khalayak luas, dapat dioperasikan pada banyak perangkat lunak trading, dan terdapat banyak ahli. '
    ],
    styleAccountRatio: [
      'Proporsi akun jangka pendek',
      'Proporsi akun jangka panjang',
      'Proporsi akun EA Kuantitatif',
      'Proporsi akun minyak mentah emas'
    ],
    speculate: 'sentimen spekulatif saat ini',
    updateFrequency: 'Diperbarui 15 menit sekali',
    tradeVariety: 'Asset ',
    accountCount: 'Akun panjang/pendek',
    accountCountTips: 'Posisi bersih saat ini adalah jumlah akun panjang atau pendek.',
    shippingSpaceLabel: 'Posisi (lot) panjang/pendek',
    shippingSpaceTips:
      'Jumlah dari jumlah lot panjang dan jumlah lot pendek yang saat ini ditahan, tidak termasuk order yang tertunda.',
    marketEmotion: 'Sentimen pasar (panjang/pendek)',
    dealStyleTip: [
      'Jumlah akun yang berisi gaya {x} dibagi dengan jumlah total akun di komunitas. ',
      'Jumlah akun yang fokus pada trading emas atau minyak mentah dibagi dengan jumlah total akun di komunitas. '
    ],
    lossRateTip: [
      'Di antara akun yang berisi gaya {x}, {y} mengalami kerugian. ',
      'Di antara akun-akun yang berfokus pada trading emas atau minyak mentah, ada {y} kerugian. '
    ],
    accountExplain:
      'Pada tanggal {0}({1}), terdapat {2} akun trading yang memperdagangkan {3}, yang mana {4} akun mengalami kerugian dan {5} akun menghasilkan keuntungan.',
    orderList: 'Buku Pesanan',
    orderListTips: 'Temukan potensi posisi support/resistance di pasar dan pahami area trading pasar yang padat harga',
    positionChange: 'Jumlah jabatan yang dipegang dan perubahan jabatan',
    longAccountNum: 'Jumlah akun panjang',
    shortAccountNum: 'Jumlah akun pendek',
    netPosition: 'posisi bersih',
    rise: 'Tren Positif ',
    fall: 'Tren Negatif ',
    putOrder: 'pesanan tertunda',
    position: 'Posisi Tertahan ',
    marketChange: 'Perubahan pasar dan posisi',
    longCash: 'posisi panjang',
    shortCash: 'posisi pendek',
    closePrice: 'Harga penutup',
    upsAndDowns: 'kenaikan atau penurunan intraday',
    newestPrice: 'Harga terbaru',
    marketEmotion1: 'sentimen',
    currentPosition: 'Pesanan terbuka {x}',
    longOrderCount: '{x} Pesanan panjang',
    shortOrderCount: '{x} pesanan singkat',
    price: 'harga',
    subscribeCnt: 'Jumlah Copy Trade',
    windVane: 'Tren',
    allMaster: 'Mereka semua adalah pakar {x}',
    longMaster: 'Pakar jangka panjang',
    shortMaster: 'Pakar jangka pendek',
    quantizationMaster: 'Pakar kuantitatif',
    form: 'Pola',
    name: 'nama',
    variety: 'Asset ',
    period: 'siklus',
    createTime: 'Waktu generasi',
    trend: 'Tren',
    dataSupport: 'Didukung oleh data dari FastBull',
    chartTimeZone: 'zona waktu grafik',
    allForm: 'Semua pola ',
    allVariety: 'Semua asset',
    allPeriod: 'semua siklus',
    kingList: 'Peringkat Top ',
    formDesc1:
      'Garis hammer adalah bentuk pembalikan bawah, yaitu garis K dengan kolom kecil namun bayangan atas atau bawah panjang (bayangan biasanya dua kali panjang kolom). Sebelum garis hammer, harus ada tren turun (bahkan tren turun yang lebih kecil), sehingga garis hammer bisa membalikkan tren tersebut. Jika ini terjadi pada tren naik, kami menyebutnya sebagai hanging man, bukan hammer.',
    formDesc2:
      'Semakin besar kesenjangan ke bawah antara tubuh sebenarnya dari hanging man dan harga pembukaan pada hari berikutnya, semakin besar kemungkinan bahwa hanging man akan menjadi market top. Setelah hanging man, jika pasar mempunyai garis negatif dan harga penutupannya lebih rendah dari harga penutupan hanging man, maka hal ini juga dapat dianggap sebagai bukti bahwa hanging man sudah mapan. The hanging man adalah pola pembalikan atas yang harus muncul setelah tren naik.',
    formDesc3:
      'Bintang jatuh juga dikenal sebagai "kepala palu terbalik", yang menyerupai kepala pistol. Bintang jatuh dapat berupa garis Yin atau garis Yang, tetapi tubuh aslinya relatif pendek dan garis bayangan atas panjang.Posisinya terutama muncul di atas, yang merupakan sinyal atas yang sangat jelas. Pembentukan pola ini adalah harga pembukaan relatif rendah, dan kekuatan organisasi bullish menyerang ke atas, pernah naik tajam, namun tekanan jual meningkat di akhir pasar, dan harga penutupan turun kembali mendekati harga pembukaan (menembak). bintang disebut juga "bintang jatuh" karena umur cahayanya yang pendek) .',
    formDesc4:
      'Perbedaan antara inverted hammer dan shooting star adalah ia muncul di bagian bawah pasar, yang menandakan bahwa harga mungkin akan rebound. Dari sudut pandang penggunaan sebenarnya, kekuatan pembalikan garis palu terbalik dan garis jatuh tidak sebaik garis gantung dan garis palu, jadi yang terbaik adalah menggabungkan garis K berikutnya dan metode analisis lainnya untuk analisis lebih lanjut ketika menggunakannya.',
    formDesc5:
      'Pola engulfing biasanya mengacu pada pola yin membungkus Yang atau Yang membungkus yin.Yang membungkus yin artinya garis K kedua dari belakang adalah garis yang, garis K kedua dari belakang adalah garis yin, dan garis K kedua dari belakang seluruhnya berisi K kedua dari belakang. garis Yin dan Yang adalah kebalikannya. Selain itu, Yang Bao Yang dan Yin Bao Yin juga sangat umum. Yang pertama biasanya menjadi titik penjualan, dan yang terakhir biasanya menjadi titik pembelian. Namun, kita tidak bisa gegabah menentukan arah jual beli hanya berdasarkan hal ini. Kami tetap perlu menggabungkannya dengan sarana teknis lainnya untuk analisis komprehensif.',
    formDesc6:
      'Pola engulfing biasanya mengacu pada pola yin membungkus Yang atau Yang membungkus yin.Yang membungkus yin artinya garis K kedua dari belakang adalah garis yang, garis K kedua dari belakang adalah garis yin, dan garis K kedua dari belakang seluruhnya berisi K kedua dari belakang. garis Yin dan Yang adalah kebalikannya. Selain itu, Yang Bao Yang dan Yin Bao Yin juga sangat umum. Yang pertama biasanya menjadi titik penjualan, dan yang terakhir biasanya menjadi titik pembelian. Namun, kita tidak bisa gegabah menentukan arah jual beli hanya berdasarkan hal ini. Kami tetap perlu menggabungkannya dengan sarana teknis lainnya untuk analisis komprehensif.',
    formDesc7:
      'Tiga burung gagak juga disebut "Tiga Tentara Hitam", yang berarti tiga garis negatif ke bawah berturut-turut, yang biasanya merupakan pertanda keruntuhan pasar.Munculnya pola garis K seperti itu umumnya menunjukkan bahwa harga akan semakin turun. Sebaliknya, jika tiga tentara merah terjadi dalam tren menurun, umumnya merupakan sinyal pembalikan yang kuat bagi pasar; jika harga pasar muncul setelah pergerakan sideways dalam jangka waktu lama, maka pola tren tiga tentara merah akan disertai. oleh Peningkatan volume trading secara bertahap adalah awal dari dimulainya pasar dan dapat menarik perhatian.',
    formDesc8:
      'Tiga burung gagak juga disebut "Tiga Tentara Hitam", yang berarti tiga garis negatif ke bawah berturut-turut, yang biasanya merupakan pertanda keruntuhan pasar.Munculnya pola garis K seperti itu umumnya menunjukkan bahwa harga akan semakin turun. Sebaliknya, jika tiga tentara merah terjadi dalam tren menurun, umumnya merupakan sinyal pembalikan yang kuat bagi pasar; jika harga pasar muncul setelah pergerakan sideways dalam jangka waktu lama, maka pola tren tiga tentara merah akan disertai. oleh Peningkatan volume trading secara bertahap adalah awal dari dimulainya pasar dan dapat menarik perhatian.',
    formDesc9:
      'Morning Star adalah bentuk kombinasi garis K yang terdiri dari tiga garis K. Ini adalah bentuk di mana pasar berada pada posisi terbawah dan berputar. Jika bentuk ini muncul dalam tren menurun sebaiknya Anda perhatikan, karena saat ini tren telah mengirimkan sinyal pembalikan yang relatif jelas, yang merupakan peluang beli yang sangat bagus.',
    formDesc10:
      'Bintang malam adalah kebalikan dari bintang pagi dan menandakan pembalikan tren naik yang lebih kuat. Jika bentuk kombinasi K-line Evening Star muncul dalam tren naik, sebaiknya kita perhatikan, karena saat ini tren tersebut telah mengirimkan sinyal pembalikan yang relatif jelas atau sinyal callback jangka pendek hingga menengah, yang mana mungkin saat yang sangat tepat bagi kita untuk menjual atau Saatnya menghindari jangka pendek dan menengah.',
    formDesc13:
      'Tutupan awan gelap, juga dikenal sebagai garis awan gelap, adalah salah satu pola pembalikan atas yang umum pada grafik garis K. Bentuk ini terdiri dari dua garis K, satu yin dan satu yang. Biasanya muncul setelah tren naik. Dalam beberapa kasus, garis tersebut juga muncul di bagian atas rentang penyesuaian horizontal, yang merupakan sinyal bearish.',
    formDesc14:
      'Lampu pertama terdiri dari dua kandil panjang yang bergerak berlawanan arah. Hari sebelumnya adalah garis Yin dan hari berikutnya adalah garis Yang. Keesokan harinya garis Yang mengalami gap ke bawah dan dibuka lebih rendah, dan harga pembukaan jauh lebih rendah dari harga penutupan hari sebelumnya; namun harga penutupan hari berikutnya lebih tinggi dari harga penutupan hari sebelumnya, dan harga penutupan harga garis Yang masuk jauh ke dalam tubuh sebenarnya dari garis Yin pertama. Sebagian, mencapai setidaknya setengah dari entitas garis negatif hari sebelumnya.',
    formDesc15:
      'Doji merupakan garis K yang hanya memiliki garis bayangan atas dan bawah serta tidak memiliki kolom, artinya harga pembukaan sama dengan harga penutupan. Diantaranya: semakin panjang garis bayangan atas, semakin kuat daya jualnya, semakin panjang garis bayangan bawah, semakin kuat pula daya belinya. Jika persilangan yang lebih jelas muncul pada harga tinggi atau rendah, berarti pasar sangat mungkin terjadi .Terjadi pembalikan.',
    formDesc16:
      'Doji merupakan garis K yang hanya memiliki garis bayangan atas dan bawah serta tidak memiliki kolom, artinya harga pembukaan sama dengan harga penutupan. Diantaranya: semakin panjang garis bayangan atas, semakin kuat daya jualnya, semakin panjang garis bayangan bawah, semakin kuat pula daya belinya. Jika persilangan yang lebih jelas muncul pada harga tinggi atau rendah, berarti pasar sangat mungkin terjadi .Terjadi pembalikan.',
    formDesc17:
      'Dibandingkan dengan pola engulfing, urutan kedua garis K justru terbalik pada pola harami. Pada pola engulfing, terdapat real body panjang di belakangnya, menutupi real body kecil di depannya; pada pola harami, real body garis K terakhir lebih kecil dan ditampung oleh real body sebelumnya yang lebih panjang. Asal usul nama bentuk ini juga karena arti “kehamilan”. Garis K yang panjang adalah garis "ibu", dan garis K kecil adalah garis "anak", atau garis "janin", untuk menunjukkan makna inklusifnya.',
    formDesc18:
      'Dibandingkan dengan pola engulfing, urutan kedua garis K justru terbalik pada pola harami. Pada pola engulfing, terdapat real body panjang di belakangnya, menutupi real body kecil di depannya; pada pola harami, real body garis K terakhir lebih kecil dan ditampung oleh real body sebelumnya yang lebih panjang. Asal usul nama bentuk ini juga karena arti “kehamilan”. Garis K yang panjang adalah garis "ibu", dan garis K kecil adalah garis "anak", atau garis "janin", untuk menunjukkan makna inklusifnya.',
    formDesc19:
      'Dibandingkan dengan pola engulfing, urutan kedua garis K justru terbalik pada pola harami. Pada pola engulfing, terdapat real body panjang di belakangnya, menutupi real body kecil di depannya; pada pola harami, real body garis K terakhir lebih kecil dan disertakan oleh real body sebelumnya yang lebih panjang (jika terakhir Jika garis K adalah bintang silang, maka disebut salib harami). Asal usul nama bentuk ini juga karena arti “kehamilan”. Garis K yang panjang adalah garis "ibu", dan garis K kecil adalah garis "anak", atau garis "janin", untuk menunjukkan makna inklusifnya.',
    formDesc20:
      'Dibandingkan dengan pola engulfing, urutan kedua garis K justru terbalik pada pola harami. Pada pola engulfing, terdapat real body panjang di belakangnya, menutupi real body kecil di depannya; pada pola harami, real body garis K terakhir lebih kecil dan disertakan oleh real body sebelumnya yang lebih panjang (jika terakhir Jika garis K adalah bintang silang, maka disebut salib harami). Asal usul nama bentuk ini juga karena arti “kehamilan”. Garis K yang panjang adalah garis "ibu", dan garis K kecil adalah garis "anak", atau garis "janin", untuk menunjukkan makna inklusifnya.',
    traderStyle: 'Preferensi',
    winningAccounts: 'Untung ',
    losingAccounts: 'Rugi',
    dealLong: 'Panjang',
    dealShort: 'Pendek',
    sellingPrice: 'harga jual',
    buyingPrice: 'Harga buy',
    hangingOrderData: 'Data pesanan tertunda',
    positionOrderData: 'Data posisi dibuka',
    periodicalNumber: 'Edisi {x}',
    greatestRule: 'Aturan seleksi',
    selectTraderStyle: 'Pilih jenis trading '
  },
  user: {
    sendMsg: 'Kirim pesan',
    userId: 'identitas pengguna',
    attention: 'Ikuti ',
    collect: 'Masukkan Koleksi ',
    home: 'Beranda',
    contest: 'Kontes',
    social: 'Chat',
    vip: 'anggota',
    setting: 'Pengaturan ',
    about: 'tentang',
    accountListLen: 'Jumlah maksimum akun trading yang diperbolehkan untuk diikat adalah {x}.',
    addAccount: 'Tambah akun',
    loginRegister: 'Masuk',
    logoutSuccess: 'Sukses Keluar ',
    accountLis: 'Daftar akun',
    totalAccount: 'Total {x} akun',
    noBindAccount: 'TA belum ikat akun apapun',
    unfoldAll: 'Lebarkan semua',
    foldAll: 'Kecilkan semua',
    similarAccount: 'Akun serupa',
    changeAccount: 'Ubah',
    signaturePlaceholder: 'Tidak ada konten apapun',
    loginViewOrder: 'Setelah masuk, lihat  posisi pesanan Anda',
    brokerGrade: 'Apakah menurut Anda trader {x} di akun ini dapat diandalkan?',
    soldOut:
      'Direkomendasikan agar FastBull Top Traders menghapus broker ini dan tidak lagi menghubungkan akun ke broker ini ',
    accountReport: 'Laporan transaksi palsu',
    suspects:
      'Harap tunjukkan poin-poin palsu dan poin-poin mencurigakan dari akun sehingga sebagian besar teman dapat merujuk atau menyaringnya.',
    reliable: 'Dapat diandalkan',
    unreliable: 'Tidak bisa diandalkan',
    suggestSoldOut: 'Disarankan untuk dihapus',
    reportSuccess: 'Laporkan berhasil!',
    emoji: 'ekspresi',
    picture: 'gambar',
    uploadFailed: 'Gagal unggah gambar',
    submitAfterUpload: 'Silakan kirimkan setelah unggah gambar!',
    addPicture: 'Tambah gambar',
    btnTextList: ['Komentar', 'Balas', 'Konfirmasi laporan'],
    praise: 'Puji ',
    reply: 'balas',
    writeYourComment: 'Silakan masukkan balasan Anda...',
    moreReply: 'Lebih banyak balasan',
    residueReplay: '{x} balasan tersisa',
    account: 'Akun',
    grade: 'Peringkat',
    subscribe: 'Copy Trade',
    accountPraise: 'Reputasi akun',
    accountComment: 'Komentar akun',
    allComment: 'Semua komentar',
    needComment:
      'Setiap orang membutuhkan komentar Anda yang langsung pada sasaran (komentar tidak dapat diubah atau dihapus, silakan berkomentar secara rasional).',
    excellent: 'bagus',
    ordinary: 'umum',
    noGood: 'jelek',
    commentSuccess: 'Telah Dikomentari! ',
    replySuccess: 'Dibalas !',
    inputNotice: 'Masukkan konten pengumuman',
    allowNoticeCount: 'Maksimal {x} pengumuman diperbolehkan per hari',
    totalCount: 'Jumlah {x} berita',
    publish: 'Publikasi',
    publishSuccess: 'Pengumuman berhasil dipublikasikan!',
    isDeleteNotice: 'Hapus pengumuman?',
    deleteNotice: 'Hapus ',
    closeComment: 'Izin berkomentar telah dinonaktifkan untuk akun ini',
    privateComment: 'Akun pribadi, tidak dapat mengirim komentar',
    privateReport: 'Akun pribadi, tidak dapat memposting informasi pelaporan',
    length1: 'Silakan masukkan setidaknya 1 karakter.',
    length512: 'Anda dapat memasukkan hingga 512 karakter',
    noAccount: 'Belum ada akun trading',
    tradingPlatform: 'Software trading',
    broker: 'Broker',
    brokerServer: 'server',
    dealAccountNum: 'Akun',
    tradingPassword: 'kata sandi',
    passwordExplain: 'Jika Anda tidak perlu mengikuti transaksi, cukup masukkan kata sandi investor.',
    inputPassword: 'Silakan masukkan kata sandi',
    tradingStrategy: 'Strategi trading',
    strategyExplain: 'Silakan perkenalkan strategi trading Anda.',
    passwordLength: 'Kata sandi transaksi sepanjang 4-32 karakter',
    strategyLength: 'Strategi trading membutuhkan minimal 16 karakter',
    searchName: 'Cari nama broker atau server',
    record: 'Riwayat pencarian',
    hotSearch: 'Pencarian Populer',
    result: 'Hasil Pencarian',
    inputAccount: 'Silakan masukkan nomor akun trading',
    inVerification: 'Verifikasi akun...',
    accountLength: 'Nomor akun trading adalah 4-16 digit',
    bindOvertime: 'Batas waktu pengikatan akun habis',
    addTradingAccount: 'Tambahkan akun trading',
    linkAccount: 'Tautkan akun',
    accountSetting: 'pengaturan akun',
    otherBind: 'Akun trading telah diikat oleh orang lain',
    howToFind: 'Bagaimana cara mengambil?',
    findAccount: 'Pulihkan akun',
    stepTitle: 'Silakan ikuti langkah-langkah di bawah ini pulihkan akun trading Anda yang ditempati orang lain:',
    findStep1: '1. Masuk ke MT4/MT5 menggunakan kata sandi Anda.',
    findStep2: '2. Ubah kata sandi saat ini atau kata sandi investor akun trading.',
    findStep3: '3. Kembali ke daftar Top Trader dan tambahkan kembali akun trading.',
    addSuccess: 'Berhasil ditambahkan',
    initExplain:
      'Sistem sedang menginisialisasi data untuk akun ini yang memakan waktu sekitar 3 menit. Setelah inisialisasi selesai, akun dapat digunakan secara normal.',
    bindNow: 'Ikat sekarang',
    brokerBan: 'Broker telah dilarang',
    accountRate:
      'baik: Kemampuan trading yang kuat\nRata-rata: Kemampuan trading rata-rata\nBuruk: Kemampuan trading lemah',
    accountReportTips:
      'FastBull Top Traders akan memberikan umpan balik kepada pedagang terkait dan memverifikasi keaslian data.',
    accountList: 'Daftar akun',
    conversionRate: 'Tingkat konversi',
    nowDay: 'hari itu',
    lastSevenDay: '7 hari terakhir',
    yesterday: 'Kemarin',
    notice: 'pengumuman',
    edit: 'Edit',
    totalYieldRate: 'Tingkat pengembalian kumulatif',
    bindAccountTips: 'Belum ada akun trading, buka sekarang~',
    subscribeTips: 'Ikuti sinyal trading dan investasi dengan Top Traders',
    toSubscribe: 'Ikuti Pesanan ',
    contesting: 'Bersaing',
    season: '{x} musim',
    rank: 'Peringkat',
    chatroom: 'ruang obrolan',
    friend: 'teman-teman',
    groupChat: 'grup',
    topic: 'tema',
    writer: 'penulis',
    news: 'berita',
    video: 'video',
    pictureVideo: 'Video gambar',
    file: 'dokumen',
    audio: 'suara',
    chatRecord: 'catatan obrolan',
    followed: 'Diikuti',
    fans: 'penggemar',
    article: 'artikel',
    cancelCollect: 'Batalkan',
    simulationGroup: 'Grup akun demo',
    actualGroup: 'Grup akun Live',
    contestData: 'Data Kompetisi',
    awardsCount: 'Jumlah Penghargaan',
    totalAward: 'Jumlah Total Hadiah',
    topScore: 'Skor Tertinggi',
    megagameRecord: 'Catatan Kompetisi',
    entryAccount: 'Akun Partisipasi',
    score: 'Nilai Poin',
    ranking: 'Peringkat',
    awards: 'Hadiah ',
    extraAward: 'Hadiah Tambahan',
    auditStatus: 'Status Pemeriksaan',
    status: ['Pemeriksaan berhasil', 'Pemeriksaan gagal', 'Dalam Tinjauan'],
    noRecord: 'Belum ada catatan kompetisi',
    socialGroup2: 'Grup yang saya kelola ({x})',
    socialGroup3: 'Grup tempat saya bergabung ({x})',
    comeFrom: 'Dari: {x}',
    socialGroup1: 'Grup yang saya buat ({x})',
    nextStep: 'Langkah berikutnya',
    selectBrokers: 'Pilih server ',
    bindSuccess: 'Terikat ',
    goFollowOrder: 'Ikuti ',
    accountDetail: 'Detail akun',
    bindAgain: 'Coba Lagi ',
    traderAccount: 'akun transaksi',
    traderLever: 'Leverage',
    subscribeNum: 'Pengikut {0}',
    depositCurrency: 'Mata uang setoran',
    accountName: 'nama akun',
    withoutSignature: 'Tidak ada moto trading yang ditetapkan',
    fastbullVIP: 'Anggota Fastbull',
    openVipForFree: 'keanggotaan gratis',
    logout: 'keluar',
    shareFB: 'Bagikan Fastbull',
    copyLink: 'Salin tautan',
    addFriend: 'Tambah teman',
    addFriendVerify: 'Tambahkan teman untuk memverifikasi',
    waitVerify: 'Tunggu verifikasi',
    added: 'ditambahkan',
    defaultVerify: 'saya {x}',
    inputVerifyInfo: 'Silakan masukkan informasi verifikasi:',
    addSuccessTip:
      'Permintaan Anda untuk menambah teman telah berhasil dikirim dan menunggu konfirmasi dari pihak lain.',
    send: 'Kirim',
    sendApplySuccess: 'Lamaran berhasil dikirim',
    cancelAttentionConfirm: 'Apakah Anda yakin tidak ingin mengikuti pengguna ini lagi?',
    userCenter: 'Pusat Pribadi',
    openFBAPP: 'Buka APP',
    supportNewsPrice: 'Menyediakan berita dan kutipan keuangan yang lebih cepat dan lengkap',
    noCollect: 'Belum ada favorit yang ditambahkan',
    accountPwd: 'Kata sandi',
    fxchat_niu_trading_select: 'pilih ',
    fxchat_niu_trading_select_first: 'pilih broker ',
    fxchat_niu_trading_server_select: 'pilih',
    fxchat_niu_account_input_hint: '4 hingga 16 digit',
    fxchat_niu_observe_account_input_hint: '4~32 digit kata sandi',
    fxchat_niu_observe_password_tip: 'Jika Anda tidak perlu mengikuti transaksi, cukup masukkan kata sandi investor.',
    fxchat_niu_trading_strategy_hint: 'Harap perkenalkan secara singkat strategi trading Anda, 16~128 kata',
    fxchat_niu_account_bind: 'Akun trading terikat oleh orang lain,',
    commentAfterLogin: 'Silakan {x} sebelum mengirim komentar^_^',
    noBodyAdd: 'Permintaan berteman gagal. Pengguna yang mengaktifkan fungsi "Tidak Berteman dengan Siapapun".'
  },
  grade: {
    synthesizeGrade: 'Peringkat keseluruhan',
    gradeTips:
      'Peringkat komprehensif didasarkan pada data transaksi enam bulan terakhir dan diperbarui satu kali sehari.',
    tradeAbility: 'kemampuan trading',
    goodAtVariety: 'Fokus Asset',
    riskLevel: 'tingkat risiko',
    maxDrawdown: 'Drawdown Maks. ',
    viewGradeReport: 'Lihat laporan peringkat komprehensif',
    rank: 'Peringkat komprehensif {x}',
    score: 'Skor komprehensif {x} poin',
    tradeAbilityList: ['sempurna', 'sangat baik', 'baik', 'sedang', 'lemah', 'sangat lemah'],
    riskLevelList: ['Risiko rendah', 'Risiko sedang', 'Risiko tinggi'],
    profitAndLoss: 'Untung Rugi akun',
    orderControl: 'Kontrol pesanan',
    varietyData: 'Data Asset',
    dealStyle: 'gaya trading',
    dealPosition: 'Data posisi',
    gradeStr: ['Sempurna', 'Baik', 'Sedang', 'Buruk'],
    gradeScore: 'Skor penilaian',
    scoreTooltip:
      'A+ (di atas 90 poin), kemampuan trading luar biasa! <br/>A (85 poin atau lebih), kemampuan trading yang kuat! <br/> B+ (di atas 80 poin), kemampuan trading yang bagus! <br/> B (75 poin atau lebih), kemampuan trading rata-rata! <br/> C+ (di atas 60 poin), kemampuan trading lemah! <br/> C (kurang dari 60 poin), kemampuan trading sangat lemah!',
    tradeGrade: 'Peringkat Transaksi',
    gradeExplain:
      'Peringkat komprehensif didasarkan pada hasil peringkat enam bulan terakhir, dan informasi peringkat diperbarui sekali sehari.',
    yieldRateTooltip:
      'Tingkat pengembalian keseimbangan dalam jangka waktu tertentu, dihitung menggunakan algoritma TWR.',
    maxDrawdownTooltip:
      'Penurunan nilai bersih terbesar (jika tidak ada data ekuitas, yang digunakan adalah data saldo) dalam jangka waktu tertentu. Karena dampak penyetoran dan penarikan, nilai ini mungkin melebihi 100%.',
    yieldRiskRatioTooltip:
      'Tingkat hasil/drawdown maks. Ketika tingkat pengembalian kurang dari atau sama dengan 0, rasio pengembalian terhadap risiko secara langsung bernilai 0; ketika penarikan maksimum adalah 0, rasio pengembalian terhadap risiko bernilai 100.',
    yieldRiskRatio: 'rasio risiko-pengembalian',
    orderTotalTooltip: 'Jumlah pesanan dalam periode yang ditentukan.',
    orderTotal: 'total pesanan',
    dealFrequencyTooltip: 'rata-rata order yang diperdagangkan per hari selama periode tertentu.',
    dealFrequency: 'Frekuensi transaksi',
    frequencyUnit: '{x} pesanan/hari',
    stopProfitRateTooltip: 'Proporsi order dengan take profit atau stop loss di antara order dalam periode tertentu.',
    stopProfitRate: 'Tingkat TP & SL',
    varietyFreight: 'Asset&posisi',
    heavyRatioTooltip:
      'Di antara pesanan dalam jangka waktu tertentu, proporsi pesanan dengan posisi berat (pesanan menempati lebih dari 15% dana).',
    heavyRatio: 'Rasio posisi jumlah besar',
    focusVarietyTooltip: 'Jumlah asset yang sering diperdagangkan dalam jangka waktu tertentu.',
    focusVariety: 'Fokus Asset',
    profitLossRatioTooltip:
      'Rasio rata-rata keuntungan pesanan yang menguntungkan terhadap rata-rata kerugian pesanan yang rugi di antara pesanan dalam periode tertentu. Ketika rata-rata kerugian adalah 0, rasio untung-rugi adalah 100.',
    profitLossRatio: 'P/L',
    dealStyleTooltip: 'Gaya trading dalam jangka waktu tertentu.',
    profitPositionTooltip:
      'Rata-rata waktu tunggu pesanan yang menguntungkan di antara pesanan-pesanan dalam periode yang ditentukan.',
    profitPosition: 'Posisi rata-rata pesanan yang menguntungkan',
    lossPositionTooltip: 'Rata-rata waktu tunggu pesanan yang hilang di antara pesanan dalam periode yang ditentukan.',
    lossPosition: 'Rata-rata posisi order yang merugi',
    gradeResult: 'Hasil pemeringkatan hanya untuk referensi dan bukan merupakan saran investasi apa pun.',
    general: 'Keseluruhan ',
    evaluateList: [
      'Jumlah pesanan terlalu kecil untuk dinilai secara akurat',
      'Bergembiralah dan berlayar melawan arus, jika Anda tidak maju, Anda akan mundur',
      'Kemampuan profesional perlu ditingkatkan',
      'Anda dapat melangkah lebih jauh , jangan menjadi orang yang bodoh',
      'Kinerjanya bagus, teruslah bekerja dengan baik',
      'seorang ahli trading yang layak',
      'tingkat trading tingkat jenius'
    ],
    profitAbility: {
      worth: 'Profitabilitas sangat buruk',
      veryBad: 'Profitabilitas sangat buruk',
      bad: 'Profitabilitas buruk',
      needToImprove: 'Profitabilitas perlu ditingkatkan',
      common: 'Profitabilitas rata-rata',
      strong: 'Profitabilitas Lebih Kuat ',
      stronger: 'Profitabilitas sangat kuat',
      strongest: 'Profitabilitas sangat kuat'
    },
    earnings: {
      veryInstability: 'Pendapatan sangat tidak stabil. ',
      instability: 'Pendapatan tidak stabil. ',
      stabilize: 'Pendapatannya relatif stabil. ',
      veryStabilize: 'Pendapatannya sangat stabil. ',
      mostStabilize: 'Pendapatannya sangat stabil. '
    },
    dealRisk: {
      lowest: 'Risiko trading sangat rendah',
      smaller: 'Risiko trading lebih rendah',
      controlled: 'Risiko transaksi dapat dikendalikan',
      high: 'Risiko trading tinggi',
      higher: 'Risiko trading tinggi',
      gigantic: 'Risiko trading sangat besar'
    },
    earningsRiskRatio: {
      worst: 'Rasio manfaat terhadap risiko sangat buruk.',
      veryBad: 'Rasio manfaat terhadap risikonya buruk.',
      needToImprove: 'Rasio manfaat-risiko perlu ditingkatkan.',
      rational: 'Rasio manfaat-risikonya masuk akal.',
      good: 'Rasio manfaat terhadap risiko sangat baik.',
      veryGood: 'Rasio manfaat terhadap risiko sangat baik.'
    },
    avgDailyYield: 'Perubahan harian rata-rata akun {x}',
    avgWeekYield: 'Saldo mingguan rata-rata akun {x}',
    avgMonthYield: 'Saldo bulanan rata-rata akun {x}',
    dayProfit: 'Probabilitas keuntungan harian adalah {x}',
    monthProfit: 'Probabilitas keuntungan bulanan adalah {x}',
    maxDrawdownIs: 'Drawdown maksimumnya adalah {x}',
    earningsRiskValue: 'Rasio risiko-pengembalian adalah {x}',
    dealFrequencyExplain: [
      'Frekuensi trading terkontrol dengan baik, mohon terus dipertahankan. Lagi pula, semakin banyak Anda melakukannya, semakin besar kemungkinan melakukan kesalahan. ',
      'Frekuensi transaksi berada pada level yang tinggi. Mengurangi frekuensi transaksi secara tepat akan membantu pengendalian risiko dengan lebih baik. '
    ],
    stopExplain: [
      'Karena rendahnya tingkat pengaturan take-profit atau stop-loss, mungkin terdapat risiko trading tertentu. ',
      'Tujuan trading tidak begitu jelas. Memanfaatkan stop-profit atau stop-loss dapat mengurangi risiko trading sampai batas tertentu. ',
      'Tujuan trading biasanya relatif jelas. Anda harus berhati-hati saat masuk dan keluar pasar, dan jangan berperang dalam pertempuran yang tidak pasti. ',
      'Tujuan trading yang jelas dan kebiasaan trading yang baik. '
    ],
    accumulativeDeal: 'trading kumulatif {x} hari',
    avgOrder: 'Rata-rata {x} pesanan per hari',
    stopPercent: 'Take-profit dan stop-loss ditetapkan untuk pesanan {x}',
    heavyExplain: [
      'Memiliki kesadaran yang baik tentang pengendalian risiko posisi, dan pengendalian posisi secara keseluruhan relatif masuk akal. ',
      'Sesekali melakukan trading berat. ',
      'Pastikan untuk melakukan pekerjaan dengan baik dalam pengendalian risiko ketika melakukan trading besar dari waktu ke waktu. ',
      'Trading dengan posisi berat terlalu sering dapat menimbulkan risiko transaksi yang sangat tinggi, jadi harap berhati-hati. '
    ],
    heavyPercent: 'Di antara pesanan {x}, proporsi posisi jumlah besar adalah {y}',
    suggestion:
      'Disarankan untuk menghentikan keuntungan dan menghentikan kerugian untuk semua pesanan gudang yang berat, meninggalkan mentalitas perjudian, dan melakukan pekerjaan dengan baik dalam pengendalian risiko.',
    noFocus:
      'Tidak ada asset atau asset khusus yang Anda kuasai, disarankan untuk fokus pada satu atau dua varietas, yang dapat meningkatkan kemampuan trading Anda dengan lebih baik.',
    focusVarietyAt: 'Fokus Asset adalah {x},',
    focusCount: 'Fokus pada asset {x} {y},',
    profitLossStr:
      'Untung Rugi kumulatif produk ini adalah {x}, dan kami masih harus terus bekerja keras untuk menjadikannya lebih baik.',
    profitLossTotal: 'Jumlah untung dan ruginya adalah {x}, lanjutkan saja.',
    goodAtStr: 'Terbaik di {x}, keuntungannya mencapai {y} dari total keuntungan, teruslah bekerja keras.',
    tradingStyle: [
      'trading intraday',
      'trading jangka pendek',
      'trading jangka panjang',
      'trading kuantitatif',
      'Tanpa gaya trading'
    ],
    tradingType: ['Intraday', 'Jangka Pendek', 'Jangka Panjang', 'Kuantitatif'],
    winAndRatio: 'Tingkat kemenangan {x} adalah sekitar {y}, dan rasio untung-rugi sekitar {z}.',
    beGoodAt: 'Bagus dalam {x}',
    noTradingStyle:
      'Tidak ada gaya trading yang jelas. Tingkat kemenangan pesanan jangka pendek adalah {x}, dan tingkat kemenangan pesanan jangka panjang adalah {y}.',
    avgPosition:
      'Total rata-rata panjang posisi adalah {x}, rata-rata profit pesanan adalah {y}, dan rata-rata loss order loss adalah {z}.',
    joinAndRate: 'Bergabunglah dengan Top Trader\nevaluasi kemampuan trading Anda',
    rated: '{x} akun trading telah ditinjau, dengan skor rata-rata {y}',
    rateNow: 'Tinjau sekarang',
    isTheRating: 'Peringkat AI sedang menilai Anda, harap tunggu...',
    scoreTips:
      'Skor komprehensif juga mencakup tiga poin tambahan, yang digunakan untuk mengukur kinerja akun trading dalam hal evaluasi pengguna, pesanan anti-tren, dan siklus bertahan. <br/>Poin tambahan untuk promosi dari mulut ke mulut: {x} poin<br/>Poin tambahan untuk posisi: {y} poin<br/>Poin tambahan untuk periode: {z} poin',
    warmPrompt: 'Tips',
    traderForShort: 'trading jangka pendek',
    traderForLong: 'trading jangka panjang',
    traderForQuantification: 'trading kuantitatif',
    traderForGold: 'trading minyak mentah emas',
    traderForShortTip: 'Pengantar trading jangka pendek',
    traderForLongTip: 'Pengantar trading jangka panjang',
    traderForQuantificationTip: 'Pengantar trading Kuantitatif',
    traderForGoldTip: 'Pengantar trading emas dan minyak mentah',
    goldMaster: 'Pakar minyak mentah emas'
  },
  subscribe: {
    openSubscribe: 'Aktifkan izin copy trading',
    connectionNormal: 'Status koneksi akun normal',
    accountIsReal: 'Ini adalah akun live',
    notAbnormal: 'Tidak ditandai sebagai akun abnormal oleh sistem',
    brokerCompliance: 'Broker terkait adalah broker teregulasi ',
    equityMoreThan: 'Kekayaan bersih akun tersebut tidak kurang dari $1000,00',
    openNow: 'Aktifkan sekarang',
    openSuccess: 'Hak copy trading berhasil diaktifkan',
    disqualification: 'Akun ini tidak memenuhi syarat untuk diaktifkan',
    openCondition: 'Untuk menjadi penyedia sinyal, syarat-syarat berikut harus dipenuhi:',
    closeSubscribe: 'Nonaktifkan hak copy trade ',
    closeSubscribeConfirm: 'Apakah Anda yakin ingin menonaktifkan izin copy trading untuk akun trading ini?',
    closePunishmentExplain:
      'Sudah ada {x} pedagang yang menyalin pada akun ini. Jika Anda menonaktifkan izin copy trading, Anda akan dikenakan sanksi sesuai aturan komunitas sebagai berikut:',
    punishment: 'Akun trading dilarang mengaktifkan izin copy trading selama 90 hari.',
    consider: 'Batalkan',
    closeNow: 'Nonaktifkan sekarang',
    closeSuccess: 'Salin izin trading dinonaktifkan',
    lengthen: 'Perpanjang copy trade',
    follow: 'Ikuti ',
    selectAccount: 'Pilih Akun',
    alreadyFollow: 'Akun diikuti',
    followDays: '{x} hari berikutnya, {y} jatuh tempo',
    notFollow: 'Akun tidak diikuti',
    accountIsDelete: 'Akun berikut telah dihapus.',
    accountDelete: 'Akun Signal telah dihapus.',
    subscribeForbid: 'Hak copy trade akun ini telah dinonaktifkan.',
    subscribeClose: 'Akun ini tidak memiliki hak copy trade.',
    closeAfterExpire: 'Akun ini tidak diperbolehkan lagi copy trade.',
    followAccountOffline:
      'Akun trading Anda <span>#{x}</span> sedang offline dan untuk sementara tidak tersedia. Jika kata sandi koneksi akun telah diubah, silakan <a target="_blank" href="{y}">masuk ke</a> halaman pengaturan akun untuk memperbarui kata sandi koneksi.',
    brokerForbid:
      'Peringkat Top Trade tidak lagi mendukung trader {x}, demikian, akun trading di bawah trader ini tidak lagi diizinkan copy trade.',
    fictitiousTradesTips: 'Akun ini mungkin melakukan transaksi palsu dan telah dilarang mengikuti pesanan.',
    violateRuleTips:
      'Karena Anda telah melanggar aturan copy trade berbayar, sistem melarang Anda salin sinyal apa pun di Peringkat Top Trader. Jika punya pertanyaan, silakan hubungi Layanan Pelanggan.',
    limitationUser: 'pengguna dibatasi',
    subscribeWarning: 'Peringatan',
    riskAccountTips:
      'Akun ini mungkin memiliki risiko lebih tinggi, harap ikuti pesanan dengan hati-hati. Jangan mudah mempercayai orang lain dan hindari penipuan. ',
    userAbnormalTips: 'Pengguna yang tergabung dalam akun ini tidak normal, harap berhati-hati ikuti pesanan.',
    noCanFollow: 'Saat ini tidak ada akun berikut.',
    noAccount: '\nAnda belum mengikat akun trading Anda,',
    accountOffline: 'Akun ini sedang offline dan untuk sementara tidak tersedia.',
    brokerLimit: 'Pedagang dibatasi',
    accountFollowTips:
      'Sandi koneksi yang saat ini digunakan oleh akun trading <span>#{x}</span> adalah Sandi Investor dan tidak memiliki izin trading, sehingga tidak dapat copy trade dalam Peringkat Trader Terbaik. <br/> Anda harus <a target="_blank" href="{y}">masuk ke setting akun</a> untuk memperbarui sandi koneksi akun menjadi <span>Sandi Trading</span> , lalu lakukan copy trade.',
    dealLimit: 'Transaksi dibatasi',
    forbidSubscribe: 'Dilarang copy trade',
    followSuccess: 'Berhasil copy trade',
    followSetting: 'Tetapkan parameter copy trade',
    subscriber: 'Pengikut',
    subscribeTypeList: [
      {value: 1, name: 'Mengikuti pesanan'},
      {value: 2, name: 'Riwayat copy trade'}
    ],
    params: 'Parameter copy trade',
    subscribeTime: 'Waktu copy trade',
    subscribePeriod: 'Periode copy trade',
    subscribeEndTime: 'Akhir Waktu Salin',
    totalSubscribePeriod: 'Total Waktu Salin ',
    otherUser: 'Masih copy trade',
    patternList: [
      {name: 'Memperbaiki ukuran lot', value: 1},
      {name: 'rasio tetap', value: 2}
    ],
    directionList: [
      {name: 'Ikuti ke depan', value: 1},
      {name: 'Ikuti secara terbalik', value: 2},
      {name: 'Ikuti saja posisi penutupannya', value: 3}
    ],
    notice: 'Pengumuman',
    moreTradingNotice: 'Untuk melihat pengumuman lebih lanjut<br/>Silakan buka halaman detail akun trading',
    hot: 'Copy trade terpopuler',
    count: 'Pengikut',
    allSource: 'Semua sumber',
    detail: 'Detail dokumentasi',
    cancelTips:
      'Jika hanya ingin menghentikan copy trade berikut, silakan buka jendela pengaturan copy trade dan atur status copy trade ke "mati"',
    cancel: 'Batalkan copy trade',
    setting: 'Pengaturan',
    detailStatusList: ['', 'Mengikuti pesanan', 'Kadaluwarsa', 'Dibatalkan', 'Dikembalikan dananya', 'Belum dimulai'],
    orderId: 'Id pemesanan',
    startTime: 'Waktu Awal',
    endTime: 'Waktu Akhir ',
    cancelTime: 'Waktu pembatalan',
    cancelReason: 'Alasan',
    notStartTips: 'Pesanan "Belum dimulai" akan berlaku setelah pesanan "Diikuti" berakhir.',
    confirmTocancel: 'Yakin batalkan copy trade/ ikuti pesanan?',
    subscribeStartTime: 'Waktu mulai copy trade ',
    followAccount: 'ikuti akun',
    followStatus: 'status',
    followStateTips:
      'Setelah mematikan follow, Anda tidak dapat membuka atau menutup posisi. Namun Anda tetap akan menerima sinyal untuk membuka dan menutup posisi pada akun sinyal Anda di pusat pesan.',
    baseSetting: 'pengaturan dasar',
    varietySetting: 'pengaturan asset',
    followNotice: 'Petunjuk',
    followPattern: 'Mode Copy trade',
    followPatternTips:
      'Rasio tetap: Ukuran lot berikut dihitung berdasarkan hubungan ekuitas antara akun sinyal dan akun berikutnya, dan ukuran lot diperbesar atau dikurangi sesuai dengan kelipatan rasio yang ditentukan di sini. <br/> Ukuran lot tetap: Tidak peduli berapa banyak lot yang dibuka di akun sinyal, hanya ukuran lot yang ditentukan di sini yang akan diikuti untuk membuka posisi. Jika tidak ada persyaratan khusus, disarankan untuk menggunakan "rasio tetap" berikut ini.',
    maxHand: 'Lot Maks',
    maxHandTips:
      'Jika jumlah lot yang dibuka dalam satu posisi tindak lanjut melebihi batas ini, maka posisi akan dibuka sesuai dengan batas tersebut.',
    noLimit: 'tidak terbatas',
    followDirection: 'Arah Copy Trade',
    followDirectionTips:
      'Hanya ikuti operasi penutupan: yaitu, tidak lagi mengikuti operasi pembukaan akun sinyal, tetapi hanya mengikuti operasi penutupan.',
    contractSize: 'Ukuran kontrak',
    contractSizeTips:
      'Ukuran kontrak dari variasi yang sama mungkin berbeda pada platform yang berbeda, sehingga dapat mengakibatkan kesalahan ukuran lot berikut. Fungsi ini hanya berlaku bila mode berikut adalah "Rasio Tetap".',
    sizeList: [
      {name: 'adaptif', value: 1},
      {name: 'Lewati', value: 2}
    ],
    signalAccount: 'akun sinyal',
    followLimit: 'Pembatasan transaksi',
    followLimitTips:
      'Fungsi ini digunakan untuk membatasi akun berikut hanya melakukan transaksi pada kategori tertentu. <br/> Dengan asumsi bahwa arah berikut adalah [reverse follow], batas trading EURUSD adalah [buka order short saja], jika: <br/> Sumber sinyal membuka order buy EURUSD, dan order short harus dibuka setelahnya ikuti pembalikan akun, dan Jika batasan trading tidak bertentangan, buka posisi short. <br/> Sumber sinyal membuka order short EURUSD. Setelah mengikuti arah sebaliknya dari akun, order long harus dibuka. Namun, ini bertentangan dengan batasan trading dan tidak dapat membuka order long. <br/>',
    setManually: 'Tidak dikenali, silakan atur secara manual',
    limitList: [
      {name: 'tidak terbatas', value: 0},
      {name: 'Hanya buka order pendek', value: 1},
      {name: 'Hanya buka order panjang', value: 2},
      {name: 'dilarang buka posisi', value: 3}
    ],
    followRuleContent:
      'Aturan berikut:<br/> 1. Pending order tidak akan langsung diikuti, hanya akan diikuti bila transaksinya merupakan market order. <br/> 2. Take-profit/stop-loss tidak akan diikuti untuk menghindari masalah seperti exit lebih awal karena perbedaan lingkungan trading (harga, spread, dll.) saat mengikuti lintas platform. <br/> 3. Fungsi adaptif kontrak tidak mendukung semua variasi, seperti indeks saham, futures, saham, dan variasi lainnya. <br/> 4. Jika ukuran lot untuk pembukaan posisi melebihi ukuran lot maksimum atau lebih rendah dari ukuran lot minimum yang ditetapkan oleh dealer, maka posisi akan dibuka berdasarkan ukuran lot maksimum atau ukuran lot minimum. <br/> 5. Dipengaruhi oleh lingkungan jaringan di setiap ujung, sinyal trading mungkin tertunda. Jika sinyalnya tertunda terlalu lama, Anda sebaiknya berhenti mengikutinya. Oleh karena itu, secara default, sistem akan membuang sinyal pembukaan posisi dengan penundaan lebih dari 180 detik atau sinyal penutupan dengan penundaan lebih dari 30 menit.',
    notMatchTips:
      'Ada {x} variasi pada akun berikut yang tidak dapat cocok dengan variasi trading pada akun sinyal, sehingga tidak dapat melakukan transaksi lanjutan. Harap konfirmasi di kolom "Pengaturan Variasi".',
    maxLotsMoreThan: 'Ukuran lot pembukaan maksimum tidak boleh kurang dari ukuran lot pembukaan tetap',
    allMatchTips:
      'Di bawah kolom "Pengaturan Aset", pastikan bahwa akun sinyal dan nama variasi akun berikut telah dipetakan dengan benar, jika tidak maka akan menyebabkan pengecualian berikut.',
    hasConfirm: 'konfirmasi',
    gotoCheck: 'verifikasi',
    settingSuccess: 'berhasil diatur',
    mySubscribe: 'Langganan Saya',
    account: 'Akun Sinyal',
    currPosition: 'Posisi saat ini',
    yesterdayEarnings: 'Penghasilan kemarin',
    monthEarnings: 'Penghasilan 1 bln akhir',
    status: 'Status copy trade ',
    statusList: ['Mengikuti Pesanan', 'Kadaluwarsa dalam {x} hari', 'Segera Kadaluwarsa'],
    totalTime: 'Waktu kumulatif  copy trade',
    operation: 'Aksi',
    viewToAccount:
      'Untuk lihat siapa yang telah mengikuti pesanan saya, silakan buka halaman <a target="_blank" href="{x}">detail akun trading</a>',
    times: 'waktu',
    connectionAnomaly:
      'Akun trading Anda #{x} sedang offline dan untuk sementara tidak tersedia. <br/>Jika kata sandi koneksi akun ini telah diubah, silakan buka halaman Pengaturan Akun-Akun Personal Center-Trading untuk memperbarui kata sandi koneksi.',
    passwordTypeTips:
      'Kata sandi koneksi yang saat ini digunakan oleh akun trading Anda #{x} adalah kata sandi observasi dan tidak memiliki izin trading, sehingga Anda tidak dapat mengikuti transaksi di daftar terbaik. <br/>Anda harus masuk ke halaman Personal Homepage-Account-Account Settings untuk memperbarui kata sandi koneksi akun menjadi kata sandi trading, lalu ikuti perintahnya.',
    goNow: 'pergi sekarang',
    warmPrompt:
      'Pengingat:<br/> 1. Anda dapat mengubah pengaturan berikut kapan saja dengan masuk ke kolom "Halaman Beranda Pribadi" -> "Mengikuti". <br/>',
    fixedHands: 'Ukuran Lot Tetap ',
    fixedRatio: 'rasio tetap',
    fixedRatioTips:
      'Ukuran lot berikut dihitung berdasarkan hubungan ekuitas antara akun sinyal dan akun berikutnya, dan ini sangat direkomendasikan. ',
    fixedHandsTips:
      'Tidak peduli berapa banyak lot yang dibuka di akun sinyal, posisi hanya akan dibuka sesuai dengan jumlah lot yang ditentukan di sini. ',
    ratio: '{x} kali',
    signalVariety: 'Asset (Akun Sinyal)',
    followVariety: 'Asset (ikuti akun)',
    selectVariety: 'Pilih asset',
    searchVariety: 'Pencarian asset',
    hasQuestion: 'Mengalami masalah? Silakan hubungi <span>layanan pelanggan resmi</span>',
    subscribeInfo: 'Informasi Copy Trade',
    followAgain: 'Salin lagi',
    residueLong:
      'Sisa jangka waktu izin penyalinan Anda adalah {0} bulan, dan perpanjangan tidak didukung saat ini. <br/>Perhatikan bahwa sisa masa tindak lanjut hanya didukung hingga {1} bulan. Oleh karena itu, Anda dapat memperpanjang masa tindak lanjut apabila sisa masa tindak lanjut kurang dari {1} bulan.',
    subscribeExpire: 'Periode Salin telah Kadaluarsa ',
    closeTips:
      'Jika Anda hanya ingin menerima sinyal dan tidak mengikuti perintah, Anda dapat menonaktifkan status berikut.',
    shareGetFollow:
      'Fungsi berbagi dan izin copy trade telah dinonaktifkan. Silakan masuk ke Pusat Anggota untuk menjadi anggota lalu melakukan copy trade.',
    signalNotFollow: 'Akun Sinyal tidak mendukung copy trade',
    initNotFollow: 'Inisialisasi, silakan coba lagi nanti'
  },
  header: {
    searchLabel: 'Cari',
    product: 'produk',
    market: 'pasar',
    information: 'Berita',
    signal: 'Sinyal',
    match: 'Kompetisi ',
    activity: 'Peristiwa',
    broker: 'Brokers',
    more: 'Lebih Banyak ',
    chart: 'Grafik ',
    stockFilter: 'Filter',
    financialCalendar: 'Kalender Finansial',
    toolKit: 'Alat',
    cost: 'harga',
    feature: 'Fitur',
    dataMarket: 'Data Pasar',
    overview: 'Ringkasan',
    myOptional: 'Pilihan Saya',
    news: 'Berita',
    transactionAnalysis: 'Analisis ',
    quickInformation: 'Berita',
    column: 'Kolom',
    answer: 'Q&A dengan Pakar',
    data: 'Data',
    video: 'Video',
    institutionalViewPoint: 'Pendapat Institusi',
    analystViewPoint: 'Pandangan Analis',
    columnTopic: 'Topik kolom',
    columnist: 'Kolumnis',
    dataCenter: 'Pusat Data',
    marketTrend: 'Tren pasar',
    institutionalData: 'Data institusi',
    centralBankInterestRate: 'suku bunga bank sentral',
    macroEconomy: 'MakroEkonomi',
    niuList: 'Top Traders',
    bestNiuer: 'Peringkat Mingguan',
    AISignal: 'Sinyal AI',
    fansActivity: 'Pesta Fans',
    web_ib_seminar: 'Seminar IB ',
    voteActivity: 'Anugerah ',
    web_fans_hongkong: 'Hongkong, China',
    web_fans_hochiminh: 'Vietnam Ho Chi Minh',
    web_fans_dubai: 'Dubai, UAE',
    web_fans_cairo: 'Kairo Mesir',
    web_fans_nigeria: 'Nigeria Lagos',
    business: 'Bisnis',
    recruit: 'Lowongan Kerja ',
    aboutUs: 'Tentang Kami',
    whiteLabel: 'Label Putih',
    dataAPI: 'Data API ',
    webPlugins: 'Plugin Web',
    feedback: 'Masukan',
    helpCenter: 'Pusat Bantuan',
    agreement: 'Ketentuan Pengguna',
    policy: 'Kebijakan Privasi',
    comingSoon: 'Segera Hadir',
    marketPrice: 'Kutipan Harga ',
    calendar: 'Kalender',
    quotation: 'Kutipan Harga ',
    PRO: 'Pro',
    AIRating: 'Peringkat AI',
    latestViewPoints: 'Pendapat Terbaru',
    calendarWallpaper: 'Wallpaper kalender',
    speculativeMood: 'Sentimen',
    hangingOrderPosition: 'Pesanan',
    varietyCorrelation: 'Korelasi aset',
    popularIndex: 'Indikator populer',
    hotTopic: 'topik hangat',
    recentUpdate: 'Update terkini',
    language: 'Bahasa',
    popularSearch: 'Pencarian Populer',
    historySearch: 'Pencarian Terkini\n',
    myCollection: 'Koleksi saya',
    myConcern: 'Fokus saya',
    mySubscription: 'Copy trade saya',
    personalInformation: 'Informasi pribadi',
    memberCenter: 'Pusat anggota',
    accountSetting: 'Setting akun',
    logOut: 'Keluar',
    scanDownload: 'Pindai dan unduh',
    moreInformation: 'Berita dan kutipan harga finansial lebih cepat',
    downloadApp: 'Unduh APP',
    addFBToDesk: 'Tambahkan Fastbull ke desktop',
    loadFromDesk: 'Lain kali Anda dapat mengakses Fastbull langsung dari desktop komputer Anda',
    addToDesk: 'Tambah ke desktop',
    recommendSelfSelection: 'Disarankan',
    waitingForDeal: 'Tertunda',
    inTransaction: 'Dalam transaksi',
    overDeal: 'Ditutup ',
    overdue: 'Kadaluwarsa',
    profitMaking: 'Untung',
    lossMaking: 'Rugi',
    profitLoss: 'Laba rugi',
    financialTools: 'Alat finansial',
    homePage: 'Halaman utama',
    clickLogin: 'Masuk',
    AppDescription: 'Berita dan kutipan harga finansial lebih cepat dan lengkap',
    supportResistance: 'Support dan Resistance',
    copyright: 'Hak Cipta © {x} FastBull Ltd',
    risk: 'Pemberitahuan Risiko',
    riskText1:
      'Berdagang Produk FInansial Seperti Saham, Mata Uang, Komoditas, Kontrak Berjangka, Obligasi, Dana, Atau Kripto Adalah Tindakan Berisiko Tinggi, Termasuk Kehilangan Sebagian Atau Seluruh Investasi Anda, Sehingga Trading Tidak Cocok Untuk Semua Investor.',
    riskText2:
      'Saat Membuat Keputusan Keuangan Apa Pun, Anda Harus Melakukan Pengecekan Anda Sendiri, Menggunakan Penilaian Anda Sendiri, Dan Berkonsultasi Dengan Penasihat Yang Memenuhi Syarat. Konten Situs Web Ini Tidak Ditujukan Kepada Anda, Situasi Keuangan Atau Kebutuhan Anda Juga Tidak Diperhitungkan. Informasi Yang Terdapat Di Situs Web Ini Belum Tentu Tersedia Secara Waktu Nyata, Juga Belum Tentu Akurat. Harga Yang Disediakan Di Situs Ini Mungkin Disediakan Oleh Pembuat Pasar Daripada Bursa. Setiap Trading Atau Keputusan Keuangan Lainnya Yang Anda Buat Sepenuhnya Menjadi Tanggung Jawab Anda Dan Tidak Boleh Bergantung Pada Informasi Apa Pun Yang Disediakan Melalui Website. Kami Tidak Memberikan Jaminan Apa Pun Untuk Informasi Apa Pun Di Website Dan Tidak Bertanggung Jawab Atas Kerugian Transaksi Apa Pun Yang Mungkin Timbul Dari Penggunaan Informasi Apa Pun Di Situs Web.',
    riskText3:
      'Dilarang Menggunakan, Menyimpan, Menggandakan, Menampilkan, Memodifikasi, Menyebarluaskan Atau Mendistribusikan Data Yang Terdapat Dalam Website Ini Tanpa Izin Tertulis Dari Website Ini. Semua Hak Kekayaan Intelektual Dilindungi Oleh Vendor Dan Bursa Yang Menyediakan Data Yang Terdapat Di Situs Web Ini.',
    cookieTips:
      'Kami Menggunakan Cookie Untuk Memahami Cara Anda Menggunakan Website Kami Dan Untuk Meningkatkan Pengalaman Anda, Termasuk Personalisasi Konten. Dengan Terus Menggunakan Situs Kami, Anda Menerima Penggunaan Cookie Kami. Jika Ingin Tahu Lebih Banyak, Silakan Klik Di Sini',
    viewDetail: 'Periksa Detail',
    authorization: 'Setuju ',
    function: 'Fungsi',
    company: 'Perusahaan',
    user: 'Pengguna',
    theLatestValue: 'Nilai Terbaru',
    allSearchResult: 'Lihat semua hasil pencarian',
    loginBtn: 'Masuk',
    signUPBtn: 'Daftar',
    freeToOpenVIP: 'Aktivasi VIP gratis',
    web_opinion_hot_author: 'Penulis Populer',
    market_finance_coverview: 'Ringkasan',
    freeForevet: '',
    moduleDark: '',
    loginForMoreFunc: '',
    noLogin: ''
  },
  sideLayout: {
    news_calendar_filter_only_import: 'Hanya Berita Teratas',
    news_snowfall: 'Tautan Terkait',
    news_unscramble: 'Interpretasi Buletin',
    news_unscramble_long: 'Panjang',
    news_unscramble_short: 'Pendek',
    news_unscramble_bearish: 'Bearish',
    news_unscramble_bullish: 'Bullish',
    calendar_time_up: 'Waktu',
    calendar_prev_up: 'Sblm.',
    calendar_est_up: 'Prediksi',
    calendar_act_up: 'Aktual',
    calendar_unrelease: 'Tidak Diterbitkan',
    calendar_revised: 'Sebelum Koreksi',
    calendar_act: 'Aktual',
    calendar_est: 'Prediksi',
    calendar_prev: 'Sblm.',
    new_share: 'Bagikan',
    vip_invite_friends_immediately: 'Rekomendasi dan dapatkan upgrade gratis ',
    vip_invite_friends_title: 'Bagikan',
    qa_header_title: 'Q&A dengan Pakar',
    qa_header_online: 'Q&A Online ',
    qa_ask_question: 'Saya punya pertanyaan...',
    qa_post_first_question: 'Ajukan pertanyaan pertama',
    qa_expert: 'Pakar',
    qa_view_translation: 'Lihat terjemahan',
    qa_view_original: 'Lihat teks sumber',
    qa_answer: 'Jawab',
    qa_cancel_answer: 'Batalkan Jawaban',
    qa_answer_placeholder: 'Jawab {0}',
    qa_confirm_delete_question: 'Yakin ingin menghapus pertanyaan tersebut?',
    qa_confirm_delete_answer: 'Yakin ingin menghapus jawaban?',
    qa_select_pic_format: 'Pilih format png, jpg, jpeg, gif, bmp, dan webp',
    qa_common_bottom: 'Tidak ada konten',
    qa_remind_max_char: 'Masukkan Maksimal {0} Karakter',
    qa_cancel_reply: 'Hapus balasan',
    qa_reply_someone: 'Balasan {0}',
    quote_nav_more: 'Lebih Banyak',
    quote_link_more: 'lihat lebih banyak',
    quote_table_asset: 'Simbol',
    quote_table_last: 'Harga\t',
    quote_table_netchg: 'Prb.\t',
    quote_table_chg: '%Prb.',
    quote_table_update: 'MEMPERBARUI',
    news_news_trending: 'Populer',
    quote_table_high: 'Tertinggi',
    quote_table_low: 'Terendah',
    quote_watchlist: 'Pilihan',
    quote_my_watchlist: 'Pilihan Saya',
    reminderg: 'Pengaturan Pengingat',
    maincontainer_market: 'Kutipan',
    news_flash: '24x7',
    news_calendar: 'Kalender',
    q_a: 'Jawab',
    home_tab_chat: 'Chat',
    common_side_layout: 'Tata Letak',
    common_layout_single: 'Satu Kolom',
    common_layout_vertical: 'Dua Baris',
    common_layout_tile: 'Dua Kolom',
    cale_unpublish_time: 'Diumumkan pada {0}',
    cale_unpublish_time_h: '{0} jam',
    cale_unpublish_time_min: '{0} menit',
    add_asset_name: 'Tambah nama atau kode aset',
    add_to_favorites: 'Tambah ke pilihan saya ',
    recentlyViewed: '',
    common_market_closed: 'Tutup ',
    chart_indicator: 'Indikator ',
    chart_strategy: 'Strategi',
    chart_edit: 'Editor',
    chart_backtest: 'Backtest',
    chart_order: 'Pesanan Baru',
    chart_template: 'Pola',
    chart_sync: 'Sinkronisasi',
    chart_history: 'Riwayat',
    chart_remind: 'Pengingat',
    chart_log: 'Catatan',
    chart_connect: 'Terhubung ke server, silahkan tunggu....',
    searchStocksTips: 'Tekan tombol apa saja dari A hingga Z atau dari 0 hingga 9 di jendela utama untuk mencari simbol'
  },
  dataCollect: {
    fxchat_login_edit_user_info_title: 'Edit informasi pribadi (1/3)',
    fxchat_login_complete_material_title: 'Lengkapi informasi Anda (2/3)',
    fxchat_login_recommendation_title: 'Rekomendasi kualitas tinggi (3/3)',
    fxchat_information_nick_name: 'nama panggilan',
    fxchat_login_field_title: 'Masukkan nama panggilan',
    fxchat_information_sex: 'sex',
    fxchat_information_sex_man: 'pria',
    fxchat_information_sex_women: 'wanita',
    fxchat_information_sex_other: 'lainnya',
    fxchat_information_sex_secret: 'Rahasia',
    fxchat_material_morning: 'Hai, "{0}" Selamat pagi! Selamat datang di FastBull',
    fxchat_material_noon: 'Hai, "{0}" Selamat siang! Selamat datang di FastBull',
    fxchat_material_afternoon: 'Hai, "{0}" Selamat siang! Selamat datang di FastBull',
    fxchat_material_night: 'Hai, selamat malam "{0}"! Selamat datang di FastBull',
    fxchat_material_introduction:
      'Untuk lebih merekomendasikan Anda konten berkualitas lebih tinggi, harap perkenalkan diri Anda secara singkat.',
    fxchat_recommendation_subtitle: 'Rekomendasi akurat untuk Anda berdasarkan informasi yang Anda pilih.',
    fxchat_material_summarize:
      'Baik! Berdasarkan informasi, kami akan menyesuaikan konten eksklusif dan berkualitas tinggi untuk Anda.',
    fxchat_material_assistant_name: 'robot AI',
    fxchat_material_look: 'Lihat sekarang',
    fxchat_material_reselect: 'Pilih kembali',
    fxchat_recommendation_see_more: 'lihat lebih banyak',
    fxchat_recommendation_open_fxchat: 'Buka FastBull',
    fxchat_recommendation_open_group: 'obrolan grup',
    fxchat_recommendation_open_niu: 'Top Trader',
    fxchat_not_group_introduction: 'Ketua kelompok sangat malas dan belum ada pengenalan kelompok~',
    fxchat_recommendation_join: 'bergabunglah',
    fxchat_recommendation_has_join: 'bergabung',
    fxchat_login_skip: 'Lewati ',
    fxchat_recommendation_follow: 'Ikuti',
    fxchat_recommendation_has_follow: 'Sudah Diikuti',
    fxchat_login_trading_type: 'Pasar trading mana yang lebih Anda minati? (Pilihan ganda)'
  },
  setting: {
    personalData: 'Info Pribadi',
    accountSafety: 'Keamanan Akun',
    informSetting: 'Pengaturan pemberitahuan',
    privacy: 'pribadi',
    blacklist: 'daftar hitam',
    remove: 'Hapus',
    removeSuccess: 'Berhasil dihapus',
    shieldingTime: 'Waktu Blacklist: {x}',
    addStyle: 'Bagaimana cara tambahkan saya sebagai teman',
    allowAll: 'Izinkan siapa pun berteman dengan saya',
    needVerify: 'Perlu verifikasi',
    notAllowAny: 'Tidak seorang pun diizinkan berteman dengan saya ',
    findByPhone: 'Temukan saya melalui no HP ',
    findByPhoneTips: 'Setelah dinon-aktif, pengguna lain tidak dapat menemukan Anda melalui informasi di atas.',
    follow: 'Copy Trade',
    followTips: 'Setelah dinyalakan, informasi copy trade akan ditampilkan secara publik.',
    contest: 'Kontes',
    contestTips: 'Setelah dinyalakan, informasi kompetisi akan ditampilkan secara publik. ',
    emailNotice: 'Preferensi notifikasi email',
    weeklySelection: 'Pilihan Mingguan FastBull',
    willPushNews: 'Kami akan memberi Anda berita utama relevan yang baru-baru ini Anda perhatikan',
    sendWeek: 'Dikirim setiap minggu',
    dailyHighlights: 'Berita pasar utama FastBull hari ini',
    sendDay: 'Dikirim satu kali sehari (Senin-Jumat)',
    baseInfo: 'Informasi dasar',
    nickname: 'nama panggilan',
    joinStyle: 'Cara bergabung dengan grup',
    aphorism: 'Motto Trading ',
    editInfo: 'Edit informasi pribadi',
    interestInfo: 'informasi menarik',
    noAddInterest: 'Belum ada konten menarik yang ditambahkan~',
    dealPlatform: 'platform trading',
    dealMarket: 'pasar ',
    dealVariety: 'Instrumen Asset ',
    dealStyle: 'Gaya',
    avatar: 'Avatar',
    modifyAvatar: 'Edit avatar',
    username: 'Nama pengguna',
    sex: 'Sex ',
    dealAge: 'Tahun Trading ',
    address: 'lokasi',
    industry: 'Industri',
    modify: 'Revisi',
    addIndustry: 'Tambahkan industri',
    userIntro: 'Profil pribadi',
    interestDealInfo: 'Preferensi',
    add: 'Tambahkan',
    sexList: [
      {value: 0, name: 'Pria'},
      {value: 1, name: 'Wanita'},
      {value: 2, name: 'Rahasia'}
    ],
    industryType: 'Jenis industri',
    inIndustry: 'Jenis Sub-Industri ',
    outIndustry: 'Profesi lainnya ',
    interestPlayform: 'Pilih Broker ',
    interestMarket: 'Pilih Pasar ',
    interestStyle: 'Pilih Gaya Trading',
    interestVariety: 'Pilih Aset Trading',
    maxOption: 'Dapat memilih paling banyak {x} item',
    blackTypeList: [
      {value: 1, name: 'Buku Alamat'},
      {value: 2, name: 'Obrolan Grup'}
    ],
    accountInfo: 'Informasi Akun',
    userPassword: 'kata sandi ',
    haveSet: 'Telah diatur',
    isNotSet: 'Belum diatur',
    phoneNumber: 'No HP ',
    notBind: 'Tidak terikat',
    bind: 'Terikat',
    email: 'Alamat Email',
    bindThird: 'Mengikat pihak ketiga',
    unBind: 'Lepas Hubungan',
    bindPhone: 'Hubungkan no HP ',
    changePhone: 'Ubah no HP ',
    inputPhone: 'Masukkan no HP ',
    and: 'Dan',
    inputPhoneTips: 'silahkan masukkan no HP yang benar',
    inputVerifyCode: 'Silakan masukkan kode verifikasi 4 digit',
    oldPhoneNumber: 'No HP asli',
    newPhoneNumber: 'No HP baru',
    bindEmailOpen: 'Ikat email untuk mengaktifkan fungsi login akun',
    bindEmail: 'Ikat email',
    setPassword: 'Atur kata sandi',
    password: 'kata sandi',
    inputPwd: 'Silakan masukkan kata sandi',
    pwdRules: 'Kata sandi memerlukan 6-20 karakter, termasuk minimal 2 jenis angka, huruf, dan simbol.',
    updatePwd: 'ganti kata sandi',
    currentPwd: 'kata sandi saat ini',
    forgetPwd: 'lupa kata sandinya?',
    newPwd: 'kata sandi baru',
    pwdNotSame: 'kata sandi dimasukkan tidak konsisten',
    emailResetPwd:
      'Masukkan alamat email Anda dan kami akan mengirimkan Anda tautan untuk mengatur ulang kata sandi Anda',
    sendResetLink: 'Kirim tautan atur ulang',
    inputEmail: 'Silakan masukkan email Anda',
    inputRightEmail: 'silakan masukkan email valid Anda',
    alreadSendLink: 'Kami telah mengirimi Anda tautan untuk mengatur ulang kata sandi Anda',
    alreadSendTo: 'Kami telah mengirim email ke',
    noGetFindHelp: 'Jika Anda tidak menerima dalam waktu 5 menit, silakan periksa Spam atau minta bantuan',
    findHelp: 'Meminta bantuan',
    getVerifyCode: 'dapatkan kode verifikasi',
    notGet: 'Masih belum menerimanya?',
    resend: 'Kirim ulang email',
    inputCode: 'silakan masukkan kode verifikasi',
    beGetting: 'mengambil...',
    resendAfter: 'Dapat dikirim ulang setelah {x} s',
    selectAvatar: 'Pilih Foto Profil',
    customAvatar: 'Tambah Foto ',
    reUpload: 'Unggah Ulang',
    defaultAvatar: 'Foto Default',
    imgType: 'Hanya format gambar {x} ',
    inputNickname: 'Masukkan Nama Panggilan',
    inputUsername: 'Masukkan Nama Pengguna',
    usernameTips:
      'Nama pengguna berisi huruf kecil, angka, garis bawah, dan titik. Mengubah nama pengguna akan mengubah alamat tautan yg terhubung ke profil Anda.'
  },
  vip: {
    equities: 'hak dan kepentingan',
    detail: 'Detail',
    hasCode: 'Saya memiliki kode penukaran',
    inputCode: 'Silakan masukkan kode penukaran',
    conversion: 'Tukarkan',
    shareGet: 'Bagikan dan dapatkan keanggotaan gratis',
    shareGetYear: 'Bagikan dan dapatkan keanggotaan 1 tahun gratis',
    inviteUser:
      'Pengguna baru yang Anda undang mengklik tautan yang Anda bagikan. Setelah menyelesaikan pendaftaran, akan mendapatkan keanggotaan 1 tahun.',
    scanQRCode: 'Pindai kode QR dengan ponsel',
    shareLink: 'Bagikan tautan untuk mendapatkan keanggotaan',
    recharge: 'Upgrade ke Fastbull Pro',
    agree: 'Saya telah membaca dan setuju',
    agreement: 'Perjanjian Layanan Anggota',
    privilege: 'hak istimewa anggota',
    time: 'waktu',
    duration: 'Dapatkan durasi keanggotaan',
    getMode: 'metode memperoleh',
    status: 'status ',
    redeemRules:
      'Aturan penggunaan kode penukaran :\n1. Kode penukaran yang telah diaktifkan tidak dapat digunakan kembali\n2. Kode penukaran tidak dapat digunakan melebihi masa berlaku',
    privilegeList: [
      {
        id: 1,
        title: 'Pengiriman berita cepat AI',
        desc: 'Pengiriman cepat lebih banyak konten berita pilihan secara real-time'
      },
      {
        id: 2,
        title: 'Lacak lebih banyak aset pasar',
        desc: 'Dan Tambahkan lebih banyak aset opsional dan lacak lebih banyak data pasar secara waktu nyata'
      },
      {
        id: 3,
        title: 'Data makro dan indikator ekonomi yang lebih komprehensif',
        desc: 'Data historis indikator yang lebih komprehensif untuk membantu menganalisis pasar makro'
      }
    ],
    shareTitle: 'Saya telah membuka VIP Super untuk Anda di FastBull, nilai maks 1.648 Yuan. Datang dan dapatkan~'
  },
  promotion: {
    volumnMuteDefault: 'Mode bisu secara default',
    enableVolumn: 'Nyalakan suara',
    kolInterview: 'wawancara KOL',
    userComment: 'Ulasan Pengguna',
    moreFunction: 'Fungsi Lebih Banyak',
    moreFunctionTxt: 'Dapatkan apa saja yang diperlukan selama Trading semuanya di Fastbull. '
  },
  tdk: {
    title: 'FastBull - Berita Dan Kutipan Finansial Yang Lebih Cepat',
    homeTitle: 'FastBull Top Traders: Lacak Trader Paling Menguntungkan',
    homeDesc:
      'FastBull Top Traders memberi peringkat pada trader berdasarkan berbagai faktor, termasuk profitabilitas, stabilitas, dan risiko. Lacak trader yang paling menguntungkan dan pelajari strategi mereka.',
    greatestTitle: 'Pilihan Mingguan FastBull',
    greatestDesc:
      'FastBull memberi peringkat pada investor dan akun setiap minggu berdasarkan untung rugi, EA, pengikut, ukuran posisi, dan tingkat menang.',
    helpTitle: 'Pusat Bantuan - FastBull',
    helpDesc: 'Dapatkan jawaban atas pertanyaan umum dan sumber daya bermanfaat di Pusat Bantuan kami.',
    userTitle: '【{x}】- Profil',
    userDesc:
      'Profil ini adalah jendela menuju dunia 【{x}】. Dari pemikiran berwawasan luas hingga koneksi yang menarik.'
  },
  about: {
    downloadApp: 'Unduh APP',
    aboutFb: 'Tentang FastBull',
    fbExplain:
      'FastBull adalah inovator teknologi di bidang Internet finansial. Kami telah membentuk tim editorial dan terjemahan di banyak wilayah dan akan terus berupaya membangun konten lokal di berbagai negara. Pada saat yang sama, kami memiliki tim R&D dan tim produk. Member tim kami diperlengkapi dengan kemampuan teknis advance, dan akan terus memberikan pengalaman software kelas atas untuk konsumen kami di masa depan.',
    service: 'Layanan Kami',
    product: 'Produk',
    productExplain:
      'Kami telah meluncurkan kalender ekonomi dan fungsi alat, dan fungsi yang lebih hebat segera diluncurkan,seperti : Grafik Super, Penyaring Saham, Data Pasar, dll. Silakan nantikan.',
    signal: 'Sinyal',
    signalExplain:
      'Berita, Top Trader, Pilihan Mingguan, Sinyal Terbaru, dan Kompetisi. Sinyal Trading waktu nyata dari Top Trader tersedia untuk disalin, membuat trading jadi lebih mudah.',
    message: 'Berita',
    messageExplain:
      'Berita, 24/7, Analisis, Kolom, Data, Video, meliputi berita top global, dan pandangan trading dari analis dan institusi. Pada saat yang sama, peristiwa terkini dan data keuangan diperbarui secara waktu nyata 24/7.',
    market: 'Pasar',
    marketExplain:
      'Kami menyediakan informasi tentang pasar valuta asing, komoditas, indeks, saham AS, mata uang digital, CME, dan pasar lainnya. Kedepannya, kami akan terus menyediakan pasar saham global, ETF, obligasi dan kondisi pasar lainnya.',
    business: 'Bisnis',
    businessExplain:
      'Kami menyediakan beberapa layanan pihak ketiga gratis/berbayar, label putih, API data, plug-in web, dan menyediakan dukungan sumber data dan dukungan teknis.',
    course: 'Jalur Pengembangan',
    contact: 'Hubungi Kami',
    partner: 'Mitra',
    email: 'Email',
    feedback: 'Masukan',
    scan: 'Pindai QR ',
    android: 'Android',
    ios: 'iOS',
    downloadTips: 'Diskusikan dan bagikan ide dan opini trading Anda dengan investor global secara waktu nyata. ',
    chat: 'Obrolan Langsung',
    chatExplain: 'Bicara dengan Top Trader Global tentang trading!',
    chart: 'Grafik Sosial',
    chartExplain: 'Analisa pasar, diskusikan trading, berlangganan sinyal',
    realTimeSignal: 'Sinyal Waktu Nyata',
    realTimeSignalExplain: 'Sinyal trading gratis disalin',
    contest: 'Kompetisi Trading',
    contestExplain: 'Panggung terbaik untuk menunjukkan kemampuan trading Anda',
    answer: 'Tanya Jawab Pakar',
    answerExplain: 'Tanyakan pada ahlinya dan dapatkan saran profesional gratis',
    analyse: 'Analisis Trading',
    analyseExplain: 'Pelajari logika trading para ahli investasi',
    calendar: 'Kalender Ekonomi',
    calendarExplain: 'Alat analisa profesional menginterpretasi data ekonomi secara mendalam',
    news: 'Berita Unggulan',
    newsExplain: 'Mengumpulkan pandangan mendalam dari para pakar ekonomi global',
    tools: 'Pembuat Poster',
    toolsExplain: 'Dukung personalisasi di berbagai poster finansial',
    more: 'Lagi',
    moreExplain: 'Unduh FastBull dan rasakan lebih banyak fitur menarik',
    downloadFrom: 'Diunduh dari'
  },
  chat: {
    headTabs: ['Semua', 'ruang obrolan', 'Grup', 'Teman-teman'],
    placeInput: 'Ketik di sini...',
    connecting: 'Menghubungkan ke ruang obrolan'
  }
}
