export default {
  common: {
    confirm: 'sah',
    affirm: 'Sahkan',
    remove: 'padam',
    cancel: 'Batal',
    tips: 'petunjuk',
    finish: 'Selesai',
    know: 'OK',
    time: 'Masa',
    count: '{x} item',
    hand: '{x} lot',
    order: '{x} pesanan',
    score: '{x} mata',
    person: '{x} pengikut',
    times: '{x} kali',
    second: '{x} saat',
    minutes: '{x} minit',
    hour: '{x} jam',
    day: '{x} hari',
    month: '{x} bulan',
    year: '{x} tahun',
    shortsecond: '{x} saat',
    shortminutes: '{x} minit',
    shorthour: '{x} jam',
    shortday: '{x} hari',
    justNow: 'Baru Ini',
    minuteAgo: '{x} minit yang lalu | {x} minit yang lalu',
    hourAgo: '{x} jam yang lalu | {x} jam yang lalu',
    yesterday: 'Semalam {x}',
    beforeYesterday: 'Dua hari lalu {x}',
    yearUnit: 'tahun',
    monthUnit: 'bulan',
    dayUnit: 'Hari',
    hourUnit: 'Jam',
    minutesUnit: 'minit ',
    secondUnit: 'saat ',
    hundredMillion: '',
    trillion: '',
    loading: 'Memuatkan...',
    noMore: 'Tiada lagi data',
    all: 'Semua',
    reset: 'Tetapkan semula',
    unfoldAll: 'Kembangkan semua',
    packUp: 'tutup',
    unfold: 'Besarkan',
    back: 'kembali',
    warning: 'Amaran',
    noData: 'Tiada data',
    imageFormat: 'Hanya format imej JPG, JPEG atau PNG disokong!',
    imageSize: 'Saiz imej tidak boleh melebihi {x} MB',
    shareFb: 'Kongsi FastBull dan dapatkan hak penyalinan selama sebulan',
    noNetLaterTry: 'Anomali rangkaian. Sila cuba sebentar lagi...',
    copy: 'salin',
    copySuccess: 'Pautan disalin',
    appDownload: 'Muat turun APL-FastBull',
    fbDownload: 'Muat turun APL FastBull',
    getSuccess: 'Mendapat akses copy trading selama satu bulan',
    reLogin: 'Log masuk anda telah tamat tempoh. Sila log masuk semula.',
    notFound: 'Maaf, alamat halaman yang anda masuk adalah salah atau halaman tidak wujud',
    returnToLast: 'Kembali',
    returnToHome: 'Halaman Utama',
    forbidden: 'akses dinafikan',
    noAccess:
      'Anda tidak mempunyai kebenaran untuk melihat direktori atau halaman ini menggunakan bukti kelayakan yang anda berikan.',
    serverError: 'ralat',
    tryRefresh: 'Sila muat semula halaman dan cuba lagi',
    operationConfirm: 'sahkan',
    select: 'Pilih',
    download: 'Muat turun',
    close: 'tutup',
    isDelete: 'Dipadamkan',
    noResult: 'Maaf, tiada hasil ditemui',
    tryAgain: 'Anda boleh mencuba kata kunci lain dan cari semula',
    loginInOther:
      'Akaun anda dilog masuk pada penyemak imbas lain. Jika ia tidak dilakukan sendiri, kata laluan mungkin bocor. Sila tukar kata laluan dengan segera.',
    chartLoading: 'Memuatkan carta...',
    custom_service: 'khidmat Pelanggan',
    common_look: 'Semak'
  },
  message: {
    messageCenter: 'Pusat Mesej',
    system: 'Pemberitahuan Komuniti',
    trading: 'isyarat dagangan',
    comment: 'Balasan',
    account: 'Pemberitahuan Akaun',
    answer: 'Q&A Pakar',
    noMoreData: 'Tiada lagi data',
    viewAll: 'Lihat semua',
    noNewMsg: 'Tiada mesej baharu lagi',
    noMessage: 'Tiada mesej',
    systemMsgTypeList: [
      {type: 0, label: 'Semua Kandungan'},
      {type: 1, label: 'Pemberitahuan Komuniti'},
      {type: 3, label: 'Mengikuti Saya'},
      {type: 4, label: 'Ikuti saya'}
    ],
    commentMsgTypeList: [
      {type: 0, label: 'Komen Akaun'},
      {type: 1, label: 'Komen Baru'},
      {type: 2, label: 'komen Video'}
    ],
    accountMsgTypeList: [
      {type: 0, label: 'Semua Kandungan'},
      {type: 1, label: 'Perubahan Akaun'},
      {type: 2, label: 'Kemas kini Ranking'},
      {type: 4, label: 'Laporan trading'}
    ],
    open: 'Buka posisi',
    openTime: 'Waktu buka',
    close: 'Tutup Posisi',
    closeTime: 'Waktu tutup',
    riskWarning: 'Amaran risiko',
    subscribeNotice: 'Pengumuman Salinan',
    clickView: 'Klik untuk melihat',
    allSource: 'Semua sumber',
    replyYou: 'membalas kepada anda',
    answerYou: 'Menjawab soalan anda\r',
    commentAccount: 'mengulas pada akaun dagangan anda',
    commentYou: 'mengulas tentang anda',
    viewDetail: 'semak butiran',
    commentTypeList: ['Ulasan akaun', 'Balasan mesej'],
    reportAccount: 'Melaporkan akaun dagangan anda',
    waitFollow: 'Menunggu',
    followSuccess: 'disalin',
    followFailed: 'Gagal menyalin',
    ignore: 'abaikan',
    tryFollow: 'Cuba menyalin isyarat ini. Sila tunggu...',
    followOrder: 'Menyalin trading',
    followStatus: 'status',
    unit: 'unit',
    noSignal: 'Tiada isyarat dagangan lagi',
    orderId: 'ID copy trade',
    statusList: ['Menunggu', 'Disalin', 'Gagal menyalin', 'Diabaikan'],
    statusTitle: ['Alasan menunggu', 'Ikuti ID pesanan', 'Sebab kegagalan', 'Abaikan sebab'],
    goSetting: 'Pergi ke tetapan',
    viewOrder: 'Lihat Pesanan',
    stopProfit: 'TP',
    stopLoss: 'SL',
    openPrice: 'harga pembukaan',
    closePrice: 'Harga penutup',
    delist: 'Kandungan telah dialih keluar',
    remove: 'Kandungan telah dipadamkan'
  },
  home: {
    actualIntro: 'Akaun Live',
    actual: 'Akaun Live',
    profitIntro: 'Akaun Live yang untung',
    profitAccount: 'Akaun untung',
    lossIntro: 'Akaun Live yang rugi',
    lossAccount: 'Akaun rugi',
    blastingIntro: 'Akaun Live dibubarkan pada masa lalu',
    blastingAccount: 'Akaun dibubarkan',
    allMen: 'Semua Top traders',
    openAccountToDate: 'Sejak pembukaan akaun',
    lastJune: '6 bulan lepas',
    already: 'Pengikut',
    yieldValueChart: 'Carta ROI (TWR).',
    favor: 'Awak juga mungkin menyukai',
    refresh: 'Ubah',
    unlimited: 'Semua',
    rank: 'Kedudukan keseluruhan',
    earnings: 'ROI',
    riskLevel: 'Tahap Risiko',
    broker: 'Broker',
    goodAt: 'Bagus terhadap',
    moreOptions: 'Lagi',
    dealWinRate: 'Kadar Menang',
    ratio: 'Nisbah P/L',
    openTime: 'Tempoh Akaun',
    capital: 'Deposit',
    accountType: 'Jenis Akaun',
    platform: 'Broker',
    clear: 'Jelas',
    noContent: 'Kandungan tidak tersedia',
    noBroker: 'Kandungan tidak tersedia',
    accountRatingRangeList: [
      {value: 1, label: 'Tahap A'},
      {value: 2, label: 'Tahap B'},
      {value: 3, label: 'Tahap C'}
    ],
    twrRangeList: [
      {value: '', label: 'Semua'},
      {value: 2, label: '0%~30%'},
      {value: 3, label: '30%~60%'},
      {value: 4, label: '60%~100%'},
      {value: 5, label: '100%~200%'},
      {value: 6, label: '> 200%'}
    ],
    riskLevelList: [
      {value: 1, label: 'rendah'},
      {value: 2, label: 'sederhana'},
      {value: 3, label: 'tinggi'}
    ],
    winRateRangeList: [
      {value: 0, label: 'Tiada had'},
      {value: 2, label: 'lebih daripada 50%'},
      {value: 3, label: 'lebih daripada 60%'},
      {value: 4, label: 'lebih daripada 70%'},
      {value: 5, label: 'lebih daripada 80%'},
      {value: 6, label: 'lebih daripada 90%'}
    ],
    profitLossRatioRangeList: [
      {value: 0, label: 'Tiada had'},
      {value: 2, label: '0.5 dan ke atas'},
      {value: 3, label: '1.0 dan ke atas'},
      {value: 4, label: '1.5 dan ke atas'},
      {value: 5, label: '2.0 dan ke atas'},
      {value: 6, label: '2.5 dan ke atas'},
      {value: 7, label: '3.0 dan ke atas'}
    ],
    openingTimeRangeList: [
      {value: 0, label: 'Tiada had'},
      {value: 1, label: '≤ 1 bulan'},
      {value: 2, label: '> 1 bulan'},
      {value: 3, label: '> 3 bulan'},
      {value: 4, label: '> 6 bulan'},
      {value: 5, label: '> 12 bulan'}
    ],
    amountOfFundsRangeList: [
      {value: 0, label: 'Tiada had'},
      {value: 1, label: 'bawah 100'},
      {value: 2, label: '100 hingga 1000'},
      {value: 3, label: '1000 hingga 3000'},
      {value: 4, label: '3000 hingga 10,000'},
      {value: 5, label: '10,000 hingga 100,000'},
      {value: 6, label: '100,000 hingga 300,000'},
      {value: 7, label: 'lebih daripada 300,000'}
    ],
    accountTypeList: [
      {value: 1, label: 'Live'},
      {value: 2, label: 'Demo'}
    ],
    orderList: [
      {value: 2, nama: 'Kadar pulangan'},
      {value: 3, nama: 'Pengeluaran maksimum'},
      {value: 4, nama: 'Kadar kemenangan'},
      {value: 5, nama: 'Nisbah untung dan rugi'},
      {value: 6, nama: 'Bilangan pelanggan'}
    ],
    niuTopTypeList: ['Pendapatan Tertinggi', 'trading EA Terbaik', 'Tempahan Terbanyak', 'Kadar Kemenangan Tertinggi'],
    threeMonthData: 'Data untuk 3 bulan yang lalu',
    dataFieldList: [
      'Pur. pendapatan harian',
      'Kadar urus niaga kuantitatif',
      'Pur. volum harian',
      'Kadar menang dagangan'
    ],
    threeMonthEarnings: 'Pendapatan untuk 3 bulan terakhir',
    positionDuration: 'Tempoh pegangan',
    lastThreeMonth: '3 bulan lepas',
    detail: 'Butiran',
    appraise: 'Kedudukan Mingguan',
    nextUpdate: 'Kemas Kini Seterusnya',
    currentStage: 'Kedudukan Semasa',
    stage: 'Isu {x}',
    nobodyOnTheList: 'Tiada kedudukan dalam isu ini',
    ruleContent:
      'Kedudukan pedagang teratas dari segi P/L, EA, bilangan dagangan, dan kadar kemenangan masing-masing dalam 3 bulan terakhir. Akaun menguntungkan dengan rekod dagangan yang cemerlang layak untuk kedudukan mingguan.',
    udpateTime: 'Dikemas kini setiap hari Sabtu pada {x}',
    weeklySelection: 'Pilihan Mingguan',
    totalAccountNum: 'Akaun am',
    echartMeaning: 'Maksud carta',
    transactionSoftwareList: [
      {value: 2, label: 'MT4'},
      {value: 1, label: 'MT5', disabled: true}
    ],
    infiniteTxt: 'Tidak terhad',
    selectBrokerNum: '{x} broker dipilih',
    moreSelect: 'Pelbagai pilihan',
    indexSubTabItem1: 'ROI 60%~100%',
    indexSubTabItem2: 'Risiko rendah',
    indexSubTabItem3: '> 12 bulan',
    indexSubTabItem4: 'Jumlah pembiayaan: USD 10 hingga 10k',
    indexSubTabItem5: 'Kadar kemenangan > 90%',
    indexSubTabItem6: 'Nisbah P/L > 3',
    filterNiuTitle: 'Pilih peniaga teratas',
    selectBrokerTitle: 'Pilih broker',
    allTimePeriod: 'bila-bila masa',
    searchBroker: 'Cari broker',
    KOLInterview: 'Temuduga KOL',
    userEvaluation: 'Ulasan Pengguna',
    interestBroker: 'Broker yang berminat'
  },
  aiRating: {
    gradeTimes: 'Bilangan penilaian AI',
    dataCutOff: 'Data pada {x}',
    gradeModel: 'Model penilaian pelbagai dimensi',
    modelIntro:
      'Sistem penarafan AI menjalankan semakan komprehensif akaun dagangan daripada lima dimensi: untung dan rugi, pesanan, kedudukan, jenis dan gaya, serta menilai prestasi akaun dengan tepat dari segi keuntungan, kestabilan dan risiko.',
    sample: 'Prestasi sampel yang besar',
    sampleIntro:
      'Beribu-ribu akaun dagangan, berpuluh-puluh juta pesanan dagangan, dan keputusan penghakiman yang objektif dan saksama ialah pengesahan terbaik sistem penarafan AI.',
    highAccount: 'Akaun premium',
    highIntro: 'Ia mempunyai keuntungan yang baik dan berprestasi baik dari segi kestabilan dan risiko.',
    profitAccount: 'akaun untung',
    middleAccount: 'Akaun perantaraan',
    middleIntro: 'Ia mempunyai keuntungan tertentu, tetapi perlu diperbaiki dari segi kestabilan dan kawalan risiko.',
    lowAccount: 'Akaun peringkat rendah',
    lowIntro: 'Keuntungan adalah lemah dan datang dengan risiko transaksi yang besar.',
    moreClient: 'Rating lebih tinggi, lebih ramai pelanggan',
    moreIntro:
      'Semakin tinggi rating, semakin kukuh akaun dan semakin besar kemungkinan untuk dilanggan dan diikuti oleh pelanggan. Antara langganan Top Traders sedia ada, akaun yang dilanggan melebihi {x} adalah semua akaun A-level atau lebih tinggi.',
    allUse: 'mereka semua menggunakan',
    yourScore:
      'Sistem penarafan AI memberikan anda skor paling realistik untuk kertas peperiksaan dagangan anda. Datang dan lihat markah anda~',
    profitLoss: 'Untung dan rugi',
    orderForm: 'Pesanan',
    position: 'kedudukan',
    variety: 'Kepelbagaian',
    style: 'gaya'
  },
  account: {
    settingOptions: [
      {value: 1, name: 'Tetapan profil'},
      {value: 2, name: 'Tetapan kebenaran'}
    ],
    deleteAccount: 'Padam akaun',
    sureToDelete: 'Adakah anda pasti mahu memadamkan akaun dagangan ini?',
    deleteMatters: 'Nota: akaun dagangan tidak boleh dipautkan setelah dipadamkan sehingga 7 hari kemudian.',
    confirmDelete: 'sahkan ',
    cancelSubscribeBeforeDel:
      'Akaun ini sedang menyalin {x} akaun isyarat. Jika anda mahu memadamkan akaun ini, sila batalkan salinan ini dahulu.',
    deleteSuccess: '{x} Dipadamkan',
    deleteFailed: '{x} Gagal memadam ',
    settingSaved: 'Tetapan disimpan',
    accountPermission: 'Kebenaran Akaun',
    subscribePermission: 'Kebenaran Penyediaan Isyarat\n',
    accountPrivate:
      'Anda tidak dibenarkan memberikan isyarat kepada pengguna lain.\nUntuk menjual isyarat, tetapkan akses akaun anda kepada "Awam" dan dayakan isyarat memberikan kebenaran',
    commentPermission: 'Kebenaran Komen',
    accountcommentForbid:
      'Akaun ini telah disekat daripada menyiarkan ulasan. Sila hubungi perkhidmatan pelanggan jika anda mempunyai sebarang pertanyaan.',
    positionOrder: 'Buka Pesanan',
    historyOrder: 'Sejarah Pesanan',
    weeklyReport: 'Hantar saya laporan dagangan untuk akaun ini setiap minggu',
    monthlyReport: 'Hantar saya laporan dagangan untuk akaun ini setiap bulan',
    tradingDayReport: 'Laporan Harian',
    tradingWeekReport: 'Laporan Mingguan',
    tradingMonthReport: 'Laporan bulanan',
    linkAbnormal: 'Terputus sambungan',
    linkAbnormalExplain: 'Akaun dagangan terputus sambungan. Tolong jangan tiru.',
    riskAccount: 'Akaun dalam kerugian',
    riskAccountExplain:
      'Akaun dagangan ini mempunyai risiko kerugian yang lebih besar. Sila berhati-hati apabila menyalin dagangan.',
    abnormalAccount: 'Akaun tidak normal',
    abnormalAccountExplain: 'Akaun dagangan ini sedang disahkan. Sila berhati-hati apabila menyalin dagangan.',
    sixMonthEarnings: 'TWR untuk 6 bulan lalu',
    actualAccount: 'Akaun Live',
    virtualAccount: 'Akaun Demo',
    balance: 'Baki akaun',
    netValue: 'Ekuiti',
    maxDrawdown: 'MDD',
    drawdownTips:
      'Pengeluaran maksimum (MDD) merujuk kepada kerugian terbesar (%) sejak pembukaan akaun. Untuk akaun yang baru dipautkan, MDDnya adalah berdasarkan baki.\nSila ambil perhatian bahawa Pedagang Teratas mengira MDD dengan cara yang berbeza daripada MT4 untuk meningkatkan ketepatan, justeru berlaku ketidakkonsistenan. ',
    deposit: 'Deposit',
    withdrawal: 'Mengeluarkan',
    fetch: 'Mengeluarkan',
    save: 'Deposit',
    creditFetch: 'Kredit masuk',
    creditSave: 'Kredit keluar',
    dealAccount: 'Akaun trading',
    dataSynchronizationErr: 'Penyegerakan data gagal, sila semak akaun atau kata laluan anda!',
    notOpen: 'Belum tersedia lagi, sila tunggu',
    signalProvider: 'Menjadi pembekal signal',
    tradingAccountSetting: 'Tetapan akaun dagangan',
    profitLossRatio: 'Nsibah P/L',
    dateOptions: [
      {value: 0, name: 'Semua tempoh masa'},
      {value: 1, name: 'Bulan lepas'},
      {value: 2, name: 'hampir 3 bulan'},
      {value: 3, name: 'hampir 6 bulan'},
      {value: 4, name: 'hampir 12 bulan'}
    ],
    yieldRate: 'TWR',
    totalProfitLoss: 'Jumlah P & L',
    synthesizeRank: 'Kedudukan Keseluruhan',
    rankTips: 'Kedudukan keseluruhan adalah berdasarkan skor agregat akaun langsung',
    synthesizeScore: 'Skor Agregat',
    scoreTips: 'Kadar dan skor akaun pada metrik seperti P/L, bilangan dagangan, saiz kedudukan, instrumen dan gaya.',
    periodList: [
      {value: 1, name: 'Hari'},
      {value: 2, name: 'Minggu'},
      {value: 4, name: 'Bulan'}
    ],
    profitLossTitle: ['P&L Harian', 'P&L Mingguan', 'P&L Bulanan'],
    forbidBroker:
      '\nAkaun dagangan yang dibuka dengan {x} hilang kelayakan daripada memberikan isyarat di Pedagang Teratas dan tidak dibenarkan untuk ditambahkan pada Pedagang Teratas lagi.',
    accountSetting: 'tetapan akaun',
    earningsReport: 'Statistik Pendapatan',
    clickToView: 'Klik bar untuk melihat laporan dagangan',
    openAccountTime: 'Waktu Pembukaan',
    currency: 'Mata wang deposit',
    timeZone: 'Zon waktu dagangan',
    cutOff: 'Data oleh',
    profitLoss: 'P/L',
    handCount: 'Lot',
    orderCount: 'Bilangan Dagangan',
    balanceOptions: [
      {
        value: 1,
        name: 'Asal',
        kandungan:
          'Carta keluk imbangan/ekuiti asal, tetapi terjejas oleh deposit dan pengeluaran, mungkin terdapat jurang. '
      },
      {
        value: 2,
        name: 'Disemak',
        kandungan:
          'Data deposit dan pengeluaran telah disemak untuk menjadikan keluk imbangan/ekuiti lebih berterusan dan lancar, supaya lebih memahami perubahan baki/ekuiti akaun . Kaedah ini tidak menghasilkan herotan.'
      }
    ],
    varietyDistribute: 'Instrumen Kewangan',
    timesOptions: [
      {value: 1, name: 'Saiz Posisi'},
      {value: 2, name: 'Amaun dagangan'}
    ],
    profitDistribute: 'Untung rugi',
    profitDirection: 'Jenis trading',
    incomeOptions: [
      {value: 1, name: 'arah'},
      {value: 2, name: 'P&L'}
    ],
    positionTime: 'Tempoh Pegangan',
    holdOptions: [
      {value: 1, name: 'Posisi'},
      {value: 2, name: 'P/L'}
    ],
    totalAvg: 'Pur. tempoh untuk semua',
    profitAvg: 'Pur. tempoh untuk dagangan untung',
    lossAvg: 'Purata tempoh untuk dagangan kerugian',
    loading: 'Memuatkan',
    promptContent:
      '<p>Tips baik:</p>\n1. Pesanan belum selesai, deposit & pengeluaran telah dikecualikan;<br/>\n2. Semua data dikemas kini pada 08:00 GMT+8 setiap hari;<br/>\n3. Simbol mata wang $ ialah petunjuk data P/L. Mata wang deposit dipaparkan di tempat lain; <br/>\n4. Pengeluaran maksimum yang dikira dalam MT4 adalah tidak sempurna, jadi Pedagang Teratas telah menambah baiknya dan menjadikannya lebih tepat, oleh itu perbezaan antara MT4 dan platform kami;<br/>\n5. Nisbah P/L dan Risiko-ke-pulangan tidak akan melebihi 100.00; TWR tidak akan melebihi 100.00w%.<br/>',
    totalOrder: '{x} berdagang secara keseluruhan, {y} dimuatkan',
    longOrder: 'Dagangan Panjang',
    shortOrder: 'Dagangan Pendek',
    longShort: 'L/S',
    shippingSize: 'Saiz Posisi',
    profitOrder: 'Dagangan Untung',
    lossOrder: 'Dagangan Rugi',
    orderPosition: 'Saiz Posisi',
    orderProfitLoss: 'P/L',
    profitLossTip: 'Swap dan yuran servis dipertimbangkan',
    handCountTip: 'Tidak termasuk pesanan yang belum selesai',
    inventory: 'Yuran Swap',
    procedure: 'Bayaran servis',
    notInclude: 'Tidak termasuk pesanan belum selesai, deposit dan pengeluaran',
    filter: 'Tapis',
    browseTotal: 'Statistik Lawatan',
    subscribeTotal: 'Statistik Pengikut',
    subscribeList: [
      {value: 1, name: 'Pengikut'},
      {value: 2, name: 'lawatan'}
    ],
    totalBrowse: 'Jumlah Lawatan',
    totalSubscribe: 'Pengikut',
    tradingOrderCnt: 'Jumlah Dagangan',
    winRate: 'Kadar Menang',
    tradingHand: 'Lot dagangan',
    orderDistribute: 'Pengagihan trading',
    profitLossDistribute: 'Agihan P/L',
    totalProfitExplain: 'Nota: Bayaran pertukaran dan perkhidmatan telah diambil kira semasa mengira P/L',
    cutDown: 'Kemas Kini Terkini',
    todayRise: 'Bangkit Hari Ini',
    today: 'Hari ini',
    totalEarnings: 'TWR kumulatif',
    earningsTips:
      'TWR kumulatif: Pulangan baki pada penghujung semalam, dikira menggunakan kaedah TWR.\nTWR Mutlak: Jumlah P/L menjelang akhir semalam dibahagikan dengan jumlah amaun deposit (termasuk had kredit) * 100%.',
    absoluteEarnings: 'TWR kekal',
    noStrategy: 'Tiada strategi dagangan untuk akaun ini',
    accountName: 'nama akaun',
    totalDeposit: 'Deposit terkumpul',
    accountNetValue: 'Ekuiti',
    positionProfit: 'P/L Terapung',
    closeProfit: 'Realisasi P/L',
    accountLever: 'Leveraj',
    totalWithdrawal: 'Pengeluaran terkumpul',
    accountBalance: 'Baki',
    credit: 'jumlah kredit',
    dataOverviewExplain: [
      'Jumlah keuntungan dan kerugian semua pesanan ',
      'Bilangan dagangan yang menguntungkan/ bilangan jumlah dagangan',
      'Purata masa pegangan setiap dagangan. ',
      'Perkadaran pesanan menggunakan EA. ',
      'Jumlah semua saiz lot ',
      'Purata. keuntungan semua dagangan yang menguntungkan / purata. kerugian semua dagangan yang rugi. ',
      ' Lot setiap dagangan',
      ' Bilangan dagangan dengan saiz kedudukan yang besar (>15% daripada dana) / bilangan semua dagangan.',
      'Bilangan semua dagangan',
      'Jumlah yuran swap',
      'Jumlah keuntungan / nombor trading yang menguntungkan',
      'Keuntungan trading yang paling menguntungkan',
      'Purata. bilangan dagangan setiap hari',
      'Jumlah yuran perkhidmatan',
      'Jumlah kerugian / bilangan semua dagangan yang rugi',
      'Kehilangan trading kerugian terbesar. '
    ],
    positionDuration: 'Pur. Tempoh Pegangan',
    quantizedRatio: 'EA Trades',
    totalHand: 'Jumlah Lot',
    avgTradingHand: 'Purata lot',
    heavyTradingRatio: 'Saiz Posisi Besar',
    totalOrderCount: 'Jumlah Pesanan',
    totalInterest: 'Jumlah yuran swap',
    avgProfit: 'Purata untung',
    maxProfit: 'Keuntungan Maksimum setiap Dagangan',
    avgDayOrder: 'Dagangan Harian',
    totalProcedure: 'Jumlah komisen',
    avgLoss: 'Purata rugi',
    maxLoss: 'Kerugian Maks setiap Dagangan',
    variety: 'Instrumen',
    type: 'Jenis',
    closeTimeRange: 'Tempoh Penutupan',
    startTime: 'masa mula',
    endTime: 'Masa tamat',
    typeList: [
      {value: -1, name: 'semua'},
      {value: 1, name: 'pesanan pasaran'},
      {value: 2, name: 'pesanan belum selesai'}
    ],
    replenish: [
      {value: 4, name: 'Deposit dan pengeluaran'},
      {value: 8, name: 'jumlah kredit'}
    ],
    period: 'kitaran',
    openTime: 'Waktu buka',
    closeTime: 'Waktu tutup',
    openClosePrice: 'Harga buka/tutup',
    open: 'buka',
    close: 'Tutup',
    openPrice: 'Harga masuk',
    closePrice: 'Harga Tutup',
    stopProfitLoss: 'SL/TP',
    direction: 'Jenis trading',
    notice: 'pengumuman',
    cannotConnect: 'Tidak dapat menyambung ke akaun ini',
    connecting: 'Menyambung ({x}s)',
    reconnectionNow: 'Sambung semula',
    noBindOrPrivate: 'Akaun dagangan telah ditetapkan sebagai peribadi atau dinyahpautkan',
    accountInit: 'Memulakan akaun. Sila tunggu...',
    dataStatistics: 'Statistik',
    tradingOrder: 'Pesanan',
    subscriber: 'Pengikut {0}',
    tradingNotice: 'Pengumuman',
    comment: 'Komen {0}',
    tradingReport: 'Pelaporan {0}',
    connectFail: 'Gagal untuk berhubung',
    connectSuccess: 'Bersambung',
    browseChange: 'Carta trafik menggambarkan populariti akaun.',
    subscribeChange: 'Carta ialah petunjuk populariti dan arah aliran akaun signal.',
    dataOverview: 'Gambaran Keseluruhan Data',
    dataDeneral: 'Pandangan Umum Data',
    importantIndex: 'Petunjuk Utama',
    plAnalysis: 'Analisis P&L',
    incomeStatistics: 'Statistik Keuntungan',
    changeAccount: 'Tukar akaun',
    stopProfit: 'TP',
    stopLoss: 'SL',
    texes: 'Cukai',
    helpYouUndestand: 'Tingkatkan prestasi dagangan anda',
    addAccount: 'Tambah akaun',
    selectTraderBrokers: 'Pilih server ',
    inputAccountNum: 'Sila masukkan 4~16 digit',
    inputAccountPwd: 'masukkan kata laluan 4~32 digit',
    inputAccountExplain: 'Sila perkenalkan secara ringkas strategi dagangan anda, 16~128 aksara',
    accountExplain:
      'Benarkan atau sekat orang luar daripada melihat data dagangan akaun ini. Apabila dilarang, akaun ini tidak akan dipaparkan secara terbuka.',
    positionExplain:
      'Benarkan atau sekat orang luar daripada melihat pesanan dagangan terbuka di bawah akaun ini, tetapi penyalin akaun ini sentiasa boleh melihatnya.',
    historyExplain:
      'Benarkan atau sekat orang luar daripada melihat pesanan dagangan sejarah di bawah akaun ini, tetapi penyalin akaun ini sentiasa boleh melihatnya.',
    commentExplain: 'Benarkan atau sekat orang luar daripada mengulas pada akaun ini.',
    weekReportExplain: 'Benarkan atau sekat daripada menghantar saya laporan dagangan mingguan untuk akaun ini.',
    monthReportExplain: 'Benarkan atau sekat daripada menghantar saya laporan dagangan bulanan untuk akaun ini.'
  },
  dataCenter: {
    market: 'Pasaran',
    report: 'Laporan posisi',
    technical: 'Corak Harga',
    profitAccount: 'Akaun Untung',
    fromYesterday: 'lwn. YTD',
    actualCount: 'Jumlah Akaun Langsung',
    yesterday: 'YTD',
    lossAccount: 'Akaun Kerugian',
    popularBroker: 'Kedudukan Broker Popular',
    popularExplain:
      'Kedudukan adalah berdasarkan bilangan akaun langsung yang dibuka dengan setiap broker; Kadar semakan negatif adalah berdasarkan ulasan pada setiap broker yang disiarkan di bahagian Butiran di Halaman Akaun Dagangan.',
    userSelect: 'Pemilihan Pengguna',
    negativeRate: 'Kadar Semakan Negatif',
    masterPosition: '{x} Jawatan Pakar',
    short: 'Jual',
    long: 'Beli',
    neutral: 'Neutral',
    blastingIntro: 'Akaun langsung yang telah dibubarkan',
    blastingAccount: 'akaun dibubarkan',
    unit: 'unit:',
    accountDistribute: 'Pengagihan akaun',
    accountChange: 'Perubahan Akaun',
    varietyDistribute: 'Pengagihan Instrumen',
    winRateDistribute: 'Agihan Kadar Menang',
    cutOff: 'Tarikh akhir',
    profit: 'keuntungan',
    loss: 'rugi',
    blasting: 'Pembubaran',
    orderForm: 'Pesanan',
    shippingSpace: 'kedudukan',
    accountRatio: 'Perkadaran akaun',
    accountNumber: 'Bilangan akaun',
    profitLossRatio: 'Untung rugi',
    dealStyle: 'Stail Dagangan',
    lossRate: 'Kadar Kerugian',
    dealStyleList: ['trading Jangka Pendek', 'trading Jangka Panjang', 'trading EA', 'trading Emas & Mentah'],
    styleExplainList: [
      'Tempoh pegangan kedudukan pendek, kadar kemenangan dagangan yang tinggi, jumlah pesanan yang banyak, dan amat disayangi oleh pedagang. Walau bagaimanapun, nisbah P/Lnya biasanya rendah, dan ia merupakan strategi keuntungan kecil dan kerugian besar. ',
      'Tempoh pegangan yang berlangsung selama beberapa minggu atau bahkan sebulan, dengan nisbah P/L yang sangat tinggi, dan kekerapan dagangan yang sangat rendah memerlukan pedagang untuk bersabar. ',
      'Ringkaskan pengalaman trading manual sebagai model matematik yang ketat secara logik, dan gunakan pemalam EA untuk menjalankan trading secara automatik mengikut peraturan yang ditetapkan. ',
      'Dua niaga hadapan komoditi yang sangat popular, dengan khalayak yang luas, boleh didagangkan pada banyak perisian dagangan, dan terdapat ramai pakar. '
    ],
    styleAccountRatio: [
      'Kadaran Akaun Jangka Pendek',
      'Kadaran Akaun Jangka Panjang',
      'Kadaran Akaun EA',
      'Kadaran Akaun Emas & Mentah'
    ],
    speculate: 'Sentimen Spekulatif Semasa',
    updateFrequency: 'Dikemas kini setiap 15 minit',
    tradeVariety: 'Instrumen',
    accountCount: 'Akaun Panjang/Pendek',
    accountCountTips: 'Kedudukan bersih semasa ialah bilangan akaun panjang atau pendek.',
    shippingSpaceLabel: 'Kedudukan (lot) panjang/pendek',
    shippingSpaceTips:
      'Jumlah bilangan lot panjang dan bilangan lot pendek dipegang pada masa ini, tidak termasuk pesanan belum selesai.',
    marketEmotion: 'Sentimen (Panjang/Pendek)',
    dealStyleTip: [
      'Bilangan akaun yang mengandungi gaya {x} dibahagikan dengan jumlah bilangan akaun dalam komuniti. ',
      'Bilangan akaun yang memfokuskan pada trading emas atau minyak mentah dibahagikan dengan jumlah bilangan akaun dalam komuniti. '
    ],
    lossRateTip: [
      'Antara akaun yang mengandungi gaya {x}, {y} berada dalam kerugian. ',
      'Antara akaun yang memfokuskan pada trading emas atau minyak mentah, terdapat {y} kerugian. '
    ],
    accountExplain:
      'Mulai {0}({1}), terdapat {2} akaun dagangan {3}, yang mana {4} akaun menanggung kerugian dan {5} akaun membuat keuntungan.',
    orderList: 'Buku pesanan',
    orderListTips:
      'Temui potensi kedudukan sokongan/rintangan dalam pasaran dan fahami kawasan dagangan berintensif harga pasaran',
    positionChange: 'Pemegang jawatan dan perubahan jawatan',
    longAccountNum: 'Bilangan akaun panjang',
    shortAccountNum: 'Bilangan akaun pendek',
    netPosition: 'Kedudukan bersih',
    rise: 'Bullish',
    fall: 'Bearish',
    putOrder: 'pesanan belum selesai',
    position: 'Buka Pesanan',
    marketChange: 'Perubahan pasaran dan kedudukan',
    longCash: 'Kedudukan panjang',
    shortCash: 'Kedudukan pendek',
    closePrice: 'Harga penutup',
    upsAndDowns: 'Kenaikan atau kejatuhan harian',
    newestPrice: 'Harga terkini',
    marketEmotion1: 'Sentimen',
    currentPosition: '{x} pesanan terbuka',
    longOrderCount: '{x} pesanan panjang',
    shortOrderCount: '{x} pesanan ringkas',
    price: 'harga',
    subscribeCnt: 'Salin kuantiti dagangan',
    windVane: 'Trenn',
    allMaster: 'Mereka semua {x} pakar',
    longMaster: 'Pakar trading jangka panjang',
    shortMaster: 'Pakar trading jangka pendek',
    quantizationMaster: 'Pakar trading kuantitatif',
    form: 'Pola',
    name: 'Nama',
    variety: 'Instrumen',
    period: 'Kitaran',
    createTime: 'Masa generasi',
    trend: 'tren',
    dataSupport: 'Dikuasakan oleh data daripada FastBull',
    chartTimeZone: 'zon waktu carta',
    allForm: 'Semua pola',
    allVariety: 'Semua instrumen',
    allPeriod: 'semua kitaran',
    kingList: 'Kedudukan Teratas',
    formDesc1:
      'Corak Hammer ialah corak pembalikan kenaikkan, terutamanya apabila ia berlaku di bahagian bawah aliran menurun. Badannya kecil, tetapi bayang bawahnya panjang (biasanya dua kali lebih panjang daripada badan sebenar). Ia mempunyai sedikit atau tiada bayang atas. Mesti ada penurunan harga (walaupun sedikit penurunan) untuk corak dipanggil tukul. Apabila corak berbentuk serupa berlaku dalam aliran menaik, kami memanggilnya corak lelaki gantung.',
    formDesc2:
      'Hanging Man ialah corak candlestick pembalikan menurun yang muncul pada penghujung aliran menaik. Jika batang lilin seterusnya selepas lelaki tergantung adalah menurun dan ditutup di bawah lelaki tergantung, corak itu dianggap sah dan mempunyai kepentingan menurun. Lebih besar jurang ke bawah antara badan sebenar lelaki tergantung dan batang lilin seterusnya terbuka, lebih besar kemungkinan lelaki tergantung itu menandakan puncak pasaran.',
    formDesc3:
      'Shooting Star ialah corak batang lilin menurun dengan bayang atas yang panjang, badan sebenar kecil yang terletak di hujung bawah, dan sedikit atau tiada bayang bawah. Ia muncul terutamanya pada penghujung ayunan harga menaik, jadi ia mungkin menandakan penghujung daripada peningkatan. Corak ini terbentuk apabila kenaikan harga memacu harga pada bahagian awal sesi dagangan. Tetapi pada penghujung sesi dagangan, penurunan harga telah secara agresif menolak harga ke bawah berhampiran pembukaan (corak ini juga dirujuk sebagai "meteor" kerana ia bertahan untuk masa yang singkat). Apabila corak yang sama berlaku pada penghujung ayunan harga ke bawah, ia dipanggil tukul terbalik).\n',
    formDesc4:
      'Perbezaan antara Inverted Hammer dan Shooting Star ialah Inverted Hammer berlaku di bahagian bawah aliran menurun dan menandakan potensi pembalikan kenaikkan. Dari segi penggunaan, kekuatan pembalikan Inverted Hammer dan Shooting Star tidak sehebat lelaki dan hammer gantung. Oleh itu, apabila menggunakan, adalah lebih baik untuk menggabungkannya dengan candlestick seterusnya dan juga menggunakan kaedah lain untuk melakukan analisis lanjut.',
    formDesc5:
      'Corak engulfing ialah corak dua batang lilin yang boleh menurun atau menaik. Corak engulfing kenaikkan terbentuk dalam ayunan menurun, dan ia terdiri daripada satu batang lilin kenaikkan diikuti dengan batang lilin kenaikkan yang menelannya. Engulfing menurun adalah sebaliknya. Selain itu, bull-engulfing-bull dan bear-engulfing-bear ialah kedua-dua corak biasa yang anda boleh lihat pada carta. Biasanya, yang pertama menunjukkan tekanan belian, manakala yang kedua menunjukkan tekanan jualan. Walau bagaimanapun, peniaga tidak seharusnya menjalankan dagangan terburu-buru semata-mata bergantung pada corak tetapi perlu dianalisis dengan kaedah teknikal yang lain.\n',
    formDesc6:
      'Corak engulfing ialah corak dua batang lilin yang boleh menurun atau menaik. Corak engulfing kenaikkan terbentuk dalam ayunan menurun, dan ia terdiri daripada satu batang lilin menurun diikuti dengan batang lilin kenaikkan yang menenggelamkannya. Penurunan menurun adalah sebaliknya. Selain itu, bull-engulfing-bull dan bear-engulfing-bear ialah kedua-dua corak biasa yang boleh anda lihat pada carta. Biasanya, yang pertama menunjukkan tekanan belian, manakala yang kedua menunjukkan tekanan jualan. Walau bagaimanapun, peniaga tidak seharusnya menjalankan dagangan terburu-buru hanya bergantung pada corak tetapi perlu menganalisis dengan kaedah teknikal yang lain.',
    formDesc7:
      '"Three Black Crows", juga dikenali sebagai " Three Black Soldiers", merujuk kepada tiga batang lilin ke bawah berturut-turut, biasanya sebagai pelopor kepada kejatuhan pasaran. Ia adalah corak yang secara amnya menunjukkan penurunan selanjutnya dalam harga. Manakala " Three Red Soldiers " adalah sebaliknya. Jika Three Red Soldiers berlaku dalam aliran menurun, ia secara amnya merupakan isyarat pembalikan pasaran yang kuat; jika harga pasaran muncul dalam corak Three Red Soldiers selepas tempoh trading sisi yang panjang, dan disertai dengan peningkatan secara beransur-ansur dalam jumlah, ia adalah permulaan kepada permulaan pasaran, yang boleh menyebabkan perhatian yang teliti.\n',
    formDesc8:
      'Three Black Crows juga dipanggil "Three Black Soldiers", yang bermaksud tiga garis negatif ke bawah berturut-turut, yang biasanya merupakan pelopor kepada kejatuhan pasaran. Kemunculan corak garis-K sedemikian secara amnya menunjukkan bahawa harga akan jatuh lebih jauh. Sebaliknya, jika three red soldiers berlaku dalam aliran menurun, ia secara amnya merupakan isyarat pembalikan yang kuat untuk pasaran; jika harga pasaran muncul selepas tempoh pergerakan mengiring yang panjang, corak aliran tiga askar merah akan disertai oleh Peningkatan secara beransur-ansur dalam jumlah dagangan adalah permulaan kepada permulaan pasaran dan boleh membangkitkan perhatian yang teliti.',
    formDesc9:
      'Morning Star ialah bentuk gabungan K-line yang terdiri daripada tiga K-lines. Ia adalah satu bentuk di mana pasaran turun dan berubah. Jika bentuk ini muncul dalam aliran menurun, anda harus memberi perhatian, kerana pada masa ini trend telah menghantar isyarat pembalikan yang agak jelas, yang merupakan peluang pembelian yang sangat baik.',
    formDesc10:
      'Evening star adalah bertentangan dengan bintang pagi dan menandakan pembalikan dalam aliran menaik yang lebih kuat. Jika bentuk gabungan K-line bagi Evening Star muncul dalam aliran menaik, kita harus memberi perhatian kepadanya, kerana pada masa ini aliran telah menghantar isyarat pembalikan yang agak jelas atau isyarat panggil balik jangka pendek hingga sederhana, yang mungkin masa yang sangat baik untuk kita menjual atau Masa untuk mengelakkan jangka pendek dan sederhana.',
    formDesc13:
      'Dark cloud cover, juga dikenali sebagai garis awan gelap, ialah salah satu corak pembalikan teratas yang lebih biasa pada carta garisan K. Bentuk ini terdiri daripada dua garis K, satu yin dan satu yang. Mereka biasanya muncul selepas aliran menaik. Dalam sesetengah kes, ia juga mungkin muncul di bahagian atas julat pelarasan mendatar, yang merupakan isyarat menurun.',
    formDesc14:
      'Lampu pertama terdiri daripada dua batang lilin yang lebih panjang yang bergerak dalam arah yang bertentangan sepenuhnya. Hari sebelumnya adalah garis Yin dan keesokan harinya adalah garis Yang. Keesokan harinya garisan Yang bergap ke bawah dan dibuka lebih rendah, dan harga pembukaan adalah jauh lebih rendah daripada harga penutupan hari sebelumnya; tetapi harga penutupan untuk hari berikutnya adalah lebih tinggi daripada harga penutupan hari sebelumnya, dan harga penutupan garisan Yang masuk jauh ke dalam badan sebenar garisan Yin pertama. Sebahagiannya, ia mencapai sekurang-kurangnya separuh daripada harga hari sebelumnya. entiti garis negatif.',
    formDesc15:
      'Doji ialah garis K dengan hanya garisan bayangan atas dan bawah serta tiada lajur, iaitu harga pembukaan adalah sama dengan harga penutup. Antaranya: semakin panjang garisan bayangan atas, semakin kuat daya jualan; semakin panjang garis bayang yang lebih rendah, semakin kuat daya beli. Jika salib yang lebih jelas muncul pada harga tinggi atau rendah, ini bermakna pasaran berkemungkinan besar. Pembalikan berlaku.',
    formDesc16:
      'Doji ialah garis K dengan hanya garisan bayangan atas dan bawah serta tiada lajur, iaitu harga pembukaan adalah sama dengan harga penutup. Antaranya: semakin panjang garisan bayangan atas, semakin kuat daya jualan; semakin panjang garis bayang yang lebih rendah, semakin kuat daya beli. Jika salib yang lebih jelas muncul pada harga tinggi atau rendah, ini bermakna pasaran berkemungkinan besar. Pembalikan berlaku.',
    formDesc17:
      'Berbanding dengan corak yang menyelubungi, susunan dua garisan K betul-betul terbalik dalam corak harami. Dalam corak yang menyelubungi, terdapat badan sebenar yang panjang di belakangnya, menutupi badan sebenar yang kecil di hadapannya; dalam corak harami, badan sebenar garis K yang terakhir adalah lebih kecil dan terkandung oleh badan sebenar yang lebih panjang sebelumnya. Asal nama bentuk ini juga disebabkan oleh makna "kehamilan". Garis K yang panjang ialah garisan "ibu", dan garisan K kecil ialah garisan "anak", atau garisan "janin", untuk menunjukkan maksud inklusifnya.',
    formDesc18:
      'Berbanding dengan corak yang menyelubungi, susunan dua garisan K betul-betul terbalik dalam corak harami. Dalam corak yang menyelubungi, terdapat badan sebenar yang panjang di belakangnya, menutupi badan sebenar yang kecil di hadapannya; dalam corak harami, badan sebenar garis K yang terakhir adalah lebih kecil dan terkandung oleh badan sebenar yang lebih panjang sebelumnya. Asal nama bentuk ini juga disebabkan oleh makna "kehamilan". Garis K yang panjang ialah garisan "ibu", dan garisan K kecil ialah garisan "anak", atau garisan "janin", untuk menunjukkan maksud inklusifnya.',
    formDesc19:
      'Berbanding dengan corak yang menyelubungi, susunan dua garisan K betul-betul terbalik dalam corak harami. Dalam corak yang menyelubungi, terdapat badan sebenar yang panjang di belakangnya, menutupi badan sebenar yang kecil di hadapannya; dalam corak harami, jasad sebenar garis-K yang terakhir adalah lebih kecil dan disertakan dengan jasad nyata sebelumnya yang lebih panjang (jika garisan kedua Jika garisan K ialah bintang silang, ia dipanggil harami silang). Asal nama bentuk ini juga disebabkan oleh makna "kehamilan". Garis K yang panjang ialah garisan "ibu", dan garisan K kecil ialah garisan "anak", atau garisan "janin", untuk menunjukkan maksud inklusifnya.',
    formDesc20:
      'Berbanding dengan corak yang menyelubungi, susunan dua garisan K betul-betul terbalik dalam corak harami. Dalam corak yang menyelubungi, terdapat badan sebenar yang panjang di belakangnya, menutupi badan sebenar yang kecil di hadapannya; dalam corak harami, jasad sebenar garis-K yang terakhir adalah lebih kecil dan disertakan dengan jasad nyata sebelumnya yang lebih panjang (jika garisan kedua Jika garisan K ialah bintang silang, ia dipanggil harami silang). Asal nama bentuk ini juga disebabkan oleh makna "kehamilan". Garis K yang panjang ialah garisan "ibu", dan garisan K kecil ialah garisan "anak", atau garisan "janin", untuk menunjukkan maksud inklusifnya.',
    traderStyle: 'Stail ',
    winningAccounts: 'Akaun menang',
    losingAccounts: 'Akaun rugi',
    dealLong: 'Beli',
    dealShort: 'Jual',
    sellingPrice: 'Tanya harga',
    buyingPrice: 'Harga bidaan',
    hangingOrderData: 'Data pesanan belum selesai',
    positionOrderData: 'Buka data pesanan',
    periodicalNumber: 'Isu {x}',
    greatestRule: 'Peraturan pemilihan',
    selectTraderStyle: 'Pilih instrumen'
  },
  user: {
    sendMsg: 'Menghantar mesej',
    userId: 'ID Pengguna',
    attention: 'Ikut',
    collect: 'Tambah ke Kegemaran',
    home: 'Halaman Utama',
    contest: 'Peraduan',
    social: 'Sembang',
    vip: 'Ahli',
    setting: 'tetapan',
    about: 'Tentang',
    accountListLen: 'Anda boleh memautkan sehingga {x} akaun dagangan.',
    addAccount: 'Tambah akaun',
    loginRegister: 'Daftar masuk',
    logoutSuccess: 'Anda telah dilog keluar',
    accountLis: 'Senarai Akaun',
    totalAccount: '{x} akaun',
    noBindAccount: 'Tiada akaun dagangan dipautkan',
    unfoldAll: 'Kembangkan Semua',
    foldAll: 'Runtuhkan Semua',
    similarAccount: 'Akaun Sama',
    changeAccount: 'Ubah',
    signaturePlaceholder: 'Tiada kandungan tersedia',
    loginViewOrder: 'Log masuk untuk melihat pesanan terbuka',
    brokerGrade: 'Bagaimanakah kebolehpercayaan broker yang digunakan oleh akaun?',
    soldOut:
      'Adalah disyorkan bahawa FastBull Top Traders mengalih keluar broker ini dan tidak lagi menyokong pemautan akaun broker ini.',
    accountReport: 'Pelaporan trading Penipuan',
    suspects: 'Sila maklumkan sebarang aktiviti mencurigakan akaun dagangan.',
    reliable: 'Sangat Dipercayai',
    unreliable: 'Tidak Dipercayai',
    suggestSoldOut: 'Syorkan untuk Alih Keluar',
    reportSuccess: 'Dilaporkan!',
    emoji: 'Emoji',
    picture: 'gambar',
    uploadFailed: 'Muat naik imej gagal',
    submitAfterUpload: 'Sila muat naik imej dahulu',
    addPicture: 'tambah gambar',
    btnTextList: ['Ulasan', 'Balas', 'Sahkan laporan'],
    praise: 'Thumbs Up',
    reply: 'balas',
    writeYourComment: 'Sila masukkan balasan anda...',
    moreReply: 'Lagi balasan',
    residueReplay: '{x} balasan yang tinggal',
    account: 'Akaun',
    grade: 'Penilaian',
    subscribe: 'Salinan',
    accountPraise: 'Reputasi ',
    accountComment: 'Komen',
    allComment: 'Semua komen',
    needComment: 'Masukkan ulasan anda (komen tidak boleh diubah suai atau dipadamkan. Sila komen dengan betul).',
    excellent: 'Baik',
    ordinary: 'normal',
    noGood: 'buruk',
    commentSuccess: 'Diulas!',
    replySuccess: 'Dibalas!',
    inputNotice: 'Sila masukkan kandungan pengumuman',
    allowNoticeCount: 'Sila masukkan announcemSehingga {x} pengumuman yang dibenarkan setiap hari',
    totalCount: 'Jumlah {x} pengumuman',
    publish: 'Terbitkan',
    publishSuccess: 'Pengumuman diterbitkan kandungan!',
    isDeleteNotice: 'Padamkan pengumuman?',
    deleteNotice: 'Padamkan ',
    closeComment: 'Anda tidak dibenarkan menyiarkan ulasan pada akaun ini',
    privateComment: 'Akaun ini boleh dilihat oleh pemilik sahaja. Anda tidak dibenarkan menyiarkan ulasan.',
    privateReport: 'Akaun ini boleh dilihat oleh pemilik sahaja. Anda tidak dibenarkan melaporkan akaun ini',
    length1: 'Sila masukkan sekurang-kurangnya 1 aksara.',
    length512: 'Anda hanya boleh memasukkan sehingga 512 aksara',
    noAccount: 'Tiada akaun dagangan lagi',
    tradingPlatform: 'Perisian trading',
    broker: 'Broker',
    brokerServer: 'Server',
    dealAccountNum: 'Akaun',
    tradingPassword: 'Kata Laluan Utama',
    passwordExplain: 'Jika anda tidak copy trade, anda boleh memasukkan kata laluan pelabur.',
    inputPassword: 'Sila masukkan kata laluan utama',
    tradingStrategy: 'Strategi trading',
    strategyExplain: 'Sila perkenalkan strategi dagangan anda.',
    passwordLength: 'Kata laluan induk memerlukan 4-32 aksara',
    strategyLength: 'Sekurang-kurangnya 16 aksara diperlukan',
    searchName: 'Cari nama broker atau pelayan',
    record: 'Sejarah carian',
    hotSearch: 'Carian Popular',
    result: 'Keputusan Carian',
    inputAccount: 'Sila masukkan nombor akaun',
    inVerification: 'Pengesahan akaun sedang dijalankan...',
    accountLength: 'Nombor akaun dagangan memerlukan 4-16 digit',
    bindOvertime: 'Memautkan Tamat Masa Akaun',
    addTradingAccount: 'Tambah akaun',
    linkAccount: 'Pautkan Akaun',
    accountSetting: 'Tetapan Akaun',
    otherBind: 'Akaun terjejas.',
    howToFind: 'Bagaimana untuk pulihkan?',
    findAccount: 'Pulihkan akaun anda.',
    stepTitle: 'Cara memulihkan akaun:',
    findStep1: '1. Log masuk ke MT4/MT5 menggunakan kata laluan induk anda.',
    findStep2: '2. Tukar kata laluan utama atau pelabur.',
    findStep3: '3. Tambah akaun dagangan anda sekali lagi di Pedagang Teratas',
    addSuccess: 'Berjaya ditambahkan',
    initExplain: 'Akaun boleh digunakan selepas permulaan data, yang mungkin mengambil masa kira-kira 3 minit.',
    bindNow: 'Pautan Sekarang',
    brokerBan: 'Broker telah dilarangkan',
    accountRate:
      'Baik: Keupayaan trading yang kukuh\nPurata: Keupayaan trading purata\nLemah: Keupayaan dagangan yang lemah',
    accountReportTips:
      '\nPedagang Teratas FastBull akan menghubungi broker yang digunakan dan mengesahkan data jika akaun dagangan dilaporkan berulang kali.',
    accountList: 'Senarai akaun',
    conversionRate: 'Kadar penukaran',
    nowDay: 'hari itu',
    lastSevenDay: '7 hari lepas',
    yesterday: 'semalam',
    notice: 'pengumuman',
    edit: 'edit',
    totalYieldRate: 'Kadar pulangan terkumpul',
    bindAccountTips: 'Tiada akaun dagangan lagi. Tambah sekarang~',
    subscribeTips: 'Ikut isyarat dagangan, melabur dengan pedagang terkemuka',
    toSubscribe: 'Pergi ke Salin',
    contesting: 'bertanding',
    season: '{x} Musim',
    rank: 'Kedudukan',
    chatroom: 'bilik sembang',
    friend: 'kawan-kawan',
    groupChat: 'Kumpulan',
    topic: 'topik',
    writer: 'penulis',
    news: 'berita',
    video: 'video',
    pictureVideo: 'Imej & Video',
    file: 'dokumen',
    audio: 'suara',
    chatRecord: 'rekod sembang',
    followed: 'Mengikuti',
    fans: 'Peminat',
    article: 'artikel',
    cancelCollect: 'Alih keluar',
    simulationGroup: 'Akaun Demo',
    actualGroup: 'Akaun Live',
    contestData: 'Data Peraduan',
    awardsCount: 'Awards',
    totalAward: 'Jumlah keseluruhan',
    topScore: 'Markah Tertinggi',
    megagameRecord: 'Rekod Peraduan',
    entryAccount: 'Akaun penyertaan',
    score: 'Skor ',
    ranking: 'Kedudukan',
    awards: 'Hadiah',
    extraAward: 'Bonus Tambahan',
    auditStatus: 'Status',
    status: ['Diluluskan', 'Ditolak', 'Menyemak'],
    noRecord: 'Rekod tidak tersedia',
    socialGroup2: 'Kumpulan yang saya urus ({x})',
    socialGroup3: 'Kumpulan yang saya sertai ({x})',
    comeFrom: 'Daripada: {x}',
    socialGroup1: 'Kumpulan yang saya cipta ({x})',
    nextStep: 'Seterusnya',
    selectBrokers: 'Pilih server',
    bindSuccess: 'Dipautkan',
    goFollowOrder: 'Pergi ke Salin',
    accountDetail: 'Butiran Akaun',
    bindAgain: 'Cuba lagi',
    traderAccount: 'Akaun trading',
    traderLever: 'Leveraj',
    subscribeNum: 'Pengikut {0}',
    depositCurrency: 'Mata wang deposit',
    accountName: 'nama akaun',
    withoutSignature: 'Tiada set moto trading',
    fastbullVIP: 'Ahli FastBull',
    openVipForFree: 'Keahlian Percuma',
    logout: 'log keluar',
    shareFB: 'Kongsi Fastbull',
    copyLink: 'Salin pautan',
    addFriend: 'Tambah rakan',
    addFriendVerify: 'Pengesahan',
    waitVerify: 'Menunggu pengesahan',
    added: 'Ditambah',
    defaultVerify: 'saya {x}',
    inputVerifyInfo: 'Sila masukkan maklumat pengesahan:',
    addSuccessTip:
      'Permintaan untuk menambah rakan telah berjaya dihantar dan sedang menunggu pengesahan daripada pihak lain.',
    send: 'hantar',
    sendApplySuccess: 'Permohonan berjaya dihantar',
    cancelAttentionConfirm: 'Adakah anda pasti anda tidak mahu mengikuti pengguna ini lagi?',
    userCenter: 'Pusat Peribadi',
    openFBAPP: 'Buka APL',
    supportNewsPrice: 'Menyediakan berita dan sebut harga kewangan yang lebih pantas dan lengkap',
    noCollect: 'Tiada kegemaran ditambah lagi',
    accountPwd: 'Kata laluan',
    fxchat_niu_trading_select: 'Pilih',
    fxchat_niu_trading_select_first: 'Sila pilih broker dahulu',
    fxchat_niu_trading_server_select: 'Pilih',
    fxchat_niu_account_input_hint: '4-16 digit',
    fxchat_niu_observe_account_input_hint: '4-32 aksara',
    fxchat_niu_observe_password_tip: 'Jika anda tidak copy trade, anda boleh memasukkan kata laluan pelabur.',
    fxchat_niu_trading_strategy_hint: 'Perkenalkan strategi dagangan anda dalam 16 ~128 aksara.',
    fxchat_niu_account_bind: 'Akaun terjejas,',
    commentAfterLogin: 'Sila {x} dahulu sebelum menyiarkan ulasan',
    noBodyAdd: 'Permintaan rakan gagal. Pengguna yang didayakan Tiada Siapa boleh menghantar permintaannya.'
  },
  grade: {
    synthesizeGrade: 'Kedudukan keseluruhan',
    gradeTips:
      'Penarafan komprehensif adalah berdasarkan data transaksi selama enam bulan yang lalu dan dikemas kini sekali sehari.',
    tradeAbility: 'Kebolehan berdagang',
    goodAtVariety: 'Fokus pada',
    riskLevel: 'Tahap risiko',
    maxDrawdown: 'keluaran maks.',
    viewGradeReport: 'Lihat laporan penilaian komprehensif',
    rank: '{x} dalam kedudukan keseluruhan',
    score: 'Skor agregat {x} mata',
    tradeAbilityList: ['Cemerlang', 'Sangat baik', 'Baik', 'Sederhana', 'Lemah', 'Teruk'],
    riskLevelList: ['Risiko rendah', 'Risiko sederhana', 'Risiko tinggi'],
    profitAndLoss: 'Akaun P/L',
    orderControl: 'Kawalan pesanan',
    varietyData: 'Data instrumen',
    dealStyle: 'Gaya dagangan',
    dealPosition: 'Data kedudukan',
    gradeStr: ['Cemerlang', 'Baik', 'Sederhana', 'Lemah'],
    gradeScore: 'Skor penilaian',
    scoreTooltip:
      'A+ (melebihi 90 mata), keupayaan trading yang sangat baik! <br/>A (85 mata atau ke atas), keupayaan dagangan yang sangat baik! <br/> B+ (melebihi 80 mata), keupayaan trading yang baik! <br/> B (75 mata atau ke atas), keupayaan dagangan purata! <br/> C+ (melebihi 60 mata), keupayaan dagangan yang lemah! <br/> C (kurang daripada 60 mata), keupayaan dagangan yang teruk!',
    tradeGrade: 'Penilaian Dagangan',
    gradeExplain:
      'Penilaian komprehensif adalah berdasarkan hasil penilaian selama enam bulan yang lalu dan maklumat penilaian dikemas kini sekali sehari.',
    yieldRateTooltip: 'Kadar pulangan baki dalam tempoh yang ditentukan, dikira menggunakan algoritma TWR.',
    maxDrawdownTooltip:
      'Penurunan terbesar dalam nilai bersih (jika tiada data nilai bersih, data baki akan digunakan sebaliknya) dalam tempoh tertentu. Disebabkan oleh kesan deposit dan pengeluaran, nilai ini mungkin melebihi 100%.',
    yieldRiskRatioTooltip:
      'Pengeluaran TWR/Maks. Apabila TWR kurang daripada atau sama dengan 0, nisbah risiko pulangan ditetapkan kepada 0. Apabila pengeluaran maksimum ialah 0, nisbah risiko pulangan ditetapkan kepada 100.',
    yieldRiskRatio: 'Nisbah Risiko Pulangan',
    orderTotalTooltip: 'Bilangan pesanan dalam tempoh yang ditetapkan.',
    orderTotal: 'Jumlah bilangan pesanan',
    dealFrequencyTooltip: 'Purata bilangan pesanan yang didagangkan setiap hari dalam tempoh yang dinyatakan.',
    dealFrequency: 'Kekerapan dagangan',
    frequencyUnit: '{x} pesanan/hari',
    stopProfitRateTooltip:
      'Perkadaran pesanan dengan ambil untung atau henti rugi antara pesanan dalam tempoh yang ditetapkan.',
    stopProfitRate: 'Kadar TP & SL',
    varietyFreight: 'Instrumen & kedudukan',
    heavyRatioTooltip:
      'Antara pesanan dalam tempoh tertentu, perkadaran pesanan dengan kedudukan berat (pesanan yang menduduki lebih daripada 15% dana).',
    heavyRatio: 'Nisbah kedudukan besar',
    focusVarietyTooltip: 'Bilangan instrumen kewangan yang kerap didagangkan dalam tempoh tertentu.',
    focusVariety: 'Instrumen',
    profitLossRatioTooltip:
      'Nisbah keuntungan purata pesanan yang menguntungkan kepada purata kerugian pesanan kerugian antara pesanan dalam tempoh tertentu. Apabila purata kerugian ialah 0, nisbah P/L ialah 100.',
    profitLossRatio: 'Nisbah P/L',
    dealStyleTooltip: 'Gaya dagangan dalam tempoh masa tertentu.',
    profitPositionTooltip:
      'Tempoh pegangan purata pesanan yang menguntungkan antara pesanan dalam tempoh yang ditetapkan.',
    profitPosition: 'Kedudukan purata pesanan yang menguntungkan',
    lossPositionTooltip: 'Purata tempoh pegangan pesanan kerugian antara pesanan dalam tempoh yang ditetapkan.',
    lossPosition: 'Kedudukan purata kehilangan pesanan',
    gradeResult: 'Keputusan penarafan adalah untuk rujukan sahaja dan tidak membentuk sebarang nasihat pelaburan.',
    general: 'Gambaran keseluruhan',
    evaluateList: [
      `Jumlah pesanan terlalu kecil untuk dinilai dengan tepat`,
      `Ceriakan diri anda dan belayar melawan arus. Jika anda tidak maju, anda akan berundur`,
      `Kebolehan profesional perlu dipertingkatkan`,
      `Anda boleh pergi lebih jauh, jangan dipermainkan untuk mamat`,
      `Prestasi anda hebat, teruskan usaha`,
      'Anda mesti menjadi peniaga terkemuka',
      'trading yang mengagumkan'
    ],
    profitAbility: {
      worst: 'Keuntungan adalah sangat miskin',
      veryBad: 'Keuntungan adalah sangat miskin',
      bad: 'Keuntungan adalah miskin',
      needToImprove: 'Keuntungan perlu dipertingkatkan',
      common: 'Keuntungan adalah purata',
      strong: 'Keuntungan adalah kuat',
      stronger: 'Keuntungan adalah sangat kuat',
      strongest: 'Keuntungan sangat kuat'
    },
    earnings: {
      veryInstability: 'Pendapatan sangat tidak stabil. ',
      instability: 'Pendapatan tidak stabil. ',
      stabilize: 'Pendapatan agak stabil. ',
      veryStabilize: 'Pendapatan sangat stabil. ',
      mostStabilize: 'Pendapatan sangat stabil. '
    },
    dealRisk: {
      lowest: 'Risiko dagangan adalah sangat rendah',
      smaller: 'Risiko dagangan adalah rendah',
      controlled: 'Risiko dagangan boleh dikawal',
      high: 'Risiko dagangan adalah tinggi',
      higher: 'Risiko dagangan adalah sangat tinggi',
      gigantic: 'Risiko dagangan adalah besar'
    },
    earningsRiskRatio: {
      worst: 'Nisbah pulangan kepada risiko adalah sangat rendah. ',
      veryBad: 'Nisbah pulangan kepada risiko adalah sangat rendah. ',
      needToImprove: 'Nisbah pulangan kepada risiko perlu diperbaiki. ',
      rasional: 'Nisbah pulangan kepada risiko adalah munasabah. ',
      good: 'Nisbah pulangan kepada risiko adalah tinggi. ',
      veryGood: 'Nisbah pulangan kepada risiko adalah sangat tinggi. '
    },
    avgDailyYield: 'Purata akaun perubahan harian {x}',
    avgWeekYield: 'Purata baki mingguan akaun {x}',
    avgMonthYield: 'Purata baki bulanan akaun {x}',
    dayProfit: 'Kebarangkalian keuntungan harian ialah {x}',
    monthProfit: 'Kebarangkalian keuntungan bulanan ialah {x}',
    maxDrawdownIs: 'Dan pengeluaran maksimum ialah {x}',
    earningsRiskValue: 'Nisbah pulangan kepada risiko ialah {x}',
    dealFrequencyExplain: [
      'Kekerapan dagangan dikawal dengan baik. Mohon terus mengekalkannya. Lagipun, lebih banyak anda lakukan, lebih besar peluang untuk membuat kesilapan. ',
      'Kekerapan transaksi berada pada bahagian yang tinggi. Mengurangkan kekerapan transaksi dengan sewajarnya akan membantu mengawal risiko dengan lebih baik. '
    ],
    stopExplain: [
      'Disebabkan kadar tetapan ambil untung atau henti rugi yang rendah, mungkin terdapat risiko dagangan tertentu. ',
      'Matlamat trading tidak begitu jelas. Menggunakan henti untung atau henti rugi boleh mengurangkan risiko dagangan ke tahap tertentu. ',
      'Objektif dagangan biasanya agak jelas. Anda perlu berhati-hati apabila masuk dan keluar pasaran, dan jangan melawan pertempuran yang tidak menentu. ',
      'Matlamat dagangan yang jelas dan tabiat dagangan yang baik. '
    ],
    accumulativeDeal: 'Dagangan kumulatif selama {x} hari',
    avgOrder: 'Purata {x} pesanan setiap hari',
    stopPercent: 'Ambil untung dan henti rugi ditetapkan untuk pesanan {x}.',
    heavyExplain: [
      'Mempunyai kesedaran yang baik tentang kawalan risiko kedudukan, dan kawalan kedudukan keseluruhan adalah agak munasabah. ',
      'Sesekali menjalankan trading berat. ',
      'Pastikan anda melakukan kerja yang baik dalam kawalan risiko apabila menjalankan dagangan berat dari semasa ke semasa. ',
      'Berdagang dengan kedudukan berat terlalu kerap boleh mengakibatkan risiko transaksi yang sangat tinggi. Sila berhati-hati. '
    ],
    heavyPercent: 'Di antara pesanan {x}, kedudukan besar menyumbang {y}',
    suggestion:
      'Adalah disyorkan untuk membawa henti untung dan henti rugi untuk semua pesanan gudang berat, meninggalkan mentaliti perjudian, dan melakukan kerja yang baik dalam kawalan risiko.',
    noFocus:
      'Tiada instrumen kewangan khas yang anda mahir. Adalah disyorkan untuk memberi tumpuan kepada satu atau dua instrumen, yang mungkin meningkatkan keupayaan dagangan anda dengan lebih baik.',
    focusVarietyAt: 'Instrumen yang difokuskan ialah {x},',
    focusCount: 'Fokus pada instrumen {x} {y},',
    profitLossStr:
      'P/L terkumpul pada instrumen ini ialah {x}, dan kami masih perlu terus bekerja keras untuk menjadikannya lebih baik.',
    profitLossTotal: 'Jumlah keuntungan dan kerugian mereka ialah {x}, teruskan.',
    goodAtStr: 'Terbaik pada {x}, keuntungannya merangkumi {y} daripada jumlah keuntungan, terus bekerja keras.',
    tradingStyle: [
      'trading intrahari',
      'trading jangka pendek',
      'trading jangka panjang',
      'trading kuantitatif',
      'Tiada gaya dagangan'
    ],
    tradingType: ['Intraday', 'Short-term', 'Long-term', 'Quantitative'],
    winAndRatio: 'Kadar kemenangan {x} adalah sekitar {y} dan nisbah P/L adalah sekitar {z}.',
    beGoodAt: 'Pandai {x}',
    noTradingStyle:
      'Tiada gaya dagangan yang jelas. Kadar kemenangan pesanan jangka pendek ialah {x} dan kadar kemenangan pesanan jangka panjang ialah {y}.',
    avgPosition:
      'Jumlah purata panjang kedudukan ialah {x}, purata keuntungan pesanan untung ialah {y}, dan purata kerugian pesanan kerugian ialah {z}.',
    joinAndRate: 'Sertai Top Trader\nuntuk menilai keupayaan dagangan anda',
    rated: '{x} akaun dagangan telah dinilai, dengan purata skor {y}',
    rateNow: 'Nilai sekarang',
    isTheRating: 'Penilaian AI sedang menilai anda. Sila tunggu...',
    scoreTips:
      'Skor komprehensif juga termasuk tiga mata tambahan, yang digunakan untuk mengukur prestasi akaun dagangan dari segi penilaian pengguna, pesanan arah aliran balas dan kitaran kelangsungan hidup. <br/>Mata tambahan untuk mulut ke mulut: {x} mata<br/>Mata tambahan untuk kedudukan: {y} mata<br/>Mata tambahan untuk tempoh: {z} mata',
    warmPrompt: 'Tips Baik',
    traderForShort: 'trading jangka pendek',
    traderForLong: 'trading jangka panjang',
    traderForQuantification: 'trading kuantitatif',
    traderForGold: 'trading emas & minyak mentah',
    traderForShortTip: 'Pengenalan kepada trading jangka pendek',
    traderForLongTip: 'Pengenalan kepada trading jangka panjang',
    traderForQuantificationTip: 'Pengenalan kepada trading kuantitatif',
    traderForGoldTip: 'Pengenalan kepada trading emas & minyak mentah',
    goldMaster: 'Pakar emas & minyak mentah'
  },
  subscribe: {
    openSubscribe: 'Kebenaran untuk memberikan isyarat',
    connectionNormal: 'Akaun dalam sambungan biasa',
    accountIsReal: 'Ia adalah akaun langsung',
    notAbnormal: 'Tidak dilabelkan sebagai tidak normal',
    brokerCompliance: 'Berdagang dengan broker yang dikawal selia',
    equityMoreThan: 'Ekuiti hendaklah lebih daripada $1,000.00',
    openNow: 'Dayakan Sekarang',
    openSuccess: 'Salin kebenaran trading didayakan',
    disqualification: 'Akaun ini tidak layak untuk memberikan isyarat',
    openCondition: 'Pembekal isyarat harus memenuhi keperluan berikut:',
    closeSubscribe: 'Lumpuhkan isyarat memberikan kebenaran',
    closeSubscribeConfirm: 'Adakah anda pasti mahu melumpuhkan isyarat yang memberikan kebenaran?',
    closePunishmentExplain:
      'Anda mempunyai {x} pengikut di bawah akaun ini. Anda akan dihukum jika isyarat yang memberikan kebenaran dilumpuhkan untuk akaun:',
    punishment: 'Akaun dagangan akan dilarang daripada memberikan isyarat selama 90 hari.',
    consider: 'Batal',
    closeNow: 'sahkan',
    closeSuccess: 'Isyarat memberikan kebenaran dilumpuhkan',
    lengthen: 'Panjangkan Langganan',
    follow: 'Salinan',
    selectAccount: 'Pilih Akaun',
    alreadyFollow: 'Akaun dalam Salinan',
    followDays: 'Menyalin selama {x} hari, akan tiba pada {y}',
    notFollow: 'Akaun Tiada dalam Salinan',
    accountIsDelete: 'Akaun penyalinan telah dipadamkan.',
    accountDelete: 'Akaun isyarat telah dipadamkan',
    subscribeForbid: 'Akaun ini telah disekat daripada memberikan isyarat',
    subscribeClose: 'Akaun ini belum mendayakan perkhidmatan penyediaan isyarat',
    closeAfterExpire: 'Akaun ini tidak membenarkan peniaga menyalin',
    followAccountOffline:
      'Akaun dagangan anda <span>#{x}</span> telah diputuskan sambungan dan tidak tersedia buat sementara waktu. Jika kata laluan sambungan akaun ini telah ditukar, sila <a target="_blank" href="{y}"> pergi ke halaman tetapan akaun </a> untuk mengemas kini kata laluan sambungan.',
    brokerForbid:
      'Pedagang Teratas tidak menyokong {x}, oleh itu semua akaun dagangan yang dibuka dengannya tidak akan dibenarkan untuk menyalin dagangan.',
    fictitiousTradesTips:
      'Disebabkan potensi fabrikasi data dagangan, akaun ini tidak dibenarkan untuk memberikan isyarat',
    violateRuleTips:
      'Anda tidak dibenarkan menyalin sebarang dagangan di Pedagang Teratas kerana melanggar peraturan komuniti kami. Sila hubungi perkhidmatan pelanggan jika anda mempunyai sebarang pertanyaan.',
    limitationUser: 'pengguna terhad',
    subscribeWarning: 'Amaran',
    riskAccountTips: 'Akaun ini mungkin melibatkan risiko kerugian yang lebih besar',
    userAbnormalTips: 'Pengguna kepunyaan akaun ini adalah tidak normal, sila ikuti pesanan dengan berhati-hati.',
    noCanFollow: 'Pada masa ini tiada akaun berikut.',
    noAccount: '\nAnda belum mengikat akaun dagangan anda lagi,',
    accountOffline:
      'Akaun ini adalah milik pengguna dengan status tidak normal. PAkaun ini telah diputuskan sambungan dan tidak tersedia buat sementara waktu.',
    brokerLimit: 'Broker Terhad',
    accountFollowTips:
      "Anda tidak boleh menyalin dagangan kerana anda menggunakan kata laluan pelabur untuk akaun anda <span>#{x}</span>. <br/>\nAnda perlu <a target='_blank' href='{y}'> pergi ke tetapan akaun </a> dan kemas kini <span> kata laluan induk </span>.pajakan salin dagangan dengan berhati-hati.",
    dealLimit: '',
    forbidSubscribe: 'Pada masa ini tiada akaun untuk disalin.',
    followSuccess: '\nAnda belum memautkan akaun dagangan anda lagi,',
    followSetting: 'Akaun ini telah diputuskan sambungan dan tidak tersedia buat sementara waktu.',
    subscriber: '',
    subscribeTypeList: 'Broker Terhad',
    params:
      "Anda tidak boleh menyalin dagangan kerana anda menggunakan kata laluan pelabur untuk akaun anda <span>#{x}</span>. <br/>\nAnda perlu <a target='_blank' href='{y}'> pergi ke tetapan akaun </a> dan kemas kini <span> kata laluan induk </span>.",
    subscribeTime: 'Masa mula',
    subscribePeriod: 'Tempoh',
    subscribeEndTime: 'Masa tamat',
    totalSubscribePeriod: 'Masa Terkumpul untuk Menyalin',
    otherUser: 'Dia masih meniru dagangan',
    patternList: [
      {name: 'Saiz Lot Tetap', value: 1},
      {name: 'Nisbah Salinan Tetap', value: 2}
    ],
    directionList: [
      {name: 'Salin', value: 1},
      {name: 'Terbalik', value: 2},
      {name: 'Salin Isyarat Tutup Sahaja', value: 3}
    ],
    notice: 'Pengumuman',
    moreTradingNotice:
      'Untuk melihat lebih banyak pengumuman dagangan,<br/>sila pergi ke halaman butiran akaun dagangan',
    hot: 'Pembekal Signal Popular',
    count: 'Pengikut',
    allSource: 'Semua sumber',
    detail: 'Butiran',
    cancelTips: 'Untuk berhenti menyalin, sila pergi ke tetapan trading salinan dan matikan ciri tersebut.',
    cancel: 'Batalkan Copy Trade',
    setting: 'tetapan',
    detailStatusList: ['', 'Menyalin', 'Tamat tempoh', 'Dibatalkan', 'Dibayar balik', 'Tidak dimulakan'],
    orderId: 'ID Pesanan',
    startTime: 'Masa mula',
    endTime: 'Masa tamat',
    cancelTime: 'Masa Pembatalan',
    cancelReason: 'Alasan',
    notStartTips: 'Pesanan """Tidak dimulakan"" akan berkuat kuasa selepas pesanan ""menyalin"" tamat tempoh."',
    confirmTocancel: 'Adakah anda pasti mahu membatalkan trading penyalinan?',
    subscribeStartTime: 'Salin Masa Mula Dagangan',
    followAccount: 'Menyalin Akaun',
    followStatus: 'Salin Status',
    followStateTips: 'Anda masih akan menerima isyarat dalam pusat mesej selepas anda berhenti menyalin dagangan',
    baseSetting: 'Tetapan Asas',
    varietySetting: 'Tetapan Instrumen',
    followNotice: 'Arahan',
    followPattern: 'Mod Menyalin',
    followPatternTips:
      'Nisbah Salinan Tetap: Saiz lot anda dikira secara berkadar dengan ekuiti anda, yang disyorkan.\n\n<br/> Saiz Lot Tetap: Buka dan tutup saiz lot tetap tanpa mengira saiz lot akaun isyarat.',
    maxHand: 'Lot Max',
    maxHandTips: 'Lot tidak akan melebihi had atas ini walaupun akaun isyarat membuka saiz lot yang lebih besar.\n',
    noLimit: 'Tiada had',
    followDirection: 'Jenis Menyalin',
    followDirectionTips: 'Salin Isyarat Tutup Sahaja: Kedudukan baharu tidak akan disalin.',
    contractSize: 'Saiz Kontrak',
    contractSizeTips:
      'Saiz kontrak mungkin berbeza dari broker ke broker, menyebabkan ketidakkonsistenan dalam saiz lot untuk anda menyalin dagangan.\nAnda boleh melaraskan saiz kontras hanya apabila anda memilih Nisbah Salinan Tetap.',
    sizeList: [
      {name: 'Penyesuaian diri', value: 1},
      {name: 'Abaikan', value: 2}
    ],
    signalAccount: 'Akaun Signal',
    followLimit: 'Sekatan',
    followLimitTips:
      'Apabila diaktifkan, akaun berikut akan dihadkan dalam trading salinan <br/> Sebagai contoh, anda menetapkan mod salinan anda kepada "Terbalik" dan hanya membenarkan pesanan pendek pada EURUSD, maka: <br/> Jika akaun isyarat membuka kedudukan beli pada EURUSE, akaun berikut akan membuat trading pendek; <br/> Namun begitu, jika akaun isyarat meletakkan dagangan pendek pada EURUSD, akaun berikut tidak akan membuka kedudukan beli walaupun ia ditetapkan untuk menyalin dagangan terbalik kerana anda telah menetapkan sekatan. <br/>',
    setManually: 'Tidak dikenali. Sila tetapkan secara manual',
    limitList: [
      {name: 'No Limit', value: 0},
      {name: 'Short Only', value: 1},
      {name: 'Long Only', value: 2},
      {name: 'Jangan Buka Kedudukan', value: 3}
    ],
    followRuleContent:
      'Peraturan:<br/>\n\n1. Pesanan belum selesai tidak akan disalin sehingga ia dilaksanakan pada harga tetap; <br/>\n2. SL/TP tidak akan diikuti kerana titik keluar mungkin berbeza dari broker ke broker (yang mungkin mempunyai sebut harga dan spread yang berbeza...);<br/>\n3. Penyesuaian diri tidak digunakan untuk beberapa aset, seperti indeks, niaga hadapan, saham; <br/>\n4. Dalam trading salinan, saiz lot kedudukan terbuka adalah tertakluk kepada saiz lot maks/min yang diperlukan oleh broker; <br/>\n5. Anda mungkin mengalami kelewatan semasa menyalin dagangan. Isyarat terbuka akan diabaikan secara automatik jika ditangguhkan selama 180s dan lebih lama, dan isyarat tutup 30 minit.',
    notMatchTips:
      '{x} instrumen dalam akaun berikut anda tidak sepadan dengan instrumen dalam akaun isyarat dan tidak boleh diikuti. Sila semak dalam "Tetapan Instrumen".',
    maxLotsMoreThan: 'Maks. saiz lot hendaklah lebih besar daripada saiz lot tetap.',
    allMatchTips:
      'Sila pastikan instrumen dalam akaun berikut anda sepadan dengan instrumen dalam akaun isyarat, atau keabnormalan mungkin berlaku.',
    hasConfirm: 'Saya telah mengesahkan',
    gotoCheck: 'Pergi ke Sahkan',
    settingSuccess: 'Tetapkan Berjaya',
    mySubscribe: 'trading Salinan Saya',
    account: 'Akaun Isyarat',
    currPosition: 'Jawatan Semasa',
    yesterdayEarnings: 'TWR YTD',
    monthEarnings: 'TWR pada 1M Lalu',
    status: 'Salin Status Dagangan',
    statusList: ['Menyalin', 'Untuk Tamat Tempoh dalam {x} Hari', 'Luput Tidak Lama Lagi'],
    totalTime: 'Jumlah Tempoh Dagangan Salinan',
    operation: 'Tindakan',
    viewToAccount:
      'Untuk melihat siapa yang telah menyalin dagangan saya, sila pergi ke halaman <a target="_blank" href="{x}"> butiran akaun dagangan </a>',
    times: 'kali',
    connectionAnomaly:
      'Akaun dagangan anda #{x} telah di luar talian dan tidak tersedia buat sementara waktu. <br/>Jika kata laluan sambungan akaun ini telah ditukar, sila kemas kini di Pusat Peribadi-Tetapan Akaun-Akaun trading.',
    passwordTypeTips:
      'Anda tidak dibenarkan menyalin dagangan kerana anda menggunakan kata laluan pelabur untuk dagangan anda ccount #{x}. <br/> Sila tukar kepada kata laluan induk di Pusat Peribadi-Tetapan Akaun-Akaun sebelum menyalin dagangan.',
    goNow: 'Pergi sekarang',
    warmPrompt:
      'Peringatan:<br/> 1. Anda boleh menukar tetapan trading salinan anda di “Halaman Utama” -> “trading Salin”. <br/>',
    fixedHands: 'Saiz Lot Tetap',
    fixedRatio: 'Nisbah Salinan Tetap',
    fixedRatioTips: 'Saiz lot untuk akaun berikut anda dikira secara berkadar dengan ekuiti anda, yang disyorkan.',
    fixedHandsTips: 'Saiz lot untuk akaun berikut anda ditetapkan tanpa mengira saiz lot akaun isyarat.',
    ratio: '{x} kali',
    signalVariety: 'Instrumen (Akaun Signal)',
    followVariety: 'Instrumen (Akaun Copy)',
    selectVariety: 'Pilih Instrumen',
    searchVariety: 'Instrumen Carian',
    hasQuestion: 'Sebarang pertanyaan? Sila hubungi <span>perkhidmatan pelanggan</span>',
    subscribeInfo: 'Salin Maklumat trading',
    followAgain: 'Salin Lagi',
    residueLong:
      'Anda boleh mengikuti akaun ini untuk baki {0} bulan. Pembaharuan tidak dibenarkan.\n<br/>Sila ambil perhatian bahawa anda boleh mengikuti akaun ini paling lama {1} bulan. Sila perbaharui langganan anda apabila baki masa lebih pendek daripada {2} bulan.',
    subscribeExpire: 'Tempoh penyalinan tamat',
    closeTips:
      'Jika anda hanya mahu menerima isyarat tanpa menyalin dagangan, anda boleh mengubah suainya dalam tetapan langganan.',
    shareGetFollow:
      'Kongsi untuk menyalin trading secara percuma"" tidak tersedia sekarang. Sila buka keahlian sebelum menyalin dagangan."',
    signalNotFollow: 'Akaun isyarat tidak membenarkan trading salinan',
    initNotFollow: 'Memulakan. Sila cuba sebentar lagi'
  },
  header: {
    searchLabel: 'Cari',
    product: 'Produk',
    market: 'Pasaran',
    information: 'Berita',
    signal: 'Isyarat',
    match: 'Peraduan',
    activity: 'Peristiwa',
    broker: 'Broker',
    more: 'Lagi',
    chart: 'carta',
    stockFilter: 'Penyaring',
    financialCalendar: 'Kalendar Ekonomi',
    toolKit: 'Alatan',
    cost: 'penetapan harga',
    feature: 'ciri-ciri',
    dataMarket: 'data pasaran',
    overview: 'Gambaran keseluruhan',
    myOptional: 'Senarai pantauan',
    news: 'berita',
    transactionAnalysis: 'Analisis',
    quickInformation: '24/7',
    column: 'Kolum',
    answer: 'Q&A dengan pakar',
    data: 'data',
    video: 'video',
    institutionalViewPoint: 'Pandangan dari Institusi',
    analystViewPoint: 'Pandangan dari Penganalisis',
    columnTopic: 'Topik',
    columnist: 'Kolumnis',
    dataCenter: 'Pusat Data',
    marketTrend: 'Aliran Pasaran',
    institutionalData: 'Data Institusi',
    centralBankInterestRate: 'Kadar Dasar',
    macroEconomy: 'Makroekonomi',
    niuList: 'Top Traders',
    bestNiuer: 'Pilihan Mingguan',
    AISignal: 'Signal AI',
    fansActivity: 'Parti Peminat',
    web_ib_seminar: 'Seminar IB',
    voteActivity: 'Anugerah',
    web_fans_hongkong: 'Hongkong, China',
    web_fans_hochiminh: 'Vietnam Bandar Ho Chi Minh',
    web_fans_dubai: 'Dubai, UAE',
    web_fans_cairo: 'Kaherah Mesir',
    web_fans_nigeria: 'Nigeria Lagos',
    business: 'Bisnes',
    recruit: 'pengambilan pekerja',
    aboutUs: 'tentang kami',
    whiteLabel: 'White Label',
    dataAPI: 'API Data',
    webPlugins: 'plug-in web',
    feedback: 'Maklum balas',
    helpCenter: 'Pusat Bantuan',
    agreement: 'Perjanjian Pengguna',
    policy: 'Dasar Privasi',
    comingSoon: 'Akan datang',
    marketPrice: 'Petikan',
    calendar: 'Kalendar',
    quotation: 'Petikan',
    PRO: 'Pro',
    AIRating: 'Penilaian AI',
    latestViewPoints: 'Pendapat terkini',
    calendarWallpaper: 'Wallpaper Kalendar',
    speculativeMood: 'Sentimen',
    hangingOrderPosition: 'Pesanan',
    varietyCorrelation: 'Korelasi',
    popularIndex: 'Indikator Teratas',
    hotTopic: 'Topik Arah Aliran',
    recentUpdate: 'Kemas Kini Terkini',
    language: 'Bahasa',
    popularSearch: 'Carian Teratas',
    historySearch: 'Carian terkini\r',
    myCollection: 'Kegemaran saya',
    myConcern: 'Mengikuti Saya',
    mySubscription: 'Dagangan Salin Saya',
    personalInformation: 'Maklumat peribadi',
    memberCenter: 'Pusat Ahli',
    accountSetting: 'Tetapan Akaun',
    logOut: 'Log keluar',
    scanDownload: 'Imbas untuk Muat Turun',
    moreInformation: 'Berita dan petikan kewangan yang lebih pantas',
    downloadApp: 'Muat turun APP',
    addFBToDesk: 'Tambahkan FastBull ke Desktop',
    loadFromDesk: 'Lain kali anda boleh mengakses FastBull terus dari desktop komputer anda',
    addToDesk: 'Tambahkan pada Desktop',
    recommendSelfSelection: 'Disyorkan',
    waitingForDeal: 'Yang belum selesai',
    inTransaction: 'trading',
    overDeal: 'tertutup',
    overdue: 'Tamat tempoh',
    profitMaking: 'Untung',
    lossMaking: 'rugi',
    profitLoss: 'P&L',
    financialTools: 'Alat Kewangan',
    homePage: 'Rumah',
    clickLogin: 'Log masuk',
    AppDescription: 'Berita dan petikan kewangan yang lebih pantas dan komprehensif',
    supportResistance: 'Sokongan & Rintangan',
    copyright: 'Hak Cipta © {x} FastBull Ltd',
    risk: 'Pendedahan Risiko',
    riskText1:
      'Dagangan saham, forex, komoditi, niaga hadapan, bon, ETF atau mata wang kripto melibatkan risiko yang tinggi. Anda mungkin kehilangan sebahagian atau semua modal anda yang dilaburkan. Oleh itu, anda harus mempertimbangkan dengan teliti sama ada trading sedemikian sesuai untuk anda.',
    riskText2:
      'Tiada keputusan untuk melabur harus dibuat tanpa menjalankan usaha wajar secara menyeluruh sendiri atau berunding dengan penasihat kewangan anda. Kandungan web kami mungkin tidak sesuai dengan anda kerana kami tidak mengetahui keadaan kewangan dan keperluan pelaburan anda. Maklumat kewangan kami mungkin mempunyai kependaman atau mengandungi ketidaktepatan, jadi anda harus bertanggungjawab sepenuhnya untuk sebarang transaksi dan keputusan pelaburan anda. Syarikat tidak akan bertanggungjawab ke atas kehilangan modal anda.',
    riskText3:
      'Tanpa mendapat kebenaran daripada tapak web, anda tidak dibenarkan menyalin grafik, teks atau tanda dagangan tapak web. Hak harta intelek dalam kandungan atau data yang dimasukkan ke dalam laman web ini adalah milik pembekal dan pedagang pertukarannya.',
    cookieTips:
      'Kami menggunakan kuki untuk memahami cara anda menggunakan tapak web kami dan meningkatkan pengalaman anda, termasuk kandungan yang diperibadikan. Jika anda terus menggunakan laman web kami, ini bermakna anda menerima penggunaan kuki kami. Sila klik di sini jika anda ingin mengetahui lebih lanjut.',
    viewDetail: 'Lihat butiran',
    authorization: 'Setuju',
    function: 'Fungsi',
    company: 'Syarikat',
    user: 'pengguna',
    theLatestValue: 'Nilai Terkini',
    allSearchResult: 'Lihat Semua Hasil Carian',
    loginBtn: 'Log masuk',
    signUPBtn: 'Daftar',
    freeToOpenVIP: 'Naik taraf kepada Pro secara Percuma',
    web_opinion_hot_author: 'Kolumnis Teratas',
    market_finance_coverview: 'Gambaran keseluruhan',
    freeForevet: '',
    moduleDark: '',
    loginForMoreFunc: '',
    noLogin: ''
  },
  sideLayout: {
    news_calendar_filter_only_import: 'Berita Utama Sahaja',
    news_snowfall: 'Pautan Berkaitan',
    news_unscramble: 'Analisis & Pendapat',
    news_unscramble_long: 'LT',
    news_unscramble_short: 'ST',
    news_unscramble_bearish: 'Bearish',
    news_unscramble_bullish: 'Bullish',
    calendar_time_up: 'Waktu',
    calendar_prev_up: 'Sblm',
    calendar_est_up: 'Rmln',
    calendar_act_up: 'Sbnr',
    calendar_unrelease: 'Tidak Diterbitkan',
    calendar_revised: 'Sebelum Pembetulan',
    calendar_act: 'sbnr',
    calendar_est: 'Ramalan',
    calendar_prev: 'Sblm',
    new_share: 'Kongsi',
    vip_invite_friends_immediately: 'Rujuk dan dapatkan peningkatan percuma',
    vip_invite_friends_title: 'Kongsi',
    qa_header_title: 'Q&A dengan Pakar',
    qa_header_online: 'Soal Jawab Dalam Talian',
    qa_ask_question: 'Saya ada soalan...',
    qa_post_first_question: 'Siarkan soalan pertama anda',
    qa_expert: 'pakar',
    qa_view_translation: 'Lihat terjemahan',
    qa_view_original: 'Lihat teks sumber',
    qa_answer: 'jawab',
    qa_cancel_answer: 'Batalkan jawapan',
    qa_answer_placeholder: 'Jawapan {0}',
    qa_confirm_delete_question: 'Adakah anda pasti mahu memadamkan soalan ini?',
    qa_confirm_delete_answer: 'Adakah anda pasti mahu memadamkan jawapan ini?',
    qa_select_pic_format: 'Sila pilih format png, jpg, jpeg, gif, bmp, webp',
    qa_common_bottom: 'Tiada lagi kandungan',
    qa_remind_max_char: 'Masukkan maksimum {0} aksara',
    qa_cancel_reply: 'Batalkan balasan',
    qa_reply_someone: 'Balas {0}',
    quote_nav_more: 'Lagi',
    quote_link_more: 'Lagi',
    quote_table_asset: 'Simbol',
    quote_table_last: 'AKHIR',
    quote_table_netchg: 'Prbhn.',
    quote_table_chg: '%Prbhn.',
    quote_table_update: 'KEMASKINI',
    news_news_trending: 'Popular',
    quote_table_high: 'TINGGI',
    quote_table_low: 'RENDAH',
    quote_watchlist: 'Senarai pantauan',
    quote_my_watchlist: 'Senarai Pantauan Saya',
    reminderg: 'Tetapan Peringatan',
    maincontainer_market: 'Quotes',
    news_flash: '24/7',
    news_calendar: 'Kalendar',
    q_a: 'Jawab',
    home_tab_chat: 'Sembang',
    common_side_layout: 'Susun atur',
    common_layout_single: 'Satu lajur',
    common_layout_vertical: 'Dua baris',
    common_layout_tile: 'Dua lajur',
    cale_unpublish_time: 'Diumumkan dalam {0}',
    cale_unpublish_time_h: '{0} j',
    cale_unpublish_time_min: '{0} min',
    add_asset_name: 'Tambah Nama Aset atau Kod',
    add_to_favorites: 'Tambahkan pada Kegemaran',
    recentlyViewed: '',
    common_market_closed: 'tertutup',
    chart_indicator: 'Indikator',
    chart_strategy: 'Strategi',
    chart_edit: 'Editor',
    chart_backtest: 'Backtest',
    chart_order: 'Pesanan Baru',
    chart_template: 'templat',
    chart_sync: 'Segerakkan',
    chart_history: 'Sejarah',
    chart_remind: 'Amaran',
    chart_log: 'Log',
    chart_connect: 'Menyambung ke server, sila tunggu...',
    searchStocksTips: 'Masukkan A-Z atau 0-9 untuk memulakan carian'
  },
  dataCollect: {
    fxchat_login_edit_user_info_title: 'Edit maklumat peribadi(1/3)',
    fxchat_login_complete_material_title: 'Lengkapkan maklumat anda(2/3)',
    fxchat_login_recommendation_title: 'Ubaisuai Kandungan Anda（3/3）',
    fxchat_information_nick_name: 'Alias',
    fxchat_login_field_title: 'Masukkan Alias ​​Anda',
    fxchat_information_sex: 'Jantina',
    fxchat_information_sex_man: 'Lelaki',
    fxchat_information_sex_women: 'perempuan',
    fxchat_information_sex_other: 'Lain-lain',
    fxchat_information_sex_secret: 'Sulit',
    fxchat_material_morning: 'Selamat Pagi! {0}. Selamat datang ke FastBull.',
    fxchat_material_noon: 'Selamat petang! {0}. Selamat datang ke FastBull.',
    fxchat_material_afternoon: 'Selamat petang! {0}. Selamat datang ke FastBull.',
    fxchat_material_night: 'Selamat petang! {0}. Selamat datang ke FastBull.',
    fxchat_material_introduction:
      'Beritahu kami ringkasan tentang diri anda untuk membantu kami memilih kandungan dengan lebih baik untuk anda.',
    fxchat_recommendation_subtitle:
      'Kami akan memilih kandungan yang diperibadikan untuk anda berdasarkan pilihan anda.',
    fxchat_material_summarize: 'Terbaik! Kami akan menyesuaikan kandungan untuk anda mengikut keutamaan anda.',
    fxchat_material_assistant_name: 'robot AI',
    fxchat_material_look: 'Lihat sekarang',
    fxchat_material_reselect: 'Pilih semula',
    fxchat_recommendation_see_more: 'lihat lagi',
    fxchat_recommendation_open_fxchat: 'Buka FastBull',
    fxchat_recommendation_open_group: 'sembang kumpulan',
    fxchat_recommendation_open_niu: 'Trending',
    fxchat_not_group_introduction: 'Tiada penerangan lagi',
    fxchat_recommendation_join: 'Sertai',
    fxchat_recommendation_has_join: 'Menyertai',
    fxchat_login_skip: 'Langkau',
    fxchat_recommendation_follow: 'Ikut',
    fxchat_recommendation_has_follow: 'Mengikuti',
    fxchat_login_trading_type: 'Pasaran dagangan manakah yang menarik minat anda? (Pilih satu atau lebih)'
  },
  setting: {
    personalData: 'Maklumat peribadi',
    accountSafety: 'Keselamatan Akaun',
    informSetting: 'Tetapan Pemberitahuan',
    privacy: 'Privasi',
    blacklist: 'Senarai hitam',
    remove: 'Alih keluar',
    shieldingTime: 'Diblok: {x}',
    addStyle: 'Cara untuk Berkawan dengan Saya',
    allowAll: 'Benarkan sesiapa sahaja berkawan dengan saya',
    needVerify: 'Perlu pengesahan',
    notAllowAny: 'Tiada sesiapa dibenarkan berkawan dengan saya',
    findByPhone: 'Cari saya melalui nombor telefon',
    findByPhoneTips: 'Pengguna lain tidak dapat mencari anda melalui maklumat di atas jika anda mematikannya.',
    follow: 'Copy Trading',
    followTips: 'Butiran copy trading anda akan dipaparkan secara terbuka selepas menghidupkannya.',
    contest: 'Peraduan',
    contestTips: 'Butiran peraduan anda akan dipaparkan secara terbuka selepas menghidupkannya.',
    emailNotice: 'Keutamaan Pemberitahuan E-mel',
    weeklySelection: 'Pilihan Editor Mingguan FastBull',
    willPushNews: 'Kami akan maklumkan berita kewangan utama dan acara penting kepada anda',
    sendWeek: 'Kemas Kini Mingguan',
    dailyHighlights: 'Berita pasaran utama FastBull untuk hari ini',
    sendDay: 'Berita akan dihantar pada hari perniagaan',
    baseInfo: 'Info asas',
    nickname: 'Alias',
    joinStyle: 'Cara Menyertai Kumpulan',
    aphorism: 'Moto trading',
    editInfo: 'Edit maklumat peribadi',
    interestInfo: 'maklumat yang diminati',
    noAddInterest: 'Tiada kandungan lagi~',
    dealPlatform: 'Broker',
    dealMarket: 'Pasaran',
    dealVariety: 'Instrumen',
    dealStyle: 'Stail',
    avatar: 'Avatar',
    modifyAvatar: 'Edit Avatar',
    username: 'Nama pengguna',
    sex: 'Jantina',
    dealAge: 'Tahun Dagangan',
    address: 'Lokasi',
    industry: 'Profesion Anda',
    modify: 'Sunting',
    addIndustry: 'Tambah Profesion',
    userIntro: 'Profil',
    interestDealInfo: 'Keutamaan Anda',
    add: 'Tambah',
    sexList: [
      {value: 0, name: 'Lelaki'},
      {value: 1, name: 'Perempuan'},
      {value: 2, name: 'Rahsia'}
    ],
    industryType: 'Jenis Profesion',
    inIndustry: 'Profesion Berkaitan',
    outIndustry: 'Profesion Lain',
    interestPlayform: 'Pilih Broker',
    interestMarket: 'Pilih Pasaran',
    interestStyle: 'Pilih Stail',
    interestVariety: 'Pilih Instrumen',
    maxOption: 'Anda boleh memilih sehingga {x} item',
    blackTypeList: [
      {nilai: 1, name: 'Kenalan'},
      {nilai: 2, nama: 'Sembang Kumpulan'}
    ],
    accountInfo: 'Maklumat akaun',
    userPassword: 'Kata Laluan Pengguna',
    haveSet: 'Disetkan',
    isNotSet: 'Tidak Ditetapkan',
    phoneNumber: 'Nombor telefon',
    notBind: 'Tidak Berpaut',
    bind: 'Pautan',
    email: 'Alamat emel',
    bindThird: 'Pautan kepada Pihak Ketiga',
    unBind: 'Nyahpaut',
    bindPhone: 'Pautkan Nombor Telefon',
    changePhone: 'Tukar Nombor Telefon',
    inputPhone: 'Masukkan Nombor Telefon',
    and: 'dan',
    inputPhoneTips: 'Masukkan nombor telefon yang sah',
    inputVerifyCode: 'Masukkan kod pengesahan 4 digit',
    oldPhoneNumber: 'Nombor Telefon Asal',
    newPhoneNumber: 'Nombor Telefon Baharu',
    bindEmailOpen: 'Sila pautkan alamat e-mel anda untuk mendayakan log masuk akaun',
    bindEmail: 'Pautan Alamat E-mel',
    setPassword: 'Tetapkan kata laluan',
    password: 'Kata laluan',
    inputPwd: 'Sila masukkan kata laluan',
    pwdRules:
      'Kata laluan memerlukan 6-20 aksara, termasuk sekurang-kurangnya 2 jenis daripada nombor, huruf dan aksara khas.',
    updatePwd: 'Tukar kata laluan',
    currentPwd: 'Kata Laluan Semasa',
    forgetPwd: 'Lupa kata laluan?',
    newPwd: 'Kata laluan baharu',
    pwdNotSame: 'Kata Laluan Salah',
    emailResetPwd: 'Masukkan alamat e-mel anda dan kami akan menghantar pautan tetapan semula kepada anda',
    sendResetLink: 'Hantar Pautan Tetapan Semula',
    inputEmail: 'Sila masukkan alamat e-mel anda',
    inputRightEmail: 'Sila masukkan alamat emel yang sah',
    alreadSendLink: 'Kami telah menghantar pautan tetapan semula kata laluan kepada anda',
    alreadSendTo: 'Kami telah menghantar e-mel kepada',
    noGetFindHelp: 'Jika anda tidak menerima e-mel dalam masa 5 minit, sila semak Spam atau minta bantuan',
    findHelp: 'Minta bantuan',
    getVerifyCode: 'Dapatkan Kod Pengesahan',
    notGet: 'Masih belum menerimanya?',
    resend: 'Hantar semula E-mel',
    inputCode: 'Masukkan kod pengesahan',
    beGetting: 'Mendapatkan semula...',
    resendAfter: 'Boleh dihantar semula dalam {x} s',
    selectAvatar: 'Pilih Avatar',
    customAvatar: 'Tambah Avatar',
    reUpload: 'Muat naik semula',
    defaultAvatar: 'Avatar lalai',
    imgType: 'Hanya {x} fail dibenarkan!',
    inputNickname: 'Sila masukkan alias anda',
    inputUsername: 'Sila masukkan nama pengguna anda',
    usernameTips:
      'Nama pengguna hanya boleh mengandungi huruf kecil, nombor, garis bawah dan noktah. Pautan ke halaman utama anda akan berubah jika anda menukar nama pengguna anda.'
  },
  vip: {
    equities: 'hak dan kepentingan',
    detail: 'Butiran',
    hasCode: 'Saya mempunyai kod penebusan',
    inputCode: 'Sila masukkan kod penebusan',
    conversion: 'pertukaran',
    shareGet: 'Kongsi keahlian percuma',
    shareGetYear: 'Kongsi dan dapatkan keahlian 1 tahun secara percuma',
    inviteUser:
      'Pengguna baharu yang anda jemput klik pautan yang anda kongsi dan lengkapkan pendaftaran log masuk untuk mendapatkan keahlian 1 tahun.',
    scanQRCode: 'Imbas kod QR dengan telefon bimbit',
    shareLink: 'Kongsi pautan untuk mendapatkan keahlian',
    recharge: 'Caj semula keahlian',
    agree: 'Saya telah membaca dan bersetuju',
    agreement: 'Perjanjian Perkhidmatan Ahli',
    privilege: 'keistimewaan ahli',
    time: 'masa',
    duration: 'Dapatkan tempoh keahlian',
    getMode: 'kaedah mendapatkan',
    status: 'negeri',
    redeemRules:
      'Peraturan penggunaan kod penebusan:\n1. Kod penebusan yang diaktifkan tidak boleh digunakan semula\n2. Kod penebusan tidak boleh digunakan melebihi tempoh sah',
    privilegeList: [
      {
        id: 1,
        title: 'Berita AI sampai dengan cepat',
        desc: 'Penghantaran segera dan pantas bagi kandungan berita yang lebih terpilih'
      },
      {
        id: 2,
        title: 'Jejaki lebih banyak jenis pasaran',
        desc:
          'Anda boleh menambah lebih banyak jenis pilihan anda dan menjejaki lebih banyak data pasaran dalam masa nyata'
      },
      {
        id: 3,
        title: 'Data makro dan penunjuk ekonomi yang lebih komprehensif',
        desc: 'Data sejarah penunjuk yang lebih komprehensif untuk membantu dalam menganalisis pasaran makro'
      }
    ],
    shareTitle:
      'Saya telah membuka VIP nilai super untuk anda di FastBull, dengan nilai maksimum 1,648 yuan. Datang dan dapatkan~'
  },
  promotion: {
    volumnMuteDefault: 'Dibisukan secara lalai',
    enableVolumn: 'Nyahbisukan',
    kolInterview: 'Temuduga KOL',
    userComment: 'Ulasan Pengguna',
    moreFunction: 'Teroka Lagi',
    moreFunctionTxt: 'Dapatkan apa sahaja yang anda perlukan untuk berdagang di FastBull'
  },
  tdk: {
    title: 'FastBull - Berita Kewangan dan Sebut Harga yang Lebih Pantas',
    homeTitle: 'Top Trader FastBull: Jejaki Pedagang Paling Menguntungkan',
    homeDesc:
      'FastBull Top Traders meletakkan kedudukan pedagang berdasarkan pelbagai faktor, termasuk keuntungan, kestabilan dan risiko. Jejaki peniaga yang paling menguntungkan dan belajar daripada strategi mereka.',
    greatestTitle: 'Pilihan Mingguan FastBull',
    greatestDesc:
      'FastBull menyusun kedudukan pelabur dan akaun setiap minggu berdasarkan keuntungan, analisis kuantitatif, pengikut, saiz posisi dan kadar kemenangan.',
    helpTitle: 'Pusat Bantuan - FastBull',
    helpDesc: 'Dapatkan jawapan kepada soalan biasa dan dapatkan sumber yang berguna dalam Pusat Bantuan kami.',
    userTitle: '【{x}】- Profil',
    userDesc:
      'Profil ini ialah tetingkap ke dunia 【{x}】. Daripada pemikiran yang bernas kepada hubungan yang menarik.'
  },
  about: {
    downloadApp: 'Muat turun APL',
    aboutFb: 'Tentang FastBull',
    fbExplain:
      'FastBull ialah inovator dalam sektor Fintech. Kami telah menubuhkan pasukan editorial dan terjemahan di banyak wilayah, bertujuan untuk membina kandungan setempat di banyak negara dan wilayah. Pada masa yang sama, kami mempunyai pasukan R&D dan pengurusan produk terbesar serta kekuatan teknikal tertinggi. Kami akan terus menyediakan pengalaman perisian terkemuka pada masa hadapan.',
    service: 'Servis kami',
    product: 'Produk',
    productExplain:
      'Kami telah melancarkan fungsi kalendar ekonomi dan alatan sokongan, dan akan melancarkan lebih banyak fungsi hebat pada masa hadapan: Carta Pro, Penyaring Stok, Data Analisis Pasaran, dsb.',
    signal: 'Signal',
    signalExplain:
      'Berita, Top Traders, Kedudukan Mingguan, Signal Terkini dan Peraduan. Signal dagangan masa nyata daripada tp traders tersedia untuk anda salin, menjadikan dagangan lebih mudah.',
    message: 'Berita',
    messageExplain:
      'Berita, 24/7, Analisis, Kolum, Data dan Video, meliputi berita tergempar global dan pandangan trading daripada penganalisis dan institusi. Pada masa yang sama, acara popular dan data ekonomi dikemas kini 24/7.',
    market: 'Pasaran',
    marketExplain:
      'Kami menyediakan forex, komoditi, indeks, saham A.S., kripto, CME dan pasaran lain. Pada masa hadapan, kami akan terus menawarkan pasaran saham global, ETF, bon, dsb.',
    business: 'Bisnes',
    businessExplain:
      'Kami menawarkan beberapa perkhidmatan pihak ketiga percuma atau berbayar seperti White label, API Data dan Plug-in Web yang menyediakan sumber data dan sokongan teknikal.',
    course: 'Pembangunan',
    contact: 'Hubungi Kami',
    partner: 'rakan kongsi',
    email: 'Alamat emel',
    feedback: 'Maklum balas',
    scan: 'Imbas Kod QR',
    android: 'Android',
    ios: 'iOS',
    downloadTips: 'Bincangkan dan kongsi idea dan pandangan dagangan anda dengan pelabur global dalam masa nyata',
    chat: 'Sembang Segera',
    chatExplain: 'Berbual dengan pedagang terkemuka global tentang trading!',
    chart: 'Carta Sosial',
    chartExplain: 'Menganalisis pasaran, membincangkan trading, melanggan isyarat',
    realTimeSignal: 'Isyarat masa nyata',
    realTimeSignalExplain: 'Isyarat dagangan sebenar, untuk disalin secara percuma',
    contest: 'Peraduan trading',
    contestExplain: 'Platform terbaik untuk menunjukkan keupayaan dagangan anda',
    answer: 'Q&A dengan Pakar',
    answerExplain: 'Dapatkan nasihat profesional percuma daripada pakar',
    analyse: 'Analisis trading',
    analyseExplain: 'Ketahui logik trading pakar pelaburan',
    calendar: 'Kalendar Ekonomi',
    calendarExplain: 'Alat analisis profesional yang menyediakan tafsiran mendalam tentang data ekonomi',
    news: 'Berita Pilihan',
    newsExplain: 'Merangkumi pandangan mendalam daripada pakar ekonomi global',
    tools: 'Pembuat Poster',
    toolsExplain: 'Sokong penyesuaian pelbagai poster kewangan',
    more: 'Lagi',
    moreExplain: 'Muat turun FastBull untuk mengalami lebih banyak ciri menarik',
    downloadFrom: 'Muat turun daripada'
  },
  chat: {
    headTabs: ['Semua', 'Bilik Sembang', 'Kumpulan', 'Rakan'],
    placeInput: 'Taip di sini...',
    connecting: 'Menyambung ke bilik sembang'
  }
}
