export default {
  common: {
    confirm: '確定',
    affirm: '確認',
    remove: '刪除',
    cancel: '取消',
    tips: '提示',
    finish: '完成',
    know: '知道了',
    time: '時間',
    count: '{x} 個',
    hand: '{x} 手',
    order: '{x} 單',
    score: '{x} 分',
    person: '{x} 人',
    times: '{x} 次',
    second: '{x} 秒',
    minutes: '{x} 分鐘',
    hour: '{x} 小時',
    day: '{x} 天',
    month: '{x} 個月',
    year: '{x} 年',
    shortsecond: '{x} 秒',
    shortminutes: '{x} 分鐘',
    shorthour: '{x} 小時',
    shortday: '{x} 天',
    justNow: '剛剛',
    minuteAgo: '{x} 分鐘前',
    hourAgo: '{x} 小時前',
    yesterday: '昨天{x}',
    beforeYesterday: '前天{x}',
    yearUnit: '年',
    monthUnit: '月',
    dayUnit: '天',
    hourUnit: '時',
    minutesUnit: '分',
    secondUnit: '秒',
    hundredMillion: '{x} 億',
    trillion: '{x} 萬億',
    loading: '載入中...',
    noMore: '沒有更多數據了',
    all: '全部',
    reset: '重置',
    unfoldAll: '展開全部',
    packUp: '收起',
    unfold: '展開',
    back: '返回',
    warning: '警告',
    noData: '暫無數據',
    imageFormat: '僅支援JPG、JPEG 或PNG 的圖片格式！',
    imageSize: '圖片大小不得超過{x} MB',
    shareFb: '分享FastBull，取得一個月的跟單權限',
    noNetLaterTry: '網路異常，請稍後再試...',
    copy: '複製',
    copySuccess: '連結已複製',
    appDownload: 'APP下載-FastBull',
    fbDownload: 'FastBull APP下載',
    getSuccess: '已取得一個月跟單權限',
    reLogin: '登入狀態已失效，請重新登入。',
    notFound: '抱歉，您造訪的頁面位址有錯誤或該頁面不存在',
    returnToLast: '回上一頁',
    returnToHome: '回首頁',
    forbidden: '訪問被拒絕',
    noAccess: '您無權使用所提供的憑證檢視此目錄或頁面。',
    serverError: '出錯了',
    tryRefresh: '請刷新頁面再試一次',
    operationConfirm: '操作確認',
    select: '請選擇',
    download: '下載',
    close: '關閉',
    isDelete: '已刪除',
    noResult: '抱歉，未能找到相關結果',
    tryAgain: '您可以嘗試更換關鍵字再次進行搜索',
    loginInOther: '您的帳號會在另外一瀏覽器上登入。 如非本人操作，則密碼可能洩露，請立即修改密碼',
    chartLoading: '圖表加載中...',
    custom_service: '客服',
    common_look: '查看'
  },
  message: {
    messageCenter: '訊息中心',
    system: '社區通知',
    trading: '交易訊號',
    comment: '評論回覆',
    account: '帳戶通知',
    answer: '專家問答',
    noMoreData: '沒有更多數據了',
    viewAll: '看全部',
    noNewMsg: '暫無新消息',
    noMessage: '訊息空空如也',
    systemMsgTypeList: [
      {type: 0, label: '所有內容'},
      {type: 1, label: '社區通知'},
      {type: 3, label: '我跟隨的'},
      {type: 4, label: '跟隨我的'}
    ],
    commentMsgTypeList: [
      {type: 0, label: '帳號評論'},
      {type: 1, label: '新聞評論'},
      {type: 2, label: '影片評論'}
    ],
    accountMsgTypeList: [
      {type: 0, label: '所有內容'},
      {type: 1, label: '帳戶變動'},
      {type: 2, label: '排名更新'},
      {type: 4, label: '交易戰報'}
    ],
    open: '開倉',
    openTime: '開倉時間',
    close: '平倉',
    closeTime: '平倉時間',
    riskWarning: '風險警告',
    subscribeNotice: '跟單公告',
    clickView: '點擊查看',
    allSource: '所有來源',
    replyYou: '回復了您',
    answerYou: '回答了您的提問\r',
    commentAccount: '評論了您的交易帳戶',
    commentYou: '評論了',
    viewDetail: '看詳情',
    commentTypeList: ['帳號評論', '訊息回應'],
    reportAccount: '檢舉了您的交易帳戶',
    waitFollow: '等待跟隨',
    followSuccess: '跟隨成功',
    followFailed: '跟隨失敗',
    ignore: '已忽略',
    tryFollow: '正在嘗試跟隨此信號，請稍後...',
    followOrder: '跟隨訂單',
    followStatus: '跟隨狀態',
    unit: '單位',
    noSignal: '暫無交易訊號',
    orderId: '跟隨訂單ID',
    statusList: ['等待跟隨', '跟隨成功', '跟隨失敗', '已忽略'],
    statusTitle: ['等待原因', '跟隨訂單ID', '失敗原因', '忽略原因'],
    goSetting: '前往設定',
    viewOrder: '查看訂單',
    stopProfit: '停利',
    stopLoss: '停損',
    openPrice: '開倉價',
    closePrice: '平倉價',
    delist: '目前內容已下架',
    remove: '目前內容已刪除'
  },
  home: {
    actualIntro: '實盤帳戶總數',
    actual: '實盤帳戶總數',
    profitIntro: '實盤獲利帳戶數',
    profitAccount: '獲利帳戶',
    lossIntro: '實盤虧損帳戶數',
    lossAccount: '虧損帳戶',
    blastingIntro: '出現過爆倉的實盤帳戶數',
    blastingAccount: '出現過爆倉的實盤帳戶數',
    allMen: '所有牛人',
    openAccountToDate: '開戶至今',
    lastJune: '近六月',
    already: '已跟單',
    yieldValueChart: '收益率（TWR）走勢圖',
    favor: '猜你喜歡',
    refresh: '換一批',
    unlimited: '不限',
    rank: '綜合評級',
    earnings: '帳戶收益',
    riskLevel: '風險等級',
    broker: '交易商',
    goodAt: '擅長品種',
    moreOptions: '更多選項',
    dealWinRate: '交易勝率',
    ratio: '盈虧比',
    openTime: '開戶時間',
    capital: '資金量級',
    accountType: '帳戶類型',
    platform: '交易平台',
    clear: '清空',
    noContent: '沒找到相關內容',
    noBroker: '未搜尋到相關交易商',
    accountRatingRangeList: [
      {value: 1, label: 'A級'},
      {value: 2, label: 'B級'},
      {value: 3, label: 'C級'}
    ],
    twrRangeList: [
      {value: '', label: '不限'},
      {value: 2, label: '0%~30%'},
      {value: 3, label: '30%~60%'},
      {value: 4, label: '60%~100%'},
      {value: 5, label: '100%~200%'},
      {value: 6, label: '200%以上'}
    ],
    riskLevelList: [
      {value: 1, label: '低'},
      {value: 2, label: '中'},
      {value: 3, label: '高'}
    ],
    winRateRangeList: [
      {value: 0, label: '不限'},
      {value: 2, label: '50% 以上'},
      {value: 3, label: '60% 以上'},
      {value: 4, label: ' 70% 以上'},
      {value: 5, label: '80% 以上'},
      {value: 6, label: '90% 以上'}
    ],
    profitLossRatioRangeList: [
      {value: 0, label: '不限'},
      {value: 2, label: '0.5 以上'},
      {value: 3, label: '1.0 以上'},
      {value: 4, label: '1.5 以上'},
      {value: 5, label: '2.0 以上'},
      {value: 6, label: '2.5 以上'},
      {value: 7, label: '3.0 以上'}
    ],
    openingTimeRangeList: [
      {value: 0, label: '不限'},
      {value: 1, label: '≤ 1 個月'},
      {value: 2, label: '> 1 個月'},
      {value: 3, label: '> 3 個月'},
      {value: 4, label: '> 6 個月'},
      {value: 5, label: '> 12 個月'}
    ],
    amountOfFundsRangeList: [
      {value: 0, label: '不限'},
      {value: 1, label: '100 以下'},
      {value: 2, label: '100 到1000'},
      {value: 3, label: '1000到3000'},
      {value: 4, label: '3000 到1 萬'},
      {value: 5, label: '1 萬到10 萬'},
      {value: 6, label: '10 萬到30 萬'},
      {value: 7, label: '30 萬以上'}
    ],
    accountTypeList: [
      {value: 1, label: '實盤'},
      {value: 2, label: '類比碟'}
    ],
    orderList: [
      {value: 2, name: '收益率'},
      {value: 3, name: '最大回撤'},
      {value: 4, name: '勝率'},
      {value: 5, name: '盈虧比'},
      {value: 6, name: '跟單人數'}
    ],
    niuTopTypeList: ['收益最高', '量化最佳', '單量最多', '勝率最高'],
    threeMonthData: '近三月數據',
    dataFieldList: ['日均收益', '量化交易佔比', '日均單量', '交易勝率'],
    threeMonthEarnings: '近三月收益',
    positionDuration: '平均持倉時間',
    lastThreeMonth: '近三個月',
    detail: '詳情',
    appraise: '每週精選',
    nextUpdate: '下次更新',
    currentStage: '目前榜單週期',
    stage: '第{x} 期',
    nobodyOnTheList: '本期無上榜名單',
    ruleContent:
      '從收益、量化、單量、勝率四個面向（基於近三月數據），選出最優秀的交易帳戶。 單一指標能力突出加上有良好的獲利表現，才能上榜每週精選。',
    udpateTime: '每週六{x}更新',
    weeklySelection: '每週精選',
    totalAccountNum: '總帳戶',
    echartMeaning: '圖表意義',
    transactionSoftwareList: [
      {value: 2, label: 'MT4'},
      {value: 1, label: 'MT5', disabled: true}
    ],
    infiniteTxt: '無限',
    selectBrokerNum: '已選{x}個交易商',
    moreSelect: '多選',
    indexSubTabItem1: '收益60%~100%',
    indexSubTabItem2: '低風險',
    indexSubTabItem3: '12月以上',
    indexSubTabItem4: '資金量1萬到10美金',
    indexSubTabItem5: '勝率90%以上',
    indexSubTabItem6: '盈虧比3倍以上',
    filterNiuTitle: '達人篩選',
    selectBrokerTitle: '選擇交易商',
    allTimePeriod: '全部時段',
    searchBroker: '搜尋交易商',
    KOLInterview: 'KOL專訪',
    userEvaluation: '用戶評價',
    interestBroker: '感興趣的交易商'
  },
  aiRating: {
    gradeTimes: 'AI評級次數',
    dataCutOff: '數據截至{x}',
    gradeModel: '多維度評判模型',
    modelIntro:
      'AI評級系統從盈虧、訂單、部位、品種、風格這五個維度對交易帳戶進行全方位的審查，準確地評估一個帳戶在盈利能力、穩定性以及風險性等方面的表現。',
    sample: '海量樣本表現',
    sampleIntro: '成千上萬的交易帳戶，數以千萬計的交易訂單，客觀、公正的評判結果，是對AI評級系統最好的贊同。',
    highAccount: '進階帳戶',
    highIntro: '擁有較好的獲利能力，在穩定性和風險性方面表現良好。',
    profitAccount: '獲利帳戶',
    middleAccount: '中級帳戶',
    middleIntro: '具備一定的獲利能力，但在穩定性和風險控制方面，還需提升。',
    lowAccount: '低級帳戶',
    lowIntro: '獲利能力較差，且伴隨著巨大的交易風險。',
    moreClient: '更高的評級，更多的客戶',
    moreIntro:
      '評級越高，帳戶的實力越強，被客戶跟單和關注的可能性就越大。牛名單現有跟單中，超過{x} 的被跟單帳戶均為A級以上帳戶。',
    allUse: '他們都在使用',
    yourScore: 'AI評級系統，為您的交易試卷打出最真實的評分。快來看看您的得分吧~',
    profitLoss: '盈虧',
    orderForm: '訂單',
    position: '部位',
    variety: '品種',
    style: '風格'
  },
  account: {
    settingOptions: [
      {value: 1, name: '資料設定'},
      {value: 2, name: '權限設定'}
    ],
    deleteAccount: '刪除帳戶',
    sureToDelete: '您確定要刪除此交易帳戶？',
    deleteMatters: '注意：已被您刪除的交易帳戶在七天內無法再次進行綁定。',
    confirmDelete: '確定刪除',
    cancelSubscribeBeforeDel: '該帳戶目前跟單了{x} 個訊號帳戶，若要刪除此帳戶，請先取消這些跟單。',
    deleteSuccess: '{x} 已成功刪除',
    deleteFailed: '{x} 刪除失敗',
    settingSaved: '設定已儲存',
    accountPermission: '帳戶權限',
    subscribePermission: '跟單權限',
    accountPrivate:
      '帳戶權限目前處於關閉狀態，其他人暫無法跟單此帳戶的交易訊號。\n若要出售交易訊號，請將帳戶權限設為“公開”，並開啟跟單權限。',
    commentPermission: '評論權限',
    accountcommentForbid: '該帳戶的評論權限已被系統停用。如有疑問，請聯絡客服。',
    positionOrder: '持倉訂單',
    historyOrder: '歷史訂單',
    weeklyReport: '每周向我發送此帳戶的交易情況。',
    monthlyReport: '每月向我發送此帳戶的交易情況。',
    tradingDayReport: '交易日報',
    tradingWeekReport: '交易週報',
    tradingMonthReport: '交易月報',
    linkAbnormal: '連線例外',
    linkAbnormalExplain: '此交易帳戶連線異常，請不要跟單。',
    riskAccount: '風險帳戶',
    riskAccountExplain: '此交易帳戶有較大虧損風險，請謹慎跟單。',
    abnormalAccount: '異常帳戶',
    abnormalAccountExplain: '此交易帳戶的真實性存疑，請謹慎跟單。',
    sixMonthEarnings: '近六月收益',
    actualAccount: '實盤交易帳戶',
    virtualAccount: '類比盤交易帳戶',
    balance: '餘額',
    netValue: '淨值',
    maxDrawdown: '史上最大回調',
    drawdownTips:
      '開戶至今，淨值曾出現過的最大的虧損幅度（百分比）。\n對於新綁定的交易帳戶，其在綁定之前的歷史最大回撤將使用餘額資料來計算。\n請注意，MT4 的最大回撤演算法有一定的缺陷，而牛人榜矯正了此演算法，以使結果更加準確，故兩者的最大回撤結果可能不一致。',
    deposit: '支付',
    withdrawal: '退出',
    fetch: '提款',
    save: '存款',
    creditFetch: '信用額出金',
    creditSave: '信用額入金',
    dealAccount: '交易帳戶',
    dataSynchronizationErr: '資料同步失敗，請檢查帳號或密碼！',
    notOpen: '暫未開通，敬請期待',
    signalProvider: '成為訊號提供者',
    tradingAccountSetting: '交易帳戶設定',
    profitLossRatio: '盈虧比',
    dateOptions: [
      {value: 0, name: '全部時段'},
      {value: 1, name: '近1月'},
      {value: 2, name: '近3月'},
      {value: 3, name: '近6月'},
      {value: 4, name: '近12月'}
    ],
    yieldRate: '殖利率',
    totalProfitLoss: '總盈虧',
    synthesizeRank: '綜合排名',
    rankTips: '綜合排名依據綜合評等得分而來，僅實盤帳戶方可參與排名。',
    synthesizeScore: '綜合得分',
    scoreTips: '從盈虧、訂單、部位、品種以及風格等多個維度對交易帳戶進行評級評分。',
    periodList: [
      {value: 1, name: '天'},
      {value: 2, name: '週'},
      {value: 4, name: '月'}
    ],
    profitLossTitle: ['每日損虧', '每週損益', '每月損虧'],
    forbidBroker:
      '牛隻榜已不再支援交易商{x}，此交易商的交易帳戶將無法綁定到本社區。同時，現有的該交易商的交易帳戶也將不再允許跟單。',
    accountSetting: '帳戶設定',
    earningsReport: '收益統計',
    clickToView: '點擊柱子查看交易報告',
    openAccountTime: '開戶時間',
    currency: '存款貨幣',
    timeZone: '交易時區',
    cutOff: '統計截至',
    profitLoss: '盈虧',
    handCount: '步數',
    orderCount: '單量',
    balanceOptions: [
      {value: 1, name: '原始', content: '原始的餘額/淨值曲線圖，但受出入金影響，可能有斷層。'},
      {
        value: 2,
        name: '修正',
        content:
          '將出入金資料進行了折算，使餘額/淨值曲線變得更加連續而平滑，以便更加真實的了解帳戶餘額/淨值的變化趨勢，此方法不會產生失真。'
      }
    ],
    varietyDistribute: '交易品種分佈',
    timesOptions: [
      {value: 1, name: '倉位'},
      {value: 2, name: '筆數'}
    ],
    profitDistribute: '交易盈虧分佈',
    profitDirection: '交易方向分佈',
    incomeOptions: [
      {value: 1, 名稱: '方向'},
      {value: 2, name: '盈虧'}
    ],
    positionTime: '持倉時間',
    holdOptions: [
      {value: 1, 名稱: '倉位'},
      {value: 2, name: '盈虧'}
    ],
    totalAvg: '總平均持倉',
    profitAvg: '獲利單平均持倉',
    lossAvg: '虧損單平均持倉',
    loading: '正在載入',
    promptContent:
      '<p>溫馨提示：</p>\n1. 計算各項統計數據時，已排除掛單和出入金數據；<br/>\n2. 綜合評級和各項統計數據於北京時間每天 08:00 發布更新；<br/>\n3. 不論帳戶存款貨幣為何種貨幣，在與盈虧相關的統計數據末尾，我們都使用符號$ 來表明該數據為盈虧類數據；<br/>\n4. MT4 的最大回撤演算法有一定的缺陷，而牛人榜矯正了此演算法，以使結果更加準確，故兩者的最大回撤結果可能不一致；<br/>\n5. 盈虧比和收益風險比的最大值被限定為100.00，收益率的最大值被限定為100.00w%。<br/>',
    totalOrder: '共{x} 個訂單，已載入{y}',
    longOrder: '多單',
    shortOrder: '空單',
    longShort: '多/空',
    shippingSize: '部位大小',
    profitOrder: '獲利訂單',
    lossOrder: '虧損訂單',
    orderPosition: '訂單部位',
    orderProfitLoss: '訂單盈虧',
    profitLossTip: '包含庫存費和手續費',
    handCountTip: '不包含掛單',
    inventory: '庫存費',
    procedure: '手續費',
    notInclude: '不包括掛單和出入金',
    filter: '篩選',
    browseTotal: '訪問量統計',
    subscribeTotal: '跟單量統計',
    subscribeList: [
      {value: 1, name: '跟單量'},
      {value: 2, name: '訪問量'}
    ],
    totalBrowse: '總訪問量',
    totalSubscribe: '總和單量',
    tradingOrderCnt: '交易單量',
    winRate: '勝率',
    tradingHand: '交易手數',
    orderDistribute: '單量分佈',
    profitLossDistribute: '盈虧分佈',
    totalProfitExplain: '註：總損益數據包含了庫存費和手續費',
    cutDown: '最近更新',
    todayRise: '今日上升',
    today: '今天',
    totalEarnings: '累計收益',
    earningsTips:
      '累積收益：截至昨日結束時的餘額收益率，使用TWR 演算法計算。\n絕對收益：截至昨日結束時的總盈虧除以總入金量（含信用額）*100%。',
    absoluteEarnings: '絕對收益',
    noStrategy: 'TA尚未填寫此帳戶的交易策略',
    accountName: '帳戶名稱',
    totalDeposit: '累計入金',
    accountNetValue: '淨值',
    positionProfit: '持倉盈虧',
    closeProfit: '已平倉盈虧',
    accountLever: '槓桿',
    totalWithdrawal: '累計出金',
    accountBalance: '餘額',
    credit: '信用額',
    dataOverviewExplain: [
      '指定週期內所有訂單的盈虧總和。',
      '獲利訂單數佔總訂單數的百分比。',
      '平均每筆訂單的持倉時間。',
      '使用EA 交易的訂單數量佔比。',
      '指定週期內所有訂單的手數總和。',
      '獲利單的平均獲利與虧損單的平均虧損之比。',
      '平均每筆訂單的交易手數。',
      '重倉交易（訂單對資金的佔用在15% 以上）的訂單數量佔比。',
      '指定週期內的訂單數量。',
      '訂單的庫存費之和。',
      '獲利訂單的總獲利金額除以獲利訂單的數量。',
      '獲利最高的一筆訂單的獲利金額。',
      '平均每天交易的訂單數量。',
      '訂單的手續費總和。',
      '虧損訂單的總虧損金額除以虧損訂單的數量。',
      '虧損最高的一筆訂單的虧損金額。'
    ],
    positionDuration: '平均持倉時間',
    quantizedRatio: '量化交易佔比',
    totalHand: '總手數',
    avgTradingHand: '平均交易手數',
    heavyTradingRatio: '重倉交易佔比',
    totalOrderCount: '總單量',
    totalInterest: '總利息',
    avgProfit: '平均獲利金額',
    maxProfit: '單筆最大獲利',
    avgDayOrder: '日均單量',
    totalProcedure: '總手續費',
    avgLoss: '平均虧損金額',
    maxLoss: '單筆最大虧損',
    variety: '品種',
    type: '類型',
    closeTimeRange: '平倉時段',
    startTime: '起始時間',
    endTime: '結束時間',
    typeList: [
      {value: -1, name: '全部'},
      {value: 1, name: '市價單'},
      {value: 2, name: '掛單'}
    ],
    replenish: [
      {value: 4, name: '存取款'},
      {value: 8, name: '信用額'}
    ],
    period: '週期',
    openTime: '開倉時間',
    closeTime: '平倉時間',
    openClosePrice: '開/平倉價格',
    open: '開',
    close: '平',
    openPrice: '開倉價格',
    closePrice: '平倉價格',
    stopProfitLoss: '停損/停盈',
    direction: '方向',
    notice: '公告',
    cannotConnect: '無法連接到該帳戶',
    connecting: '正在連結（{x}s）',
    reconnectionNow: '立即重連',
    noBindOrPrivate: '該交易帳戶已被設為私人或解綁',
    accountInit: '帳戶初始化中，請稍後...',
    dataStatistics: '數據統計',
    tradingOrder: '交易訂單',
    subscriber: '跟單者 {0}',
    tradingNotice: '交易公告',
    comment: '評論 {0}',
    tradingReport: '虛假交易舉報 {0}',
    connectFail: '連線失敗',
    connectSuccess: '連線成功',
    browseChange: '帳戶的訪問量變化曲線，可反映該帳戶近期的熱度。',
    subscribeChange: '帳戶的跟單量變化曲線，可反映該帳戶的受歡迎程度和趨勢。',
    dataOverview: '數據概覽',
    dataDeneral: '數據總覽',
    importantIndex: '重要指標',
    plAnalysis: '盈虧分析',
    incomeStatistics: '收益統計',
    changeAccount: '切換帳戶',
    stopProfit: '停利',
    stopLoss: '停損',
    texes: '稅金',
    helpYouUndestand: '幫助您了解自己的交易帳戶',
    addAccount: '新增帳號',
    selectTraderBrokers: '請選擇交易伺服器',
    inputAccountNum: '請輸入4~16位數字',
    inputAccountPwd: '請輸入4~32位密碼',
    inputAccountExplain: '請簡單介紹您的交易策略，16~128字符',
    accountExplain: '允許或禁止其他人查看此帳戶的交易資料。 禁止後，此帳戶將不會對外展示。',
    positionExplain: '允許或禁止其他人查看此帳戶的持倉交易訂單，但此帳戶的跟隨者始終可以查看。',
    historyExplain: '允許或禁止其他人查看此帳戶的歷史交易訂單，但此帳戶的跟隨者始終可以查看。',
    commentExplain: '允許或禁止其他人對此帳戶進行評論。',
    weekReportExplain: '允許或禁止每周向我發送此帳戶的交易情況。',
    monthReportExplain: '允許或禁止每月向我發送此帳戶的交易情況。'
  },
  dataCenter: {
    market: '交易市場',
    report: '持倉報告',
    technical: '技術形態',
    profitAccount: '獲利帳戶',
    fromYesterday: '較昨日',
    actualCount: '實盤帳戶總數',
    yesterday: '昨天',
    lossAccount: '虧損帳戶',
    popularBroker: '流行交易商排行',
    popularExplain:
      '根據交易商在社群內的實盤帳戶數量形成排名，差評率則以用戶在交易帳戶詳情頁內對交易商的評價結果統計而來。',
    userSelect: '使用者選擇',
    negativeRate: '差評率',
    masterPosition: '{x} 高手持倉',
    short: '看空',
    long: '看多',
    neutral: '中性',
    blastingIntro: '出現過爆倉的實盤帳戶數',
    blastingAccount: '爆倉帳戶',
    unit: '單位：',
    accountDistribute: '帳戶分佈',
    accountChange: '帳戶數量變化',
    varietyDistribute: '交易品種分佈',
    winRateDistribute: '交易勝率分佈',
    cutOff: '截止',
    profit: '獲利',
    loss: '虧損',
    blasting: '爆倉',
    orderForm: '訂單',
    shippingSpace: '部位',
    accountRatio: '帳戶佔比',
    accountNumber: '帳戶數（個）',
    profitLossRatio: '獲利/ 虧損',
    dealStyle: '交易風格偏好',
    lossRate: '虧損率',
    dealStyleList: ['短線交易', '長線交易', '量化EA 交易', '黃金原油交易'],
    styleExplainList: [
      '持倉時間短，交易勝率高，單量可觀，深受交易者喜愛。但其損益比通常較低，屬小賺大虧型策略。',
      '長達數週甚至上月的持倉週期，極高的盈虧比，極低的交易頻率，需要交易者有十足的耐心。',
      '將手工操盤經驗總結固化為一個邏輯嚴謹的數學模型，使用EA 插件按照既定的規則自動進行交易。',
      '非常受歡迎的兩個商品期貨，具有較廣的受眾群體，在諸多交易軟體上均可操作，高手如雲。'
    ],
    styleAccountRatio: ['短線帳戶佔比', '長線帳戶佔比', '量化EA 帳戶佔比', '黃金原油帳戶佔比'],
    speculate: '投機情緒現狀',
    updateFrequency: '每15 分鐘更新一次',
    tradeVariety: '交易品種',
    accountCount: '帳戶數（個） 多/空',
    accountCountTips: '目前持倉的淨部位為做多或做空的帳戶數量',
    shippingSpaceLabel: '部位（手） 多/空',
    shippingSpaceTips: '目前持倉的多單手數總和空單手數總和，不含掛單',
    marketEmotion: '市場情緒（多/空）',
    dealStyleTip: ['包含{x} 風格的帳戶數除以社區總帳戶數。', '專注黃金或原油交易的帳戶數除以社區總帳戶數。'],
    lossRateTip: ['包含{x} 風格的帳戶中，有{y} 是虧損的。', '專注於黃金或原油交易的帳戶中，有{y} 是虧損的。'],
    accountExplain: '截至{0}({1})，共有{2} 個交易帳戶在交易{3}，其中持倉虧損的帳戶有{4} 個，持倉獲利的帳戶有{5} 個。',
    orderList: '訂單簿',
    orderListTips: '發現市場潛在的支撐/阻力位置，了解市場的價格密集成交區',
    positionChange: '持倉人數和部位變化',
    longAccountNum: '多頭帳戶數',
    shortAccountNum: '空頭帳戶數',
    netPosition: '淨頭寸',
    rise: '看漲',
    fall: '看跌',
    putOrder: '掛單',
    position: '持倉',
    marketChange: '行情和頭寸變化',
    longCash: '多頭頭寸',
    shortCash: '空頭部位',
    closePrice: '收盤價',
    upsAndDowns: '日內漲跌',
    newestPrice: '最新價',
    marketEmotion1: '市場情緒',
    currentPosition: '目前持倉訂單{x} 個',
    longOrderCount: '多單{x} 個',
    shortOrderCount: '{x} 個空單',
    price: '價格',
    subscribeCnt: '跟單量',
    windVane: '交易風向標',
    allMaster: '他們都是{x} 高手',
    longMaster: '長線高手',
    shortMaster: '短線高手',
    quantizationMaster: '量化高手',
    form: '形態',
    name: '名稱',
    variety: '品種',
    period: '週期',
    createTime: '產生時間',
    trend: '趨勢',
    dataSupport: '由FastBull 提供數據支持',
    chartTimeZone: '圖表時區',
    allForm: '所有形態',
    allVariety: '所有品種',
    allPeriod: '所有週期',
    kingList: '榜單之王',
    formDesc1:
      '鎚子線屬於底部反轉形態，是一種柱體較小，但上影線或下影線較長的 K 線（影線通常比柱體長兩倍以上）。在錘子線之前，必定先有一段下降趨勢（即使是較小規模的下降趨勢），這樣錘子線才可能夠逆轉這個趨勢。如果這是出現在上升趨勢中，則我們稱它為上吊線，而非錘子線。',
    formDesc2:
      '上吊線的實體與上吊線隔日的開盤價之間向下的缺口越大，那麼上吊線就越有可能構成市場的頂部。在上吊線之後，如果市場走出了一根陰線，而且它的收盤價低於上吊線的收盤價，那麼，這也可以看做上吊線成立的一種佐證。上吊線屬於頂部反轉形態，必須出現在一段上升趨勢之後。',
    formDesc3:
      '射擊之星又稱為“倒轉鎚頭”，彷如槍的準頭。射擊之星可以是陰線或陽線，但實體比較短小，上影線較長，其位置主要出現在頂部，是一種十分明顯的見頂訊號。這型態的形成是開盤價比較低，多頭組織力量向上攻，一度急升，但尾市賣壓加強，收盤價又回落至開盤價附近（射擊之星因為光芒短暫又被稱為「流星」） 。',
    formDesc4:
      '倒錘線與射擊之星不同的地方在於，它出現在行情的底部，表示價格有可能回升。從實際使用來看，倒錘線與射擊之星的反轉強度不如上吊線和錘子線，因此在使用時最好結合下一根 K 線及其他分析方法來進一步分析。',
    formDesc5:
      '吞沒形態通常指陰包陽或陽包陰形態，陽包陰即倒數第二根K 線為陽線，倒數第一根為陰線，且倒數第二根K 線完全包含了倒數第一根K 線，陰包陽則與此相反。此外，陽包陽和陰包陰也很常見，前者通常是賣點，後者通常是買點，但不能僅以此貿然斷定買賣方向，還是需要結合其他技術手段綜合分析。',
    formDesc6:
      '吞沒形態通常指陰包陽或陽包陰形態，陽包陰即倒數第二根K 線為陽線，倒數第一根為陰線，且倒數第二根K 線完全包含了倒數第一根K 線，陰包陽則與此相反。此外，陽包陽和陰包陰也很常見，前者通常是賣點，後者通常是買點，但不能僅以此貿然斷定買賣方向，還是需要結合其他技術手段綜合分析。',
    formDesc7:
      '三隻烏鴉也稱“黑三兵”，意思是連續出現三根向下的陰線，通常為行情崩盤的前兆，出現此類K線形態一般表明價格後勢將進一步下跌。而「紅三兵」則與此相反，紅三兵如果發生在下降趨勢中，一般是市場的強烈反轉訊號；如果市價在較長的橫盤後出現紅三兵的走勢形態，並且伴隨著成交量的逐漸放大，則是行情啟動的前奏，可引起密切關注。',
    formDesc8:
      '三隻烏鴉也稱“黑三兵”，意思是連續出現三根向下的陰線，通常為行情崩盤的前兆，出現此類K線形態一般表明價格後勢將進一步下跌。而「紅三兵」則與此相反，紅三兵如果發生在下降趨勢中，一般是市場的強烈反轉訊號；如果市價在較長的橫盤後出現紅三兵的走勢形態，並且伴隨著成交量的逐漸放大，則是行情啟動的前奏，可引起密切關注。',
    formDesc9:
      '啟明星是由三條 K 線組成的 K 線組合形態，它是一種行情見底轉勢的形態。這種形態如果出現在下降趨勢中應引起注意，因為此時趨勢已發出比較明確的反轉訊號，是一個非常好的買入時機。',
    formDesc10:
      '黃昏星與啟明星正好相反，它是較強烈的上升趨勢中出現反轉的信號。黃昏之星的K 線組合形態如果出現在上升趨勢中應引起注意，因為此時趨勢已發出比較明確的反轉信號或中短期的回調信號，對於我們來說可能是非常好的賣出時機或中短線迴避的時機。',
    formDesc13:
      '烏雲蓋頂又稱烏雲線，是 K 線圖較常見頂部反轉形態之一。這種形態由一陰一陽兩根K線組成，它們一般出現在上升趨勢之後，在有些情況下也可能出現在水平調整區間的頂部，是一個看跌信號。',
    formDesc14:
      '曙光初現由兩條走勢完全相反的較長的 K 線構成。前一天為陰線，後一天為陽線。第二天陽線向下跳空低開，開盤價遠低於前一天的收盤價；但第二天的收盤價卻高於前一天的收盤價，並且陽線的收盤價深入第一根陰線的實體部分中，至少達到前一天陰線實體的一半。',
    formDesc15:
      '十字星，是一種只有上下影線，沒有柱體的 K 線，即開盤價等於收盤價。其中：上影線越長，表示賣盤力量較大；而下影線越長，表示買盤力量較大，如果在價格的高位或低位出現較為明顯的十字線，則表示行情很有可能出現反轉。',
    formDesc16:
      '十字星，是一種只有上下影線，沒有柱體的 K 線，即開盤價等於收盤價。其中：上影線越長，表示賣盤力量較大；而下影線越長，表示買盤力量較大，如果在價格的高位或低位出現較為明顯的十字線，則表示行情很有可能出現反轉。',
    formDesc17:
      '孕線形態與吞沒形態相比，兩條 K 線的順序正好顛倒。在吞沒形態中，後面是一根長長的實體，將它前面的小實體覆蓋進去；孕線形態是後一根 K 線實體較小，並且被前一根較長的實體包容進去。此形態的名字的由來，也是緣於「懷孕」的意思。長的 K 線為「母」線，小的 K 線為「子」線，或是「胎」線，以示其包容意義。',
    formDesc18:
      '孕線形態與吞沒形態相比，兩條 K 線的順序正好顛倒。在吞沒形態中，後面是一根長長的實體，將它前面的小實體覆蓋進去；孕線形態是後一根 K 線實體較小，並且被前一根較長的實體包容進去。此形態的名字的由來，也是緣於「懷孕」的意思。長的 K 線為「母」線，小的 K 線為「子」線，或是「胎」線，以示其包容意義。',
    formDesc19:
      '孕線形態與吞沒形態相比，兩條 K 線的順序正好顛倒。在吞沒形態中，後面是一根長長的實體，將它前面的小實體覆蓋進去；孕線形態是後一根K 線實體較小，並且被前一根較長的實體包容進去（如果後一根K 線是十字星，則稱為十字孕線）。此形態的名字的由來，也是緣於「懷孕」的意思。長的 K 線為「母」線，小的 K 線為「子」線，或是「胎」線，以示其包容意義。',
    formDesc20:
      '孕線形態與吞沒形態相比，兩條 K 線的順序正好顛倒。在吞沒形態中，後面是一根長長的實體，將它前面的小實體覆蓋進去；孕線形態是後一根K 線實體較小，並且被前一根較長的實體包容進去（如果後一根K 線是十字星，則稱為十字孕線）。此形態的名字的由來，也是緣於「懷孕」的意思。長的 K 線為「母」線，小的 K 線為「子」線，或是「胎」線，以示其包容意義。',
    traderStyle: '交易偏好',
    winningAccounts: '獲利帳戶佔比',
    losingAccounts: '虧損帳戶佔比',
    dealLong: '做多',
    dealShort: '做空',
    sellingPrice: '賣價',
    buyingPrice: '買價',
    hangingOrderData: '掛單數據',
    positionOrderData: '持倉數據',
    periodicalNumber: '第{x}期',
    greatestRule: '評選規則',
    selectTraderStyle: '選擇交易品種'
  },
  user: {
    sendMsg: '發訊息',
    userId: '使用者ID',
    attention: '關注',
    collect: '收藏',
    home: '首頁',
    contest: '比賽',
    social: '社群',
    vip: '會員',
    setting: '設定',
    about: '關於',
    accountListLen: '允許綁定的交易帳戶數量上限為{x} 個。',
    addAccount: '新增帳戶',
    loginRegister: '註冊/登入',
    logoutSuccess: '退出成功',
    accountLis: '帳戶列表',
    totalAccount: '共{x} 個帳戶',
    noBindAccount: 'TA還沒有綁定交易帳戶',
    unfoldAll: '展開全部',
    foldAll: '收起全部',
    similarAccount: '相似帳戶',
    changeAccount: '換一批',
    signaturePlaceholder: '這個人很懶，什麼都沒留下',
    loginViewOrder: '登入後可查看持倉訂單',
    brokerGrade: '您認為該帳戶的交易商{x} 可靠嗎？',
    soldOut: '建議匯聊牛人榜下架該交易商，不再支援該交易商的帳戶綁定',
    accountReport: '虛假交易舉報',
    suspects: '請指出該交易帳戶的虛假點、可疑點，以便廣大匯友參考或甄別',
    reliable: '挺可靠',
    unreliable: '不可靠',
    suggestSoldOut: '建議下架',
    reportSuccess: '檢舉成功！',
    emoji: '表情',
    picture: '圖片',
    uploadFailed: '圖片上傳失敗',
    submitAfterUpload: '請在圖片上傳完成後提交！',
    addPicture: '新增圖片',
    btnTextList: ['評論', '回覆', '確定檢舉'],
    praise: '讚',
    reply: '回覆',
    writeYourComment: '請輸入回覆內容...',
    moreReply: '更多回覆',
    residueReplay: '剩餘{x} 筆回复',
    account: '帳戶',
    grade: '評級',
    subscribe: '跟單',
    accountPraise: '帳戶口碑',
    accountComment: '帳號評論',
    allComment: '所有評論',
    needComment: '大家都需要您一針見血的評論（評論無法修改與刪除，請理性評論）。',
    excellent: '優秀',
    ordinary: '一般',
    noGood: '差勁',
    commentSuccess: '評論成功！',
    replySuccess: '回覆成功！',
    inputNotice: '請輸入公告內容',
    allowNoticeCount: '交易公告每天最多允許發送{x} 條',
    totalCount: '共{x}條',
    publish: '發布',
    publishSuccess: '公告發布成功！',
    isDeleteNotice: '是否刪除公告？',
    deleteNotice: '刪除公告',
    closeComment: '該帳號已關閉評論權限',
    privateComment: '私人帳戶，不能發布評論',
    privateReport: '私有帳戶，不能發布檢舉訊息',
    length1: '請至少輸入1 個字元。',
    length512: '最多只能輸入512 個字符',
    noAccount: '還沒有交易帳戶',
    tradingPlatform: '交易軟體',
    broker: '交易商',
    brokerServer: '交易伺服器',
    dealAccountNum: '交易帳號',
    tradingPassword: '交易密碼',
    passwordExplain: '如果您不需要進行跟隨交易，輸入觀摩密碼即可。',
    inputPassword: '請輸入交易密碼',
    tradingStrategy: '交易策略',
    strategyExplain: '請簡單介紹您的交易策略。',
    passwordLength: '交易密碼為4-32 個字符',
    strategyLength: '交易策略最少需要輸入16 個字符',
    searchName: '搜尋交易商或伺服器名稱',
    record: '搜尋記錄',
    hotSearch: '熱門搜尋',
    result: '搜尋結果',
    inputAccount: '請輸入交易帳號',
    inVerification: '帳戶驗證中...',
    accountLength: '交易帳號為4-16 位數字',
    bindOvertime: '綁定帳戶超時',
    addTradingAccount: '新增交易帳戶',
    linkAccount: '連接帳戶',
    accountSetting: '帳戶設定',
    otherBind: '交易帳戶已被他人綁定',
    howToFind: '如何找回？',
    findAccount: '找回帳號',
    stepTitle: '請依下列步驟找回您被他人佔用的交易帳號：',
    findStep1: '1. 使用交易密碼登入MT4/MT5。',
    findStep2: '2. 更改交易帳戶目前的交易密碼或觀摩密碼。',
    findStep3: '3. 回到牛人榜，重新加入交易帳戶。',
    addSuccess: '添加成功',
    initExplain: '系統正在為該帳戶進行資料初始化操作，大概需要3 分鐘，初始化完成後該帳戶即可正常使用。',
    bindNow: '立即綁定',
    brokerBan: '該交易商已被停用',
    accountRate: '優：交易能力較強\n一般：交易能力一般\n差勁：交易能力較弱',
    accountReportTips: '如果交易帳號被多人舉報為虛假交易，匯聊牛人榜將向相關交易商回饋並驗證資料的真實性。',
    accountList: '帳戶列表',
    conversionRate: '轉換率',
    nowDay: '當天',
    lastSevenDay: '近7日',
    yesterday: '昨天',
    notice: '公告',
    edit: '編輯',
    totalYieldRate: '累計收益率',
    bindAccountTips: '綁定帳戶，AI評級幫您偵測交易',
    subscribeTips: '跟著交易訊號，與大咖為伍',
    toSubscribe: '去跟單',
    contesting: '正在參賽',
    season: '{x} 賽季',
    rank: '排名',
    chatroom: '聊天室',
    friend: '好友',
    groupChat: '群聊',
    topic: '話題',
    writer: '作家',
    news: '新聞',
    video: '影片',
    pictureVideo: '圖片影片',
    file: '文件',
    audio: '語音',
    chatRecord: '聊天記錄',
    followed: '已關注',
    fans: '粉絲',
    article: '文章',
    cancelCollect: '取消收藏',
    simulationGroup: '模擬帳戶組',
    actualGroup: '實盤帳戶組',
    contestData: '大賽數據',
    awardsCount: '得獎次數',
    totalAward: '獎勵總金額',
    topScore: '最高得分',
    megagameRecord: '比賽紀錄',
    entryAccount: '參賽帳戶',
    score: '分數',
    ranking: '排名',
    awards: '獎勵',
    extraAward: '額外獎勵',
    auditStatus: '審核狀態',
    status: ['審核通過', '審核失敗', '審核中'],
    noRecord: '暫無交易比賽紀錄',
    socialGroup2: '我管理的群({x})',
    socialGroup3: '我加入的群({x})',
    comeFrom: '來自於: {x}',
    socialGroup1: '我創建的群({x})',
    nextStep: '下一步',
    selectBrokers: '選擇交易伺服器',
    bindSuccess: '綁定成功',
    goFollowOrder: '去跟單',
    accountDetail: '帳戶詳情',
    bindAgain: '重新綁定',
    traderAccount: '交易帳戶',
    traderLever: '槓桿',
    subscribeNum: '跟單人數 {0}',
    depositCurrency: '存款貨幣',
    accountName: '帳戶名稱',
    withoutSignature: '未設定交易格言',
    fastbullVIP: 'Fastbull會員',
    openVipForFree: '免費開通會員',
    logout: '登出登入',
    shareFB: '分享Fastbull',
    copyLink: '複製連結',
    addFriend: '加好友',
    addFriendVerify: '加好友驗證',
    waitVerify: '等待驗證',
    added: '已新增',
    defaultVerify: '我是{x}',
    inputVerifyInfo: '請輸入驗證資訊：',
    addSuccessTip: '您的好友添加請求已經發送成功，正在等待對方確認。',
    send: '傳送',
    sendApplySuccess: '發送申請成功',
    cancelAttentionConfirm: '確定不再關注該用戶嗎？',
    userCenter: '個人中心',
    openFBAPP: '開啟APP',
    supportNewsPrice: '提供更快更全的財經新聞和報價',
    noCollect: '暫未新增收藏',
    accountPwd: '帳號密碼',
    fxchat_niu_trading_select: '請選擇交易商',
    fxchat_niu_trading_select_first: '請先選擇交易商',
    fxchat_niu_trading_server_select: '請選擇',
    fxchat_niu_account_input_hint: '4～16位數字',
    fxchat_niu_observe_account_input_hint: '4～32位密碼',
    fxchat_niu_observe_password_tip: '如果您不需要進行跟單交易，輸入觀摩密碼即可',
    fxchat_niu_trading_strategy_hint: '請簡單介紹你的交易策略，16~128字',
    fxchat_niu_account_bind: '交易帳戶被他人綁定,',
    commentAfterLogin: '請先{x}後發表評論',
    noBodyAdd: '增加失敗，對方設定了不允許任何人加好友。'
  },
  grade: {
    synthesizeGrade: '綜合評級',
    gradeTips: '綜合評級依據近六月的交易數據統計而來，每天更新一次。',
    tradeAbility: '交易能力',
    goodAtVariety: '專注品種',
    riskLevel: '風險等級',
    maxDrawdown: '最大回撤',
    viewGradeReport: '查看綜合評級報告',
    rank: '綜合排名{x} 名',
    score: '綜合得分{x} 分',
    tradeAbilityList: ['超強', '很強', '良好', '一般', '較弱', '很弱'],
    riskLevelList: ['低風險', '中風險', '高風險'],
    profitAndLoss: '帳戶盈虧',
    orderControl: '訂單控制',
    varietyData: '品種數據',
    dealStyle: '交易風格',
    dealPosition: '部位數據',
    gradeStr: ['優', '良好', '一般', '較差'],
    gradeScore: '評級得分',
    scoreTooltip:
      'A+（90 分以上），交易能力超強！<br/> A（85 分以上），交易能力很強！<br/> B+（80 分以上），交易能力良好！<br/> B（75 分以上），交易能力一般！<br/> C+（60 分以上），交易能力較弱！<br/> C（60 分以下），交易能力很弱！',
    tradeGrade: '交易評級',
    gradeExplain: '綜合評級以近六月的評級結果為準，評級資訊每天更新一次',
    yieldRateTooltip: '指定時段內的餘額收益率，使用TWR 演算法計算。',
    maxDrawdownTooltip:
      '指定時段內，淨值（若無淨值資料則以餘額資料取代）曾出現過的最大跌幅。因出入金影響，該數值可能超過100%。',
    yieldRiskRatioTooltip:
      '收益率/ 最大回撤率。當收益率小於等於0 時，收益風險比直接取0；當最大回撤為0 時，收益風險比則取100。',
    yieldRiskRatio: '收益風險比',
    orderTotalTooltip: '指定時段內的訂單數量。',
    orderTotal: '訂單總數',
    dealFrequencyTooltip: '指定時段內平均每天交易的訂單數量。',
    dealFrequency: '交易頻率',
    frequencyUnit: '{x} 單/天',
    stopProfitRateTooltip: '指定時段內的訂單中，設有停盈或停損的訂單佔比。',
    stopProfitRate: '停損率',
    varietyFreight: '品種部位',
    heavyRatioTooltip: '指定時段內的訂單中，重倉交易（訂單對資金的佔用在15% 以上）的訂單數量佔比。',
    heavyRatio: '重倉比例',
    focusVarietyTooltip: '指定時段內，經常交易的品種數量。',
    focusVariety: '專注品種',
    profitLossRatioTooltip:
      '指定時段內的訂單中，獲利單的平均獲利與虧損單的平均虧損之比。當平均虧損為0 時，盈虧比則取100。',
    profitLossRatio: '盈虧比',
    dealStyleTooltip: '指定時段內的交易風格。',
    profitPositionTooltip: '指定時段內的訂單中，獲利單的平均持倉時長。',
    profitPosition: '獲利單平均持倉',
    lossPositionTooltip: '指定時段內的訂單中，虧損單的平均持倉時長。',
    lossPosition: '虧損單平均持倉',
    gradeResult: '評級結果僅供參考，不構成任何投資建議',
    general: '整體概況',
    evaluateList: [
      '訂單數量太少，無法準確評級',
      '給自己打個氣，逆水行舟，不進則退',
      '專業能力還有待提高',
      '還可以再進一步，不要當韭菜',
      '表現很棒，繼續努力',
      '當之無愧的交易牛人',
      '天才級的交易水準'
    ],
    profitAbility: {
      worst: '盈利能力非常差',
      veryBad: '盈利能力很差',
      bad: '盈利能力較差',
      needToImprove: '盈利能力有待提高',
      common: '盈利能力一般',
      strong: '盈利能力較強',
      stronger: '獲利能力很強',
      strongest: '獲利能力非常強'
    },
    earnings: {
      veryInstability: '收益很不穩定。',
      instability: '收益不太穩定。',
      stabilize: '收益較穩定。',
      veryStabilize: '收益很穩定。',
      mostStabilize: '收益非常穩定。'
    },
    dealRisk: {
      lowest: '交易風險很低',
      smaller: '交易風險較小',
      controlled: '交易風險可控',
      high: '交易風險偏高',
      higher: '交易風險很高',
      gigantic: '交易風險巨大'
    },
    earningsRiskRatio: {
      worst: '收益風險比非常差。',
      veryBad: '收益風險比很差。',
      needToImprove: '收益風險比有待提高。',
      rational: '收益風險比合理。',
      good: '收益風險比很好。',
      veryGood: '收益風險比非常好。'
    },
    avgDailyYield: '帳戶平均日化{x}',
    avgWeekYield: '帳戶平均週化{x}',
    avgMonthYield: '帳戶平均月化{x}',
    dayProfit: '日盈餘機率為{x}',
    monthProfit: '月盈餘機率為{x}',
    maxDrawdownIs: '而最大回撤為{x}',
    earningsRiskValue: '收益風險比為{x}',
    dealFrequencyExplain: [
      '交易頻率控制較好，請繼續保持，畢竟做得越多，做錯的幾率越大。',
      '交易頻率偏高，適當降低交易頻率，有助於更好的控制風險。'
    ],
    stopExplain: [
      '由於停盈或停損設定率較低，可能會有一定的交易風險。',
      '交易目標較不明確，善用停盈或停損，可在一定程度上降低交易風險。',
      '交易目標通常比較明確，進出場需謹慎，不打無把握的仗。',
      '交易目標明確，具有良好的交易習慣。'
    ],
    accumulativeDeal: '累計交易{x} 天',
    avgOrder: '平均每天{x} 單',
    stopPercent: '對{x} 的訂單設定了止盈止損',
    heavyExplain: [
      '具有良好的部位風控意識，整體部位控制較合理。',
      '偶爾進行重倉交易。',
      '時常進行重倉交易，務必做好風險控制。',
      '重倉交易太過頻繁，可能產生極高的交易風險，請謹慎。'
    ],
    heavyPercent: '在{x} 個訂單中，重倉佔比為{y}',
    suggestion: '建議為所有重倉單帶好停損，摒棄賭博思維，做好風險控制。',
    noFocus: '無任何專注品種或擅長品種，建議專註一兩個品種，或許能更好的提升交易能力。',
    focusVarietyAt: '專注的品種為{x}，',
    focusCount: '專注於{x} {y}個品種，',
    profitLossStr: '在這個品種上累積盈虧為{x}，還需要繼續努力，把它做得更好。',
    profitLossTotal: '它們的損益和為{x}，繼續加油。',
    goodAtStr: '最擅長{x}，其利潤佔了總利潤的{y}，繼續加油。',
    tradingStyle: ['日內交易', '短線交易', '長線交易', '量化交易', '無交易風格'],
    tradingType: ['日內', '短線', '長線', '量化'],
    winAndRatio: '{x}單的勝率在{y} 左右，盈虧比在{z} 左右。',
    beGoodAt: '擅長{x}',
    noTradingStyle: '沒有明確的交易風格，短線單的勝率在{x}，長線單的勝率在{y}。',
    avgPosition: '總平均持股時長為{x}，獲利單平均獲利{y}，虧損單平均虧損{z}。',
    joinAndRate: '加入牛隻榜\n評測您的交易能力',
    rated: '已評測{x} 個交易帳戶，平均分數{y}',
    rateNow: '立即評測',
    isTheRating: 'AI評級正在為您評級，請稍後…',
    scoreTips:
      '綜合得分還包含了另外三項附加分，用於衡量交易帳戶在用戶評價、逆勢扛單以及生存週期等方面的表現。<br/>口碑附加分：{x} 分<br/>持倉附加分：{y} 分<br/>週期附加分：{z} 分',
    warmPrompt: '溫馨提示',
    traderForShort: '短線交易',
    traderForLong: '長線交易',
    traderForQuantification: '量化交易',
    traderForGold: '黃金原油交易',
    traderForShortTip: '短線交易簡介',
    traderForLongTip: '長線交易簡介',
    traderForQuantificationTip: '量化交易簡介',
    traderForGoldTip: '黃金原油交易簡介',
    goldMaster: '黃金原油高手'
  },
  subscribe: {
    openSubscribe: '開通跟單權限',
    connectionNormal: '帳戶連線狀態正常',
    accountIsReal: '帳戶類型為實盤帳戶',
    notAbnormal: '未被系統標記為異常帳戶',
    brokerCompliance: '所屬交易商為合規交易商',
    equityMoreThan: '帳戶淨值不低於1000.00$',
    openNow: '立即開通',
    openSuccess: '跟單權限開通成功',
    disqualification: '該帳戶不符合開通條件',
    openCondition: '成為訊號提供者，需滿足以下條件：',
    closeSubscribe: '關閉跟單權限',
    closeSubscribeConfirm: '您確定要關閉此交易帳戶的跟單權限嗎？',
    closePunishmentExplain: '該帳戶名下已有{x} 個跟單者，如果此時關閉跟單權限，系統將根據社區規則對您進行以下懲罰：',
    punishment: '禁止該交易帳戶的跟單權限，為期90 天。',
    consider: '再想想',
    closeNow: '立即關閉',
    closeSuccess: '跟單權限關閉成功',
    lengthen: '延長跟單',
    follow: '跟單',
    selectAccount: '請選擇跟隨帳戶',
    alreadyFollow: '已跟隨帳戶',
    followDays: '已跟隨{x} 天，{y} 到期',
    notFollow: '未跟隨帳戶',
    accountIsDelete: '跟隨帳戶已被刪除。',
    accountDelete: '信號帳戶已被刪除。',
    subscribeForbid: '該帳戶的跟單權限已被禁止。',
    subscribeClose: '該帳戶沒有開通跟單權限。',
    closeAfterExpire: '該帳戶不再允許跟單。',
    followAccountOffline:
      '您的交易賬戶<span>#{x}</span>已掉線，暫時無法使用。如果該賬戶的連接密碼已被更改，請<a target="_blank" href="{y}">前往賬戶設置</a>頁更新連接密碼。',
    brokerForbid: '牛隻榜將不再支援交易商{x}，因此，該交易商下的交易帳戶也將不再允許跟單。',
    fictitiousTradesTips: '該帳戶可能有虛假交易，已被禁止跟單。',
    violateRuleTips: '由於您違反付費跟單規則，系統已禁止您跟單牛人榜內的任何訊號。如有疑問，請聯絡客服。',
    limitationUser: '受限用戶',
    subscribeWarning: '跟單警告',
    riskAccountTips: '該帳戶可能有較高風險，請謹慎跟單。切勿輕信他人，避免上當受騙。',
    userAbnormalTips: '該帳戶所屬用戶出現異常，請謹慎跟單。',
    noCanFollow: '暫無可跟隨帳戶，',
    noAccount: '\n您還沒有綁定交易帳戶，',
    accountOffline: '該帳戶已斷線，暫時無法使用。',
    brokerLimit: '交易商受限',
    accountFollowTips:
      "您的交易賬戶<span>#{x}</span>當前使用的連接密碼爲觀摩密碼，不具有交易權限，因此無法在牛人榜內進行跟隨交易。<br/>\n您需<a target='_blank' href='{y}'>前往賬戶設置</a>將該賬戶的連接密碼更新爲<span>交易密碼</span>，然後再進行跟單。",
    dealLimit: '交易受限',
    forbidSubscribe: '禁止跟單',
    followSuccess: '跟單成功',
    followSetting: '設定跟單參數',
    subscriber: '跟單者',
    subscribeTypeList: [
      {value: 1, name: '正在跟單'},
      {value: 2, name: '歷史跟單'}
    ],
    params: '跟單參數',
    subscribeTime: '跟單時間',
    subscribePeriod: '跟單週期',
    subscribeEndTime: '跟單結束時間',
    totalSubscribePeriod: '累計跟單時長',
    otherUser: '他還在跟單',
    patternList: [
      {name: '固定手數', value: 1},
      {name: '固定比例', value: 2}
    ],
    directionList: [
      {name: '正向跟隨', value: 1},
      {name: '反向跟隨', value: 2},
      {name: '只跟隨平倉', value: 3}
    ],
    notice: '跟單公告',
    moreTradingNotice: '查看更多交易公告<br/>請前往交易帳號詳情頁',
    hot: '熱門跟單',
    count: '跟單量',
    allSource: '全部來源',
    detail: '跟單詳情',
    cancelTips: '如果只是想暫停跟隨交易，請前往跟單設定窗口，將跟隨狀態設為「關」即可',
    cancel: '取消跟單',
    setting: '跟單設定',
    detailStatusList: ['', '跟單中', '已到期', '已取消', '已退款', '未開始'],
    orderId: '訂單ID',
    startTime: '開始時間',
    endTime: '結束時間',
    cancelTime: '取消時間',
    cancelReason: '取消原因',
    notStartTips: '「未開始」的訂單將在「跟單中」的訂單到期後開始生效',
    confirmTocancel: '確定要取消跟單？',
    subscribeStartTime: '跟單開始時間',
    followAccount: '跟隨帳戶',
    followStatus: '跟隨狀態',
    followStateTips: '關閉跟隨後，既無法跟隨開倉，也無法跟隨平倉。但您仍會在訊息中心收到訊號帳戶的開平倉訊號。',
    baseSetting: '基本設定',
    varietySetting: '品種設置',
    followNotice: '跟隨須知',
    followPattern: '跟隨模式',
    followPatternTips:
      '固定比例：根據訊號帳戶與跟隨帳戶之間的淨值關係來計算跟隨手數，並按此處指定的比例倍數來放大或縮小手數大小。<br/> 固定手數：無論訊號帳號開多少手，均只按此處指定的手數來跟隨開倉。如無特殊要求，建議使用「固定比例」跟隨。',
    maxHand: '最大移動次數',
    maxHandTips: '單筆跟隨開倉手數若超過此限定值，則依此限定值開倉。',
    noLimit: '不限制',
    followDirection: '跟隨方向',
    followDirectionTips: '只跟隨平倉：即不再跟隨訊號帳戶的開倉操作，只跟隨平倉操作。',
    contractSize: '合約大小',
    contractSizeTips:
      '相同品種的合約大小在不同平台上可能不一樣，這會導致跟隨手數不正確。本功能僅在跟隨模式為「固定比例」時生效。',
    sizeList: [
      {name: '自適應', value: 1},
      {name: '忽略', value: 2}
    ],
    signalAccount: '訊號帳戶',
    followLimit: '交易限制',
    followLimitTips:
      '此功能用於限制跟隨帳戶只進行指定類別的交易。<br/> 假設跟隨方向為【反向跟隨】，EURUSD 的交易限制為【只開空單】，若：<br/> 訊號源開EURUSD 多單，跟隨帳戶反向之後應開空單，與交易限制不衝突，開空。<br/> 訊號源開EURUSD 空單，跟隨帳戶反向後應開多單，但與交易限制衝突，不開多。<br/>',
    setManually: '無法識別，請手動設定',
    limitList: [
      {name: '不限制', value: 0},
      {name: '只開空單', value: 1},
      {name: '只開多單', value: 2},
      {name: '禁止開倉', value: 3}
    ],
    followRuleContent:
      '跟隨規則：<br/> 1. 掛單不會立即跟隨，當其成交為市價單時，方才進行跟隨。<br/> 2. 停盈/停損不會跟隨，以避免跨平台跟隨時因交易環境（價格、點差等）的差異而導致的提前出場等問題。<br/> 3. 合約自適應功能並非支援所有品種，如股指、期貨、股票等品種便不被支持。<br/> 4. 開倉手數若超過交易商規定的最大手數或低於交易商規定的最小手數，則按最大手數或最小手數開倉。<br/> 5. 受各端網路環境影響，交易訊號可能會產生延遲。若訊號被延遲太久，應放棄跟隨。因此，系統預設會丟棄延遲時間超過180s 的開倉訊號或超過30 分鐘的平倉訊號。',
    notMatchTips:
      '跟隨帳戶下有{x} 個品種無法與訊號帳戶下的交易品種相匹配，導致它們無法進行跟隨交易，請在「品種設定」欄位下予以確認。',
    maxLotsMoreThan: '最大開倉手數不得小於固定開倉手數',
    allMatchTips: '在「品種設定」欄位下，請務必確保訊號帳戶與跟隨帳戶的品種名稱已被映射正確，否則將導致跟隨異常。',
    hasConfirm: '我已確認',
    gotoCheck: '前往核實',
    settingSuccess: '設定成功',
    mySubscribe: '我跟單的',
    account: '訊號帳戶',
    currPosition: '目前持倉',
    yesterdayEarnings: '昨日收益',
    monthEarnings: '近1月收益',
    status: '跟單狀態',
    statusList: ['跟單中', '{x} 天後到期', '即將到期'],
    totalTime: '累積跟單時長',
    operation: '操作',
    viewToAccount: '查看跟單我的人，請前往<a target="_blank" href="{x}">交易帳戶詳情</a>頁面',
    times: '倍',
    connectionAnomaly:
      '您的交易帳戶#{x} 已斷線，暫時無法使用。<br/>如果該帳號的連線密碼已被更改，請前往個人中心-交易帳號-帳號設定頁更新連線密碼。',
    passwordTypeTips:
      '您的交易帳戶#{x} 目前使用的連線密碼為觀摩密碼，不具有交易權限，因此無法在牛人榜內進行跟隨交易。<br/>您需前往個人中心-交易帳號-帳號設定頁將該帳號的連線密碼更新為交易密碼，然後再進行跟單。',
    goNow: '立即前往',
    warmPrompt: '小提醒：<br/> 1. 您可隨時進入「個人首頁」->「跟單」欄位下修改您的跟隨設定。<br/>',
    fixedHands: '固定移動次數',
    fixedRatio: '固定比例',
    fixedRatioTips: '根據訊號帳戶與跟隨帳戶之間的淨值關係來計算跟隨手數，並按此處指定的比例倍數來放大或縮小手數大小。',
    fixedHandsTips: '無論訊號帳戶開多少手，均只按此處指定的手數來跟隨開倉。如無特殊要求，建議使用「固定比例」 跟隨。',
    ratio: '{x} 倍',
    signalVariety: '品種(訊號帳戶)',
    followVariety: '品種(跟隨帳戶)',
    selectVariety: '選擇品種',
    searchVariety: '搜尋品種',
    hasQuestion: '遇到問題？請聯絡<span>官方客服</span>',
    subscribeInfo: '跟單訊息',
    followAgain: '再次跟單',
    residueLong:
      '您的跟單權限剩餘時長為{0} 個月，暫不支援繼續延長跟單。<br/>注意，剩餘的跟單時長最長只支援{1} 個月。因此，您可在剩餘的跟單時長不到{2} 個月時再來延長跟單。',
    subscribeExpire: '跟單期滿',
    closeTips: '只想接收訊號，不跟單，可關閉跟隨狀態',
    shareGetFollow: '分享取得跟單權限功能已停用，請前往會員中心開通會員後進行跟單',
    signalNotFollow: '訊號帳戶不支援跟單',
    initNotFollow: '初始化中，請稍後重試'
  },
  header: {
    searchLabel: '搜尋',
    product: '產品',
    market: '市場',
    information: '資訊',
    signal: '訊號',
    match: '比賽',
    activity: '活動',
    broker: 'Brokers',
    more: '更多',
    chart: '圖表',
    stockFilter: '篩選器',
    financialCalendar: '財經日曆',
    toolKit: '工具',
    cost: '價格',
    feature: '功能特色',
    dataMarket: '市場數據',
    overview: '概覽',
    myOptional: '我的自選',
    news: '新聞',
    transactionAnalysis: '分析',
    quickInformation: '快訊',
    column: '專欄',
    answer: '專家問答',
    data: '數據',
    video: '影片',
    institutionalViewPoint: '機構觀點',
    analystViewPoint: '分析師觀點',
    columnTopic: '專欄議題',
    columnist: '專欄作家',
    dataCenter: '數據中心',
    marketTrend: '市場動向',
    institutionalData: '機構數據',
    centralBankInterestRate: '央行利率',
    macroEconomy: '總體經濟',
    niuList: '牛榜',
    bestNiuer: '每週精選',
    AISignal: '最新訊號',
    fansActivity: '粉絲交流會',
    web_ib_seminar: 'IB研討會',
    voteActivity: '紅人評選',
    web_fans_hongkong: '中國·香港',
    web_fans_hochiminh: '越南·胡志明',
    web_fans_dubai: '杜拜',
    web_fans_cairo: '埃及·開羅',
    web_fans_nigeria: '奈及利亞·拉各斯',
    business: '商業',
    recruit: '招募',
    aboutUs: '關於我們',
    whiteLabel: '白標',
    dataAPI: '資料API',
    webPlugins: '網頁插件',
    feedback: '意見回饋',
    helpCenter: '幫助中心',
    agreement: '用戶協議',
    policy: '隱私政策',
    comingSoon: '即將上線',
    marketPrice: '行情',
    calendar: '日曆',
    quotation: '報價',
    PRO: 'Pro',
    AIRating: 'AI評級',
    latestViewPoints: '最新觀點',
    calendarWallpaper: '日曆壁紙',
    speculativeMood: '投機情緒',
    hangingOrderPosition: '掛單持倉',
    varietyCorrelation: '品種相關性',
    popularIndex: '熱門指標',
    hotTopic: '熱門話題',
    recentUpdate: '最近更新',
    language: '語言',
    popularSearch: '熱門搜尋',
    historySearch: '最近搜尋',
    myCollection: '我的收藏',
    myConcern: '我的關注',
    mySubscription: '我的跟單',
    personalInformation: '個人訊息',
    memberCenter: '會員中心',
    accountSetting: '帳號設定',
    logOut: '登出',
    scanDownload: '掃一掃，下載',
    moreInformation: '更快的財經資訊和報價',
    downloadApp: '下載 APP',
    addFBToDesk: '新增 FastBull 到桌面',
    loadFromDesk: '下次可以從電腦桌面直接存取 FastBull',
    addToDesk: '新增到桌面',
    recommendSelfSelection: '推薦自選',
    waitingForDeal: '待成交',
    inTransaction: '交易中',
    overDeal: '交易結束',
    overdue: '已過期',
    profitMaking: '獲利',
    lossMaking: '虧損',
    profitLoss: '盈虧',
    financialTools: '金融工具',
    homePage: '首頁',
    clickLogin: '點擊登入',
    AppDescription: '更快更全的財經新聞報價',
    supportResistance: '支撐阻力',
    copyright: 'Copyright © {x} FastBull Ltd',
    risk: '風險披露',
    riskText1:
      '交易股票、貨幣、商品、期貨、債券、基金等金融工具或加密貨幣屬高風險行為，這些風險包括損失您的部分或全部投資金額，所以交易並非適合所有投資者。',
    riskText2:
      '做出任何財務決定時，應該進行自己的盡職調查，運用自己的判斷力，並諮詢合格的顧問。本網站的內容並非直接針對您，我們也未考慮您的財務狀況或需求。本網站所含資訊不一定是即時提供的，也不一定是準確的。本站提供的價格可能由造市商而非交易所提供。您做出的任何交易或其他財務決定均應完全由您負責，並且您不得依賴通過網站提供的任何資訊。我們不對網站中的任何資訊提供任何保證，並且對因使用網站中的任何資訊而可能造成的任何交易損失不承擔任何責任。',
    riskText3:
      '未經本站書面許可，禁止使用、儲存、複製、展現、修改、傳播或分發本網站所含數據。提供本網站所含數據的供應商及交易所保留其所有知識產權。',
    cookieTips:
      '我們使用 cookie 來了解您如何使用我們的網站並改善您的體驗，包括個性化內容。 如繼續使用我們的網站，即表示您接受我們使用 cookies。 如您想了解更多，請 點擊這裡',
    viewDetail: '查看詳情',
    authorization: '授權使用',
    function: '功能',
    company: '公司',
    user: '使用者',
    theLatestValue: '最新值',
    allSearchResult: '查看所有搜尋結果',
    loginBtn: '登入',
    signUPBtn: '註冊',
    freeToOpenVIP: '免費開通VIP',
    web_opinion_hot_author: '热门作家',
    market_finance_coverview: '概覽',
    freeForevet: '',
    moduleDark: '',
    loginForMoreFunc: '',
    noLogin: ''
  },
  sideLayout: {
    news_calendar_filter_only_import: '只看重要',
    news_snowfall: '相關連接',
    news_unscramble: '快訊解讀',
    news_unscramble_long: '長期',
    news_unscramble_short: '短期',
    news_unscramble_bearish: '利空',
    news_unscramble_bullish: '利多',
    calendar_time_up: '時間',
    calendar_prev_up: '前值',
    calendar_est_up: '預測值',
    calendar_act_up: '公佈值',
    calendar_unrelease: '未公佈',
    calendar_revised: '修正前',
    calendar_act: '公佈值',
    calendar_est: '預測值',
    calendar_prev: '前值',
    new_share: '分享',
    vip_invite_friends_immediately: '分享給好友，免費得會員',
    vip_invite_friends_title: '立即分享',
    qa_header_title: '專家問答',
    qa_header_online: '網路答疑',
    qa_ask_question: '我要問...',
    qa_post_first_question: '快來發布第一條提問吧',
    qa_expert: '專家',
    qa_view_translation: '查看翻譯',
    qa_view_original: '看原文',
    qa_answer: '回答',
    qa_cancel_answer: '取消回答',
    qa_answer_placeholder: '回答{0}',
    qa_confirm_delete_question: '確認刪除該條提問？',
    qa_confirm_delete_answer: '確認刪除該條回答？',
    qa_select_pic_format: '請選擇png、jpg、jpeg、gif、bmp，webp格式',
    qa_common_bottom: '我是有底線的',
    qa_remind_max_char: '最多輸入{0}個字元',
    qa_cancel_reply: '取消回覆',
    qa_reply_someone: '回覆{0}',
    quote_nav_more: '更多',
    quote_link_more: '查看更多',
    quote_table_asset: '資產',
    quote_table_last: '最新價',
    quote_table_netchg: '漲跌額',
    quote_table_chg: '漲跌幅',
    quote_table_update: '更新時間',
    news_news_trending: '熱門',
    quote_table_high: '最高',
    quote_table_low: '最低',
    quote_watchlist: '自選',
    quote_my_watchlist: '我的自選',
    reminderg: '提醒設定',
    maincontainer_market: '行情',
    news_flash: '快訊',
    news_calendar: '日曆',
    q_a: '問答',
    home_tab_chat: '聊天',
    common_side_layout: '佈局',
    common_layout_single: '單列佈局',
    common_layout_vertical: '上下佈局',
    common_layout_tile: '並列佈局',
    cale_unpublish_time: '{0}後公布',
    cale_unpublish_time_h: '{0}時',
    cale_unpublish_time_min: '{0}分',
    add_asset_name: '添加資產名稱或代碼',
    add_to_favorites: '添加自選',
    recentlyViewed: '最近瀏覽',
    common_market_closed: '市場關閉',
    chart_indicator: '指標',
    chart_strategy: '策略',
    chart_edit: '編輯器',
    chart_backtest: '回調',
    chart_order: '新訂單',
    chart_template: '範本',
    chart_sync: '同步',
    chart_history: '歷史',
    chart_remind: '提醒',
    chart_log: '紀錄',
    chart_connect: '正在連接伺服器，請稍後...',
    searchStocksTips: '在主視窗按 A-Z 或 0-9 任意鍵，即可啟動品種搜尋'
  },
  dataCollect: {
    fxchat_login_edit_user_info_title: '編輯個人訊息(1/3)',
    fxchat_login_complete_material_title: '完善您的資料(2/3)',
    fxchat_login_recommendation_title: '優質推薦(3/3)',
    fxchat_information_nick_name: '暱稱',
    fxchat_login_field_title: '輸入您的暱稱',
    fxchat_information_sex: '性別',
    fxchat_information_sex_man: '男',
    fxchat_information_sex_women: '女',
    fxchat_information_sex_other: '其他',
    fxchat_information_sex_secret: '保密',
    fxchat_material_morning: 'Hi，“{0}”早安! 歡迎來到FastBull',
    fxchat_material_noon: 'Hi，“{0}”午安! 歡迎來到FastBull',
    fxchat_material_afternoon: 'Hi，“{0}”午安! 歡迎來到FastBull',
    fxchat_material_night: 'Hi，“{0}”晚安! 歡迎來到FastBull',
    fxchat_material_introduction: '為了推薦給您更優質的內容，請簡單介紹一下自己吧。',
    fxchat_recommendation_subtitle: '根據您所選資料，為您精準推薦。',
    fxchat_material_summarize: '太棒了！根據您提供的訊息，我們將定制專屬優質的內容給您。',
    fxchat_material_assistant_name: 'AI機器人',
    fxchat_material_look: '立即查看',
    fxchat_material_reselect: '重新選擇',
    fxchat_recommendation_see_more: '查看更多',
    fxchat_recommendation_open_fxchat: '開啟FastBull',
    fxchat_recommendation_open_group: '群聊',
    fxchat_recommendation_open_niu: '熱門達人',
    fxchat_not_group_introduction: '群主很懶，還沒有群組介紹~',
    fxchat_recommendation_join: '加入',
    fxchat_recommendation_has_join: '已加入',
    fxchat_login_skip: '跳過',
    fxchat_recommendation_follow: '關注',
    fxchat_recommendation_has_follow: '已關注',
    fxchat_login_trading_type: '您比較有興趣的交易市場？ （可多選）'
  },
  setting: {
    personalData: '個人資料',
    accountSafety: '帳戶安全',
    informSetting: '通知設定',
    privacy: '隱私',
    blacklist: '黑名單',
    remove: '移除',
    shieldingTime: '拉黑時間: {x}',
    addStyle: '加我為好友的方式',
    allowAll: '允許任何人加好友',
    needVerify: '需要發送驗證訊息',
    notAllowAny: '不允許任何人加好友',
    findByPhone: '透過手機找到我',
    findByPhoneTips: '關閉後，其他用戶將無法透過上述資訊找到你',
    follow: '跟單',
    followTips: '開啟後，跟單資訊將對外顯示',
    contest: '比賽',
    contestTips: '開啟後，比賽資訊將對外顯示',
    emailNotice: '電子郵件通知偏好',
    weeklySelection: 'FastBull每週市集精選資訊',
    willPushNews: '我們將為你推播您近期關注的相關重大資訊新聞',
    sendWeek: '每週發送',
    dailyHighlights: 'FastBull今日市場重大資訊',
    sendDay: '每天發送一次（週一-週五）',
    baseInfo: '基本訊息',
    nickname: '暱稱',
    joinStyle: '入群方式',
    aphorism: '交易格言',
    editInfo: '編輯個人資訊',
    interestInfo: '感興趣的訊息',
    noAddInterest: '暫未添加感興趣的內容~',
    dealPlatform: '交易平台',
    dealMarket: '交易市場',
    dealVariety: '交易品種',
    dealStyle: '交易風格',
    avatar: '頭像',
    modifyAvatar: '修改頭像',
    username: '用戶名',
    sex: '性別',
    dealAge: '交易年齡',
    address: '所在地',
    industry: '從事行業',
    modify: '修改',
    addIndustry: '增加從事行業',
    userIntro: '個人簡介',
    interestDealInfo: '有興趣的交易訊息',
    add: '添加',
    sexList: [
      {value: 0, name: '男'},
      {value: 1, name: '女'},
      {value: 2, name: '保密'}
    ],
    industryType: '行業類型',
    inIndustry: '業內行業',
    outIndustry: '非業內行業',
    interestPlayform: '有興趣的交易平台',
    interestMarket: '有興趣的交易市場',
    interestStyle: '有興趣的交易風格',
    interestVariety: '有興趣的交易品種',
    maxOption: '最多可以選擇{x}項',
    blackTypeList: [
      {value: 1, name: '通訊錄'},
      {value: 2, name: '群組聊天'}
    ],
    accountInfo: '帳號資訊',
    userPassword: '使用者密碼',
    haveSet: '已設定',
    isNotSet: '未設定',
    phoneNumber: '手機號碼',
    notBind: '未綁定',
    bind: '綁定',
    email: '郵件地址',
    bindThird: '綁定第三方',
    unBind: '解除',
    bindPhone: '綁定手機號',
    changePhone: '修改手機號碼',
    inputPhone: '請輸入手機號',
    and: '和',
    inputPhoneTips: '請輸入正確的手機號',
    inputVerifyCode: '請輸入4位驗證碼',
    oldPhoneNumber: '原手機號碼',
    newPhoneNumber: '新手機號碼',
    bindEmailOpen: '請綁定郵件信箱開啟帳密登入功能',
    bindEmail: '綁定信箱',
    setPassword: '設定密碼',
    password: '密碼',
    inputPwd: '請輸入密碼',
    pwdRules: '密碼要求6-20位，包含數字、字母、符號中至少2種',
    updatePwd: '修改密碼',
    currentPwd: '目前密碼',
    forgetPwd: '忘記密碼？',
    newPwd: '新密碼',
    pwdNotSame: '兩次密碼不一致',
    emailResetPwd: '輸入您的電子郵件地址，我們將向您發送連結以重設您的密碼',
    sendResetLink: '發送重置連結',
    inputEmail: '請輸入郵件號碼',
    inputRightEmail: '請輸入正確的信箱',
    alreadSendLink: '我們已經向您發送了一個連結來重置您的密碼',
    alreadSendTo: '我們已發送一封郵件到',
    noGetFindHelp: '如果您在5分鐘內沒有收到一封信，請檢查「垃圾郵件」或尋求協助',
    findHelp: '尋求協助',
    getVerifyCode: '取得驗證碼',
    notGet: '仍未收到？',
    resend: '重發郵件',
    inputCode: '請輸入驗證碼',
    beGetting: '正在獲取...',
    resendAfter: '{x} s 後可重發',
    selectAvatar: '選擇頭像',
    customAvatar: '自訂頭像',
    reUpload: '重新上傳',
    defaultAvatar: '預設頭像',
    imgType: '僅支援 {x} 的圖片格式!',
    inputNickname: '請輸入暱稱',
    inputUsername: '請輸入使用者名稱',
    usernameTips: '使用者名稱只能包含小寫字母、數字、底線、句點。更改你的用戶名也將更改你的個人主頁鏈接'
  },
  vip: {
    equities: '權益',
    detail: '明細',
    hasCode: '我有兌換碼',
    inputCode: '請輸入兌換碼',
    conversion: '兌換',
    shareGet: '分享免費得會員',
    shareGetYear: '分享免費領1年會員',
    inviteUser: '邀請的新用戶點擊你分享的鏈接，完成登入註冊後即可獲得1年會員時長',
    scanQRCode: '手機掃描二維碼',
    shareLink: '分享連結領取會員',
    recharge: '儲值得會員',
    agree: '我已閱讀並同意',
    agreement: '會員服務協議',
    privilege: '會員特權',
    time: '時間',
    duration: '取得會員時長',
    getMode: '獲取方式',
    status: '狀態',
    redeemRules: '兌換碼使用規則：\n1.已啟動的兌換碼無法再次使用\n2.超過兌換碼有效期限無法使用',
    privilegeList: [
      {id: 1, title: 'AI快訊快速達', desc: '即時快速送達更多精選快訊內容'},
      {id: 2, title: '追蹤更多行情品種', desc: '可增加更多自選品種，即時追蹤更多行情數據'},
      {id: 3, title: '宏觀數據、經濟指標更全面', desc: '更全面的指標歷史數據，協助分析宏觀市場'}
    ],
    shareTitle: '我在FastBull開通了超值VIP，最高價值1648元，快來領取吧~'
  },
  promotion: {
    volumnMuteDefault: '默認靜音播放',
    enableVolumn: '開啟聲音',
    kolInterview: 'KOL專訪',
    userComment: '用戶評價',
    moreFunction: '更多功能',
    moreFunctionTxt: '探索新功能，你想要的這裡都有！'
  },
  tdk: {
    title: 'FastBull - 更快的財經資訊和報價',
    homeTitle: '外匯神級人物_外匯達人榜_外匯達人盤點 - （品牌字）',
    homeDesc: 'FastBull 達人榜，讓您跟隨最賺錢的投資者，學習他們的策略，提升交易水準。',
    greatestTitle: 'FastBull每週精選\n',
    greatestDesc: 'FastBull每周精選，收益、量化、單量、勝率，評選出最優秀的投資者。',
    helpTitle: '幫助中心-FastBull',
    helpDesc: '在我們的幫助中心尋找常見問題的答案和有用的資源。',
    userTitle: '【{x}】- 個人主頁',
    userDesc: '透過個人主頁，找到志同道合的交易者吧。'
  },
  about: {
    downloadApp: '下載APP',
    aboutFb: '關於 FastBull',
    fbExplain:
      'FastBull是金融互聯網的技術創新者，我們在眾多地區建立了編輯和翻譯團隊，並將繼續致力於各國的在地化內容建立。 同時我們擁有最具技術實力和規模的研發團隊和產品團隊，將在未來持續提供頂級的軟體體驗。',
    service: '提供的服務',
    product: '產品',
    productExplain: '我們已上架財經日曆和工具功能，更多重磅功能即將上線：超級圖表，股票篩選器，市場數據等敬請期待。',
    signal: '訊號',
    signalExplain: '資訊、牛人榜、每週精選、最新訊號、比賽。 交易大佬做單訊號即時提供，可即時跟單交易，讓交易更簡單。',
    message: '資訊',
    messageExplain:
      '新聞、快訊、分析、專欄、數據、影片。 涵蓋全球即時熱點，分析師的交易觀點，和機構觀點數據。 同時7X24小時即時更新熱點事件，財經數據。',
    market: '市場',
    marketExplain:
      '我們提供了，外匯市場、商品、指數，美股，虛擬貨幣，CME等市場行情。 未來我們將持續提供全球股票市場及ETF、債券等市場行情。',
    business: '商業',
    businessExplain: '我們提供一些免費/付費的第三方服務，白標、資料API、網頁插件，提供資料來源支援和技術支援。',
    course: '發展歷程',
    contact: '聯絡我們',
    partner: '合作夥伴',
    email: '官方信箱',
    feedback: '意見回饋',
    scan: '掃碼體驗',
    android: 'Android版',
    ios: 'iOS版',
    downloadTips: '與全球投資者即時討論、分享你的交易想法和觀點',
    chat: '即時聊天',
    chatExplain: '匯聚全球交易達人，暢聊交易',
    chart: '社交圖表',
    chartExplain: '分析行情、討論交易、訂閱訊號',
    realTimeSignal: '即時訊號',
    realTimeSignalExplain: '真實交易訊號，免費跟單',
    contest: '交易競賽',
    contestExplain: '展現交易能力的最佳舞台',
    answer: '專家解惑',
    answerExplain: '向專家提問，免費取得專業意見',
    analyse: '交易分析',
    analyseExplain: '觀摩學習投資專家的交易邏輯',
    calendar: '財經日曆',
    calendarExplain: '專業分析工具深入解讀經濟數據',
    news: '精選新聞',
    newsExplain: '匯聚全球金融專家的深度觀點',
    tools: '海報工具',
    toolsExplain: '支援個人化客製化各類金融海報',
    more: '更多',
    moreExplain: '下載FastBull，體驗更多精彩功能',
    downloadFrom: '下載自'
  },
  chat: {
    headTabs: ['全部', '聊天室', '群聊', '好友'],
    placeInput: '請輸入...',
    connecting: '正在連接聊天室'
  }
}
