export default {
  common: {
    confirm: 'Xác nhận',
    affirm: 'Xác nhận',
    remove: 'Xóa',
    cancel: 'Hủy',
    tips: 'Lưu ý',
    finish: 'Xong',
    know: 'OK',
    time: 'Thời gian',
    count: '{x} ',
    hand: '{x} lot',
    order: '{x} lệnh',
    score: '{x} point',
    person: '{x} người',
    times: '{x} lần',
    second: '{x} giây',
    minutes: '{x} phút',
    hour: '{x} giờ',
    day: '{x} ngày',
    month: '{x} tháng',
    year: '{x} năm',
    shortsecond: '{x}s',
    shortminutes: '{x} min',
    shorthour: '{x}h',
    shortday: '{x}d',
    justNow: 'Vừa qua',
    minuteAgo: '{x} phút trước',
    hourAgo: '{x} giờ trước',
    yesterday: '{x}, hôm qua',
    beforeYesterday: '2 ngày trước',
    yearUnit: 'Năm',
    monthUnit: 'Tháng',
    dayUnit: 'Ngày',
    hourUnit: 'Giờ',
    minutesUnit: 'Phút',
    secondUnit: 'Giây',
    hundredMillion: '{x} tỷ',
    trillion: '{x} nghìn tỷ',
    loading: 'Đang tải...',
    noMore: 'Không có dữ liệu nhiều hơn',
    all: 'Tất cả',
    reset: 'Đặt lại',
    unfoldAll: 'Xem tất cả',
    packUp: 'Thu gọn',
    unfold: 'Xem thêm',
    back: 'Quay lại',
    warning: 'Cảnh báo',
    noData: 'Không có dữ liệu',
    imageFormat: 'Chỉ hỗ trợ định dạng ảnh JPG, JPEG hoặc PNG!',
    imageSize: 'Kích thước hình ảnh không được vượt quá {x} MB',
    shareFb: 'Chia sẻ FastBull và nhận quyền sao chép giao dịch 1 tháng',
    noNetLaterTry: 'Kết nối mạng bất thường, vui lòng thử lại sau...',
    copy: 'Sao chép',
    copySuccess: 'Đã sao chép Link',
    appDownload: 'Tải xuống APP-FastBull',
    fbDownload: 'Tải xuống APP FastBull',
    getSuccess: 'Đã nhận được quyền sao chép giao dịch 1 tháng',
    reLogin: 'Trạng thái đăng nhập đã hết hạn, vui lòng đăng nhập lại.',
    notFound: 'Xin lỗi, địa chỉ trang web không chính xác hoặc trang này không tồn tại',
    returnToLast: 'Quay lại ',
    returnToHome: 'Quay về trang chủ',
    forbidden: 'Truy cập bị từ chối',
    noAccess: 'Bạn không có quyền xem thư mục hoặc trang này bằng thông tin đăng nhập bạn đã cung cấp.',
    serverError: 'Error',
    tryRefresh: 'Hãy làm mới trang và thử lại',
    operationConfirm: 'Xác nhận',
    select: 'Chọn',
    download: 'Tải xuống',
    close: 'Đóng',
    isDelete: 'Đã xóa',
    noResult: 'Xin lỗi, không tìm thấy kết quả liên quan',
    tryAgain: 'Bạn có thể thay đổi từ khóa và tìm kiếm lại',
    loginInOther:
      'Tài khoản của bạn được đăng nhập trên một trình duyệt khác. Nếu không tự mình thực hiện, mật khẩu có thể bị rò rỉ, hãy đổi mật khẩu ngay lập tức.',
    chartLoading: 'Đang tải biểu đồ...',
    custom_service: 'Dịch vụ Khách hàng',
    common_look: 'Xem'
  },
  message: {
    messageCenter: 'Thông báo',
    system: 'Thông báo cộng đồng',
    trading: 'Tín hiệu giao dịch',
    comment: 'Trả lời',
    account: 'Thông báo tài khoản',
    answer: 'Q&A cùng chuyên gia',
    noMoreData: 'Không có dữ liệu nhiều hơn',
    viewAll: 'Xem tất cả',
    noNewMsg: 'Không có tin tức mới',
    noMessage: 'Tin nhắn trống',
    systemMsgTypeList: [
      {type: 0, nhãn: 'Tất cả nội dung'},
      {type: 1, label: 'Thông báo Cộng đồng'},
      {type: 3, label: 'Tôi đang sao chép'},
      {type: 4, label: 'Người sao chép tôi'}
    ],
    commentMsgTypeList: [
      {type: 0, label: 'Bình luận tài khoản'},
      {type: 1, label: 'Bình luận tin tức'},
      {type: 2, label: 'Bình luận video'}
    ],
    accountMsgTypeList: [
      {type: 0, nhãn: 'Tất cả nội dung'},
      {type: 1, label: 'Trạng thái bị thay đổi'},
      {type: 2, label: 'Cập nhật xếp hạng'},
      {type: 4, label: 'Báo cáo giao dịch'}
    ],
    open: 'Vào lệnh',
    openTime: 'Thời gian vào lệnh',
    close: 'Đóng lệnh',
    closeTime: 'Thời gian đóng lệnh',
    riskWarning: 'Cảnh báo Rủi ro',
    subscribeNotice: 'Thông báo',
    clickView: 'Xem chi tiết',
    allSource: 'Tất cả nguồn',
    replyYou: 'đã trả lời bạn',
    answerYou: 'đã trả lời câu hỏi của bạn',
    commentAccount: 'đã bình luận tài khoản giao dịch của bạn',
    commentYou: 'đã bình luận bạn',
    viewDetail: 'Xem chi tiết',
    commentTypeList: ['Bình luận tài khoản', 'Trả lời'],
    reportAccount: 'đã báo cáo tài khoản giao dịch của bạn',
    waitFollow: 'Đang chờ sao chép',
    followSuccess: 'Sao chép thành công',
    followFailed: 'Sao chép thất bại',
    ignore: 'Đã bỏ qua',
    tryFollow: 'Đang sao chép tín hiệu này, vui lòng chờ đợi...',
    followOrder: 'Sao chép giao dịch',
    followStatus: 'Trạng thái sao chép',
    unit: 'Đơn vị',
    noSignal: 'Chưa có tín hiệu giao dịch',
    orderId: 'ID lệnh sao chép',
    statusList: ['Chờ sao chép', 'Sao chép thành công', 'Sao chép thất bại', 'Đã bỏ qua'],
    statusTitle: ['Lý do chờ đợi', ' ID Sao chép giao dịch', 'Lý do thất bại', 'Lý do bỏ qua'],
    goSetting: 'Đi tới phần cài đặt',
    viewOrder: 'Xem chi tiết lệnh',
    stopProfit: 'TP',
    stopLoss: 'SL',
    openPrice: 'Giá vào lệnh',
    closePrice: 'Giá đóng lệnh',
    delist: 'Nội dung này đã bị gỡ xuống',
    remove: 'Nội dung này đã bị xóa'
  },
  home: {
    actualIntro: 'Tổng số tài khoản thật',
    actual: 'Tổng số tài khoản thật',
    profitIntro: 'Tài khoản thật sinh lời',
    profitAccount: 'Tài khoản sinh lời',
    lossIntro: 'Tài khoản thật thua lỗ',
    lossAccount: 'Tài khoản thua lỗ',
    blastingIntro: 'Số lượng tài khoản thật bị thanh lý',
    blastingAccount: 'Tài khoản bị thanh lý',
    allMen: 'Tất cả Top Traders',
    openAccountToDate: 'Từ khi mở tài khoản đến nay',
    lastJune: '6 tháng qua',
    already: 'Đã sao chép',
    yieldValueChart: 'Tỷ lệ lợi nhuận (TWR)',
    favor: 'Bạn có thể thích',
    refresh: 'Đổi',
    unlimited: 'Tất cả',
    rank: 'Đánh giá tổng thể',
    earnings: 'Tỷ lệ lợi nhuận',
    riskLevel: 'Mức độ rủi ro',
    broker: 'Nhà môi giới',
    goodAt: 'Giỏi về',
    moreOptions: 'Nhiều hơn',
    dealWinRate: 'Tỷ lệ thắng',
    ratio: 'Tỷ lệ lời/lỗ',
    openTime: 'Thời gian mở tài khoản',
    capital: 'Tiền gửi',
    accountType: 'Loại tài khoản',
    platform: 'Nhà môi giới',
    clear: 'Xóa',
    noContent: 'Không có nội dung liên quan',
    noBroker: 'Không tìm thấy nhà môi giới phù hợp',
    accountRatingRangeList: [
      {value: 1, label: 'A'},
      {value: 2, label: 'B'},
      {value: 3, label: 'C'}
    ],
    twrRangeList: [
      {value: '', label: 'Tất cả'},
      {value: 2, label: '0%~30%'},
      {value: 3, label: '30%~60%'},
      {value: 4, label: '60%~100%'},
      {value: 5, label: '100%~200%'},
      {value: 6, label: '>200%'}
    ],
    riskLevelList: [
      {value: 1, label: 'Thấp'},
      {value: 2, label: 'Trung bình'},
      {value: 3, label: 'Cao'}
    ],
    winRateRangeList: [
      {value: 0, label: 'Tất cả'},
      {value: 2, label: '>50%'},
      {value: 3, label: '>60%'},
      {value: 4, label: '>70%'},
      {value: 5, label: '>80%'},
      {value: 6, label: '>90%'}
    ],
    profitLossRatioRangeList: [
      {value: 0, label: 'Tất cả'},
      {value: 2, label: '>0.5'},
      {value: 3, label: '>1.0 '},
      {value: 4, label: '>1.5'},
      {value: 5, label: '>2.0'},
      {value: 6, label: '>2.5'},
      {value: 7, label: '>3.0'}
    ],
    openingTimeRangeList: [
      {value: 0, label: 'Tất cả'},
      {value: 1, label: '≤1 tháng'},
      {value: 2, label: '> 1 tháng'},
      {value: 3, label: '> 3 tháng'},
      {value: 4, label: '> 6 tháng'},
      {value: 5, label: '> 12 tháng'}
    ],
    amountOfFundsRangeList: [
      {value: 0, label: 'Tất cả'},
      {value: 1, label: '<100'},
      {value: 2, label: '100~1000'},
      {value: 3, label: '1000~3000'},
      {value: 4, label: '3000~10000'},
      {value: 5, label: '10000~100000'},
      {value: 6, label: '100000~300000'},
      {value: 7, label: '>300000'}
    ],
    accountTypeList: [
      {value: 1, label: 'Tài khoản thật'},
      {value: 2, label: 'Tài khoản Demo'}
    ],
    orderList: [
      {value: 2, name: 'Tỷ lệ lợi nhuận'},
      {value: 3, name: 'Sụt giảm tối đa'},
      {value: 4, name: 'Tỷ lệ thắng'},
      {value: 5, name: 'Tỷ lệ lời/lỗ'},
      {value: 6, name: 'Số người sao chép'}
    ],
    niuTopTypeList: ['Lợi nhuận cao nhất', 'Giao dịch EA tốt nhất', 'Số lượng lệnh nhiều nhất', 'Tỷ lệ thắng cao nhất'],
    threeMonthData: 'Dữ liệu trong 3 tháng qua',
    dataFieldList: ['Lợi nhuận/ngày', 'Tỷ lệ giao dịch định lượng', 'Số lượng lệnh/ngày', 'Tỷ lệ thắng'],
    threeMonthEarnings: 'Lợi nhuận 3 tháng',
    positionDuration: 'Nắm giữ trung bình',
    lastThreeMonth: '3 tháng qua',
    detail: 'Chi tiết',
    appraise: 'Bảng xếp hạng hàng tuần',
    nextUpdate: 'Cập nhật lần tới',
    currentStage: 'Xếp hạng hiện tại',
    stage: 'Kỳ {x}',
    nobodyOnTheList: 'Không có danh sách trong kỳ này',
    ruleContent:
      'Xếp hạng các nhà giao dịch hàng đầu lần lượt về P/L, EA, số lượng giao dịch và tỷ lệ thắng trong 3 tháng qua. Các tài khoản có lợi nhuận với hồ sơ giao dịch xuất sắc đủ điều kiện để xếp hạng hàng tuần.',
    udpateTime: 'Cập nhật vào mỗi thứ bảy',
    weeklySelection: 'Đề xuất hàng tuần',
    totalAccountNum: 'Tổng số tài khoản ',
    echartMeaning: 'Tuyết minh',
    transactionSoftwareList: [
      {value: 2, label: 'MT4'},
      {value: 1, label: 'MT5', disabled: true}
    ],
    infiniteTxt: 'Không giới hạn',
    selectBrokerNum: 'Đã chọn {x} nhà môi giới',
    moreSelect: 'Nhiều lựa chọn',
    indexSubTabItem1: 'Tỷ lệ lợi nhuận: 60%~100%',
    indexSubTabItem2: 'Rủi ro thấp',
    indexSubTabItem3: '12 tháng trở lên',
    indexSubTabItem4: 'Mức tài sản: 10000USD~100000USD',
    indexSubTabItem5: 'Tỷ lệ thắng > 90%',
    indexSubTabItem6: 'Tỷ lệ lời lỗ > 3',
    filterNiuTitle: 'Chọn Top trader',
    selectBrokerTitle: 'Chọn nhà môi giới',
    allTimePeriod: 'Tất cả thời gian',
    searchBroker: 'Tìm kiếm một nhà môi giới',
    KOLInterview: 'Phỏng vấn KOL',
    userEvaluation: 'Đánh giá từ người dùng',
    interestBroker: 'Nhà môi giới mà bạn quan tâm'
  },
  aiRating: {
    gradeTimes: 'Số lần AI đánh giá',
    dataCutOff: 'Tính đến {x}',
    gradeModel: 'Mô hình đánh giá đa chiều',
    modelIntro:
      'Hệ thống AI đanh giá tiến hành đánh giá toàn diện các tài khoản giao dịch từ năm khía cạnh: lời lỗ, lệnh giao dịch, sản phẩm giao dịch, phong cách giao dịch, đồng thời đánh giá khách quan về khả năng sinh lời, tính ổn định và rủi ro v.v.',
    sample: 'Một lượng lớn dữ liệu',
    sampleIntro:
      'Hàng nghìn tài khoản giao dịch, hàng chục triệu lệnh giao dịch, và kết quả đánh giá khách quan và công bằng là sự công nhận tốt nhất đối với Hệ thống AI Đánh giá.',
    highAccount: 'Tài khoản cao cấp',
    highIntro: 'Khả năng sinh lời tốt, và tính ổn định và việc quản lý rủi ro cũng tốt.',
    profitAccount: 'Tài khoản sinh lời',
    middleAccount: 'Tài khoản trung cấp',
    middleIntro: 'Có khả năng sinh lời nhất định nhưng còn phải cải thiện về tính ổn định và việc quản lý rủi ro.',
    lowAccount: 'Tài khoản sơ cấp',
    lowIntro: 'Khả năng sinh lời kém và rủi ro giao dịch rất lớn.',
    moreClient: 'Xếp hạng càng cao, khách hàng càng nhiều',
    moreIntro:
      'Xếp hạng càng cao, tài khoản càng mạnh và khả năng được khách hàng theo dõi, sao chép giao dịch. Trong danh sách các tài khoản được đăng ký sao chép giao dịch của Top Traders, có hơn {x} tài khoản đều là tài khoản cấp A trở lên.',
    allUse: 'Họ đang sử dụng',
    yourScore:
      'Hệ thống AI đánh giá mang lại cho bạn số điểm thực tế nhất cho bài thi giao dịch của bạn. Hãy đến và xem điểm của bạn ~',
    profitLoss: 'Lời lỗ',
    orderForm: 'Lệnh',
    position: 'Vị thế',
    variety: 'Sản phẩm giao dịch',
    style: 'Phong cách'
  },
  account: {
    settingOptions: [
      {value: 1, name: 'Cài đặt dữ liệu'},
      {value: 2, name: 'Cài đặt quyền'}
    ],
    deleteAccount: 'Xóa tài khoản',
    sureToDelete: 'Bạn có chắc chắn xóa tài khoản giao dịch này không?',
    deleteMatters: 'Lưu ý: Tài khoản giao dịch đã bị bạn xóa sẽ không thể bị ràng buộc lại trong vòng bảy ngày.',
    confirmDelete: 'Xác nhận',
    cancelSubscribeBeforeDel:
      'Tài khoản này hiện đang đăng ký sao chép giao dịch từ {x} tài khoản tín hiệu. Nếu bạn muốn xóa tài khoản này, vui lòng hủy đăng ký sao chép giao dịch trước.',
    deleteSuccess: 'Xóa thành công {x}',
    deleteFailed: 'Xóa thất bại {x}',
    settingSaved: 'Đã lưu cài đặt',
    accountPermission: 'Quyền tài khoản',
    subscribePermission: 'Quyền sao chép giao dịch',
    accountPrivate:
      'Quyền truy cập tài khoản đã bị tắt và người khác không thể sao chép giao dịch của tài khoản này. <br/>\nĐể bán tín hiệu giao dịch, hãy cài đặt quyền truy cập tài khoản thành "Công khai" và bật quyền cho phép sao chép giao dịch.',
    commentPermission: 'Quyền bình luận',
    accountcommentForbid:
      'Quyền bình luận cho tài khoản này đã bị hệ thống vô hiệu hóa. Nếu bạn có bất kỳ câu hỏi nào, vui lòng liên hệ với Dịch vụ Khách hàng.',
    positionOrder: 'Lệnh',
    historyOrder: 'Lịch sử giao dịch',
    weeklyReport: 'Gửi cho tôi tình hình giao dịch hàng tuần.',
    monthlyReport: 'Gửi cho tôi tình hình giao dịch hàng tháng.',
    tradingDayReport: 'Báo cáo hàng ngày',
    tradingWeekReport: 'Báo cáo hàng tuần',
    tradingMonthReport: 'Báo cáo hàng tháng',
    linkAbnormal: 'Kết nối bất thường',
    linkAbnormalExplain:
      'Tình trạng kết nối của tài khoản giao dịch này bất thường, vui lòng không sao chép giao dịch của tài khoản này.',
    riskAccount: 'Tài khoản Rủi ro',
    riskAccountExplain:
      'Tài khoản giao dịch này có rủi ro thua lỗ cao, vui lòng thực hiện sao chép giao dịch một cách thận trọng.',
    abnormalAccount: 'Tài khoản bất thường',
    abnormalAccountExplain:
      'Tính xác thực của tài khoản giao dịch này còn nhiều nghi vấn, vui lòng thực hiện sao chép giao dịch một cách thận trọng.',
    sixMonthEarnings: 'Lợi nhuận 6M',
    actualAccount: 'Tài khoản Thật',
    virtualAccount: 'Tài khoản Demo',
    balance: 'Số dự',
    netValue: 'Tài sản ròng',
    maxDrawdown: 'Sụt giảm tối đa',
    drawdownTips:
      'Kể từ thời gian mở tài khoản, mức sụt giảm tối đa (%) trong tài sản.<br/>\n       Đối với các tài khoản giao dịch mới được liên kết, mức rút vốn tối đa trước đó, sẽ được tính toán theo dữ liệu số dư. <br/>\n       Vui lòng lưu ý rằng, thuật toán sụt giảm tối đa của MT4 có tồn tại một số sai sót nhất định, và Top Traders đã có chỉnh sửa thuật toán này để làm cho kết quả chính xác hơn, do đó kết quả tính toán mức sụt giảm tối đa của chúng có thể không nhất trí.',
    deposit: 'Gửi tiền',
    withdrawal: 'Rút tiền',
    fetch: 'Tiền rút',
    save: 'Tiền gửi',
    creditFetch: 'Tiền gửi tín dụng',
    creditSave: 'Tiền rút tín dụng',
    dealAccount: 'Tài khoản giao dịch',
    dataSynchronizationErr: 'Đồng bộ dữ liệu thất bại, vui lòng kiểm tra tài khoản hoặc mật khẩu!',
    notOpen: 'Chưa có sẵn, vui lòng theo dõi',
    signalProvider: 'Trở thành nhà cung cấp tín hiệu',
    tradingAccountSetting: 'Cài đặt tài khoản giao dịch',
    profitLossRatio: 'Tỷ lệ lời lỗ',
    dateOptions: [
      {value: 0, name: 'Tất cả '},
      {value: 1, name: '1 tháng qua'},
      {value: 2, name: '3 tháng qua'},
      {value: 3, name: '6 tháng qua'},
      {value: 4, name: '12 tháng qua'}
    ],
    yieldRate: 'Tỷ lệ lợi nhuận',
    totalProfitLoss: 'Tổng lời lỗ',
    synthesizeRank: 'Xếp hạng tổng thể',
    rankTips: 'Xếp hạng tổng thể dựa trên điểm tổng hợp của các tài khoản trực tiếp',
    synthesizeScore: 'Điểm đánh giá tổng thể',
    scoreTips:
      'Đánh giá tài khoản giao dịch từ nhiều khía cạnh như lời lỗ, lệnh giao dịch, khối lượng vị thế, sản phẩm giao dịch và phong cách giao dịch.',
    periodList: [
      {value: 1, name: 'Ngày'},
      {value: 2, name: 'Tuần'},
      {value: 4, name: 'Tháng'}
    ],
    profitLossTitle: ['Lời lỗ hàng ngày', 'Lời lỗ hàng tuần', 'Lời lỗ hàng tháng'],
    forbidBroker:
      'Top Traders không còn hỗ trợ nhà môi giới {x} nữa và tài khoản giao dịch của nhà môi giới này sẽ không thể liên kết tới cộng đồng này. Đồng thời, tài khoản giao dịch của nhà môi giới sẽ không được phép sao chép giao dịch.',
    accountSetting: 'Cài đặt tài khoản',
    earningsReport: 'Thống kê lợi nhuận',
    clickToView: 'Nhấp vào thanh để xem báo cáo giao dịch',
    openAccountTime: 'Thời gian mở tài khoản',
    currency: 'Tiền gửi',
    timeZone: 'Múi giờ',
    cutOff: 'Dữ liệu tính đến',
    profitLoss: 'Lời lỗ',
    handCount: 'Lot',
    orderCount: 'Số lượng lệnh',
    balanceOptions: [
      {
        value: 1,
        name: 'Nguyên thủy',
        content:
          'Đường cong Số dư/Tài sản nguyên gốc, nhưng vì sự ảnh hưởng của hoạt động gửi và rút tiền, cho nên nó có thể xuất hiện khoảng trống.'
      },
      {
        value: 2,
        name: 'Sửa đổi',
        content:
          'Đã điều chỉnh dữ liệu gửi/rút tiền để làm mịn hơn cho đường cong Số dư/Tài sản ròng, và phản ứng thực tế hơn đối với xu hướng biến động của Số dư/Tài sản ròng. Phương pháp này sẽ không tạo ra sự sai lệch.'
      }
    ],
    varietyDistribute: 'Sản phẩm giao dịch',
    timesOptions: [
      {value: 1, name: 'Khối lượng vị thế'},
      {value: 2, name: 'Số lượng lệnh'}
    ],
    profitDistribute: 'Lời lỗ',
    profitDirection: 'Mua/Bán',
    incomeOptions: [
      {value: 1, name: 'Mua/Bán'},
      {value: 2, name: 'Lời lỗ'}
    ],
    positionTime: 'Thời gian nắm giữ',
    holdOptions: [
      {value: 1, name: 'Vị thế'},
      {value: 2, name: 'Lời lỗ'}
    ],
    totalAvg: 'Thời gian nắm giữ trung bình',
    profitAvg: 'Thời gian nắm giữ lệnh thắng',
    lossAvg: 'Thời gian nắm giữ lệnh thua',
    loading: 'Đang tải',
    promptContent:
      '<p>Lưu ý:</p>\n1. Trong khi tính toán, đã loại trừ dữ liệu lệnh chờ và dữ liệu gửi/rút tiền. <br/>\n2. Đánh giá tổng hợp và dữ liệu thống kế được cập nhật vào 08:00 mỗi ngày (GMT+8). <br/>\n3. Bất kể loại tiền gửi vào tài khoản là gì, khi kết thúc dữ liệu thống kê liên quan đến lời lỗ, chúng tôi sử dụng ký hiệu $ để chỉ ra rằng dữ liệu đó là dữ liệu lời lỗ; <br/>\n4. Thuật toán mức sụt giảm tối đa của MT4 có tồn tại một số sai sót nhất định, do đó, Top Traders đã cải thiện nó và làm cho nó chính xác hơn, do đó có sự khác biệt giữa MT4 và nền tảng của chúng tôi;\n5. Lời lỗ và Tỷ lệ rủi ro/lợi nhuận tối đa là 100,00; Tỷ lệ lợi nhuận tối đa 100,00w%.<br/>"',
    totalOrder: 'Tổng cộng {x} lệnh. Đã tải {y}',
    longOrder: 'Lệnh Mua',
    shortOrder: 'Lệnh Bán',
    longShort: 'Mua/Bán',
    shippingSize: 'Khối lượng vị thế',
    profitOrder: 'Lệnh thắng',
    lossOrder: 'Lệnh thua',
    orderPosition: 'Khối lượng vị thế',
    orderProfitLoss: 'Lời lỗ',
    profitLossTip: 'Bao gồm phí qua đêm và phí hoa hồng',
    handCountTip: 'Trừ lệnh chờ',
    inventory: 'Phí qua đêm',
    procedure: 'Phí hoa hồng',
    notInclude: 'Trừ lệnh chờ và gửi/rút tiền',
    filter: 'Lọc',
    browseTotal: 'Thống kê lượt truy cập',
    subscribeTotal: 'Thống kê số lượng sao chép',
    subscribeList: [
      {value: 1, name: 'Lượng sao chép'},
      {value: 2, name: 'Lượt truy cập'}
    ],
    totalBrowse: 'Tổng lượt truy cập',
    totalSubscribe: 'Tổng lượng sao chép',
    tradingOrderCnt: 'Tổng lượng lệnh giao dịch',
    winRate: 'Tỷ lệ thắng',
    tradingHand: 'Số lot giao dịch',
    orderDistribute: 'Lệnh',
    profitLossDistribute: 'Lời lỗ',
    totalProfitExplain: 'Lưu ý: tổng lời lỗ sẽ tính thêm phí qua đêm phí hoa hồng',
    cutDown: 'Cập nhật mới nhất',
    todayRise: 'Mức tăng hôm nay',
    today: 'Hôm nay',
    totalEarnings: 'Lợi nhuận tích lũy',
    earningsTips:
      'Lợi nhuận tích lũy: tỷ suất lợi nhuận tính đến ngày hôm qua. Tính theo thuận toán TWR. <br/>\n      Lợi nhuận tuyệt đối: Tổng lời/lỗ ÷ Tổng số tiền gửi (gồm tín dụng) × 100% (tính đến ngày hôm qua).',
    absoluteEarnings: 'Lợi nhuận tuyệt đối',
    noStrategy: 'Người dùng này chưa để lại chiến lược giao dịch',
    accountName: 'Tên tài khoản',
    totalDeposit: 'Tiền gửi tích lũy',
    accountNetValue: 'Tài sản ròng',
    positionProfit: 'Lời lỗ thả nổi',
    closeProfit: 'Lời lỗ thực tế',
    accountLever: 'Đòn bẩy',
    totalWithdrawal: 'Tiền rút tích lũy',
    accountBalance: 'Số dư',
    credit: 'Tín dụng',
    dataOverviewExplain: [
      'Tổng lời lỗ trong một khoảng thời gian nhất định',
      'Tỷ lệ phần trăm tổng số lệnh thắng so với tổng số lệnh giao dịch.',
      'Thời gian nắm giữ lệnh giao dịch trung bình.',
      'Tỷ lệ lệnh giao dịch EA',
      'Tổng số lot của tất cả lệnh giao dịch trong một khoảng thời gian nhất định.',
      'Tỷ lệ lợi nhuận trung bình của các lệnh thắng so với thua lỗ trung bình của các lệnh thua.',
      'Số lot trung bình/lệnh.',
      'Tỷ lệ số lượng lệnh giao dịch với khối lượng vị thế lớn (hơn 15% tổng số vốn tài khoản).',
      'Tổng số lệnh giao dịch trong một khoảng thời gian nhất định.',
      'Tổng phí qua đêm của tất cả lệnh giao dịch.',
      'Tổng lợi nhuận của các lệnh thắng ÷ Tổng số lệnh thắng.',
      'Lợi nhuận tối đa của một lệnh giao dịch.',
      'Số lượng lệnh giao dịch trung bình/ngày.',
      'Tổng phí hoa hồng.',
      'Tổng thua lỗ của các lệnh thua ÷ Tổng số lệnh thua.',
      'Thua lỗ tối đa của một lệnh giao dịch.'
    ],
    positionDuration: 'Thời gian nắm giữ trung bình',
    quantizedRatio: 'Giao dịch EA',
    totalHand: 'Tổng số lot',
    avgTradingHand: 'Số lot trung bình',
    heavyTradingRatio: 'Vị thế khối lượng lớn',
    totalOrderCount: 'Tổng số lệnh',
    totalInterest: 'Tổng lãi suất',
    avgProfit: 'Lợi nhuận trung bình',
    maxProfit: 'Lời tối đã/lệnh',
    avgDayOrder: 'Số lượng lệnh/ngày',
    totalProcedure: 'Tổng phí hoa hồng',
    avgLoss: 'Lỗ trung bình',
    maxLoss: 'Lỗ tối đa/lệnh',
    variety: 'Sản phẩm giao dịch',
    type: 'Loại',
    closeTimeRange: 'Thời gian đóng lệnh',
    startTime: 'thời gian bắt đầu',
    endTime: 'Thời gian kết thúc',
    typeList: [
      {value: -1, name: 'Tất cả'},
      {value: 1, name: 'Lệnh thị trường'},
      {value: 2, name: 'Lệnh chờ'}
    ],
    replenish: [
      {value: 4, name: 'Gửi/Rút tiền'},
      {value: 8, name: 'Tín dụng'}
    ],
    period: 'Chu kỳ',
    openTime: 'Thời gian vào',
    closeTime: 'Thời gian đóng',
    openClosePrice: 'Giá Vào/Đóng',
    open: 'Vào',
    close: 'Đóng',
    openPrice: 'Giá vào lệnh',
    closePrice: 'Giá đóng lệnh',
    stopProfitLoss: 'SL/TP',
    direction: 'Mua/Bán',
    notice: 'Thông báo',
    cannotConnect: 'Không thể kết nối với tài khoản này',
    connecting: 'Đang kết nối ({x}s)',
    reconnectionNow: 'Kết nối lại ngay',
    noBindOrPrivate: 'Tài khoản giao dịch đã được đặt ở chế độ riêng tư hoặc không bị ràng buộc',
    accountInit: 'Đang khởi tạo tài khoản, vui lòng đợi...',
    dataStatistics: 'Số liệu thống kê',
    tradingOrder: 'Lệnh giao dịch',
    subscriber: '{0} Người sao chép',
    tradingNotice: 'Thông báo',
    comment: '{0} Bình luận',
    tradingReport: '{0} Báo cáo',
    connectFail: 'Kết nối thất bại',
    connectSuccess: 'Kết nối thành công',
    browseChange: 'Đường cong thay đổi lượt truy cập, có thể phản ánh mức độ phổ biến gần đây của tài khoản này.',
    subscribeChange:
      'Đường cong thay đổi lượt đăng ký sao chép của tài khoản có thể phản ánh mức độ phổ biến và xu hướng của tài khoản này.',
    dataOverview: 'Tổng quan Dữ liệu ',
    dataDeneral: 'Tổng quan về dữ liệu',
    importantIndex: 'Chỉ báo quan trọng',
    plAnalysis: 'Phân tích lời lỗ',
    incomeStatistics: 'Thống kế lợi nhuận',
    changeAccount: 'Thay đổi tài khoản',
    stopProfit: 'TP',
    stopLoss: 'SL',
    texes: 'Thuế',
    helpYouUndestand: 'Cải thiện hiệu suất giao dịch của bạn',
    addAccount: 'Thêm tài khoản',
    selectTraderBrokers: 'Chọn máy chủ',
    inputAccountNum: 'Nhập 4~16 ký tự',
    inputAccountPwd: 'Nhập mật khẩu 4~32 ký tự',
    inputAccountExplain: 'Vui lòng giới thiệu ngắn gọn về chiến lược giao dịch của bạn (16~128 ký tự)',
    accountExplain:
      'Cho phép hoặc cấm người dùng khác xem dữ liệu giao dịch của tài khoản này. Sau khi cấm, tài khoản này sẽ không không khai.',
    positionExplain:
      'Cho phép hoặc cấm người dùng khác xem lệnh giao dịch của tài khoản này. Người sao chép giao dịch của tài khoản này ',
    historyExplain:
      'Cho phép hoặc cấm người dùng khác xem lịch sử lệnh của tài khoản này. Người sao chép giao dịch của tài khoản này ',
    commentExplain: 'Cho phép hoặc cấm người dùng khác bình luận tài khoản này',
    weekReportExplain: 'Cho phép hoặc cấm gửi tình hình giao dịch của tài khoản này cho tôi mỗi tuần.',
    monthReportExplain: 'Cho phép hoặc cấm gửi tình hình giao dịch của tài khoản này cho tôi mỗi tháng.'
  },
  dataCenter: {
    market: 'Thị trường',
    report: 'Báo cáo COT',
    technical: 'Mô hình nến',
    profitAccount: 'Tài khoản sinh lời',
    fromYesterday: 'So với hôm qua',
    actualCount: 'Tổng số tài khoản thật',
    yesterday: 'Hôm qua',
    lossAccount: 'Tài khoản thua lỗ',
    popularBroker: 'Xếp hạng các nhà giao dịch phổ biến',
    popularExplain:
      'Bảng xếp hạng dựa trên tất cả các tài khoản thật của các nhà môi giới trong cộng đồng của chúng tôi. Tỷ lệ đánh giá tốt/kém dựa trên kết quả đánh giá các nhà môi giới từ người dùng trang phần Chi tiêt tài khoản.',
    userSelect: 'Lựa chọn người dùng',
    negativeRate: 'Tỷ lệ đánh giá tiêu cực',
    masterPosition: 'lệnh từ chuyên gia',
    short: 'Bán',
    long: 'Mua',
    neutral: 'Trung lập',
    blastingIntro: 'Số lượng tài khoản thật bị thanh lý',
    blastingAccount: 'Tài khoản bị thanh lý',
    unit: 'Đơn vị:',
    accountDistribute: 'Tài khoản',
    accountChange: 'Thay đổi số lượng tài khoản',
    varietyDistribute: 'Sản phẩm giao dịch',
    winRateDistribute: 'Tỷ lệ thắng',
    cutOff: 'Thời hạn',
    profit: 'Lời',
    loss: 'Lỗ',
    blasting: 'Bị thanh lý',
    orderForm: 'Lệnh',
    shippingSpace: 'Vị thế',
    accountRatio: 'Tỷ lệ tài khoản',
    accountNumber: 'Số lượng tài khoản',
    profitLossRatio: 'Lời / Lỗ',
    dealStyle: 'Phong cách giao dịch',
    lossRate: 'Tỷ lệ lỗ',
    dealStyleList: ['Giao dịch ngắn hạn', 'Giao dịch dài hạn', 'Giao dịch EA định lượng', 'Giao dịch vàng và dầu thô'],
    styleExplainList: [
      'Thời gian nắm giữ vị thế lệnh ngắn, tỷ lệ thắng cao, số lượng lệnh nhiều và được các nhà giao dịch yêu thích. Nhưng tỷ lệ lời lỗ thường thấp, thuộc về loại chiến lược sinh lời ít, thua lỗ nhiều.',
      'Thời gian nắm giữ lệnh kéo dài vài tuần hoặc thậm chí vài tháng, tỷ lệ lời lỗ  cao và tần suất giao dịch khá thấp, vì vậy, chiến lược này yêu cầu nhà giao dịch phải kiên nhẫn nhiều hơn.',
      'Tổng kết kinh nghiêm giao dịch thành mô hình thuật toán logic, và sử dụng EA để thực hiện giao dịch theo quy tắc đã được thiết lập.',
      'Đây là hai loại hợp đồng tương lai hàng hóa rất phổ biến, và được lựa chọn bởi một lượng lớn trader. Chúng tôi có thể thực hiện trên nhiều phần mềm giao dịch, và tìm kiếm được nhiều chuyên gia.'
    ],
    styleAccountRatio: [
      'Tài khoản giao dịch ngắn hạn',
      'Tài khoản giao dịch dài hạn',
      'Tài khoản giao dịch EA',
      'Tài khoản giao dịch Vàng&Dầu thô'
    ],
    speculate: 'Tâm lý thị trường',
    updateFrequency: 'Cập nhật 15 phút/lần',
    tradeVariety: 'Sản phẩm giao dịch',
    accountCount: 'Số lượng tài khoản (cái)   Mua/Bán',
    accountCountTips: 'Số lượng tài khoản với vị thế ròng hiện tại là mua hoặc bán',
    shippingSpaceLabel: 'Khối lượng (lot)    Mua/Bán',
    shippingSpaceTips: 'Tổng số khối lượng giao dịch lot của lệnh mua/bán hiện tại (trừ lệnh chờ).',
    marketEmotion: 'Tâm lý thị trường (Mua/Bán)',
    dealStyleTip: [
      'Số lượng tài khoản chứa phong cách {x} chia cho tổng số tài khoản trong cộng đồng. ',
      'Số lượng tài khoản tập trung vào giao dịch Vàng&Dầu thô chia cho tổng số tài khoản trong cộng đồng. '
    ],
    lossRateTip: [
      'Trong số các tài khoản chứa phong cách {x}, có {y} đang thua lỗ. ',
      'Trong số các tài khoản tập trung vào giao dịch Vàng&Dầu thô, có {y} tài khoản thua. '
    ],
    accountExplain:
      'Tính đến {0}({1}), có {2} tài khoản giao dịch {3}, trong đó, có {4} tài khoản thua và {5} tài khoản thắng.',
    orderList: 'Order book',
    orderListTips:
      'Khám phá các vị trí hỗ trợ/kháng cự tiềm năng trên thị trường và tìm hiểu những mức giá được khớp lệnh nhiều nhất trong thị trường.',
    positionChange: 'Người nắm giữ  vị thế và Thay đổi vị thế',
    longAccountNum: 'Tài khoản Mua',
    shortAccountNum: 'Tài khoản Bán',
    netPosition: 'Vị thế ròng',
    rise: 'Tăng',
    fall: 'Giảm',
    putOrder: 'Lệnh chờ',
    position: 'Lệnh',
    marketChange: 'Thị trường và Thay đổi vị thế',
    longCash: 'Lệnh Mua',
    shortCash: 'Lệnh Bán',
    closePrice: 'Giá đóng cửa',
    upsAndDowns: 'Tăng/Giảm trong ngày',
    newestPrice: 'Giá mới nhất',
    marketEmotion1: 'Tâm lý thị trường',
    currentPosition: 'Đang nắm giữ {x} lệnh',
    longOrderCount: '{x} lệnh mua',
    shortOrderCount: '{x} lệnh bán',
    price: 'Giá',
    subscribeCnt: 'Lượng sao chép',
    windVane: 'Xu hướng',
    allMaster: 'Họ là chuyên gia giao dịch {x}',
    longMaster: 'Chuyên gia giao dịch dài hạn',
    shortMaster: 'Chuyên gia giao dịch ngắn hạn',
    quantizationMaster: 'Chuyên gia giao dịch định lượng',
    form: 'Mô hình',
    name: 'Tên',
    variety: 'Sản phẩm giao dịch',
    period: 'Chu kỳ',
    createTime: 'Thời gian',
    trend: 'Xu hướng',
    dataSupport: 'Dữ liệu được hỗ trợ bởi FastBull',
    chartTimeZone: 'Múi giờ',
    allForm: 'Tất cả mô hình',
    allVariety: 'Tất cả sản phẩm',
    allPeriod: 'Tất cả chu kỳ',
    kingList: 'Xếp hạng Top',
    formDesc1:
      'Mô hình búa là một mô hình đảo chiều tăng giá, đặc biệt khi nó xuất hiện ở đáy của một xu hướng giảm. Thân của nó nhỏ nhưng bóng dưới của nó dài (thường dài gấp hai lần so với thân thật). Nó có ít hoặc không có bóng trên, thường có trải qua một xu hướng giảm.  Nếu nó được xuất hiện trong xu hướng tăng, thì được gọi là mô hình nến Người Treo Cổ.',
    formDesc2:
      'Người treo cổ là mô hình nến đảo chiều giảm giá xuất hiện ở cuối xu hướng tăng.. Ngoài ra, nếu nến sau là một cây nến giảm với giá đóng cửa thấp hơn nến Người Treo Cổ này, thì tín hiệu này cũng khá vững chắc. Mô hình Người Treo Cổ là một mô hình đảo chiều ở đỉnh và thường được xuất hiện sau khi thị trường có trải qua một xu hướng tăng',
    formDesc3:
      'shooting star là một mô hình nến giảm giá có bóng trên dài, thân nến nhỏ nằm ở đầu dưới và có rất ít hoặc không có bóng dưới. Nó chủ yếu xuất hiện ở cuối một xu hướng tăng, vì vậy nó có thể báo hiệu sự kết thúc của xu hướng tăng. Mô hình này hình thành khi bên mua đẩy giá lên cao vào đầu phiên giao dịch.Nhưng đến cuối phiên giao dịch, bên bán đã đẩy giá xuống gần mức mở cửa (mô hình này còn được gọi là "Shooting star" vì nó tồn tại trong thời gian ngắn). Khi một mô hình tương tự xuất hiện ở cuối một đợt giảm giá, nó được gọi là búa đảo ngược).\n',
    formDesc4:
      'Sự khác biệt giữa nến Búa Ngược và nến Shooting Star là nó thường được xuất hiện ở đáy, và đưa ra tín hiệu rằng giá cả sẽ đảo chiều tăng lên. Trên thực tế, sức đảo chiều của nến Búa Ngược và nến Shooting Star không bằng với nến Người Treo Cổ và Nến Búa, vì vậy, chúng ta tốt nhất phải kết hợp với các cây nến tiếp theo và các chỉ báo khác để làm phân tích.',
    formDesc5:
      'Mô hình nến Nhấn Chìm là một mô hình đảo chiều hai cây nến. Nếu cây nến đầu tiên là nến tăng, nến thứ hai là nến giảm, và cấy nên giảm này hoàn toàn bao phủ nến tăng, thì là mô hình nến nhấn chìm giảm. Nếu ngược lại, nếu cây nến đầu tiên là nến giảm, cây nến thứ hai là nến tăng, và cây nến tăng hoàn toàn bao phủ nến giảm, thì là mô hình nhấn chìm tăng. Ngoài ra, còn có những mô hình nến tăng bao phủ nến tăng, nến giảm bao phủ nến giảm với tín hiệu  giao dịch lần lượt là mua vào và bán ra, nhưng chúng ta cũng không nên đưa ra quyết định quá nóng vội, còn phải kết hợp với các công cụ phân tích kỹ thuật khác để làm phân tích.',
    formDesc6:
      'Mô hình nến Nhấn Chìm là một mô hình đảo chiều hai cây nến. Nếu cây nến đầu tiên là nến tăng, nến thứ hai là nến giảm, và cấy nên giảm này hoàn toàn bao phủ nến tăng, thì là mô hình nến nhấn chìm giảm. Nếu ngược lại, nếu cây nến đầu tiên là nến giảm, cây nến thứ hai là nến tăng, và cây nến tăng hoàn toàn bao phủ nến giảm, thì là mô hình nhấn chìm tăng. Ngoài ra, còn có những mô hình nến tăng bao phủ nến tăng, nến giảm bao phủ nến giảm với tín hiệu  giao dịch lần lượt là mua vào và bán ra, nhưng chúng ta cũng không nên đưa ra quyết định quá nóng vội, còn phải kết hợp với các công cụ phân tích kỹ thuật khác để làm phân tích.',
    formDesc7:
      'Mô hình nến “Three Black Crows” - Ba Con Quạ Đen là sự xuất hiện liên tục của ba nến giảm, thường báo hiệu rằng một xu hướng giảm lớn. Mỗi khi có xuất hiện mô hình này, thị trường thường sẽ giảm giá tiếp trong thời gian tương lai. Và Mô hình “Three White Soldiers” thì ngược lại, sự xuất hiện của nó trong một xu hướng giảm thường là một tín hiệu đảo chiều tăng giá mạnh của thị trường.',
    formDesc8:
      'Mô hình nến “Three Black Crows” - Ba Con Quạ Đen là sự xuất hiện liên tục của ba nến giảm, thường báo hiệu rằng một xu hướng giảm lớn. Mỗi khi có xuất hiện mô hình này, thị trường thường sẽ giảm giá tiếp trong thời gian tương lai. Và Mô hình “Three White Soldiers” thì ngược lại, sự xuất hiện của nó trong một xu hướng giảm thường là một tín hiệu đảo chiều tăng giá mạnh của thị trường.',
    formDesc9:
      'Mô hình nến sao mai là một mô hình đảo chiều ba cây nến, và thường xuất hiện ở đáy. Mỗi khi mô hình này được xuất hiện trong một xu hướng giảm, thì thường có đưa ra một tín hiệu rằng thị trường sẽ đảo chiều tăng giá, và lúc này chính là một thời cơ đăt lệnh mua khá tốt.',
    formDesc10:
      'Mô hình nến Sao Hôm trái ngược với mô hình nến Sao Mai, thuộc về một mô hình đảo chiều giảm giá. Mỗi khi mô hình này được xuất hiện trong một xu hướng tăng, thì là một tín hiệu đảo chiều giảm hoặc thoái lui mạnh mẽ, cho nên, lúc này mới là một thời cơ đặt lệnh bán khá tốt.',
    formDesc13:
      'Mây đen che phủ là một tín hiệu đảo chiều giảm thường gặp ở đỉnh. Đây là một mô hình hai cây nến, với nến trước là một nến tăng, và nến sau là một nến giảm dài hơn. Nó thường được xuất hiện sau xu hướng tăng, và có khi mô hình này cũng được xuất hiện ở đỉnh của xu hướng đi ngang.',
    formDesc14:
      'Mô hình nến Xuyên là một mô hình đảo chiều hai cây nến, với nến trước là một cây nến giảm đầu tiên, và nến sau nến tăng với giá mở cửa khá thấp, nhưng cuối cùng giá cả không ngừng tăng lên và đóng cửa ở mức cao hơn giá đóng cửa của nến trước. Và thân nến tăng có bao phủ hơn 50% thân nến giảm.',
    formDesc15:
      'Nến Doji là một nến chỉ có nến bóng trên và nến bóng dưới, không có thân nến, tức giá mở cửa có bằng với giá đóng cửa. Trong đó, nến bóng trên càng dài thì có nghĩa là sức bán càng lớn; nến bóng dưới càng dài thì đại điện cho sức mua càng mạnh. Nếu có nên Doji được xuất hiện ở đỉnh hoặc đáy thì thường có nghĩa là thị trường sẽ có thể xuất hiện đảo chiều.',
    formDesc16:
      'Nến Doji là một nến chỉ có nến bóng trên và nến bóng dưới, không có thân nến, tức giá mở cửa có bằng với giá đóng cửa. Trong đó, nến bóng trên càng dài thì có nghĩa là sức bán càng lớn; nến bóng dưới càng dài thì đại điện cho sức mua càng mạnh. Nếu có nên Doji được xuất hiện ở đỉnh hoặc đáy thì thường có nghĩa là thị trường sẽ có thể xuất hiện đảo chiều.',
    formDesc17:
      'Mô hình Harami là mô hình đảo chiều hai cây nến với hình dạng giống như mô hình đảo ngược của mô hình nến nhấn chìm. Trong mô hình nhấn chìm, nến sau có thân thên dài, và bao trọn toàn bộ nến trước. Nhưng trong mô hình Harami, là nến trước có thân nến dài, và bao trọn toàn bộ nến sau. Hình dạng này giống như một người phụ nữ đang bồng con, cho nên, mô hình này cũng được gọi là mô hình nến mẹ bồng con.',
    formDesc18:
      'Mô hình Harami là mô hình đảo chiều hai cây nến với hình dạng giống như mô hình đảo ngược của mô hình nến nhấn chìm. Trong mô hình nhấn chìm, nến sau có thân thên dài, và bao trọn toàn bộ nến trước. Nhưng trong mô hình Harami, là nến trước có thân nến dài, và bao trọn toàn bộ nến sau. Hình dạng này giống như một người phụ nữ đang bồng con, cho nên, mô hình này cũng được gọi là mô hình nến mẹ bồng con.',
    formDesc19:
      'Mô hình Harami là mô hình đảo chiều hai cây nến với hình dạng giống như mô hình đảo ngược của mô hình nến nhấn chìm. Trong mô hình nhấn chìm, nến sau có thân thên dài, và bao trọn toàn bộ nến trước. Nhưng trong mô hình Harami, là nến trước có thân nến dài, và bao trọn toàn bộ nến sau. Hình dạng này giống như một người phụ nữ đang bồng con, cho nên, mô hình này cũng được gọi là mô hình nến mẹ bồng con.',
    formDesc20:
      'Mô hình Harami là mô hình đảo chiều hai cây nến với hình dạng giống như mô hình đảo ngược của mô hình nến nhấn chìm. Trong mô hình nhấn chìm, nến sau có thân thên dài, và bao trọn toàn bộ nến trước. Nhưng trong mô hình Harami, là nến trước có thân nến dài, và bao trọn toàn bộ nến sau. Hình dạng này giống như một người phụ nữ đang bồng con, cho nên, mô hình này cũng được gọi là mô hình nến mẹ bồng con.',
    traderStyle: 'Phong cách  ',
    winningAccounts: 'Tài khoản thắng',
    losingAccounts: 'Tài khoản thua',
    dealLong: 'Mua',
    dealShort: 'Bán',
    sellingPrice: 'Giá bán (Ask)',
    buyingPrice: 'Giá mua (Bid)',
    hangingOrderData: 'Lệnh chờ',
    positionOrderData: 'Lệnh thị trường',
    periodicalNumber: 'Kỳ {x}',
    greatestRule: 'Quy tắc',
    selectTraderStyle: 'Chọn sản phẩm giao dịch '
  },
  user: {
    sendMsg: 'Gửi tin nhắn',
    userId: 'ID Người dùng',
    attention: 'Theo dõi',
    collect: 'Mục ưa thích',
    home: 'Trang chủ',
    contest: 'Cuộc thi',
    social: 'Trò chuyện',
    vip: 'FastBull Pro',
    setting: 'Cài đặt',
    about: 'Về',
    accountListLen: 'Bạn có thể liên kết tối đa {x} tài khoản giao dịch.',
    addAccount: 'Thêm tài khoản',
    loginRegister: 'Đăng ký/Đăng nhập',
    logoutSuccess: 'Bạn đã đăng xuất',
    accountLis: 'Danh sách tài khoản',
    totalAccount: '{x} tài khoản',
    noBindAccount: 'Người dùng này chưa liên kết tài khoản giao dịch',
    unfoldAll: 'Xem thêm',
    foldAll: 'Thu gọn ',
    similarAccount: 'Tài khoản tương tự',
    changeAccount: 'Đổi',
    signaturePlaceholder: 'Không có nội dung',
    loginViewOrder: 'Đăng nhập để xem chi tiết lệnh',
    brokerGrade: 'Bạn cho rằng nhà môi giới {x} trên tài khoản này đáng tin cậy không?',
    soldOut:
      'Đề nghị FastBull Top Traders gỡ xuống nhà môi giới này và không còn hỗ trợ liên kết tài khoản của nhà môi giới này nữa.',
    accountReport: 'Báo cáo giao dịch gian lận',
    suspects: 'Vui lòng mô tả chi tiết về bất kỳ hoạt động đáng ngờ nào của tài khoản giao dịch này.',
    reliable: 'Rất đáng tin cậy',
    unreliable: 'Không đáng tin cậy',
    suggestSoldOut: 'Đề nghị gỡ xuống',
    reportSuccess: 'Báo cáo thành công!',
    emoji: 'Emoji',
    picture: 'Hình ảnh',
    uploadFailed: 'Tải lên thất bại',
    submitAfterUpload: 'Vui lòng tải hình ảnh lên trước',
    addPicture: 'Thêm hình ảnh',
    btnTextList: ['Bình luận', 'Trả lời', 'Xác nhận báo cáo'],
    praise: 'Thích',
    reply: 'Trả lời',
    writeYourComment: 'Vui lòng nhập câu trả lời của bạn...',
    moreReply: 'Thêm câu trả lời',
    residueReplay: 'còn lại {x} câu trả lời',
    account: 'Tài khoản',
    grade: 'Xếp hạng',
    subscribe: 'Sao chép giao dịch',
    accountPraise: 'Danh tiếng tài khoản',
    accountComment: 'Bình luận tài khoản',
    allComment: 'Tất cả bình luận',
    needComment: 'Nhập bình luận của bạn (bình luận không thể sửa hoặc xóa. Hãy bình luận đúng cách).',
    excellent: 'Tuyệt vời',
    ordinary: 'Trung bình',
    noGood: 'Yếu kém',
    commentSuccess: 'Bình luận thành công',
    replySuccess: 'Trở lời thành công',
    inputNotice: 'Vui lòng nhập nội dung thông báo',
    allowNoticeCount: 'Chỉ cho phép đăng tối đa {x} thông báo mỗi ngày',
    totalCount: 'Tổng cộng {x} thông báo',
    publish: 'Đăng',
    publishSuccess: 'Thông báo được xuất bản thành công!',
    isDeleteNotice: 'Xóa thông báo?',
    deleteNotice: 'Xóa thông báo',
    closeComment: 'Quyền bình luận đã bị tắt đối với tài khoản này',
    privateComment: 'Tài khoản riêng tư, không thể gửi bình luận',
    privateReport: 'Tài khoản riêng, không thể đăng thông tin báo cáo',
    length1: 'Vui lòng nhập ít nhất 1 ký tự.',
    length512: 'Bạn có thể nhập tối đa 512 ký tự',
    noAccount: 'Chưa có tài khoản giao dịch',
    tradingPlatform: 'Phần mềm giao dịch',
    broker: 'Nhà môi giới',
    brokerServer: 'Máy chủ',
    dealAccountNum: 'Tài khoản',
    tradingPassword: 'Mật khẩu Master  ',
    passwordExplain: 'Nếu không cần thực hiện sao chép giao dịch, thì bạn chỉ cần nhập mật khẩu Passview',
    inputPassword: 'Vui lòng nhập mật khẩu giao dịch',
    tradingStrategy: 'Chiến lược giao dịch',
    strategyExplain: 'Vui lòng giới thiệu ngắn gọn chiến lược giao dịch của bạn.',
    passwordLength: 'Mật khẩu Master là mật khẩu 4-32 ký tự',
    strategyLength: 'Giới thiệu chiến lược giao dịch yêu cầu tối thiểu 16 ký tự',
    searchName: 'Tìm kiếm tên nhà môi giới hoặc máy chủ',
    record: 'Lịch sử tìm kiếm',
    hotSearch: 'Tìm kiếm phổ biến',
    result: 'Kết quả tìm kiếm',
    inputAccount: 'Vui lòng nhập số tài khoản giao dịch',
    inVerification: 'Đang xác minh tài khoản...',
    accountLength: 'Số tài khoản giao dịch có 4-16 chữ số',
    bindOvertime: 'Liên kết tài khoản hết thời gian chờ',
    addTradingAccount: 'Thêm tài khoản giao dịch',
    linkAccount: 'Liên kết tài khoản',
    accountSetting: 'Cài đặt tài khoản',
    otherBind: 'Tài khoản giao dịch đã bị ràng buộc bởi người khác',
    howToFind: 'Làm thế nào để lấy lại?',
    findAccount: 'Lấy lại tài khoản',
    stepTitle: 'Vui lòng làm theo các bước sau để lấy lại tài khoản giao dịch của bạn:',
    findStep1: '1. Đăng nhập vào MT4/MT5 bằng mật khẩu Master',
    findStep2: '2. Thay đổi mật khẩu Master hoặc mật khẩu Passview.',
    findStep3: '3. Quay lại Top Traders và thêm lại tài khoản.',
    addSuccess: 'Thêm thành công',
    initExplain:
      'Hệ thống đang khởi tạo dữ liệu cho tài khoản này, quá trình này sẽ mất khoảng 3 phút, sau khi quá trình khởi tạo hoàn tất, tài khoản có thể được sử dụng bình thường.',
    bindNow: 'Liên kết ngay',
    brokerBan: 'Nhà môi giới đã bị cấm',
    accountRate:
      'Tuyệt vời: Năng lực giao dịch xuất sắc\nTrung bình: Năng lực giao dịch trung bình\nYếu kém: Năng lực giao dịch yếu kém',
    accountReportTips:
      'Nếu một tài khoản giao dịch bị nhiều người báo cáo là giao dịch sai, FastBull Top Traders sẽ cung cấp phản hồi cho các nhà giao dịch có liên quan và xác minh tính xác thực của dữ liệu.',
    accountList: 'Danh sách tài khoản',
    conversionRate: 'Tỷ lệ chuyển đổi',
    nowDay: 'ngày hôm đó',
    lastSevenDay: '7 ngày qua',
    yesterday: 'Hôm qua',
    notice: 'Thông báo',
    edit: 'Chỉnh sửa',
    totalYieldRate: 'Tỷ lệ lợi nhuận tích lũy',
    bindAccountTips: 'Chưa thêm tài khoản giao dịch nào. vui lòng thêm nó vào ~',
    subscribeTips: 'Sao chép tín hiệu để giao dịch cùng Top trader',
    toSubscribe: 'Đi sao chép ngay',
    contesting: 'Cạnh tranh',
    season: 'Mùa giải {x}',
    rank: 'Xếp hạng',
    chatroom: 'Phòng Chat',
    friend: 'Bạn bè',
    groupChat: 'Nhóm',
    topic: 'Chủ đề',
    writer: 'Tác giả',
    news: 'Tin tức',
    video: 'Video',
    pictureVideo: 'Ảnh & Video',
    file: 'Tài liệu',
    audio: 'Âm thanh',
    chatRecord: 'Lịch sử trò chuyện',
    followed: 'Đang theo dõi',
    fans: 'Fans',
    article: 'Bài viết',
    cancelCollect: 'Xóa từ mục ưa thích',
    simulationGroup: 'Tài khoản Demo',
    actualGroup: 'Tài khoản Thật',
    contestData: 'Dữ liệu cuộc thi',
    awardsCount: 'Giải',
    totalAward: 'Tổng số tiền thưởng',
    topScore: 'Điếm tối đa',
    megagameRecord: 'Lịch sử thi đấu',
    entryAccount: 'Tài khoản',
    score: 'Điểm',
    ranking: 'Xếp hạng',
    awards: 'Phần thưởng',
    extraAward: 'Bonus đặc biệt',
    auditStatus: 'Trạng thái xét duyệt',
    status: ['Xét duyệt thông qua', 'Không được thông qua', 'Đang xét duyệt'],
    noRecord: 'Không có dữ liệu',
    socialGroup2: 'Nhóm tôi quản lý ({x})',
    socialGroup3: 'Nhóm tôi tham gia ({x})',
    comeFrom: 'Từ: {x}',
    socialGroup1: 'Nhóm tôi tạo ({x})',
    nextStep: 'Tiếp theo',
    selectBrokers: 'Chọn máy chủ giao dịch',
    bindSuccess: 'Liên kết thành công',
    goFollowOrder: 'Sao chép giao dịch',
    accountDetail: 'Chi tiết tài khoản',
    bindAgain: 'Thử lại',
    traderAccount: 'Tài khoản giao dịch',
    traderLever: 'Đòn bẩy',
    subscribeNum: '{0} Người sao chép',
    depositCurrency: 'Đông tiền gửi tiền',
    accountName: 'Tên tài khoản',
    withoutSignature: 'Chưa cài đặt châm ngôn giao dịch',
    fastbullVIP: 'Fastbull Pro',
    openVipForFree: 'Đăng ký thành viên miễn phí',
    logout: 'Đăng xuất',
    shareFB: 'Chia sẻ Fastbull',
    copyLink: 'sao chép đường dẫn',
    addFriend: 'Thêm bạn',
    addFriendVerify: 'Xác thực kết bạn',
    waitVerify: 'Chờ xác thực',
    added: 'Đã kết bạn',
    defaultVerify: 'Tôi là {x}',
    inputVerifyInfo: 'Vui lòng nhập thông tin xác minh:',
    addSuccessTip: 'Yêu cầu kết bạn đã được gửi thành công và đang chờ xác nhận từ bên kia.',
    send: 'Gửi',
    sendApplySuccess: 'Gửi thành công',
    cancelAttentionConfirm: 'Bạn có chắc chắn không còn theo dõi người dùng này nữa không?',
    userCenter: 'Trung tâm cá nhân',
    openFBAPP: 'Mở APP',
    supportNewsPrice: 'Cung cấp tin tức và bảng giá tài chính nhanh chóng và toàn diện',
    noCollect: 'Chưa thêm mục ưa thích nào',
    accountPwd: 'Mật khẩu',
    fxchat_niu_trading_select: 'Chọn nhà môi giới',
    fxchat_niu_trading_select_first: 'Vui lòng chọn nhà môi giới trước',
    fxchat_niu_trading_server_select: 'Chọn',
    fxchat_niu_account_input_hint: '4-16 chữ số',
    fxchat_niu_observe_account_input_hint: '4-32 ký tự',
    fxchat_niu_observe_password_tip:
      'Nếu không cần thực hiện sao chép giao dịch, thì bạn chỉ cần nhập mật khẩu Passview',
    fxchat_niu_trading_strategy_hint: 'Vui lòng giới thiệu ngắn gọn về chiến lược giao dịch của bạn (16~128 ký tự)',
    fxchat_niu_account_bind: 'Tài khoản giao dịch này đã bị liên kết bởi người khác,',
    commentAfterLogin: 'Vui lòng đăng {x} trước khi đăng bình luận^_^',
    noBodyAdd: 'Gửi yêu cầu kết bạn thất bại. Người dùng này không cho phep bất kỳ ai thêm bạn.'
  },
  grade: {
    synthesizeGrade: 'Đánh giá tổng thể',
    gradeTips: 'Đánh giá tổng thể dựa trên dữ liệu giao dịch trong sáu tháng qua và được cập nhật mỗi ngày một lần.',
    tradeAbility: 'Năng lực giao dịch',
    goodAtVariety: 'Tập trung vào',
    riskLevel: 'Mức độ rủi ro',
    maxDrawdown: 'Sụt giảm tối đa',
    viewGradeReport: 'Xem báo cáo xếp hạng tổng hợp',
    rank: 'Xếp hạng toàn diện {x}',
    score: 'Điểm toàn diện {x} điểm',
    tradeAbilityList: ['Tuyệt vời', 'Rất tốt', 'Tốt', 'Trung bình', 'Yếu', 'Rất yếu'],
    riskLevelList: ['Rủi ro thấp', 'Rủi ro trung bình', 'Rủi ro cao'],
    profitAndLoss: 'Lời lỗ tài khoản',
    orderControl: 'Quản lý lệnh',
    varietyData: 'Dữ liệu sản phẩm',
    dealStyle: 'Phong cách giao dịch',
    dealPosition: 'Dữ liệu vị thế',
    gradeStr: ['Tuyệt vời', 'Tốt', 'Trung bình', 'Yếu'],
    gradeScore: 'Điểm đánh giá',
    scoreTooltip:
      'A+ (Hơn 90 điểm),  năng lực giao dịch xuất sắc! <br/>\nA (Hơn 85 điểm), năng lực giao dịch rất tốt! <br/>\nB+ (Hơn 80 điểm), năng lực giao dịch  tốt! <br/>\nB (Hơn 75 điểm), năng lực giao dịch trung bình! <br/>\nC+ (Hơn 60 điểm), năng lực giao dịch  yếu! <br/>\nC (Dưới 60 điểm), năng lực giao dịch rất yếu!',
    tradeGrade: 'Đánh giá giao dịch',
    gradeExplain: 'Đánh giá tổng thể dựa trên dữ liệu giao dịch trong sáu tháng qua và được cập nhật mỗi ngày một lần.',
    yieldRateTooltip: 'Tỷ lệ hoàn vốn của số dư tài khoản trong khoảng thời gian nhất định. Tính bằng thuật toán TWR.',
    maxDrawdownTooltip:
      'Mức sụt giảm tối đa của giá trị tài sản ròng (nếu không có dữ liệu về giá trị tài sản ròng, thì sẽ tính bằng số dư.) trong khoảng thời gian nhất định. Do ảnh hưởng của việc gửi và rút tiền, dữ liệu có thể vượt quá 100%.',
    yieldRiskRatioTooltip:
      'Tỷ lệ lợi nhuận /tỷ lệ sụt giảm tối đa. Khi tỷ lệ lợi nhuận ≤ 0, tỷ lệ lợi/rủi ro sẽ tự động tính bằng 0; khi tỷ lệ sụt giảm bằng 0, tỷ lệ lợi nhuận/rủi ro sẽ tự động tính bằng 100.',
    yieldRiskRatio: 'Tỷ lệ lợi nhuận/rủi ro',
    orderTotalTooltip: 'Số lượng lệnh trong khoảng thời gian nhất định.',
    orderTotal: 'Tổng số lệnh',
    dealFrequencyTooltip: 'Số lượng lệnh trung bình được giao dịch mỗi ngày trong khoảng thời gian được chỉ định.',
    dealFrequency: 'Tần suất giao dịch',
    frequencyUnit: '{x} lệnh/ngày',
    stopProfitRateTooltip: 'Tỷ lệ các lệnh chốt lời hoặc dừng lỗ trong số các lệnh trong khoảng thời gian nhất định.',
    stopProfitRate: 'Tỷ lệ chốt lời & cắt lỗ',
    varietyFreight: 'Sản phẩm giao dịch& Vị thế',
    heavyRatioTooltip:
      'Trong một khoảng thời gian nhất định, tỷ lệ các lệnh với khối lượng vị thế lớn (lệnh giao dịch chiếm trên 15% số tiền tài khoản).',
    heavyRatio: 'Tỷ lệ vào lệnh bằng khối lượng vị thế lớn',
    focusVarietyTooltip: 'Những sản phẩm được thực hiện giao dịch nhiều hơn trong một khoảng thời gian nhất định.',
    focusVariety: 'Sản phẩm giao dịch',
    profitLossRatioTooltip:
      'Tỷ lệ lợi nhuận trung bình của các lệnh thắng so với lỗ trung bình của các lệnh thua rong một khoảng thời gian nhất định. Khi mức lỗ trung bình là 0 thì tỷ lệ lời lỗ là 100.',
    profitLossRatio: 'Tỷ lệ lời lỗ',
    dealStyleTooltip: 'Phong cách giao dịch trong một khoảng thời gian nhất định.',
    profitPositionTooltip: 'Thời gian nắm giữ trung bình các lệnh thắng trong khoảng thời gian nhất định.',
    profitPosition: 'Thời gian nắm giữ trung bình các lệnh thắng',
    lossPositionTooltip: 'Thời gian nắm giữ trung bình các lệnh thua trong khoảng thời gian nhất định.',
    lossPosition: 'Thời gian nắm giữ trung bình các lệnh thua',
    gradeResult: 'Kết quả đánh giá chỉ mang tính chất tham khảo và không mang tính chất tư vấn đầu tư.',
    general: 'Tổng quan',
    evaluateList: [
      'Số lượng lệnh quá ít, không thể đánh giá chính xác',
      'Hãy vui lên và chèo thuyền ngược dòng, nếu bạn không tiến lên, bạn sẽ rút lui.',
      'Năng lực chuyên môn cần được nâng cao',
      'Bạn có thể tiến thêm một bước nữa, đừng là tỏi tây',
      'Hiệu suất tuyệt vời, hãy tiếp tục phát huy nhé',
      'Một bậc thầy giao dịch xứng đáng',
      'Kỹ năng giao dịch cấp thiên tài'
    ],
    profitAbility: {
      worst: 'Khả năng sinh lời rất thấp',
      veryBad: 'Khả năng sinh lời thấp',
      bad: 'Khả năng sinh lời khá thấp',
      needToImprove: 'Khả năng sinh lời cần cải thiện',
      common: 'Khả năng sinh lời trung bình',
      strong: 'Khả năng sinh lời khá cao',
      stronger: 'Khả năng sinh lời cao',
      strongest: 'Khả năng sinh lời rất cao'
    },
    earnings: {
      veryInstability: 'Lợi nhuận rất không ổn định.',
      instability: 'Lợi nhuận không ổn định.',
      stabilize: 'Lợi nhuận khá ổn định.',
      veryStabilize: 'Lợi nhuận ổn định.',
      mostStabilize: 'Lợi nhuận rất ổn định.'
    },
    dealRisk: {
      lowest: 'Rủi ro rất thấp',
      smaller: 'Rủi ro thấp',
      controlled: 'Rủi ro khá thấp',
      high: 'Rủi ro khá cao',
      higher: 'Rủi ro cao',
      gigantic: 'Rủi ro rất cao'
    },
    earningsRiskRatio: {
      worst: 'Tỷ lệ lợi nhuận rủi ro rất thấp',
      veryBad: 'Tỷ lệ lợ nhuận rủi ro thấp.',
      needToImprove: 'Tỷ lệ lợ nhuận rủi ro khá thấp',
      rational: 'Tỷ lệ lợ nhuận rủi ro khá cao',
      good: 'Tỷ lệ lợ nhuận rủi ro cao',
      veryGood: 'Tỷ lệ lợ nhuận rủi ro rất cao.'
    },
    avgDailyYield: 'Mức biến động trung bình/ngày: {x}',
    avgWeekYield: 'Mức biến động trung bình/tuần: {x}',
    avgMonthYield: 'Mức biến động trung bình/tháng: {x}',
    dayProfit: 'Tỷ lệ thắng hàng ngày: {x}',
    monthProfit: 'Tỷ lệ thắng hàng tháng: {x}',
    maxDrawdownIs: 'Sụt giảm tối đa: {x}',
    earningsRiskValue: 'Tỷ lệ lợi nhuận rủi ro: {x}',
    dealFrequencyExplain: [
      'Tần suất giao dịch được kiểm soát khá tốt, hãy tiếp tục duy trì, vì giao dịch càng nhiều thì rủi ro thua lỗ sẽ càng cao.',
      'Tần suất giao dịch tương đối cao. Việc giảm tần suất giao dịch một cách hợp lý, sẽ giúp bạn kiểm soát rủi ro tốt hơn. '
    ],
    stopExplain: [
      'Vì tỷ lệ chốt lời/cắt lỗ thấp, cho nên có thể tiềm ẩn rủi ro nhất định.',
      'Mục tiêu giao dịch không rõ ràng. Việc sử dụng lệnh chốt lời/cắt lỗ có thể giảm bớt rủi ro trên một mức độ nhất định.',
      'Mục tiêu giao dịch khá rõ ràng, tuy nhiên bạn cần phải thận trọng hơn trong khi vào/đóng lệnh. Đừng đặt lệnh trong trường hợp bạn không chắc chắn.',
      'Mục tiêu giao dịch rõ ràng, có thói quen giao dịch tốt.'
    ],
    accumulativeDeal: 'Tổng cộng giao dịch {x} ngày',
    avgOrder: '{x} lệnh trung bình/ngày',
    stopPercent: 'Đã cài đặt chốt lời/cắt lỗ cho {x} lệnh giao dịch',
    heavyExplain: [
      'Năng lực kiểm soát rủi ro khá tốt, khối lượng vị thế tương đối hợp lý',
      'Thỉnh thoảng giao dịch với khối lượng vị thế lớn',
      'Thường giao dịch với khối lượng vị thế lớn. Xin hãy quản lý rủi ro cho tốt.',
      'Giao dịch với khối lượng vị thế quá nhiều, có rủi ro rất cao, vui lòng giao dịch cẩn thận hơn.'
    ],
    heavyPercent: 'Trong {x} lệnh, tỷ lệ giao dịch với khối lượng vị thế lớn là {y}',
    suggestion:
      'Đề nghị cài đặt lệnh chốt lời và cắt lỗ cho tất cả các lệnh giao dịch với khối lượng vị thế lớn, hãy loại bỏ tâm lý đánh cược và quản lý rủi ro cho tốt.',
    noFocus:
      'Nếu bạn không có chuyên về giao dịch loại sản phẩm nào, thì bạn nên tập trung vào một đến hai loại sản phẩm giao dịch, như vậy, bạn mới có thể nâng cao năng lực giao dịch.',
    focusVarietyAt: 'Chuyên về giao dịch {x}.',
    focusCount: 'Tập trung vào {x} {y}.',
    profitLossStr: 'Tổng lời lỗ trong sản phẩm này là {x}.',
    profitLossTotal: 'Tổng lời lỗ là {x}.',
    goodAtStr: 'Kết quả giao dịch tốt nhất là {x}, lợi nhuận của sản phẩm này chiếm {y} tổng lợi nhuận.',
    tradingStyle: [
      'Giao dịch trong ngày',
      'Giao dịch ngắn hạn',
      'Giao dịch dài hạn',
      'Giao dịch định lượng',
      'Không có phong cách giao dịch'
    ],
    tradingType: ['Trong ngày', 'Ngắn hạn', 'Dài hạn', 'Định lượng'],
    winAndRatio: 'Tỷ lệ thắng của giao dịch {x} là khoảng {y}, và tỷ lệ lời lỗ là khoảng {z}',
    beGoodAt: 'Giỏi về {x}',
    noTradingStyle:
      'Không có phong cách giao dịch rõ ràng, tỷ lệ thắng của giao dịch ngắn hạn là {x}, và tỷ lệ thắng của giao dịch dài hạn là {x}',
    avgPosition:
      'Tổng thời gian nắm giữ lệnh trung bình là {x}. Lệnh thắng sinh lời trung bình {y}. Lệnh thua lỗ vốn trung bình {z}.',
    joinAndRate: 'Gia nhập vào Top Traders</br>\nđể đánh giá năng lực giao dịch của bạn',
    rated: 'Tổng cộng {x} tài khoản giao dịch. Điểm đánh giá trung bình là {y}.',
    rateNow: 'Đánh giá ngay',
    isTheRating: 'AI Đánh giá đang đánh giá cho bạn, vui lòng chờ đợi...',
    scoreTips:
      'Điểm đánh giá còn cò bao gồm 3 loại đánh giá khác, để đánh giá tình hình đánh giá từ người dùng khác, tình hình giữ lệnh ngược xu hướng cũng như chu kỳ sống trên thị trường. <br/>Đánh giá từ người dùng: {x}<br/>Lệnh giao dịch: {y} <br/>Chu kỳ: {z}',
    warmPrompt: 'Lưu ý:',
    traderForShort: 'Giao dịch ngắn hạn',
    traderForLong: 'Giao dịch dài hạn',
    traderForQuantification: 'Giao dịch định lượng',
    traderForGold: 'Giao dịch Vàng&Dầu thô',
    traderForShortTip: 'Về giao dịch ngắn hạn',
    traderForLongTip: 'Về giao dịch dài hạn',
    traderForQuantificationTip: 'Về giao dịch định lượng',
    traderForGoldTip: 'Về  giao dịch Vàng&Dầu thô',
    goldMaster: 'Chuyên gia giao dịch Vàng&Dầu thô'
  },
  subscribe: {
    openSubscribe: 'Bật quyền sao chép giao dịch',
    connectionNormal: 'Tài khoản kết nối bình thường',
    accountIsReal: 'Tài khoản Thật',
    notAbnormal: 'Chưa được hệ thống đánh dấu bất thường',
    brokerCompliance: 'Nhà môi giới liên quan là nhà môi giới được cấp phép',
    equityMoreThan: 'Tài sản ròng của tài khoản không ít hơn $1000',
    openNow: 'Bật',
    openSuccess: 'Đã bật quyền sao chép giao dịch',
    disqualification: 'Tài khoản này không đủ điều kiện bật quyền sao chép giao dịch',
    openCondition: 'Để trở thành nhà cung cấp tín hiệu, phải đáp ứng các điều kiện sau:',
    closeSubscribe: 'Tắt quyền sao chép giao dịch',
    closeSubscribeConfirm: 'Bạn có chắc chắn muốn tắt quyền sao chép giao dịch của tài khoản này không?',
    closePunishmentExplain:
      'Đã có {x} người đăng ký sao chép tài khoản này. Theo quy định của cộng đồng, nếu bạn tắt quyền sao chép vào lúc này, thì bạn sẽ bị xử phạt như sau:',
    punishment: 'Tài khoản giao dịch bị cấm bật quyền sao chép giao dịch trong 90 ngày.',
    consider: 'Hủy',
    closeNow: 'Tắt',
    closeSuccess: 'Tắt quyền sao chép giao dịch thành công',
    lengthen: 'Gia hạn đăng ký sao chép',
    follow: 'Sao chép',
    selectAccount: 'Chọn tài khoản để sao chép',
    alreadyFollow: 'Đã sao chép tài khoản',
    followDays: '{x} ngày tiếp theo, đến hạn {y}',
    notFollow: 'Chưa sao chép tài khoản',
    accountIsDelete: 'Tài khoản này đã bị xóa',
    accountDelete: 'Tài khoản tín hiệu đã bị xóa.',
    subscribeForbid: 'Quyền sao chép giao dịch của tài khoản này đã bị cấm.',
    subscribeClose: 'Tài khoản này chưa bật quyền sao chép giao dịch',
    closeAfterExpire: 'Tài khoản này không còn cho phép sao chép giao dịch nữa.',
    followAccountOffline:
      'Tài khoản giao dịch <span>#{x}</span> của bạn đã đăng xuất và tạm thời không khả dụng. Nếu mật khẩu liên kết tài khoản này đã bị thay đổi, vui lòng <a target="_blank" href="{y}"> vào trang cài đặt tài khoản </a> để cập nhật mật khẩu liên kết.',
    brokerForbid:
      'Top Traders không còn hỗ trợ nhà môi giới {x} nữa, do đó, các tài khoản của nhà môi giới này sẽ không được phép sao chép giao dịch.',
    fictitiousTradesTips: 'Tài khoản này có thể có giao dịch gian lận và đã bị cấm sao chép giao dịch',
    violateRuleTips:
      'Vì bạn đã vi phạm quy tắc sao chép giao dịch trả phí, hệ thống đã cấm bạn sao chép bất kỳ tín hiệu nào trong Top Traders. Nếu bạn có bất kỳ câu hỏi gì, vui lòng liên hệ với nhân viên chăm sóc khách hàng.',
    limitationUser: 'Người dùng bị hạn chế',
    subscribeWarning: 'Cảnh báo',
    riskAccountTips:
      'Tài khoản này có rủi ro khá cao, vui lòng đăng ký sao chép một cách thận trọng. Đừng tin tưởng người khác một cách dễ dàng để tránh bị lừa đảo.',
    userAbnormalTips: 'Người dùng này có hành vi bất thường, vui lòng đăng ký sao chép một cách thận trọng.',
    noCanFollow: 'Hiện tại không có tài khoản nào sau đây.',
    noAccount: 'Bạn chưa liên kết tài khoản giao dịch',
    accountOffline: 'Tài khoản này đã đăng xuất và tạm thời không khả dụng.',
    brokerLimit: 'Nhà môi giới bị hạn chế',
    accountFollowTips:
      "Tài khoản giao dịch của bạn <span>#{x</span> đang sử dụng mật khẩu Passview và không có quyền thực hiện giao dịch, và bạn không thể đăng ký sao chép giao dịch trong Top Traders. <br/>\nBạn cần <a target='_blank' href='{y}'> chuyển sang cài đặt</a> để cập nhật mật khẩu sang<span>mật khẩu Master</span>, sau đó mới có thể thực hiện sao chép giao dịch.",
    dealLimit: 'Giao dịch bị hạn chế',
    forbidSubscribe: 'Đã bị cấm sao chép',
    followSuccess: 'Đăng ký sao chép thành công',
    followSetting: 'Cài đặt thông số',
    subscriber: 'Người sao chép',
    subscribeTypeList: [
      {value: 1, name: 'Đang sao chép'},
      {value: 2, name: 'Lịch sử sao chép'}
    ],
    params: 'Thông số sao chép',
    subscribeTime: 'Thời gian bắt đầu',
    subscribePeriod: 'Thời gian sao chép',
    subscribeEndTime: 'Thời gian kết thúc',
    totalSubscribePeriod: 'Tổng thời gian sao chép giao dịch',
    otherUser: 'Bạn ấy vẫn đang sao chép giao dịch',
    patternList: [
      {name: 'Số lot cố định', value: 1},
      {name: 'Tỷ lệ cố định', value: 2}
    ],
    directionList: [
      {name: 'Sao chép giao dịch', value: 1},
      {name: 'Giao dịch ngược lại', value: 2},
      {name: 'Chỉ sao chép lệnh đóng', value: 3}
    ],
    notice: 'Thông báo',
    moreTradingNotice: 'Để xem thêm thông báo giao dịch<br/>Vui lòng truy cập trang chi tiết tài khoản giao dịch',
    hot: 'Phổ biến',
    count: 'Lượng sao chép',
    allSource: 'Tất cả các nguồn',
    detail: 'Chi tiết',
    cancelTips:
      'Nếu bạn muốn tạm ngừng sao chép giao dịch, vui lòng chuyển sang cửa sổ cài đặt sao chép và cập nhật trạng thái sao chép thành "Tắt"',
    cancel: 'Hủy sao chép',
    setting: 'Cài đặt',
    detailStatusList: ['', 'Đang sao chép', 'Đã hết hạn', 'Đã hủy', 'Đã hoàn tiền', 'Chưa bắt đầu'],
    orderId: 'ID lệnh',
    startTime: 'Thời gian bắt đầu',
    endTime: 'Thời gian kết thúc',
    cancelTime: 'Thời gian hủy',
    cancelReason: 'Lý do hủy',
    notStartTips: 'Lệnh "Chưa bắt đầu" sẽ có hiệu lực sau khi lệnh "Đang sao chép" hết hạn.',
    confirmTocancel: 'Bạn có chắc chắn muốn hủy sao chép không?',
    subscribeStartTime: 'Thời gian bắt đầu sao chép',
    followAccount: 'Đang sao chép',
    followStatus: 'Trạng thái sao chép',
    followStateTips:
      'Sau khi tắt theo dõi, bạn không thể mở hoặc đóng một vị thế. Nhưng bạn vẫn sẽ nhận được tín hiệu mở và đóng vị thế trên tài khoản tín hiệu của mình trong trung tâm tin nhắn.',
    baseSetting: 'Cài đặt chung',
    varietySetting: 'Cài đặt sản phẩm giao dịch ',
    followNotice: 'Thuyết minh',
    followPattern: 'Chế độ sao chép',
    followPatternTips:
      'Tỷ lệ cố định: Tính toán số lot theo mối quan hệ tài sản ròng giữa tài khoản tín hiệu và tài khoản sao chép, và sẽ tăng hoặc giảm số lot theo số lần cố định.\n<br/>\n      Số lot cố định: Bất cứ tài khoản tín hiệu vào lệnh bằng số lot như thế nào, đều vào lệnh bằng số lot cố định. Nếu bạn không có nhu cầu đăc biệt, chúng tôi đề xuất bạn sao chép giao dịch theo tỷ lệ cố định',
    maxHand: 'Số lot tối đa',
    maxHandTips:
      'Nếu khối lượng lot được mở ở một vị thế tiếp theo vượt quá giới hạn này thì vị thế sẽ được mở theo giới hạn này.',
    noLimit: 'Không giới hạn',
    followDirection: 'Loại sao chép',
    followDirectionTips:
      'Chỉ sao chép lệnh đóng: sẽ không sao chép hành động vào lệnh của tài khoản tín hiệu, và chỉ sao chép lệnh đóng',
    contractSize: 'Quy mô hợp đồng',
    contractSizeTips:
      'Quy mô hợp đồng của cùng một loại sản phẩm giao dịch có thể khác nhau trên các nền tảng khác nhau, và điều này có thể dẫn đến số lot sao chép không chính xác. Chức năng này chỉ có hiệu lực khi bật chế độ "Tỷ lệ cố định".',
    sizeList: [
      {name: 'Tự thích ứng', value: 1},
      {name: 'Bỏ qua', value: 2}
    ],
    signalAccount: 'Tài khoản tín hiệu',
    followLimit: 'Giới hạn giao dịch',
    followLimitTips:
      'Chức năng này được dùng để giới hạn tài khoản sao chép chỉ thực hiện loại giao dịch được chỉ định. <br/>\n      Nếu cài đặt loại sao chép thành "Giao dịch ngược lại", và giới hạn hành động giao dịch EURUSD là "Chỉ vào lệnh bán", thì: <br/>\n      khi tài khoản tín hiệu vào lệnh mua EURUSD, tài khoản sao chép nên giao dịch ngược lại  tức vào lệnh bán, phù hợp với điều kiện giới hạn giao dịch, cho nên hệ thống tự động vào lệnh bán.<br/>\n      khi tài khoản tín hiệu vào lệnh bán EURUSD, tài khoản sao chép nên giao dịch ngược lại tức vào lệnh mua. Nhưng điều này không phù hợp với điều kiện giới hạn giao dịch, cho nên hệ thống sẽ không vào lệnh mua.<br/>',
    setManually: 'Xác định thất bại, vui lòng cài đặt thủ công',
    limitList: [
      {name: 'Không giới hạn', value: 0},
      {name: 'Chỉ vào lệnh bán', value: 1},
      {name: 'Chỉ vào lệnh mua', value: 2},
      {name: 'Ngừng vào lệnh', value: 3}
    ],
    followRuleContent:
      'Quy tắc sao chép:<br/>\n       1. Đối với lệnh chờ, không thực hiện sao chép ngay, và sẽ chờ đến khi nó được khớp lệnh thì mới tiến hành sao chép. <br/>\n       2. Không sao chép lệnh chốt lời/cắt lỗ, vì môi trường giao dịch của các sàn giao dịch không giông nhau gồm giá cả, chênh lệch v.v, để tránh các vấn đề như bị đóng lệnh sớm hơn so với tài khoản tín hiệu. <br/>\n       3. Chức năng tự thích ứng hợp đồng không hỗ trợ tất cả các loại sản phẩm ví dụ, chỉ số chứng khoán, tương lai, cổ phiếu và các loại sản phẩm khác. <br/>\n       4. Nếu số lot vào lệnh vượt quá số lot tối đa hoặc thấp hơn số lot tối thiểu do đại lý chỉ định, thì hệ thống sẽ vào lệnh bằng số lot tối đa hoặc số lot tối thiểu. <br/>\n       5. Do sự ảnh hưởng của môi trường mạng của các bên, tín hiệu giao dịch có thể bị trễ. Nếu tín hiệu bị trễ quá lâu, bạn nên từ bỏ sao chép. Do đó, hệ thống mặc định loại bỏ các tín hiệu vào lệnh có trễ hơn 180 giây, hoặc các tín hiệu đóng lệnh có trễ hơn 30 phút.',
    notMatchTips:
      'Có {x} loại sản phẩm không khớp với sản phẩm giao dịch của tài khoản tín hiệu, vì vậy, không thể sao chép hành động giao dịch về những loại sản phẩm này. Vui lòng bạn xác nhận lại trong mục "Sản phẩm giao dịch".',
    maxLotsMoreThan: 'Số lot vào lệnh tối đa không thể thấp hơn số lot vào lệnh cố định.',
    allMatchTips:
      'Trong mục "Sản phẩm giao dịch", vui lòng đảm bảo rằng sản phẩm giao dịch của tài khoản tín hiệu và tài khoản sao chép đã khớp nhau, nếu không, thì có thể sao chép bất thường.',
    hasConfirm: 'Đã xác nhận',
    gotoCheck: 'Xác nhận lại',
    settingSuccess: 'Cài đặt thành công',
    mySubscribe: 'Đang sao chép',
    account: 'Tài khoản tín hiệu',
    currPosition: 'Lệnh đang nắm giữ',
    yesterdayEarnings: 'Lợi nhuận hôm qua',
    monthEarnings: 'Lợi nhuận 1 tháng qua',
    status: 'Trạng thái sao chép',
    statusList: ['Đang sao chép', 'Hết hạn sau {x} ngày', 'Sắp hết hạn'],
    totalTime: 'Tổng thời gian sao chép giao dịch',
    operation: 'Thao tác',
    viewToAccount:
      'Để xem những người đã đăng ký sao chép giao dịch của tôi, vui lòng chuyển sang <a target="_blank" href="{x}"> trang chi tiết tài khoản </a>',
    times: 'lần',
    connectionAnomaly:
      'Tài khoản giao dịch #{x} của bạn đã đăng xuất và tạm thời không khả dụng. <br/>Nếu mật khẩu kết nối tài khoản này đã bị thay đổi, vui lòng chuyển sang trang Tôi-Tài khoản giao dịch-Cài đặt tài khoản để cập nhật mật khẩu kết nối.',
    passwordTypeTips:
      'Mật khẩu kết nối tài khoản giao dịch #{x} là mật khẩu Passview và không có quyền giao dịch, vì vậy bạn không thể sao chép giao dịch trong Top Traders. <br/>Bạn có thể chuyển sang trang Trang Cá nhân-Tài khoản giao dịch-Cài đặt Tài khoản để cập nhật mật khẩu kết nối tài khoản thành mật khẩu Master, sau mới được phép thực hiện sao chép giao dịch.',
    goNow: 'Chuyển sang ngay',
    warmPrompt:
      'Lưu ý: <br/> \n      1. Bạn có thể thay đổi cài đặt sao chép giao dịch của bạn vào bất kỳ lúc nào thông qua "Trang chủ cá nhân" -> "Sao chép giao dịch". <br/>',
    fixedHands: 'Số lot cố định',
    fixedRatio: 'Tỷ lệ cố định',
    fixedRatioTips:
      'Tính toán số lot theo mối quan hệ tài sản ròng giữa tài khoản tín hiệu và tài khoản sao chép, và sẽ tăng hoặc giảm số lot theo số lần cố định.',
    fixedHandsTips:
      'Bất cứ tài khoản tín hiệu vào lệnh bằng số lot như thế nào, đều vào lệnh bằng số lot cố định. Nếu bạn không có nhu cầu đăc biệt, chúng tôi đề xuất bạn sao chép giao dịch theo tỷ lệ cố định',
    ratio: '{x} lần',
    signalVariety: 'Sản phẩm (Tài khoản tín hiệu)',
    followVariety: 'Sản phẩm (Tài khoản sao chép)',
    selectVariety: 'Chọn',
    searchVariety: 'Tìm kiếm',
    hasQuestion: 'Gặp phải vấn đề? Vui lòng liên hệ với <span>dịch vụ khách hàng chính thức</span>',
    subscribeInfo: 'Thông tin sao chép',
    followAgain: 'Sao chép lại',
    residueLong:
      'Thời gian sao chép giao dịch của bạn còn lại {0} tháng, và hiện nay không hỗ trợ việc kéo dài thời gian sao chép. \n      <br/>Lưu ý: thời gian sao chép tối đa là {1} tháng. Vì vậy, bạn có thể kéo dài thời gian sao chép khi thời gian còn lại dưới {1} tháng.',
    subscribeExpire: 'Lệnh sao chép đã hết hạn',
    closeTips: 'Nếu bạn chỉ muốn nhận tín hiệu và không muốn sao chép giao dịch thì có thể tắt trạng thái sao chép.',
    shareGetFollow: 'Vui lòng nâng cấp lên Pro trước khi thực hiện sao chép giao dịch',
    signalNotFollow: 'Tài khoản tín hiệu không thể sao chép giao dịch',
    initNotFollow: 'Đang khởi tạo dữ liệu, vui lòng thử lại sau'
  },
  header: {
    searchLabel: 'Tìm kiếm',
    product: 'Sản phẩm',
    market: 'Thị trường',
    information: 'Tin tức',
    signal: 'Tín hiệu',
    match: 'Cuộc thi',
    activity: 'Sự kiện',
    broker: 'Brokers',
    more: 'Nhiều hơn',
    chart: 'Biểu đồ',
    stockFilter: 'Lọc',
    financialCalendar: 'Lịch kinh tế',
    toolKit: 'Công cụ',
    cost: 'Giá',
    feature: 'Tính năng đặc sắc',
    dataMarket: 'Dữ liệu thị trường',
    overview: 'Tổng quan',
    myOptional: 'Mục quan tâm',
    news: 'Tin tức',
    transactionAnalysis: 'Phân tích',
    quickInformation: '24x7',
    column: 'Chuyên đề',
    answer: 'Q&A cùng chuyên gia',
    data: 'Dữ liệu',
    video: 'Video',
    institutionalViewPoint: 'Quan điểm từ tổ chức',
    analystViewPoint: 'Quan điểm từ nhà phân tích',
    columnTopic: 'Chủ đề',
    columnist: 'Tác giả',
    dataCenter: 'Trung tâm Dữ liệu',
    marketTrend: 'Xu hướng thị trường',
    institutionalData: 'Dữ liệu từ sở giao dịch',
    centralBankInterestRate: 'Lãi suất chính sách',
    macroEconomy: 'Kinh tế vĩ mô',
    niuList: 'Top Traders',
    bestNiuer: 'Xếp hạng hàng tuần',
    AISignal: 'Tín hiệu AI',
    fansActivity: 'Fans Party',
    web_ib_seminar: 'IB Seminar',
    voteActivity: 'Giải',
    web_fans_hongkong: 'Hồng Kông, Trung Quốc',
    web_fans_hochiminh: 'TP Hồ Chí Minh, Việt Nam',
    web_fans_dubai: 'Dubai, UAE',
    web_fans_cairo: 'Cairo, Ai Cập',
    web_fans_nigeria: 'Lagos, Nigeria',
    business: 'Thương mại',
    recruit: 'Tuyển dụng',
    aboutUs: 'Về chúng tôi',
    whiteLabel: 'Nhãn trắng',
    dataAPI: 'Data API',
    webPlugins: 'Tiện ích Website',
    feedback: 'Phản hồi',
    helpCenter: 'Trung tâm trợ giúp',
    agreement: 'Thỏa thuận Người dùng',
    policy: 'Chính sách Bảo mật',
    comingSoon: 'Sắp ra mắt',
    marketPrice: 'Thị trường',
    calendar: 'Lịch',
    quotation: 'Thị trường',
    PRO: 'Pro',
    AIRating: 'AI Đánh giá',
    latestViewPoints: 'Quan điểm ​​mới nhất',
    calendarWallpaper: 'Hình nền Lịch',
    speculativeMood: 'Tâm lý',
    hangingOrderPosition: 'Lệnh',
    varietyCorrelation: 'Mối tương quan',
    popularIndex: 'Chỉ báo phổ biến',
    hotTopic: 'Chủ đề Hot nhất',
    recentUpdate: 'Cập nhật mới nhất',
    language: 'ngôn ngữ',
    popularSearch: 'Xu hướng tìm kiếm',
    historySearch: 'Tìm kiếm gần đây',
    myCollection: 'Mục ưa thích',
    myConcern: 'Mục theo dõi',
    mySubscription: 'Mục đăng ký sao chép',
    personalInformation: 'Thông tin cá nhân',
    memberCenter: 'FastBull Pro',
    accountSetting: 'Cài đặt tài khoản',
    logOut: 'Đăng xuất',
    scanDownload: 'Quét để tải xuống',
    moreInformation: 'Faster Chart, Chat Faster!',
    downloadApp: 'Tải APP',
    addFBToDesk: 'Thêm Fastbull vào Desktop',
    loadFromDesk: 'Lần sau, bạn có thể trực tiếp truy cập FastBull từ màn hình Desktop',
    addToDesk: 'Thêm vào Desktop',
    recommendSelfSelection: 'Đề xuất',
    waitingForDeal: 'Chờ khớp lệnh',
    inTransaction: 'Đang giao dịch',
    overDeal: 'Đã kết thúc',
    overdue: 'Đã hết hạn',
    profitMaking: 'Lời',
    lossMaking: 'Lỗ',
    profitLoss: 'Lời lỗ',
    financialTools: 'Công cụ tài chính',
    homePage: 'Trang chủ',
    clickLogin: 'Đăng nhập',
    AppDescription: 'Tin tức và báo giá tài chính nhanh hơn và đầy đủ hơn',
    supportResistance: 'Hỗ trợ và Kháng cự',
    copyright: 'Copyright © {x} FastBull Ltd',
    risk: 'Tuyên bố rủi ro',
    riskText1:
      'Giao dịch các công cụ tài chính như cổ phiếu, tiền tệ, hàng hóa, hợp đồng tương lai, trái phiếu, quỹ hoặc tiền kỹ thuật số tiềm ẩn mức độ rủi ro cao, bao gồm rủi ro mất một phần hoặc toàn bộ vốn đầu tư, và có thể không phù hợp với mọi nhà đầu tư.',
    riskText2:
      'Trước khi quyết định giao dịch các công cụ tài chính hoặc tiền điện tử, bạn cần hiểu đầy đủ về rủi ro và chi phí giao dịch trên thị trường tài chính, thận trọng cân nhắc đối tượng đầu tư, và tiến hành tư vấn chuyên môn cần thiết. Dữ liệu trên trang web này không nhất thiết là theo thời gian thực hay chính xác. Dữ liệu và giá cả trên trang web không nhất thiết là thông tin do bất kỳ sở giao dịch nào cung cấp, nhưng có thể được cung cấp bởi các nhà tạo lập thị trường. Bạn chịu trách nhiệm hoàn toàn về tất cả quyết kết giao dịch bạn đã thực hiện. Chúng tôi không chấp nhận bất cứ nghĩa vụ nào trước bất kỳ tổn thất hay thiệt hại nào xảy ra từ kết quả giao dịch của bạn, hoặc trước việc bạn dựa vào thông tin có trong trang web này.',
    riskText3:
      'Bạn không được phép sử dụng, lưu trữ, sao chép, hiển thị, sửa đổi, truyền hay phân phối dữ liệu có trên trang web này và chưa nhận được sự cho phép rõ ràng bằng văn bản của Trang web này. Tất cả các quyền sở hữu trí tuệ đều được bảo hộ bởi các nhà cung cấp và/hoặc sở giao dịch cung cấp dữ liệu có trên trang web này.',
    cookieTips:
      'Chúng tôi sử dụng cookie để hiểu cách bạn sử dụng trang web của chúng tôi và cải thiện trải nghiệm của bạn, bao gồm cả việc cá nhân hóa nội dung. Nếu bạn tiếp tục sử dụng trang web của chúng tôi, thì có nghĩa bạn đã chấp nhận việc chúng tôi sử dụng cookie. Nếu bạn muốn tìm hiểu thêm, xin vui lòng nhấp vào đây.',
    viewDetail: 'Xem chi tiết',
    authorization: 'Đồng ý',
    function: 'Chức năng',
    company: 'Công ty',
    user: 'Người dùng',
    theLatestValue: 'Mới nhất',
    allSearchResult: 'Xem tất cả kết quả tìm kiếm',
    loginBtn: 'Đăng nhập',
    signUPBtn: 'Đăng ký',
    freeToOpenVIP: 'Nâng cấp lên Pro miễn phí',
    web_opinion_hot_author: 'Tác giả Hot nhất',
    market_finance_coverview: 'Tổng quan',
    freeForevet: 'Miễn phí vĩnh viễn',
    moduleDark: 'Chế độ tối',
    loginForMoreFunc: 'Đăng nhập để xem nội dung nhiều hơn',
    noLogin: 'Chưa đăng nhập'
  },
  sideLayout: {
    news_calendar_filter_only_import: 'Chỉ xem Tin Top',
    news_snowfall: 'Link liên quan',
    news_unscramble: 'Phân tích & Quan điểm',
    news_unscramble_long: 'Dài hạn',
    news_unscramble_short: 'Ngắn hạn',
    news_unscramble_bearish: 'Giảm',
    news_unscramble_bullish: 'Tăng',
    calendar_time_up: 'Thời gian',
    calendar_prev_up: 'Trước đây',
    calendar_est_up: 'Dự báo',
    calendar_act_up: 'Thực tế',
    calendar_unrelease: 'Chưa công bố',
    calendar_revised: 'Chưa sửa đổi',
    calendar_act: 'Thực tế',
    calendar_est: 'Dự báo',
    calendar_prev: 'Trước đây',
    new_share: 'Chia sẻ',
    vip_invite_friends_immediately: 'Chia sẻ để nhận Pro',
    vip_invite_friends_title: 'Chia sẻ',
    qa_header_title: 'Q&A cùng chuyên gia',
    qa_header_online: 'Q&A Online',
    qa_ask_question: 'Đặt câu hỏi...',
    qa_post_first_question: 'Đăng câu hỏi đầu tiên đi',
    qa_expert: 'Chuyên gia',
    qa_view_translation: 'Xem bản dịch',
    qa_view_original: 'Xem bản gốc',
    qa_answer: 'Trả lời',
    qa_cancel_answer: 'Hủy trả lời',
    qa_answer_placeholder: 'Trả lời{0}',
    qa_confirm_delete_question: 'Bạn có chắc chắn xóa câu hỏi này không?',
    qa_confirm_delete_answer: 'Bạn có chắc chắn xóa trả lời này không?',
    qa_select_pic_format: 'Vui lòng chọn định dạng png, jpg, jpeg, gif, bmp, webp',
    qa_common_bottom: '- Hết - ',
    qa_remind_max_char: 'Nhập tối đa {0} ký tự',
    qa_cancel_reply: 'Hủy trả lời',
    qa_reply_someone: 'Trả lời {0}',
    quote_nav_more: 'Xem thêm',
    quote_link_more: 'Xem thêm',
    quote_table_asset: 'Tài sản',
    quote_table_last: 'Giá',
    quote_table_netchg: 'Tăng/Giảm',
    quote_table_chg: '%CHG.',
    quote_table_update: 'Thời gian',
    news_news_trending: 'Phổ biến',
    quote_table_high: 'Cao nhất',
    quote_table_low: 'Thấp nhất',
    quote_watchlist: 'Quan tâm',
    quote_my_watchlist: 'Mục quan tâm',
    reminderg: 'Cài đặt lời nhắc',
    maincontainer_market: 'Thị trường',
    news_flash: '24x7',
    news_calendar: 'Lịch',
    q_a: 'Q&A',
    home_tab_chat: 'Trò chuyện',
    common_side_layout: 'Bố cục',
    common_layout_single: 'Cột đơn',
    common_layout_vertical: 'Hai hàng',
    common_layout_tile: 'Hai cột',
    cale_unpublish_time: 'Công bố sau {0}',
    cale_unpublish_time_h: '{0} giờ',
    cale_unpublish_time_min: '{0} phút',
    add_asset_name: 'Thêm tên tài sản hoặc mã',
    add_to_favorites: 'Quan tâm',
    recentlyViewed: 'Lịch sử',
    common_market_closed: 'Đã đóng cửa',
    chart_indicator: 'Chỉ báo',
    chart_strategy: 'Chiến lược',
    chart_edit: 'Trình chỉnh sửa',
    chart_backtest: 'Backtest',
    chart_order: 'Lệnh mới',
    chart_template: 'Mẫu',
    chart_sync: 'Đồng bộ',
    chart_history: 'Lịch sử',
    chart_remind: 'Lời nhắc',
    chart_log: 'Nhật ký',
    chart_connect: 'Đang kết nối với máy chủ. Vui lòng chờ đợi...',
    searchStocksTips: 'Nhập A-Z hoặc 0-9 để bắt đầu tìm kiếm'
  },
  dataCollect: {
    fxchat_login_edit_user_info_title: 'Chỉnh sửa thông tin cá nhân(1/3)',
    fxchat_login_complete_material_title: 'Điền đầy đủ thông tin của bạn(2/3)',
    fxchat_login_recommendation_title: 'Đề xuất ưu tiên (3/3)',
    fxchat_information_nick_name: 'Nickname',
    fxchat_login_field_title: 'Nhập Nickname của bạn',
    fxchat_information_sex: 'Giới tính',
    fxchat_information_sex_man: 'Nam',
    fxchat_information_sex_women: 'Nữ',
    fxchat_information_sex_other: 'Khác',
    fxchat_information_sex_secret: 'Ẩn',
    fxchat_material_morning: 'Chào buổi sáng "{0}" ! Chào mừng bạn đến với FastBull',
    fxchat_material_noon: 'Chào buổi trưa "{0}" ! Chào mừng bạn đến với FastBull',
    fxchat_material_afternoon: 'Chào buổi chiều "{0}" ! Chào mừng bạn đến với FastBull',
    fxchat_material_night: 'Chào buổi tối "{0}"! Chào mừng bạn đến với FastBull',
    fxchat_material_introduction:
      'Để đề xuất cho bạn nội dung chất lượng cao hơn, vui lòng giới thiệu ngắn gọn về bản thân đi~',
    fxchat_recommendation_subtitle: 'Đề xuất nội dung dựa trên dữ liệu mà bạn đã lựa chọn.',
    fxchat_material_summarize:
      'Tuyệt vời! Dựa trên thông tin bạn cung cấp, chúng tôi sẽ đề xuất  cho bạn nội dung cá nhân hóa và chất lượng cao hơn.',
    fxchat_material_assistant_name: 'AI Chatbot',
    fxchat_material_look: 'Xem ngay',
    fxchat_material_reselect: 'Chọn lại',
    fxchat_recommendation_see_more: 'Xem thêm',
    fxchat_recommendation_open_fxchat: 'Mở FastBull',
    fxchat_recommendation_open_group: 'Nhóm',
    fxchat_recommendation_open_niu: 'Trader phổ biến nhất',
    fxchat_not_group_introduction: 'Không có giới thiệu',
    fxchat_recommendation_join: 'Tham gia',
    fxchat_recommendation_has_join: 'Đã tham gia',
    fxchat_login_skip: 'Bỏ qua',
    fxchat_recommendation_follow: 'Theo dõi',
    fxchat_recommendation_has_follow: 'Đã theo dõi',
    fxchat_login_trading_type: 'Bạn quan tâm đến thị trường nào nhiều hơn? (Nhiều lựa chọn)'
  },
  setting: {
    personalData: 'Thông tin cá nhân',
    accountSafety: 'Bảo mật tài khoản',
    informSetting: 'Cài đặt thông báo',
    privacy: 'Riêng tư',
    blacklist: 'Danh sách đen',
    remove: 'Xóa',
    shieldingTime: 'Thời gian đưa vào danh sách đen: {x}',
    addStyle: 'Phương thức kết bạn với tôi',
    allowAll: 'Cho phép tất cả mọi người kết bạn với tôi',
    needVerify: 'Cần gửi thông tin xác thực',
    notAllowAny: 'Không cho phép kết bạn',
    findByPhone: 'Tìm kiếm tôi thông qua số điện thoại',
    findByPhoneTips: 'Sau khi tắt, người dùng khác sẽ không thể tìm thấy bạn thông qua những thông tin trên.',
    follow: 'Sao chép giao dịch',
    followTips: 'Sau khi bật, thông tin sao chép giao dịch của bạn sẽ được công khai',
    contest: 'Cuộc thi',
    contestTips: 'Sau khi bật, thông tin chi tiết trong cuộc thi giao dịch của bạn sẽ được công khai',
    emailNotice: 'Tùy chọn thông báo Email',
    weeklySelection: 'Tin tức đề xuất trong thị trường hàng tuần của FastBull',
    willPushNews:
      'Chúng tôi sẽ đề xuất cho bạn các tin tức tài chính và sự kiện lớn có liên quan mà bạn đã quan tâm gần đây',
    sendWeek: 'Đề xuất hàng tuần',
    dailyHighlights: 'Tin nóng trong thị trường hàng ngày của FastBull',
    sendDay: 'Đề xuất hàng ngày (T2-T6)',
    baseInfo: 'Thông tin cơ bản',
    nickname: 'Nickname',
    joinStyle: 'Cách tham gia nhóm',
    aphorism: 'Châm ngôn',
    editInfo: 'Chỉnh sửa thông tin cá nhân',
    interestInfo: 'Thông tin quan tâm',
    noAddInterest: 'Không có nội dung nào~',
    dealPlatform: 'Sàn giao dịch',
    dealMarket: 'Thị trường',
    dealVariety: 'Sản phẩm giao dịch',
    dealStyle: 'Phong cách giao dịch',
    avatar: 'Ảnh đại diện',
    modifyAvatar: 'Thay đổi ảnh đại diện',
    username: 'Tên người dùng',
    sex: 'Giới tính',
    dealAge: 'Thời gian giao dịch',
    address: 'Vị trí',
    industry: 'Nghề nghiệp',
    modify: 'Chỉnh sửa',
    addIndustry: 'Thêm ngành nghề',
    userIntro: 'Thông tin cá nhân',
    interestDealInfo: 'Thông tin mà bạn muốn quan tâm',
    add: 'Thêm',
    sexList: [
      {value: 0, name: 'Nam'},
      {value: 1, name: 'Nữ'},
      {value: 2, name: 'Ẩn'}
    ],
    industryType: 'Loại nghề nghiệp',
    inIndustry: 'Nghề nghiệp liên quan',
    outIndustry: 'Nghề nghiệp khác',
    interestPlayform: 'Chọn sàn giao dịch mà bạn muốn quan tâm',
    interestMarket: 'Chọn thị trường mà bạn muốn quan tâm',
    interestStyle: 'Chọn phong cách giao dịch mà bạn muốn quan tâm',
    interestVariety: 'Chọn sản phẩm giao dịch mà bạn muốn quan tâm',
    maxOption: 'Bạn có thể chọn tối đa {x} mục',
    blackTypeList: [
      {value: 1, name: 'Danh bạ'},
      {value: 2, name: 'Nhóm'}
    ],
    accountInfo: 'Thông tin tài khoản',
    userPassword: 'Mật khẩu người dùng',
    haveSet: 'Đã cài đặt',
    isNotSet: 'Chưa cài đặt',
    phoneNumber: 'Số điện thoại',
    notBind: 'Chưa liên kết',
    bind: 'Liên kết',
    email: 'Địa chỉ email',
    bindThird: 'Liên kết bên thứ ba',
    unBind: 'Hủy liên kết',
    bindPhone: 'Liên kết số điện thoại',
    changePhone: 'Thay đổi số điện thoại',
    inputPhone: 'Vui lòng nhập số điện thoại',
    and: 'Và',
    inputPhoneTips: 'Xin vui lòng nhập số điện thoại hợp lệ',
    inputVerifyCode: 'Vui lòng nhập mã xác minh',
    oldPhoneNumber: 'Số điện thoại cũ',
    newPhoneNumber: 'Số điện thoại mới',
    bindEmailOpen: 'Vui lòng liên kết email của bạn để kích hoạt chức năng đăng nhập tài khoản',
    bindEmail: 'Liên kết Email',
    setPassword: 'Cài đặt mật khẩu',
    password: 'Mật khẩu',
    inputPwd: 'Vui lòng nhập mật khẩu',
    pwdRules: 'Mật khẩu 6-20 ký tự, bao gồm ít nhất 2 loại sau: số, chữ và ký hiệu đặc biệt.',
    updatePwd: 'Thay đổi mật khẩu',
    currentPwd: 'Mật khẩu hiện tại',
    forgetPwd: 'Quên mật khẩu?',
    newPwd: 'Mật khẩu mới',
    pwdNotSame: 'Không trùng nhau',
    emailResetPwd: 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi cho bạn một link để cài đặt lại mật khẩu',
    sendResetLink: 'Gửi link',
    inputEmail: 'Vui lòng nhập Email của bạn',
    inputRightEmail: 'vui lòng nhập Email hợp lệ',
    alreadSendLink: 'Chúng tôi đã gửi cho bạn một liên kết để đặt lại mật khẩu của bạn',
    alreadSendTo: 'Chúng tôi đã gửi Email đến',
    noGetFindHelp: 'Nếu bạn không nhận được thư trong vòng 5 phút, vui lòng kiểm tra Spam hoặc yêu cầu trợ giúp',
    findHelp: 'Trợ giúp',
    getVerifyCode: 'Lấy mã xác minh',
    notGet: 'Chưa nhận được?',
    resend: 'Gửi lại Email',
    inputCode: 'Vui lòng nhập mã xác minh',
    beGetting: 'Đang lấy...',
    resendAfter: 'Gửi lại sau {x}s',
    selectAvatar: 'Chọn ảnh đại diện',
    customAvatar: 'Tùy chọn',
    reUpload: 'Tải lên lại',
    defaultAvatar: 'Ảnh đại diện mặc định',
    imgType: 'Chỉ hỗ trợ định dạng hình ảnh {x}',
    inputNickname: 'Vui lòng nhập Nickname',
    inputUsername: 'Vui lòng nhập tên người dùng',
    usernameTips:
      'Tên người dùng chỉ hỗ trợ chữ viết thường, số, dấu gạch dưới và dấu chấm. Thay đổi tên người dùng của bạn cũng sẽ thay đổi link trang chủ của bạn'
  },
  vip: {
    equities: 'Đặc quyền',
    detail: 'Chi tiết',
    hasCode: 'Tôi có mã Redeem',
    inputCode: 'mã Redeem',
    conversion: 'Đổi',
    shareGet: 'Chia sẻ để nhận FastBull Pro miễn phí',
    shareGetYear: 'Chia sẻ để nhận FastBull Pro 1 năm',
    inviteUser:
      'Sau khi người dùng mới đăng ký tài khoản thành công bằng Link mời của bạn, thì bạn sẽ có thể nhận được FastBull Pro 1 tháng.',
    scanQRCode: 'Quét mã QR',
    shareLink: 'Chia sẻ Link để nhận FastBull Pro',
    recharge: 'Nạp tiền thành viên',
    agree: 'Tôi đã đọc và đồng ý',
    agreement: 'Thỏa thuận Dịch vụ Pro',
    privilege: 'Đặc quyền',
    time: 'Thời gian',
    duration: 'Nhận thời lượng Pro',
    getMode: 'Phương thức nhận',
    status: 'Trạng thái',
    redeemRules:
      'Quy tắc sử dụng mã Redeem:<br/>\n1. Mỗi mã Redeem chỉ được phép sử dụng một lần<br/>\n2. Một khi mã Redeem quá hạn sẽ trở nên vô hiệu',
    privilegeList: [
      {id: 1, title: 'Nhận Tin tức nhanh hơn 24x7', desc: 'Truy cập nhanh hơn các tin tức đề xuất thời gian thực'},
      {
        id: 2,
        title: 'Theo dõi tài sản nhiều hơn',
        desc: 'Cho phép quan tâm nhiều tài sản hơn, nhận dữ liệu thị trường toàn diện theo thời gian thực'
      },
      {
        id: 3,
        title: 'Dữ liệu vĩ mô và các chỉ báo kinh tế toàn diện hơn',
        desc: 'Cung cấp dữ liệu lịch sử toàn diện hơn, hỗ trợ phân tích thị trường vĩ mô'
      }
    ],
    shareTitle: 'Tôi đã mua FastBull Pro cho bạn, giá trị %s USD, hãy nhận đị~'
  },
  promotion: {
    volumnMuteDefault: 'Mặc định tắt âm thanh',
    enableVolumn: 'Bật âm thanh',
    kolInterview: 'Phỏng vấn KOL',
    userComment: 'Đánh giá từ người dùng',
    moreFunction: 'Tìm hiểu thêm',
    moreFunctionTxt: 'Nhận bất cứ thứ gì bạn cần để giao dịch tại FastBull'
  },
  tdk: {
    title: 'FastBull - Faster Chart, Chat Faster!',
    homeTitle: 'FastBull Top Traders: Theo dõi các trader kiếm lời cao nhất',
    homeDesc:
      'FastBull Top Traders: cho phép bạn học theo các trader kiếm lời cao nhất, để nâng cao trình độ giao dịch',
    greatestTitle: 'Bảng xếp hạng hàng tuần',
    greatestDesc:
      'FastBull sẽ bình chọn ra Trader ưu tư nhất mỗi tuần, thông qua lợi nhuận, phân tích định lượng, số lượng giao dịch, và tỷ lệ thắng.',
    helpTitle: 'Trung tâm trợ giúp - FastBull',
    helpDesc: 'Nhận các câu trả lời và các tài nguyên hữu ích trong Trung tâm trợ giúp của chúng tôi.',
    userTitle: '【{x}】- Cá nhân',
    userDesc: 'Hãy tìm kiếm trader có mục đích giống như bạn thông qua trang cá nhân đi.'
  },
  about: {
    downloadApp: 'Tải APP',
    aboutFb: 'Về FastBull',
    fbExplain:
      'FastBull là một nhà đổi mới trong lĩnh vực Fintech. Chúng tôi đã thành lập nhóm biên tập và phiên dịch tại nhiều khu vực, nhằm xây dựng nội dung được bản địa hóa tại nhiều quốc gia và khu vực. Đồng thời, chúng tôi có đội ngũ R&D và quản lý sản phẩm lớn nhất và có sức mạnh kỹ thuật cao nhất. Chúng tôi sẽ tiếp tục cung cấp những trải nghiệm phần mềm hàng đầu trong tương lai.',
    service: 'Dịch vụ',
    product: 'Sản phẩm',
    productExplain:
      'Chúng tôi đã ra mắt chưc năng lịch kinh tế và công cụ hỗ trợ, và sẽ ra mắt nhiều chức năng lớn trong tương lai: Biểu đồ Pro, Công cụ lọc cổ phiểu, Dữ liệu phân tích thị trường v.v.',
    signal: 'Tín hiệu',
    signalExplain:
      'Tin tức, Top Traders, Bảng xếp hạng hàng tuần, Tín hiệu mới nhất, Cuộc thi giao dịch. Tín hiệu giao dịch từ các cao thủ trader. Sao chép giao dịch theo thời gian thực, để làm giao dịch dễ dàng hơn!',
    message: 'Tin tức',
    messageExplain:
      'Tin tức, 24×7, Phân tích, Chuyên đề, Dữ liệu, Video, bao gồm tin nóng toàn cầu. Quan điểm từ nhà phân tích và tổ chức tài chính. Cập nhật sự kiện và dữ liệu kinh tế 24×7.',
    market: 'Thị trường',
    marketExplain:
      'Chúng tôi cung cấp dữ liệu từ thị trường ngọi hối, hành hòa, chỉ số, chứng khoán Mỹ, tiền kỹ thuật số , CME v.v. Trong tương lai, chúng tôi sẽ cung cấp thêm dữ liệu từ thị trường chứng khoán toàn cầu, ETF, và trái phiếu.',
    business: 'Thương mại',
    businessExplain:
      'Chúng tôi đã cung cấp dịch vụ bên thứ ba miễn phí và trả phí. gồm nhãn trắng, dữ liệu API, tiện ích website v.v để cung cấp dịch vụ hỗ trợ nguồn dữ liệu và kỹ thuật. ',
    course: 'Hành trình phát triển',
    contact: 'Liên hệ chúng tôi',
    partner: 'Đối tác',
    email: 'Email',
    feedback: 'Ý kiến phản hồi',
    scan: 'Quét mã QR',
    android: 'Android',
    ios: 'iOS',
    downloadTips: 'Thảo luận, chia sẻ quan điểm và ý tưởng của bạn với nhà đầu tư toàn cầu.',
    chat: 'Trò chuyện tức thời',
    chatExplain: 'Hội tụ Top Trader toàn cầu. Chat mọi thứ liên quan về giao dịch.',
    chart: 'Biểu đồ xã hội',
    chartExplain: 'Phân tích thị trường, Thảo luận và giao lưu, Đăng ký tín hiệu giao dịch',
    realTimeSignal: 'Tín hiệu thời gian thực',
    realTimeSignalExplain: 'Tín hiệu giao dịch thật. Sao chép miễn phí',
    contest: 'Cuộc thi giao dịch',
    contestExplain: 'Nền tảng tốt nhất để thể hiện khả năng giao dịch của bạn',
    answer: 'Q&A cùng chuyên gia',
    answerExplain: 'Đặt câu hỏi cho chuyên gia, nhận ý kiến chuyên nghiệp miễn phí',
    analyse: 'Phân tích giao dịch',
    analyseExplain: 'Học tập logic giao dịch của chuyên gia đầu tư',
    calendar: 'Lịch kinh tế',
    calendarExplain: 'Giải thích dữ liệu kinh tế sâu sắc bằng công cụ phân tích chuyên nghiệp',
    news: 'Tin tức đề xuất',
    newsExplain: 'Hội tụ quan điểm phân tích sâu sắc của các chuyên gia tài chính toàn cầu',
    tools: 'Công cụ thiết kê Poster',
    toolsExplain: 'Hỗ trợ thiết kết tùy chỉnh các loại Poster tài chính',
    more: 'Xem thêm',
    moreExplain: 'Tải FastBull để trải nghiệm nhiều tính năng tuyệt vời',
    downloadFrom: 'Tải xuống từ'
  },
  chat: {
    headTabs: ['Tất cả', 'Phòng Chat', 'Nhóm', 'Bạn bè'],
    placeInput: 'Nhập nội dung...',
    connecting: 'Đang kết nối Phòng Chat'
  }
}
